/* ============================================================================
 * questions-mock3.js —— 全真模拟(三)整卷（60 道选择题 + 作文题）
 * ----------------------------------------------------------------------------
 * 来源：用户提供的 PDF《英语全真模拟卷及答案解析（五套）》第三套（原书第 13-18 页）。
 * 逐题对照卷末【参考答案及解析】录入，解析取自原书【应试指导】，压成一两句。
 *
 * ⚠️ 这是【模拟卷】不是真题：只打 mock:true，绝不打 real:true。
 * ⚠️ 第 11 题原书【答案】印的是 A，但它自己的解析通篇在讲 "ever since"（B 项），
 *    且 has worked there ever since 才是固定说法 —— 按解析+语法事实录 B（下方注明）。
 * 字段：paper:"M3" + ord（卷面题号），模考页可按整卷原始顺序考。
 * ========================================================================== */

window.PAPERS = (window.PAPERS || []).concat([{
  id: "M3", name: "全真模拟(三)",
  essay: "以 “Failure and Success” 为题写一篇短文，内容包括：（1）人生中遭遇失败很常见；（2）每个人都渴望成功；（3）失败是走向成功的必经之路。",
}]);

/* ---------- 完形填空原文（美国北方人南下过冬） ---------- */
var M3_CLOZE = "The northern parts of the United States get very cold in the winter. It snows a great deal and the temperature often goes (21)____ zero degree in January, (22)____ and March. But the northeastern and northcentral regions of (23)____ have been financial and industrial centers, and they are heavily polluted.\n\nIn recent years, people in these regions have begun to take vacations (24)____ cold winter months. They go to southern parts of the country (25)____ it is warmer. Many go to Florida where the weather is (26)____ . Others go to the southwestern states of Arizona, New Mexico and Texas where they (27)____ dry desert climates.\n\nIt has become (28)____ nowadays for old people to move south to these places (29)____ they retire. Typically these people sell their houses in their home communities and move south to begin a new life (30)____ senior citizens.\n\nTheir children likely have homes (31)____ and many of them are moving south (32)____ communities where they were (33)____ . The southern and southwestern parts of the country are now growing (34)____ any other part. Business and industry (35)____ many offices and factories in the south. California is already the most popular state in the country.";

/* ---------- 阅读理解 5 篇原文 ---------- */
var M3_P1 = "There is a popular belief among parents that schools are no longer interested in spelling. No school I have taught in has ever ignored spelling or considered it unimportant as a basic skill. There are, however, vastly different ideas about how to teach it, or how much priority it must be given over general language development and writing ability. The problem is, how to encourage a child to express himself freely and confidently in writing without holding him back with the complexities of spelling.\n\nIf spelling becomes the only focal point of his teacher's interest, clearly a bright child will be likely to \"play safe\". He will tend to write only words within his spelling range, choosing to avoid adventurous language. That's why teachers often encourage the early use of dictionaries and pay attention to content rather than technical ability.\n\nI was once shocked to read on the bottom of a sensitive piece of writing about a personal experience: \"This work is terrible! There are far too many spelling errors and your writing is illegible (难以辨认的).\" It may have been a sharp criticism of the pupil's technical abilities in writing, but it was also a sad reflection on the teacher who had omitted to read the essay, which contained some beautiful expressions of the child's deep feelings. The teacher was not wrong to draw attention to the errors, but if his priorities had centred on the child's idea, an expression of his disappointment with the presentation would have given the pupil more motivation to seek improvement.";
var M3_P2 = "It was Ann's first experience of flying. She had always been afraid of heights and so was prepared to be frightened. Only the fact that she was going to meet her son who she had not seen for three years had given her the courage to make the flight.\n\nShe sat in her seat, her hands gripping its arms, her seat belt already fastened. The air hostess was talking, telling everyone what to do in case of emergency, showing them where their life-jackets were. The plane was crowded, and every seat was full. From her window seat, getting out in a hurry would be impossible, thought Ann. In any case who would want to get out of a plane in mid-air?\n\nThe engines began to shake—the noise increased till it was like a great rushing wind. She looked out to see the runway slip past at astonishing speed. She wanted to cry out—to stop the plane before it left the ground, but she knew she was trapped in this great roaring machine. I must scream, she told herself, and put her hands over her eyes.\n\nThere was a strange feeling as if she were going up in a lift. The noise died down. Carefully she opened her eyes. Through the window she saw a great carpet of cloud above, so beautiful that she stared in wonder, hardly turning away from the window till they touched down.";
var M3_P3 = "In ancient times wealth was measured and exchanged in things that could be touched: food, tools, and precious metals and stones. Then the barter system was replaced by coins, which still had real value since they were pieces of rare metal. Coins were followed by fiat money, paper notes that have value only because everyone agrees to accept them.\n\nToday electronic monetary systems are gradually being introduced that will transform money into even less tangible forms, reducing it to a series of \"bits and bytes\", or units of computerized information, going between machines at the speed of light. Already, electronic fund transfer allows money to be instantly sent and received by different banks, companies, and countries through computers and telecommunications devices.";
var M3_P4 = "Mr. Smith was a wealthy industrialist, but he was not satisfied with life. He did not sleep well and his food did not agree with him. This situation lasted for some time. Finally, after several sleepless nights, he decided to consult his doctor. The doctor advised a change of surroundings. \"Go abroad,\" he said. \"But I'm not good at foreign language,\" said Mr. Smith. \"It doesn't matter,\" said the doctor. \"It won't hurt you to talk a little less. Go on a voyage. Take plenty of exercise. Try to reduce your weight. Avoid rich food.\"\n\nMr. Smith went to Switzerland. He did not know French or German, and had to communicate through gestures. He attended a physical training course. The instructor made him bend his knees, swing his arms, stretch his neck and shake his head rapidly. He had to lie on the ground and raise his right and left legs alternately. After a time his muscles grew hard and firm. He forgot the financial crisis and the importance of raising the level of production. He even began to notice individual trees and individual birds.\n\nFinally he returned home. But unfortunately his improvement was only temporary. Soon he was a normal businessman again, worried about his property, his profits, his savings, his advancement in a technological society, and things in general.";
var M3_P5 = "There was a river with a small town on either side of it. The towns were linked by a bridge.\n\nOne day, a hole appeared in the bridge. Both towns agreed that the hole should be mended. However, disagreement came up as to who should mend it. Each town thought that it had a better reason for the other to mend the hole. The town on the right bank said that it was at the end of the road, so the left-bank town should mend the hole. The town on the left bank, on the other hand, insisted that all the traffic came to the right-bank town, so it was in their interest to mend the bridge.\n\nThe quarrel went on and on, and so did the hole. The more it went on, the more the hostility between the two towns grew.\n\nOne day a man fell into the hole and broke his leg. People from both towns questioned him closely about whether he was walking from the right bank to the left or from the left bank to the right, in order to decide which town should be blamed for the accident. But he could not remember, since he got drunk that night.\n\nSome time later, a car was crossing the bridge and broke an axle (轴) because of the hole. Neither town paid any attention to the accident, as the traveler was not going from one to the other, but was merely passing through. The angry traveler got out of the car and asked why the hole was not mended.\n\nOn hearing the reason, he declared, \"I'll buy this hole. Who's the owner?\"\n\nBoth towns at once declared that they owned the hole.\n\n\"One or the other, whoever owns the hole must prove it.\"\n\n\"How shall we prove it?\" asked both sides.\n\n\"That's simple. Only the owner of the hole has the right to mend it. I'll buy the hole from whoever mends the bridge.\"\n\nPeople from both towns rushed to do the job while the traveler smoked a cigar and his driver changed the axle. They mended the bridge in no time and asked for the money for the hole.\n\n\"What hole?\" The traveler looked surprised. \"I can't see any hole. I've been looking for a hole for several years now. I'm prepared to pay a good price for it, but there's no hole here. Are you pulling my leg or what?\"\n\nHe got into his car and drove off.";

/* ---------- 补全对话原文（订机票确认座位） ---------- */
var M3_DLG = "A: Northwind Airlines. Can I help you?\nB: Hello, I'd like to (56)____ , please.\nA: May I have your name and (57)____ , please?\nB: My name is Daniel Adams and my flight number is 374.\nA: When are you leaving?\nB: (58)____ .\nA: And your destination?\nB: Buenos Aires.\nA: (59)____ , please... All right. Your seat is confirmed, Mr. Adams. You'll be arriving in Buenos Aires at 4 o'clock p.m. local time.\nB: Thank you. Can I pick up my ticket when I check in?\nA: Yes, but (60)____ at least one hour before departure time.";

window.QUESTIONS = (window.QUESTIONS || []).concat([

/* ==================== Ⅰ. 语音（5 题）==================== */
{ id: "mk3-01", paper: "M3", ord: 1, mock: true, level: 3, module: "phonetics", topic: "phonetics-ea",
  source: "全真模拟(三) 第1题", stem: "选出划线部分读音与其它三个不同的一项：",
  options: ["sw__ea__t", "l__ea__p", "f__ea__ture", "ch__ea__t"], answer: 0,
  explanation: "ea 在 leap / feature / cheat 里都读 /iː/，只有 sweat 读 /e/。" },
{ id: "mk3-02", paper: "M3", ord: 2, mock: true, level: 3, module: "phonetics", topic: "phonetics-our",
  source: "全真模拟(三) 第2题", stem: "选出划线部分读音与其它三个不同的一项：",
  options: ["f__our__", "p__our__", "h__our__", "y__our__"], answer: 2,
  explanation: "four / pour / your 里的 our 都读 /ɔː/，只有 hour 读 /aʊə/（h 不发音）。" },
{ id: "mk3-03", paper: "M3", ord: 3, mock: true, level: 3, module: "phonetics", topic: "phonetics-o",
  source: "全真模拟(三) 第3题", stem: "选出划线部分读音与其它三个不同的一项：",
  options: ["forg__o__t", "l__o__st", "p__o__t", "p__o__st"], answer: 3,
  explanation: "forgot / lost / pot 里的 o 都读短音 /ɒ/，只有 post 读 /əʊ/。" },
{ id: "mk3-04", paper: "M3", ord: 4, mock: true, level: 3, module: "phonetics", topic: "phonetics-oo",
  source: "全真模拟(三) 第4题", stem: "选出划线部分读音与其它三个不同的一项：",
  options: ["sh__oo__t", "bl__oo__d", "r__oo__f", "t__oo__l"], answer: 1,
  explanation: "shoot / roof / tool 里的 oo 读 /uː/，只有 blood 读 /ʌ/。" },
{ id: "mk3-05", paper: "M3", ord: 5, mock: true, level: 3, module: "phonetics", topic: "phonetics-th",
  source: "全真模拟(三) 第5题", stem: "选出划线部分读音与其它三个不同的一项：",
  options: ["clo__th__", "ba__th__e", "wi__th__", "__th__ey"], answer: 0,
  explanation: "bathe / with / they 里的 th 读浊音 /ð/，只有 cloth 读清音 /θ/。" },

/* ==================== Ⅱ. 词汇与语法（15 题）==================== */
{ id: "mk3-06", paper: "M3", ord: 6, mock: true, level: 3, module: "grammar", topic: "inversion",
  source: "全真模拟(三) 第6题",
  stem: "Not only ____ very well, but also ____ well.",
  options: ["she cooks; does she dance", "she cooks; she dances", "does she cook; she dances", "does she cook; does she dance"],
  answer: 2,
  explanation: "not only 放句首，**它引导的那半句要部分倒装**（does she cook）；but also 后面那半句**不倒装**（she dances）。只倒前不倒后，这是这道题唯一的考点。",
  optionNotes: ["错：前半句该倒装却没倒", "错：两句都没倒装", "对：前倒后不倒，正是 Not only 置句首的规则", "错：后半句多倒了一次"] },
{ id: "mk3-07", paper: "M3", ord: 7, mock: true, level: 3, module: "grammar", topic: "relative-clause",
  source: "全真模拟(三) 第7题",
  stem: "I'd like to live somewhere ____ the sun shines all year long.",
  options: ["which", "of which", "where", "at where"], answer: 2,
  explanation: "先行词 somewhere 是地点，且从句 the sun shines all year long 主谓齐全**不缺成分**，缺的是地点状语 → 用关系副词 where。",
  optionNotes: ["错：which 要在从句里当主语或宾语，这里从句不缺", "错：of which 要接名词", "对：从句不缺成分、缺地点状语 → where", "错：where 本身已含介词，不能再加 at"] },
{ id: "mk3-08", paper: "M3", ord: 8, mock: true, level: 4, module: "grammar", topic: "comparative",
  source: "全真模拟(三) 第8题",
  stem: "The facilities of the older hotel ____.",
  options: ["is as good or better than the new hotel", "are as good or better than the new hotel",
            "is as good as or better than those of the new hotel", "are as good as or better than those of the new hotel"],
  answer: 3,
  explanation: "三处一起考：主语 facilities 是复数 → **are**；as good 后面必须补 **as**（as good as or better than）；比较对象要对等，是设施比设施 → **those of** the new hotel。",
  optionNotes: ["错：is 与复数主语不一致，且缺 as、比较对象不对等", "错：缺第二个 as，比较对象也不对等", "错：is 与复数主语 facilities 不一致", "对：are + as good as or better than + those of，三处全对"] },
{ id: "mk3-09", paper: "M3", ord: 9, mock: true, level: 2, module: "grammar", topic: "collocation",
  source: "全真模拟(三) 第9题",
  stem: "You should have been more patient ____ that customer; I'm sure that selling him the watch was a possibility.",
  options: ["of", "with", "for", "at"], answer: 1,
  explanation: "**be patient with sb.** = 对某人有耐心，固定搭配。",
  optionNotes: ["错：没有 patient of 这个搭配", "对：be patient with sb. = 对某人有耐心", "错：patient for 不成立", "错：patient at 不成立"] },
{ id: "mk3-10", paper: "M3", ord: 10, mock: true, level: 3, module: "grammar", topic: "word-choice",
  source: "全真模拟(三) 第10题",
  stem: "He promised that he would ____ to get us two tickets for the soccer game.",
  options: ["manage", "fulfil", "accomplish", "succeed"], answer: 0,
  explanation: "只有 **manage to do sth.**（设法做成某事）能直接接不定式。succeed 要说 succeed **in doing**。",
  optionNotes: ["对：manage to do sth. = 设法做成", "错：fulfil 是履行、实现，不接不定式", "错：accomplish 是完成（某事），不接不定式", "错：要说 succeed in doing，不能接 to do"] },
{ id: "mk3-11", paper: "M3", ord: 11, mock: true, level: 3, module: "grammar", topic: "word-choice",
  source: "全真模拟(三) 第11题（⚠️原书答案字母与解析矛盾，按解析录 B）",
  stem: "He got a job with the corporation in 2000 and has worked there ____.",
  options: ["since", "ever since", "ever before", "till then"], answer: 1,
  explanation: "**ever since = from then on**（自那时起一直），常跟现在完成时呼应，正是「2000 年进公司，从此一直干到现在」。\n⚠️ 原书【答案】印的是 A，但它自己的解析整段在讲 ever since，且 has worked there ever since 才是固定说法，属印刷错误。",
  optionNotes: ["错：单个 since 作副词较少这样用，且原书解析讲的就是 ever since", "对：ever since = 自那时起一直，与现在完成时呼应", "错：ever before 指「以前曾经」，时间方向相反", "错：till then 指「到那时为止」，与现在完成时冲突"] },
{ id: "mk3-12", paper: "M3", ord: 12, mock: true, level: 2, module: "grammar", topic: "collocation",
  source: "全真模拟(三) 第12题",
  stem: "The river, which is ____ the Yangtze River, is the longest river in China.",
  options: ["named after", "known for", "known as", "called for"], answer: 2,
  explanation: "**be known as** = 被称为、被叫做。四个搭配意思完全不同，背下来即可。",
  optionNotes: ["错：be named after = 以……命名（跟在某人名字后面取名）", "错：be known for = 因……而闻名", "对：be known as = 被称为", "错：call for = 需要、要求"] },
{ id: "mk3-13", paper: "M3", ord: 13, mock: true, level: 3, module: "grammar", topic: "collocation",
  source: "全真模拟(三) 第13题",
  stem: "There is no specific rule ____ what we should wear to a dinner party.",
  options: ["because of", "as to", "as of", "but for"], answer: 1,
  explanation: "**as to** = 关于、至于，后面接名词或从句。句意：关于宴会该穿什么并没有具体规定。",
  optionNotes: ["错：because of = 因为", "对：as to = 关于、至于", "错：as of = 从……开始（时间起点）", "错：but for = 要不是（虚拟语气）"] },
{ id: "mk3-14", paper: "M3", ord: 14, mock: true, level: 3, module: "grammar", topic: "collocation",
  source: "全真模拟(三) 第14题",
  stem: "The two parties have ____ an agreement on the date of talk.",
  options: ["come across", "come down", "come up", "come to"], answer: 3,
  explanation: "**come to an agreement** = 达成一致，固定搭配。同一个动词换个介词意思全变，这类只能一条条记。",
  optionNotes: ["错：come across = 偶然碰上", "错：come down = 下来、下跌", "错：come up = （问题）出现、被提出", "对：come to an agreement = 达成一致"] },
{ id: "mk3-15", paper: "M3", ord: 15, mock: true, level: 3, module: "grammar", topic: "modal-verb",
  source: "全真模拟(三) 第15题",
  stem: "My mobile phone isn't in my bag. Where ____ I have put it?",
  options: ["can", "must", "should", "would"], answer: 0,
  explanation: "**can + have done** 用在疑问句里表推测「究竟会……呢」。must 表推测只用于肯定句，不用于疑问句；should / would + have done 意思不符。",
  optionNotes: ["对：疑问句里的推测用 can have done", "错：must 表推测不用于疑问句", "错：should have done = 本该做却没做", "错：would have done 是虚拟语气"] },
{ id: "mk3-16", paper: "M3", ord: 16, mock: true, level: 3, module: "grammar", topic: "word-choice",
  source: "全真模拟(三) 第16题",
  stem: "Last year, some poor people had hardly ____ the severe winter.",
  options: ["remained", "lived", "endured", "survived"], answer: 3,
  explanation: "**survive** = 挺过来、幸存下来（后面可直接跟被熬过的对象）。句意：去年有些穷人几乎没能挺过严冬。",
  optionNotes: ["错：remain = 保留、剩余", "错：live 是不及物的「生活」，不能直接跟 the winter", "错：endure = 忍耐、忍受，语义不如 survive 准", "对：survive the winter = 熬过冬天"] },
{ id: "mk3-17", paper: "M3", ord: 17, mock: true, level: 2, module: "grammar", topic: "collocation",
  source: "全真模拟(三) 第17题",
  stem: "The university ____ four colleges and five academies.",
  options: ["is made of", "is composed of", "is consisted of", "composed of"], answer: 1,
  explanation: "表示「由……组成」的固定说法只有三个：**be made up of / be composed of / consist of**。注意 **consist of 没有被动式**。",
  optionNotes: ["错：be made of 是「由……材料制成」，不是「由……组成」", "对：be composed of = 由……组成", "错：consist of 本身就是主动，没有 be consisted of", "错：缺 be 动词"] },
{ id: "mk3-18", paper: "M3", ord: 18, mock: true, level: 3, module: "grammar", topic: "collocation",
  source: "全真模拟(三) 第18题",
  stem: "____, he is not a very bright pupil.",
  options: ["As far as his intelligence is concerned", "As far his intelligence is concerned",
            "So his intelligence is concerned", "As far as his intelligence are concerned"], answer: 0,
  explanation: "**as far as ... be concerned** = 就……而言，固定句型，一个词都不能改。另外 intelligence 是不可数名词 → is。",
  optionNotes: ["对：as far as ... is concerned，句型完整且主谓一致", "错：漏了第二个 as", "错：没有 so ... is concerned 这个句型", "错：intelligence 不可数，不能用 are"] },
{ id: "mk3-19", paper: "M3", ord: 19, mock: true, level: 3, module: "grammar", topic: "so-that",
  source: "全真模拟(三) 第19题",
  stem: "He is ____ nervous ____ he moved about the room all the time.",
  options: ["such; that", "that; that", "so; that", "so; as"], answer: 2,
  explanation: "**so + 形容词/副词 + that**；such 后面要接**名词**。这里 nervous 是形容词 → 用 so...that。",
  optionNotes: ["错：such 后面要接名词，不能直接接形容词", "错：that 不能这样用", "对：so + 形容词 + that = 如此……以至于", "错：结果状语从句用 that，不用 as"] },
{ id: "mk3-20", paper: "M3", ord: 20, mock: true, level: 3, module: "grammar", topic: "word-choice",
  source: "全真模拟(三) 第20题",
  stem: "Mr. Verder never thought that he would become a member of the board of directors because of his ____ origin.",
  options: ["humble", "previous", "critical", "false"], answer: 0,
  explanation: "**humble origin** = 出身卑微。句意：由于出身卑微，他从未想过自己会成为董事会的一员。",
  optionNotes: ["对：humble = 卑微的、谦逊的", "错：previous = 先前的、以前的", "错：critical = 批评的、关键的", "错：false = 错误的、假的"] },

/* ==================== Ⅲ. 完形填空（15 题）==================== */
{ id: "mk3-21", paper: "M3", ord: 21, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(三) 完形 第21题", passageId: "M3-cloze", passage: M3_CLOZE,
  stem: "(21) 处应填：", options: ["below", "above", "near", "over"], answer: 0,
  explanation: "上文说冬天很冷、雪很大，所以气温常常**低于**零度 → below zero。" },
{ id: "mk3-22", paper: "M3", ord: 22, mock: true, level: 2, module: "cloze", topic: "cloze",
  source: "全真模拟(三) 完形 第22题", passageId: "M3-cloze",
  stem: "(22) 处应填：", options: ["April", "May", "February", "June"], answer: 2,
  explanation: "空格前是 January、后是 March，三个月份并列 → 中间只能是 February。" },
{ id: "mk3-23", paper: "M3", ord: 23, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(三) 完形 第23题", passageId: "M3-cloze",
  stem: "(23) 处应填：", options: ["the town", "the country", "the city", "the state"], answer: 1,
  explanation: "前文讲的是美国北部地区气候寒冷，这里指的是「**这个国家**的东北部和中北部地区」→ the country（指代美国）。" },
{ id: "mk3-24", paper: "M3", ord: 24, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(三) 完形 第24题", passageId: "M3-cloze",
  stem: "(24) 处应填：", options: ["among", "toward", "during", "before"], answer: 2,
  explanation: "空格后是 cold winter months，是一段较长的时间 → 用 during（在……期间）。among / toward 不用于指时间，before 指某个时间点之前。" },
{ id: "mk3-25", paper: "M3", ord: 25, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(三) 完形 第25题", passageId: "M3-cloze",
  stem: "(25) 处应填：", options: ["where", "when", "which", "that"], answer: 0,
  explanation: "这是修饰 southern parts of the country 的定语从句，从句不缺主语宾语、缺地点状语 → 关系副词 where。" },
{ id: "mk3-26", paper: "M3", ord: 26, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(三) 完形 第26题", passageId: "M3-cloze",
  stem: "(26) 处应填：", options: ["typical", "usual", "tropical", "practical"], answer: 2,
  explanation: "前文说南部气候温暖、许多人去那里，佛罗里达的气候应该是热带的 → tropical。" },
{ id: "mk3-27", paper: "M3", ord: 27, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(三) 完形 第27题", passageId: "M3-cloze",
  stem: "(27) 处应填：", options: ["get rid of", "look for", "search for", "find"], answer: 3,
  explanation: "去了那里就**找到了**干燥的沙漠气候，表结果 → find。其余三项都是「摆脱 / 寻找 / 搜寻」，语义不合。" },
{ id: "mk3-28", paper: "M3", ord: 28, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(三) 完形 第28题", passageId: "M3-cloze",
  stem: "(28) 处应填：", options: ["strange", "traditional", "common", "rare"], answer: 2,
  explanation: "下文说这已经成了老人退休后的典型做法 → common（普遍的）。" },
{ id: "mk3-29", paper: "M3", ord: 29, mock: true, level: 2, module: "cloze", topic: "cloze",
  source: "全真模拟(三) 完形 第29题", passageId: "M3-cloze",
  stem: "(29) 处应填：", options: ["when", "where", "unless", "though"], answer: 0,
  explanation: "「退休之后就搬到南方」是时间关系 → when 引导时间状语从句。" },
{ id: "mk3-30", paper: "M3", ord: 30, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(三) 完形 第30题", passageId: "M3-cloze",
  stem: "(30) 处应填：", options: ["for", "as", "to", "toward"], answer: 1,
  explanation: "**as senior citizens** = 作为老年人。介词 as 表示身份。" },
{ id: "mk3-31", paper: "M3", ord: 31, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(三) 完形 第31题", passageId: "M3-cloze",
  stem: "(31) 处应填：", options: ["of their", "of their own", "for theirs", "for their own's"], answer: 1,
  explanation: "**of one's own** = 属于某人自己的，固定搭配：homes of their own（他们自己的家）。" },
{ id: "mk3-32", paper: "M3", ord: 32, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(三) 完形 第32题", passageId: "M3-cloze",
  stem: "(32) 处应填：", options: ["nearest", "among", "away from", "far to"], answer: 2,
  explanation: "**away from** = 远离。前面说他们搬去南方，既然是搬家，那就是**远离**了自己原来生活的地方。" },
{ id: "mk3-33", paper: "M3", ord: 33, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(三) 完形 第33题", passageId: "M3-cloze",
  stem: "(33) 处应填：", options: ["born", "raised", "lost", "found"], answer: 1,
  explanation: "原书解析：born 表示「出生」，而这里说的是他们**成长**的地方 → raised（be raised = 被养大）更贴合。" },
{ id: "mk3-34", paper: "M3", ord: 34, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(三) 完形 第34题", passageId: "M3-cloze",
  stem: "(34) 处应填：", options: ["less than", "as fast as", "as slow as", "faster than"], answer: 3,
  explanation: "空格后的 **any other part** 是比较级的标志 → faster than any other part（比其他任何地区都发展得快）。" },
{ id: "mk3-35", paper: "M3", ord: 35, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(三) 完形 第35题", passageId: "M3-cloze",
  stem: "(35) 处应填：", options: ["have opened", "closed", "rebuilt", "setup"], answer: 0,
  explanation: "此处表示「在南部已经开设了许多办公室和工厂」→ have opened（现在完成时，强调对现在的影响）。" },

/* ==================== Ⅳ. 阅读理解（20 题 / 5 篇）==================== */
/* Passage One —— 拼写教学 */
{ id: "mk3-36", paper: "M3", ord: 36, mock: true, level: 4, module: "reading", topic: "reading",
  source: "全真模拟(三) 阅读 Passage One", passageId: "M3-p1", passage: M3_P1,
  stem: "Teachers are different in their opinions about ____.",
  options: ["the difficulties in teaching spelling", "the role of spelling in general language development",
            "the complexities of the basic writing skills", "the necessity of teaching spelling"], answer: 1,
  explanation: "第一段第三句说：至于怎样教孩子拼写、拼写在总体语言发展和写作能力中该被摆到多重的位置，看法却大不相同。故选 B。" },
{ id: "mk3-37", paper: "M3", ord: 37, mock: true, level: 4, module: "reading", topic: "reading",
  source: "全真模拟(三) 阅读 Passage One", passageId: "M3-p1",
  stem: "The expression \"play safe\" probably means ____.",
  options: ["to write carefully", "to do as teachers say", "to use dictionaries frequently", "to avoid using words one is not sure of"],
  answer: 3,
  explanation: "第二段紧接着解释：他会只写自己拼写范围内的词，避免用有冒险性的语言 —— 也就是「不用没把握的词」。故选 D。" },
{ id: "mk3-38", paper: "M3", ord: 38, mock: true, level: 4, module: "reading", topic: "reading",
  source: "全真模拟(三) 阅读 Passage One", passageId: "M3-p1",
  stem: "The writer seems to think that the teacher's judgement on that sensitive piece of writing is ____.",
  options: ["reasonable", "unfair", "foolish", "careless"], answer: 1,
  explanation: "第三段作者说这位老师根本没读文章内容（omitted to read the essay），却给了尖刻的批语 —— 作者认为这样的评判不公平。故选 B。" },
{ id: "mk3-39", paper: "M3", ord: 39, mock: true, level: 4, module: "reading", topic: "reading",
  source: "全真模拟(三) 阅读 Passage One", passageId: "M3-p1",
  stem: "The major point discussed in the passage is ____.",
  options: ["the importance of developing writing skills", "the complexities of spelling",
            "the correct way of marking compositions", "the relationship between spelling and the content of a composition"],
  answer: 3,
  explanation: "主旨题。通读全文，作者讨论的始终是拼写正确性与作文内容孰轻孰重的关系。故选 D。" },
/* Passage Two —— Ann 第一次坐飞机 */
{ id: "mk3-40", paper: "M3", ord: 40, mock: true, level: 3, module: "reading", topic: "reading",
  source: "全真模拟(三) 阅读 Passage Two", passageId: "M3-p2", passage: M3_P2,
  stem: "Ann thought she would be frightened because ____.",
  options: ["she had never flown before", "she had a fear of being in high places",
            "she hadn't made proper preparations", "she was naturally timid"], answer: 1,
  explanation: "第一段第二句：She had always been afraid of heights（她一向恐高），所以早就做好了害怕的准备。故选 B。" },
{ id: "mk3-41", paper: "M3", ord: 41, mock: true, level: 3, module: "reading", topic: "reading",
  source: "全真模拟(三) 阅读 Passage Two", passageId: "M3-p2",
  stem: "How was Ann sitting before the plane took off?",
  options: ["With her arms folded.", "With her seat belt undone.", "Holding tight to her seat belt.", "Holding on to part of the seat."],
  answer: 3,
  explanation: "第二段第一句：her hands gripping its arms（双手紧抓座椅扶手），扶手是座椅的一部分。故选 D。" },
{ id: "mk3-42", paper: "M3", ord: 42, mock: true, level: 3, module: "reading", topic: "reading",
  source: "全真模拟(三) 阅读 Passage Two", passageId: "M3-p2",
  stem: "Why did Ann want to scream?",
  options: ["Because the plane didn't leave the ground.", "Because she couldn't make the plane stop.",
            "Because she couldn't hear the wind.", "Because she couldn't see the runway."], answer: 1,
  explanation: "第三段：她想喊停飞机，但知道自己被困在这台轰鸣的机器里 —— 因为阻止不了飞机，所以才想尖叫。故选 B。" },
{ id: "mk3-43", paper: "M3", ord: 43, mock: true, level: 3, module: "reading", topic: "reading",
  source: "全真模拟(三) 阅读 Passage Two", passageId: "M3-p2",
  stem: "How did Ann feel after she had opened her eyes?",
  options: ["Very much pleased.", "Very much frightened.", "Greatly attracted.", "Greatly surprised."], answer: 2,
  explanation: "最后一段：她看到窗外的云海如此美丽，以致 stared in wonder、一直不肯把目光移开 —— 被深深吸引。故选 C。" },
/* Passage Three —— 财富与货币 */
{ id: "mk3-44", paper: "M3", ord: 44, mock: true, level: 4, module: "reading", topic: "reading",
  source: "全真模拟(三) 阅读 Passage Three", passageId: "M3-p3", passage: M3_P3,
  stem: "Which of the following would be the most appropriate title for the passage?",
  options: ["International Banking Policies", "The History of Monetary Exchange",
            "The Development of Paper Currencies", "Current Problems in the Economy"], answer: 1,
  explanation: "主旨题。全文按实物 → 硬币 → 纸币 → 电子货币的顺序讲货币交换的演变史。故选 B。" },
{ id: "mk3-45", paper: "M3", ord: 45, mock: true, level: 3, module: "reading", topic: "reading",
  source: "全真模拟(三) 阅读 Passage Three", passageId: "M3-p3",
  stem: "According to the passage, which of the following was the earliest kind of exchange of wealth?",
  options: ["Bartered foods.", "Fiat money.", "Coin currency.", "Intangible forms."], answer: 0,
  explanation: "第一段第一句：古时候财富是用能摸得着的东西衡量和交换的 —— 食物、工具、稀有金属和石头。四个选项里只有 A 属于这一类。故选 A。" },
{ id: "mk3-46", paper: "M3", ord: 46, mock: true, level: 3, module: "reading", topic: "reading",
  source: "全真模拟(三) 阅读 Passage Three", passageId: "M3-p3",
  stem: "According to the passage, coins once had real value as currency because they ____.",
  options: ["represented a great improvement over barter", "permitted easy transportation of wealth",
            "were made of precious metals", "could become collector's items"], answer: 2,
  explanation: "第一段第二句：硬币仍有真实价值，因为它们本身就是稀有金属做的（pieces of rare metal）。故选 C。" },
{ id: "mk3-47", paper: "M3", ord: 47, mock: true, level: 4, module: "reading", topic: "reading",
  source: "全真模拟(三) 阅读 Passage Three", passageId: "M3-p3",
  stem: "Which of the following statements about computerized monetary systems is NOT supported by the passage?",
  options: ["They promote international trade.", "They allow very rapid money transfers.",
            "They are still limited to small transactions (交易).", "They are dependent on good telecommunications systems."],
  answer: 2,
  explanation: "第二段说电子转账极快、可在不同银行公司国家之间进行、依赖计算机和电信设备 —— A、B、D 都提到了，唯独没说「仅限小额交易」。故选 C。" },
/* Passage Four —— Mr. Smith 出国疗养 */
{ id: "mk3-48", paper: "M3", ord: 48, mock: true, level: 3, module: "reading", topic: "reading",
  source: "全真模拟(三) 阅读 Passage Four", passageId: "M3-p4", passage: M3_P4,
  stem: "Mr. Smith went to see his doctor because he ____.",
  options: ["had little to eat", "was seriously ill", "had to sleep", "didn't feel well"], answer: 3,
  explanation: "第一段：他睡不好觉、吃东西也不消化，连续几夜失眠后才去看医生 —— 概括起来就是「不舒服」。故选 D。" },
{ id: "mk3-49", paper: "M3", ord: 49, mock: true, level: 3, module: "reading", topic: "reading",
  source: "全真模拟(三) 阅读 Passage Four", passageId: "M3-p4",
  stem: "In the second paragraph, the word \"gestures\" means ____.",
  options: ["body movements", "simple words", "pens or pencils", "handshakes"], answer: 0,
  explanation: "词义猜测题。第二段第二句说他不懂法语德语，只能通过 gestures 交流 —— 只能是**肢体动作**。故选 A。" },
{ id: "mk3-50", paper: "M3", ord: 50, mock: true, level: 3, module: "reading", topic: "reading",
  source: "全真模拟(三) 阅读 Passage Four", passageId: "M3-p4",
  stem: "When he traveled abroad, Mr. Smith ____.",
  options: ["learned boxing", "forgot all about his business", "raised the level of production", "shook his head all the time"],
  answer: 1,
  explanation: "第二段末：He forgot the financial crisis and the importance of raising the level of production —— 把生意上的事全忘了。故选 B。" },
{ id: "mk3-51", paper: "M3", ord: 51, mock: true, level: 3, module: "reading", topic: "reading",
  source: "全真模拟(三) 阅读 Passage Four", passageId: "M3-p4",
  stem: "In the last paragraph, the word \"temporary\" means ____.",
  options: ["lasting for a short time", "not deep", "unimportant", "developing very slowly"], answer: 0,
  explanation: "词义猜测题。最后一段说他一回国很快又变回那个焦虑的商人 —— 可见好转只是**短暂的**。故选 A。" },
/* Passage Five —— 桥上的洞 */
{ id: "mk3-52", paper: "M3", ord: 52, mock: true, level: 3, module: "reading", topic: "reading",
  source: "全真模拟(三) 阅读 Passage Five", passageId: "M3-p5", passage: M3_P5,
  stem: "What did the two towns quarrel about?",
  options: ["Which of them should mend the hole.", "Whether the hole should be mended.",
            "Why there was a hole in the bridge.", "When they should mend the hole."], answer: 0,
  explanation: "第二段第三句：两个镇都同意洞该补，分歧在于**谁来补**。故选 A。" },
{ id: "mk3-53", paper: "M3", ord: 53, mock: true, level: 3, module: "reading", topic: "reading",
  source: "全真模拟(三) 阅读 Passage Five", passageId: "M3-p5",
  stem: "The man who had fallen into the hole failed to answer any questions because he ____.",
  options: ["had one of his legs broken", "was busy changing the axle", "had drunk too much wine", "was afraid to blame anybody"],
  answer: 2,
  explanation: "第四段最后一句：he could not remember, since he got drunk that night（那晚喝醉了，记不清）。故选 C。" },
{ id: "mk3-54", paper: "M3", ord: 54, mock: true, level: 4, module: "reading", topic: "reading",
  source: "全真模拟(三) 阅读 Passage Five", passageId: "M3-p5",
  stem: "Both towns rushed to mend the hole in order to prove that ____.",
  options: ["they owned the whole bridge", "they had the right to sell the hole",
            "they were able to mend the hole", "they could afford to mend the hole"], answer: 1,
  explanation: "过路人说「只有洞的主人才有权补它，我就从补桥的人手里买这个洞」—— 抢着补桥是为了证明自己是主人、从而有权把洞卖掉。故选 B。" },
{ id: "mk3-55", paper: "M3", ord: 55, mock: true, level: 4, module: "reading", topic: "reading",
  source: "全真模拟(三) 阅读 Passage Five", passageId: "M3-p5",
  stem: "In \"Are you pulling my leg or what?\", the phrase \"pulling my leg\" refers to ____.",
  options: ["trying to stop me", "laughing at me", "putting me in trouble", "making fun of me"], answer: 3,
  explanation: "词义猜测题。洞已经被补上、不见了，过路人却装作一直在找洞 —— 这句是他的狡辩之词，pull one's leg = 开玩笑、拿人寻开心。故选 D。" },

/* ==================== Ⅴ. 补全对话（5 题 · 8 选 5 改编为四选一）==================== */
{ id: "mk3-56", paper: "M3", ord: 56, mock: true, level: 2, module: "conversation", topic: "conversation", adapted: true,
  source: "全真模拟(三) 补全对话 第56题（8选5改编为四选一）", passageId: "M3-conv", passage: M3_DLG,
  stem: "(56) 处应填：",
  options: ["reconfirm my seat", "ask a question", "please check in", "flight number"], answer: 0,
  explanation: "对方是航空公司（Northwind Airlines. Can I help you?），下文马上问姓名和航班号、最后说 Your seat is confirmed —— 所以打电话的目的就是**再次确认座位**。\n💡 I'd like to + 动词原形，四个选项里只有动词短语能接上。",
  optionNotes: ["对：I'd like to reconfirm my seat＝我想再确认一下座位，下文 Your seat is confirmed 正是回应", "错：ask a question 太空泛，与下文确认座位对不上", "错：please check in 是祈使句，接不到 I'd like to 后面", "错：flight number 是名词，不能接在 to 后面"] },
{ id: "mk3-57", paper: "M3", ord: 57, mock: true, level: 2, module: "conversation", topic: "conversation", adapted: true,
  source: "全真模拟(三) 补全对话 第57题（8选5改编为四选一）", passageId: "M3-conv",
  stem: "(57) 处应填：",
  options: ["To New York", "flight number", "On May 11th", "Hold the line"], answer: 1,
  explanation: "**看下一句的回答**：My name is Daniel Adams and my flight number is 374 —— 对方报了姓名和航班号，所以问的就是 name and flight number。\n💡 补全对话最好用的方法：空格后面那句就是答案的镜子。",
  optionNotes: ["错：目的地是后面第二次才问的", "对：下一句正好答了 name 和 flight number", "错：日期是 (58) 处的答案", "错：Hold the line 是让对方别挂机，不是提问"] },
{ id: "mk3-58", paper: "M3", ord: 58, mock: true, level: 2, module: "conversation", topic: "conversation", adapted: true,
  source: "全真模拟(三) 补全对话 第58题（8选5改编为四选一）", passageId: "M3-conv",
  stem: "(58) 处应填：",
  options: ["To New York", "Hold the line", "On May 11th", "please check in"], answer: 2,
  explanation: "上一句问 When are you leaving?（什么时候走），问的是**时间** → 只能答日期 On May 11th。\n⚠️ 特殊疑问句不能用 Yes/No 回答，也不能答非所问 —— When 问时间就只答时间。",
  optionNotes: ["错：To New York 回答的是 Where/destination", "错：Hold the line 是「请别挂机」", "对：When 问时间 → On May 11th", "错：check in 是办登机手续，答非所问"] },
{ id: "mk3-59", paper: "M3", ord: 59, mock: true, level: 2, module: "conversation", topic: "conversation", adapted: true,
  source: "全真模拟(三) 补全对话 第59题（8选5改编为四选一）", passageId: "M3-conv",
  stem: "(59) 处应填：",
  options: ["Hold the line", "May I have your name", "To New York", "reconfirm my seat"], answer: 0,
  explanation: "空后是 ...All right. Your seat is confirmed —— 中间有个停顿，说明客服在**查系统**，所以先请对方**别挂机**。\n💡 电话英语固定说法：Hold the line, please. = 请稍等、别挂机。",
  optionNotes: ["对：Hold the line, please＝请别挂机，正好对上后面查完再说 All right", "错：姓名在 (57) 处已经问过了", "错：目的地对方已答 Buenos Aires", "错：这是 (56) 处乘客说的话，不是客服说的"] },
{ id: "mk3-60", paper: "M3", ord: 60, mock: true, level: 2, module: "conversation", topic: "conversation", adapted: true,
  source: "全真模拟(三) 补全对话 第60题（8选5改编为四选一）", passageId: "M3-conv",
  stem: "(60) 处应填：",
  options: ["May I have your name", "please check in", "On May 11th", "ask a question"], answer: 1,
  explanation: "上一句乘客问「我能在办登机手续时取票吗」，客服答 Yes, but ____ at least one hour before departure time —— 但要**至少起飞前一小时办登机手续**。\n💡 but 后面一定是加条件、加限制，顺着上一句的动作往下说就对了。",
  optionNotes: ["错：姓名早就问过了", "对：呼应上一句的 check in，加上「至少提前一小时」的限制", "错：日期是 (58) 处的答案", "错：与语境无关"] },
]);
