/* ============================================================================
 * questions-mock5.js —— 全真模拟(五)整卷（60 道选择题 + 作文题）
 * 来源：用户提供的 PDF《英语全真模拟卷及答案解析（五套）》第五套（原书第 25-30 页）。
 * 逐题对照卷末【参考答案及解析】录入，解析取自原书【应试指导】。
 * ⚠️ 模拟卷，不是真题：只打 mock:true。
 * ⚠️ 补全对话第 57 题：原书把 56、57 两题的答案**都印成了 D**，8 选 5 不可能重复用。
 *    56 回应的是 "How do you like the idea..."，答 That's a good idea（D）最贴；
 *    57 回应 "What about going to the Western Hill?"，剩下能接的只有 Wonderful（B）。
 *    按语境录 B（下方注明）。
 * ========================================================================== */

window.PAPERS = (window.PAPERS || []).concat([{
  id: "M5", name: "全真模拟(五)",
  essay: "你是 Lucy，写一封给老同学 Allen 的邀请信，邀请他参加下个星期日下午 4 点（12月23日）的校友聚会。希望 Allen 尽快回信接受邀请，以便他们及时做好安排。",
}]);

var M5_CLOZE = "We were late as usual. My husband had (21)____ watering the flowers in the garden by himself, and when he discovered that he couldn't manage, he asked me for (22)____ at the last moment. So now we had only one hour to get to the airport. Luckily, there were not many cars (23)____ buses on the road and we were (24)____ to get there just in time. We checked in and went straight to the big hall to wait for our flight to be called. We waited and waited (25)____ no announcement was made. We asked for (26)____ and the girl there told us the plane hadn't even arrived yet. In the end, there came an announcement telling us that those (27)____ for flight No. 108 could get a free meal voucher and that the plane hadn't left Spain (28)____ technical problems. We thought that meant (29)____ it wasn't safe for the plane to (30)____ . We waited again for a long time until late evening when we were asked to report again. This time we were (31)____ free vouchers to spend the night in a nearby hotel.\n\nThe next morning after a (32)____ night because of all the planes taking off and landing, we were reported back to the airport. Guess (33)____ had happened while we were asleep. Our plane had arrived and taken off again. All the other (34)____ had been waken up in the night to catch the plane, but for some reasons or other we had been (35)____ . You can imagine how we felt!";

var M5_P1 = "Animals have different ways of protecting themselves against wintertime weather. Some animals grow heavy coats of fur or feathers, while others dig into the ground to find a warm wintertime home. Some animals spend the winter in a deep sleep because by going to sleep they avoid the time of the year when food is scarce and the temperatures are low. Their sleep is known as hibernation.\n\nThere is much about hibernation that puzzles scientists. For example, they are wondering how hibernation came into being. Some scientists have explored the possibility that animals release a chemical that starts them hibernating.\n\nOne thing that scientists are certain about is that animals hibernate only when it is cold. Hibernation is a seasonal practice.\n\nSome animals that fall into a wintertime sleep are not true hibernators because they spend only a part of the cold season asleep. Bears, for example, can easily be awakened from their winter nap. They are not true hibernators.\n\nSometimes it is difficult to determine whether a particular animal is a true hibernator. For example, some mice hibernate, but others do not. The same is true of bats. Some of them hibernate. Other do not.";
var M5_P2 = "The strange close understanding between twins is a familiar enough phenomenon. Often they seem to understand each other and share each other's emotions to such an extent that one suspects some kind of thought communication.\n\nWhat is not so widely known is that this special relationship often acts as brake on twins' intellectual development. As they are partly isolated in their own private world, twins communicate less with adults than do other children. The verbal ability of a four-year-old twin is typically six months behind that of a non-twin. The problem can be particularly severe in an underprivileged family, a one-parent family for example, where there is little stimulation for children anyway.\n\nSuch children, while capable of mutual comprehension in a private language, often remain incomprehensible to outsiders and thus are at a severe educational disadvantage. The only solution to the problem, cruel though it may seem, is to separate the twins thus forcing them to acquire ordinary speech helped and guided by sympathetic parents and teachers.";
var M5_P3 = "The intelligence test used most often today are based on the work of a Frenchman, Alfred Binet. In 1905, Binet was asked by the French Ministry of Education to develop a way to identify those children in French schools who were too \"mentally deficient (不足的)\" to benefit from ordinary schooling and who needed special education. The tests had to distinguish those who were merely behind in school from those who were actually mentally deficient.\n\nThe items that Binet and his colleague Theophile Simon included on the test were chosen on the basis of their ideas about intelligence. Binet and Simon believed intelligence includes such abilities as understanding the meaning of words; solving problems, and making commonsense judgements. Two other important assumptions also shaped Binet's and Simon's work: (1) that children with more intelligence will do better in school and (2) that older children have a greater ability than younger children.\n\nBinet's first test consisted of thirty tasks. They were simple things most children learn as a result of their everyday experiences. The tasks were arranged in groups, according to age. Binet decided which tasks were appropriate for a given age group by giving them first to a large number of children of different ages. If more than half of the children of a given age passed a test, it was considered appropriate for that age group.";
var M5_P4 = "How men first learned to invent words is unknown; in other words, the origin of language is a mystery. All we really know is that men, unlike animals, somehow invented certain sounds to express thoughts and feelings, actions and things, so that they could communicate with each other; and that later they agreed upon certain signs, called letters, which could be combined to represent those sounds and which could be written down. Those sounds, whether spoken, or written in letters, we call words.\n\nThe power of words, then, lies in their associations—the things they bring up before our minds. Words become filled with meaning for us by experience; and the longer we live, the more certain words recall to us the glad and sad events of our past; and the more we read and learn, the more the number of words that mean something to us increases.\n\nGreat writers are those who not only have great thoughts but also express these thoughts in words which appeal powerfully to our minds and emotions. This charming and telling use of words is what we call literary (文字的) style. Above all, the real poet is a master of words. He can convey his meaning in words which sing like music, and which by their position and association can move men to tears. We should therefore learn to choose our words carefully and use them accurately, or they will make our speech silly and rude.";
var M5_P5 = "It is customary for adults to forget how hard and dull and long school is. The learning by memory of all the basic things one must know is a most incredible and unending effort. Learning to read is probably the most difficult and revolutionary thing that happens to the human brain and if you don't believe that, watch an illiterate adult try to do it. School is not easy and it is not for the most part very much fun, but then, if you are very lucky, you may find a real teacher. Three real teachers in a lifetime is the very best of my luck. My first was a science and math teacher in high school, my second, a professor of creative writing at Stanford, and my third was my friend and partner, Ed Ricketts.\n\nMy three had these things in common: They all loved what they were doing. They did not tell; they catalyzed a burning desire to know. Under their influence, the horizons sprung wide and fear went away and the unknown became knowable. But most important of all, the truth, that dangerous stuff, became beautiful and very precious.\n\nI shall speak only of my first teacher because in addition to the other things, she brought discovery.\n\nShe aroused us to shouting, book-waving discussions. She had the noisiest class in school and she didn't even seem to know it. We could never stick to the subject. Our speculation ranged the world. She breathed curiosity into us so that we brought in facts or truths shielded in our hands like captured fireflies.\n\nI can tell my son who looks forward with horror to fifteen years of drudgery that somewhere in the dusty dark a magic may happen that will light up the years if he is very lucky.";

var M5_DLG = "Jane: How do you like the idea of having a picnic this Saturday?\nMichael: (56)____ . But where shall we go?\nJane: What about going to the Western Hill? It's quite cool there.\nMichael: (57)____ . Shall we invite John and his girlfriend to go with us?\nJane: OK. And we can ask them to prepare some drinks.\nMichael: What should I do then?\nJane: (58)____ .\nMichael: (59)____ ?\nJane: I like oranges, watermelons, grapes, and bananas.\nMichael: When shall we start off?\nJane: (60)____ ? We can get there in an hour and a half.\nMichael: OK. I'll call John and tell him about our plan.";

window.QUESTIONS = (window.QUESTIONS || []).concat([

/* ==================== Ⅰ. 语音（5 题）==================== */
{ id: "mk5-01", paper: "M5", ord: 1, mock: true, level: 3, module: "phonetics", topic: "phonetics-ie",
  source: "全真模拟(五) 第1题", stem: "选出划线部分读音与其它三个不同的一项：",
  options: ["t__ie__", "l__ie__", "f__ie__ld", "d__ie__"], answer: 2,
  explanation: "tie / lie / die 里的 ie 读 /aɪ/，只有 field 读 /iː/。" },
{ id: "mk5-02", paper: "M5", ord: 2, mock: true, level: 3, module: "phonetics", topic: "phonetics-ere",
  source: "全真模拟(五) 第2题", stem: "选出划线部分读音与其它三个不同的一项：",
  options: ["sinc__ere__", "th__ere__", "m__ere__", "h__ere__"], answer: 1,
  explanation: "sincere / mere / here 里的 ere 读 /ɪə/，只有 there 读 /eə/。" },
{ id: "mk5-03", paper: "M5", ord: 3, mock: true, level: 3, module: "phonetics", topic: "phonetics-ar",
  source: "全真模拟(五) 第3题", stem: "选出划线部分读音与其它三个不同的一项：",
  options: ["c__ar__", "f__ar__", "w__ar__", "st__ar__"], answer: 2,
  explanation: "car / far / star 里的 ar 读 /ɑː/，只有 war 读 /ɔː/（w 后面的 ar 常变音）。" },
{ id: "mk5-04", paper: "M5", ord: 4, mock: true, level: 3, module: "phonetics", topic: "phonetics-ay",
  source: "全真模拟(五) 第4题", stem: "选出划线部分读音与其它三个不同的一项：",
  options: ["pl__ays__", "d__ays__", "s__ays__", "p__ays__"], answer: 2,
  explanation: "plays / days / pays 里读 /eɪz/，只有 says 读 /ez/ —— say 的第三人称单数是个著名的例外。" },
{ id: "mk5-05", paper: "M5", ord: 5, mock: true, level: 3, module: "phonetics", topic: "phonetics-a",
  source: "全真模拟(五) 第5题", stem: "选出划线部分读音与其它三个不同的一项：",
  options: ["w__a__ll", "sh__a__ll", "f__a__ll", "c__a__ll"], answer: 1,
  explanation: "wall / fall / call 里的 a 读 /ɔː/，只有 shall 读 /æ/。" },

/* ==================== Ⅱ. 词汇与语法（15 题）==================== */
{ id: "mk5-06", paper: "M5", ord: 6, mock: true, level: 2, module: "grammar", topic: "collocation",
  source: "全真模拟(五) 第6题",
  stem: "Does everyone on earth have an equal right ____ an equal share of its resources?",
  options: ["by", "at", "to", "over"], answer: 2,
  explanation: "**right to sth.** = ……的权利，固定搭配。",
  optionNotes: ["错：没有 right by 这个搭配", "错：没有 right at 这个搭配", "对：right to = ……的权利", "错：没有 right over 这个搭配"] },
{ id: "mk5-07", paper: "M5", ord: 7, mock: true, level: 3, module: "grammar", topic: "word-choice",
  source: "全真模拟(五) 第7题",
  stem: "This ticket ____ you to a free meal in our new restaurant.",
  options: ["gives", "grants", "entitles", "credits"], answer: 2,
  explanation: "**entitle sb. to sth.** = 使某人有权（享有）……。只有它能接「sb. + to + sth.」这个结构。",
  optionNotes: ["错：give 要说 give sb. sth. 或 give sth. to sb.", "错：grant 要说 grant sb. sth.", "对：entitle sb. to sth. = 使某人有资格获得", "错：credit sb. with sth. 是信任、把……归功于"] },
{ id: "mk5-08", paper: "M5", ord: 8, mock: true, level: 4, module: "grammar", topic: "modal-verb",
  source: "全真模拟(五) 第8题",
  stem: "You ____ her in her office last Friday; she's been out of town for two weeks.",
  options: ["needn't have seen", "must have seen", "might have seen", "can't have seen"], answer: 3,
  explanation: "她已经出城两周了，所以上周五**不可能**在办公室见到她 → **can't have done** = 对过去的否定推测。\n💡 这一组要背死：must have done（一定做过）↔ can't have done（不可能做过），互为反义。",
  optionNotes: ["错：needn't have done = 本不必做却做了，语义不合", "错：must have seen 是肯定推测，与「出城两周」矛盾", "错：might have seen = 可能见过，语气太弱，不合「不可能」的语境", "对：can't have seen = 不可能见过，正是 must have done 的否定"] },
{ id: "mk5-09", paper: "M5", ord: 9, mock: true, level: 4, module: "grammar", topic: "collocation",
  source: "全真模拟(五) 第9题",
  stem: "That was so serious a matter that I had no choice but ____ the police.",
  options: ["called in", "calling in", "call in", "to call in"], answer: 3,
  explanation: "**have no choice but + 带 to 的不定式** = 除了……别无选择。\n⚠️ 别和另一个结构搞混：**have nothing to do but + 不带 to 的原形**。前面出现过 do 才省 to。",
  optionNotes: ["错：but 后面要接不定式，不能用过去式", "错：but 后面不接动名词", "错：只有 have nothing to do but 才用不带 to 的原形", "对：have no choice but to do sth."] },
{ id: "mk5-10", paper: "M5", ord: 10, mock: true, level: 2, module: "grammar", topic: "collocation",
  source: "全真模拟(五) 第10题",
  stem: "She was so ____ in her job that she didn't hear anybody knocking at the door.",
  options: ["attracted", "absorbed", "drawn", "concentrated"], answer: 1,
  explanation: "**be absorbed in** = 专心致志于，固定搭配。其余三个都不与 in 这样搭配（concentrate 要说 concentrate **on**）。",
  optionNotes: ["错：be attracted **to/by**，不是 in", "对：be absorbed in = 全神贯注于", "错：be drawn to，不是 in", "错：要说 concentrate on，不是 concentrated in"] },
{ id: "mk5-11", paper: "M5", ord: 11, mock: true, level: 4, module: "grammar", topic: "non-finite",
  source: "全真模拟(五) 第11题",
  stem: "I haven't decided which hotel ____.",
  options: ["to stay", "is to stay at", "to stay at", "is for staying"], answer: 2,
  explanation: "**疑问词 + 不定式** 作宾语（which hotel to stay at）。注意 stay 是不及物动词，后面必须补介词 **at**，否则 hotel 无处安放。",
  optionNotes: ["错：stay 不及物，缺介词 at", "错：多了 is，结构不对", "对：which hotel to stay at，疑问词+不定式且补齐了介词", "错：结构不成立"] },
{ id: "mk5-12", paper: "M5", ord: 12, mock: true, level: 4, module: "grammar", topic: "emphasis",
  source: "全真模拟(五) 第12题",
  stem: "It was not until midnight ____ they reached the campsite.",
  options: ["when", "that", "while", "as"], answer: 1,
  explanation: "**It is/was + 被强调部分 + that + 其余成分** 是强调句。这里强调 not until midnight，所以只能用 **that**。还原后是：They didn't reach the campsite until midnight.\n💡 判断是不是强调句：把 It was ... that 去掉，剩下的还是完整句子，就是强调句。",
  optionNotes: ["错：强调句的连接词只能是 that / who，不能用 when", "对：It was + 被强调部分 + that + 其余", "错：while 不用于强调句", "错：as 不用于强调句"] },
{ id: "mk5-13", paper: "M5", ord: 13, mock: true, level: 4, module: "grammar", topic: "subjunctive",
  source: "全真模拟(五) 第13题",
  stem: "It is politely requested by the hotel management that radios ____ after 11 o'clock at night.",
  options: ["were not played", "not to play", "not be played", "did not play"], answer: 2,
  explanation: "**request** 后面的从句要用虚拟语气 **should + 动词原形**，should 可省略；又因为收音机是「被播放」→ 被动 be played。合起来就是 (should) not be played。",
  optionNotes: ["错：虚拟语气不用过去式", "错：从句要用完整的谓语，不是不定式", "对：(should) not be played —— 虚拟 + 被动，should 省略", "错：既不是虚拟语气，也没体现被动"] },
{ id: "mk5-14", paper: "M5", ord: 14, mock: true, level: 3, module: "grammar", topic: "word-choice",
  source: "全真模拟(五) 第14题",
  stem: "Although I like the appearance of the house, what really made me decide to buy it was the beautiful ____ through the window.",
  options: ["vision", "look", "picture", "view"], answer: 3,
  explanation: "**view** = （从某处看出去的）景色、风景。「透过窗户看到的美景」只能用 view。",
  optionNotes: ["错：vision 是视力、视野、幻象", "错：look 是神色、看一眼", "错：picture 是图画、画面", "对：view = 从窗口望出去的景色"] },
{ id: "mk5-15", paper: "M5", ord: 15, mock: true, level: 4, module: "grammar", topic: "conjunction",
  source: "全真模拟(五) 第15题",
  stem: "Make a note of it ____ you should forget it.",
  options: ["so", "to", "how", "lest"], answer: 3,
  explanation: "**lest** = 免得、以免，后面接虚拟语气（should + 原形，should 可省）。句意：把它记下来，免得你忘了。",
  optionNotes: ["错：so 表结果，不表「以免」", "错：to 不能引导从句", "错：how 表方式", "对：lest = 免得，正好呼应从句里的 should"] },
{ id: "mk5-16", paper: "M5", ord: 16, mock: true, level: 4, module: "grammar", topic: "relative-clause",
  source: "全真模拟(五) 第16题",
  stem: "Many children, ____ parents are away working in big cities, are taken good care of in the village.",
  options: ["of them", "whose", "their", "with whom"], answer: 1,
  explanation: "这是非限制性定语从句，从句里 parents 前面缺一个「谁的」→ 用 **whose**（关系代词作定语）。\n💡 定语从句选词只看从句缺什么：缺主语/宾语用 that/which/who；**缺定语（「……的」）用 whose**；缺状语用 where/when/why。",
  optionNotes: ["错：of them 不能引导从句（会变成两个句子逗号相连）", "对：whose parents = 他们的父母，whose 在从句里作定语", "错：their 是代词，不能引导从句", "错：with whom 后面要跟完整句子，且语义不通"] },
{ id: "mk5-17", paper: "M5", ord: 17, mock: true, level: 2, module: "grammar", topic: "collocation",
  source: "全真模拟(五) 第17题",
  stem: "The manager needs an assistant that he can ____ to take care of problems in his absence.",
  options: ["count on", "count in", "count up", "count out"], answer: 0,
  explanation: "**count on** = 依靠、指望。经理需要一个他不在时可以**指望**的助手。",
  optionNotes: ["对：count on = 依靠、指望", "错：count in = 把……计算在内", "错：count up = 加起来", "错：count out = 逐个数出、不把……算在内"] },
{ id: "mk5-18", paper: "M5", ord: 18, mock: true, level: 4, module: "grammar", topic: "inversion",
  source: "全真模拟(五) 第18题",
  stem: "The organization had broken no rules, but ____ had it acted responsibly.",
  options: ["neither", "so", "either", "both"], answer: 0,
  explanation: "空后是倒装结构（had it acted），说明空里要填一个引起倒装的否定词。前半句是**否定**（had broken no rules），后半句表示「也不」→ **neither**。\n⚠️ so + 倒装 用在**前半句是肯定**的时候，这里前半句是否定，所以 so 错。",
  optionNotes: ["对：前否定 + neither + 倒装 = 也不", "错：so + 倒装要求前半句是肯定句", "错：either 表「也不」时放句末，不引起倒装", "错：both 不引起倒装"] },
{ id: "mk5-19", paper: "M5", ord: 19, mock: true, level: 2, module: "grammar", topic: "collocation",
  source: "全真模拟(五) 第19题",
  stem: "We gave out a cheer when the red roof of the cottage came ____ view.",
  options: ["from", "in", "before", "into"], answer: 3,
  explanation: "**come into view** = 进入视线、映入眼帘，固定搭配。",
  optionNotes: ["错：没有 come from view 这个搭配", "错：in view 是「在视野内」的静态，这里是动态进入", "错：没有 come before view 这个搭配", "对：come into view = 出现在眼前"] },
{ id: "mk5-20", paper: "M5", ord: 20, mock: true, level: 3, module: "grammar", topic: "word-choice",
  source: "全真模拟(五) 第20题",
  stem: "They took ____ measures to prevent poisonous gases from escaping.",
  options: ["fruitful", "beneficial", "valuable", "effective"], answer: 3,
  explanation: "**take effective measures** = 采取有效措施，固定说法。effective 强调「能产生预期效果的」。",
  optionNotes: ["错：fruitful = 硕果累累的、成效大的（多指成果）", "错：beneficial = 对……有益的（常跟 to）", "错：valuable = 有价值的、贵重的", "对：effective measures = 有效的措施"] },

/* ==================== Ⅲ. 完形填空（15 题）==================== */
{ id: "mk5-21", paper: "M5", ord: 21, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(五) 完形 第21题", passageId: "M5-cloze", passage: M5_CLOZE,
  stem: "(21) 处应填：", options: ["stopped", "insisted on", "finished", "given"], answer: 1,
  explanation: "A、B、C 后面都能跟 v.-ing，但此处意为「我丈夫**坚持**自己浇花园里的花（结果搞不定才来求我）」→ insisted on。" },
{ id: "mk5-22", paper: "M5", ord: 22, mock: true, level: 2, module: "cloze", topic: "cloze",
  source: "全真模拟(五) 完形 第22题", passageId: "M5-cloze",
  stem: "(22) 处应填：", options: ["food", "advice", "praise", "help"], answer: 3,
  explanation: "自己搞不定，当然是**求助** → ask sb. for help。" },
{ id: "mk5-23", paper: "M5", ord: 23, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(五) 完形 第23题", passageId: "M5-cloze",
  stem: "(23) 处应填：", options: ["and", "but", "or", "since"], answer: 2,
  explanation: "「路上既没有很多小轿车也没有很多公共汽车」—— **否定词后面用 or 表示「也不」**，不用 and。" },
{ id: "mk5-24", paper: "M5", ord: 24, mock: true, level: 2, module: "cloze", topic: "cloze",
  source: "全真模拟(五) 完形 第24题", passageId: "M5-cloze",
  stem: "(24) 处应填：", options: ["impossible", "necessary", "able", "unable"], answer: 2,
  explanation: "**be able to do sth.** = 能够做某事。路上不堵，所以刚好赶到了。" },
{ id: "mk5-25", paper: "M5", ord: 25, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(五) 完形 第25题", passageId: "M5-cloze",
  stem: "(25) 处应填：", options: ["so", "but", "otherwise", "if"], answer: 1,
  explanation: "「我们一直等一直等，**可是**没有任何通知」—— 前后是转折关系 → but。" },
{ id: "mk5-26", paper: "M5", ord: 26, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(五) 完形 第26题", passageId: "M5-cloze",
  stem: "(26) 处应填：", options: ["time", "advice", "help", "information"], answer: 3,
  explanation: "「我们去询问**消息**」→ ask for information，下一句「那个女孩告诉我们飞机还没到」正是给出的消息。" },
{ id: "mk5-27", paper: "M5", ord: 27, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(五) 完形 第27题", passageId: "M5-cloze",
  stem: "(27) 处应填：", options: ["coming", "sitting", "waiting", "working"], answer: 2,
  explanation: "those **waiting** for flight No. 108 = 等 108 次航班的人。wait for = 等候。" },
{ id: "mk5-28", paper: "M5", ord: 28, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(五) 完形 第28题", passageId: "M5-cloze",
  stem: "(28) 处应填：", options: ["for", "since", "because", "from"], answer: 0,
  explanation: "for、since、because 都能表原因，但 **since / because 后面要接句子**，而这里后面是名词短语 technical problems → 只能用介词 **for**。" },
{ id: "mk5-29", paper: "M5", ord: 29, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(五) 完形 第29题", passageId: "M5-cloze",
  stem: "(29) 处应填：", options: ["when", "which", "what", "that"], answer: 3,
  explanation: "that 引导宾语从句（meant that...），且在从句中**不作任何成分** —— 从句 it wasn't safe... 本身是完整的。" },
{ id: "mk5-30", paper: "M5", ord: 30, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(五) 完形 第30题", passageId: "M5-cloze",
  stem: "(30) 处应填：", options: ["repair", "sell", "fly", "telephone"], answer: 2,
  explanation: "「飞机飞行会不安全」→ it wasn't safe for the plane to fly。" },
{ id: "mk5-31", paper: "M5", ord: 31, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(五) 完形 第31题", passageId: "M5-cloze",
  stem: "(31) 处应填：", options: ["giving", "given", "offering", "taken"], answer: 1,
  explanation: "we were ____ free vouchers —— 我们是**被**给了免费券，被动语态用过去分词 → given。" },
{ id: "mk5-32", paper: "M5", ord: 32, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(五) 完形 第32题", passageId: "M5-cloze",
  stem: "(32) 处应填：", options: ["bad", "quiet", "sweet", "pleasant"], answer: 0,
  explanation: "空后紧跟原因：because of all the planes taking off and landing（飞机起降的噪音）—— 那一夜当然过得**糟糕**。" },
{ id: "mk5-33", paper: "M5", ord: 33, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(五) 完形 第33题", passageId: "M5-cloze",
  stem: "(33) 处应填：", options: ["what", "where", "it", "that"], answer: 0,
  explanation: "Guess ____ had happened —— 宾语从句里**缺主语** → 用 what（它自己充当主语）。这就是 what 和 that 的分界线。" },
{ id: "mk5-34", paper: "M5", ord: 34, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(五) 完形 第34题", passageId: "M5-cloze",
  stem: "(34) 处应填：", options: ["workers", "planes", "passengers", "flights"], answer: 2,
  explanation: "「所有**别的乘客**都被叫醒赶飞机了」→ passengers。" },
{ id: "mk5-35", paper: "M5", ord: 35, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(五) 完形 第35题", passageId: "M5-cloze",
  stem: "(35) 处应填：", options: ["woken", "announced", "lost", "forgotten"], answer: 3,
  explanation: "别人都被叫醒了，唯独我们没有 —— 「不知什么原因我们**被忘了**」→ forgotten，正好解释了最后一句 You can imagine how we felt!" },

/* ==================== Ⅳ. 阅读理解（20 题 / 5 篇）==================== */
{ id: "mk5-36", paper: "M5", ord: 36, mock: true, level: 3, module: "reading", topic: "reading",
  source: "全真模拟(五) 阅读 Passage One", passageId: "M5-p1", passage: M5_P1,
  stem: "Hibernation is a seasonal practice. This means it ____.",
  options: ["takes place only during a particular season", "occurs only during the night",
            "is a daily practice", "only happens when a species becomes over-populated"], answer: 0,
  explanation: "既然是 seasonal practice（季节性的做法），那就是只发生在特定季节。故选 A。" },
{ id: "mk5-37", paper: "M5", ord: 37, mock: true, level: 3, module: "reading", topic: "reading",
  source: "全真模拟(五) 阅读 Passage One", passageId: "M5-p1",
  stem: "Some scientists believe that hibernation is started by ____.",
  options: ["over-eating", "calcium deposits", "a body chemical", "a lack of water"], answer: 2,
  explanation: "第二段最后一句：animals release a chemical that starts them hibernating（动物释放一种化学物质引发冬眠）。故选 C。" },
{ id: "mk5-38", paper: "M5", ord: 38, mock: true, level: 3, module: "reading", topic: "reading",
  source: "全真模拟(五) 阅读 Passage One", passageId: "M5-p1",
  stem: "The underlined word \"hibernation\" in paragraph 1 means ____.",
  options: ["a sleep to avoid eating", "a temperature in cold weather",
            "a sleep in the cold season", "an animal to practice sleep in winter"], answer: 2,
  explanation: "词义猜测题。第一段倒数第二句就是对它的解释：动物在冬季食物匮乏、气温低时进入深度睡眠 —— 就是「寒冷季节里的睡眠」。故选 C。" },
{ id: "mk5-39", paper: "M5", ord: 39, mock: true, level: 4, module: "reading", topic: "reading",
  source: "全真模拟(五) 阅读 Passage One", passageId: "M5-p1",
  stem: "The main idea of this passage is that ____.",
  options: ["many animals die during hibernation", "hibernation protects animals during the wintertime",
            "scientists feel puzzled about hibernation", "some bats hibernate and others do not"], answer: 2,
  explanation: "主旨题。文章首段引出 hibernation，后面几段全在讲科学家对它的种种不解（puzzles / wondering / difficult to determine）。故选 C。" },
{ id: "mk5-40", paper: "M5", ord: 40, mock: true, level: 4, module: "reading", topic: "reading",
  source: "全真模拟(五) 阅读 Passage Two", passageId: "M5-p2", passage: M5_P2,
  stem: "Many people don't know that ____.",
  options: ["twins understand each other very well", "twins are slow to learn to talk",
            "twins are unlikely to do less well at school than other children", "there exists more communication between twins"],
  answer: 1,
  explanation: "第二段开头 What is not so widely known is that... 后面说双胞胎语言能力比同龄人落后半年 —— 「很多人不知道」的正是这一点。故选 B。" },
{ id: "mk5-41", paper: "M5", ord: 41, mock: true, level: 4, module: "reading", topic: "reading",
  source: "全真模拟(五) 阅读 Passage Two", passageId: "M5-p2",
  stem: "What's the reason for twins to be at a disadvantage in their intellectual development?",
  options: ["They can only understand their own private language.", "They communicate with outsiders less than non-twins.",
            "There is little stimulation for them.", "Adults don't like to talk with them."], answer: 1,
  explanation: "第二段第二句：双胞胎部分地活在自己的小世界里，**与成年人交流比其他孩子少** —— 这才是智力发展受阻的原因。故选 B。" },
{ id: "mk5-42", paper: "M5", ord: 42, mock: true, level: 4, module: "reading", topic: "reading",
  source: "全真模拟(五) 阅读 Passage Two", passageId: "M5-p2",
  stem: "The author probably feels that twins' problem ____.",
  options: ["can not be solved because solution is very cruel", "can be solved because twins will be separated",
            "can not be solved unless the twins are forced to live in an ordinary environment",
            "can be solved if the adults communicate with them more often"], answer: 2,
  explanation: "最后一句：唯一的解决办法（虽然看似残酷）是把双胞胎分开，迫使他们学会普通的说话方式 —— 也就是必须让他们进入普通环境。故选 C。" },
{ id: "mk5-43", paper: "M5", ord: 43, mock: true, level: 4, module: "reading", topic: "reading",
  source: "全真模拟(五) 阅读 Passage Two", passageId: "M5-p2",
  stem: "The writer mentions all of the items listed below EXCEPT ____.",
  options: ["twins can help each other", "twins share each other's emotion",
            "twins are able to understand each other in a private language", "twins communicate less with their parents"],
  answer: 0,
  explanation: "文中提到了共享情感、用私密语言互相理解、与成年人交流少 —— 唯独没有提「双胞胎能互相帮助」。故选 A。" },
{ id: "mk5-44", paper: "M5", ord: 44, mock: true, level: 4, module: "reading", topic: "reading",
  source: "全真模拟(五) 阅读 Passage Three", passageId: "M5-p3", passage: M5_P3,
  stem: "The main purpose of this passage is to ____.",
  options: ["tell the origin of intelligence tests", "explain the basic principle of intelligence tests",
            "describe the changes in the content of intelligence tests", "state the development of intelligence tests"],
  answer: 0,
  explanation: "主旨题。全文讲的是法国人 Alfred Binet 如何开始做智力测试 —— 目的是告诉我们智力测试的**起源**。故选 A。" },
{ id: "mk5-45", paper: "M5", ord: 45, mock: true, level: 3, module: "reading", topic: "reading",
  source: "全真模拟(五) 阅读 Passage Three", passageId: "M5-p3",
  stem: "What was the purpose of the intelligence test designed by Alfred Binet in 1905?",
  options: ["To select top students.", "To know who had received ordinary schooling.",
            "To put students in a right order.", "To make sure who required particular treatment."], answer: 3,
  explanation: "第一段：法国教育部请他开发一种方法，找出那些智力不足、**需要特殊教育**的孩子。故选 D。" },
{ id: "mk5-46", paper: "M5", ord: 46, mock: true, level: 4, module: "reading", topic: "reading",
  source: "全真模拟(五) 阅读 Passage Three", passageId: "M5-p3",
  stem: "Which of the following is NOT true according to the passage?",
  options: ["Intelligence includes word understanding and problem solving.",
            "More intelligent children usually do better in school.",
            "The French Ministry of Education was charged with the development of first intelligence tests.",
            "Intelligence is related with age."], answer: 2,
  explanation: "A、B、D 文中都有。第一段只说教育部**委托** Binet 开发，并没有说教育部自己负责完成 —— C 项与原文不符。故选 C。" },
{ id: "mk5-47", paper: "M5", ord: 47, mock: true, level: 4, module: "reading", topic: "reading",
  source: "全真模拟(五) 阅读 Passage Three", passageId: "M5-p3",
  stem: "How did Binet decide which task to include on his first test?",
  options: ["He first worked out thirty tasks for mentally deficient children.",
            "He first gave all the tasks to many children both younger and older.",
            "He first gave the tasks to many children he thought appropriate.",
            "He first gave some of the tasks to different groups of children."], answer: 1,
  explanation: "最后一段倒数第二句：他把事先设计好的全部测试题发给**不同年龄**的大量孩子，据此确定哪些题适合哪个年龄段。故选 B。" },
{ id: "mk5-48", paper: "M5", ord: 48, mock: true, level: 4, module: "reading", topic: "reading",
  source: "全真模拟(五) 阅读 Passage Four", passageId: "M5-p4", passage: M5_P4,
  stem: "The origin of language ____.",
  options: ["is a legend handed down from the past", "is reflected in sounds and letters",
            "dates back to the prehistoric period", "is a problem not yet solved"], answer: 3,
  explanation: "第一段第一句：人类最初如何创造词语无人知晓，**语言的起源是个谜**（a mystery）—— 也就是尚未解决的问题。故选 D。" },
{ id: "mk5-49", paper: "M5", ord: 49, mock: true, level: 3, module: "reading", topic: "reading",
  source: "全真模拟(五) 阅读 Passage Four", passageId: "M5-p4",
  stem: "One of the reasons why men invented certain sounds to express thoughts and actions is that ____.",
  options: ["they could agree upon certain signs", "they could write them down",
            "they could communicate with each other", "they could combine them"], answer: 2,
  explanation: "第一段第二句明写目的：so that they could **communicate with each other**。故选 C。" },
{ id: "mk5-50", paper: "M5", ord: 50, mock: true, level: 3, module: "reading", topic: "reading",
  source: "全真模拟(五) 阅读 Passage Four", passageId: "M5-p4",
  stem: "What is true about words?",
  options: ["They are used to express feelings only.", "They can not be written down.",
            "They are represented either by sounds or letters.", "They are visual letters."], answer: 2,
  explanation: "第一段最后一句：Those sounds, whether spoken, or written in letters, we call words —— 词语既可以是声音，也可以是字母。故选 C。" },
{ id: "mk5-51", paper: "M5", ord: 51, mock: true, level: 4, module: "reading", topic: "reading",
  source: "全真模拟(五) 阅读 Passage Four", passageId: "M5-p4",
  stem: "The real power of words exists in their ____.",
  options: ["accuracy", "beauty", "charm", "representative function"], answer: 3,
  explanation: "第二段第一句：The power of words lies in their associations—the things they bring up before our minds —— 词的力量在于它的**指代／联想功能**。故选 D。" },
{ id: "mk5-52", paper: "M5", ord: 52, mock: true, level: 3, module: "reading", topic: "reading",
  source: "全真模拟(五) 阅读 Passage Five", passageId: "M5-p5", passage: M5_P5,
  stem: "According to the author, what is the difficult thing to people in school?",
  options: ["Listening.", "Reading.", "Writing.", "Speaking."], answer: 1,
  explanation: "第一段第三句：Learning to read is probably the most difficult and revolutionary thing... —— 学阅读是最难的。故选 B。" },
{ id: "mk5-53", paper: "M5", ord: 53, mock: true, level: 3, module: "reading", topic: "reading",
  source: "全真模拟(五) 阅读 Passage Five", passageId: "M5-p5",
  stem: "The very best of the author is that he ____.",
  options: ["met a good teacher", "he graduated from Stanford",
            "made friends with his teachers", "met some good teachers in his life"], answer: 3,
  explanation: "第一段：Three real teachers in a lifetime is the very best of my luck —— 最大的幸运是一生中遇到过几位好老师。故选 D。" },
{ id: "mk5-54", paper: "M5", ord: 54, mock: true, level: 4, module: "reading", topic: "reading",
  source: "全真模拟(五) 阅读 Passage Five", passageId: "M5-p5",
  stem: "Among his teachers, ____ left him a very deep impression.",
  options: ["the university teacher", "the high school teacher", "Ed Ricketts", "the first two teachers"], answer: 1,
  explanation: "第三段开头：I shall speak only of my first teacher because... she brought discovery —— 而第一位老师正是中学的理化和数学老师。故选 B。" },
{ id: "mk5-55", paper: "M5", ord: 55, mock: true, level: 4, module: "reading", topic: "reading",
  source: "全真模拟(五) 阅读 Passage Five", passageId: "M5-p5",
  stem: "The author hoped that his son ____.",
  options: ["may be lucky to meet a good teacher", "may study in school for fifteen years",
            "can read many books", "may study science and math"], answer: 0,
  explanation: "最后一段：他告诉儿子，如果足够幸运，在漫长枯燥的求学路上某处会发生一种魔法照亮岁月 —— 也就是希望他能幸运地遇到好老师。故选 A。" },

/* ==================== Ⅴ. 补全对话（5 题 · 8 选 5 改编为四选一）==================== */
{ id: "mk5-56", paper: "M5", ord: 56, mock: true, level: 2, module: "conversation", topic: "conversation", adapted: true,
  source: "全真模拟(五) 补全对话 第56题（8选5改编为四选一）", passageId: "M5-conv", passage: M5_DLG,
  stem: "(56) 处应填：",
  options: ["That's a good idea", "I'll say I did", "What kind of fruit do you like", "I'll be there"], answer: 0,
  explanation: "上一句 How do you like **the idea** of having a picnic? —— 问的就是对这个**主意**的看法，回答直接接 That's a good idea 最自然，而且下半句 But where shall we go? 说明是先赞成再往下商量。\n💡 「How do you like...?」= 你觉得……怎么样，是征求意见，先表态再补充。",
  optionNotes: ["对：That's a good idea 直接呼应上一句的 the idea", "错：I'll say I did 是对过去做没做的回应，时态和语境都不对", "错：这是 (59) 处的问句", "错：I'll be there 是答应赴约，这里还没定地点"] },
{ id: "mk5-57", paper: "M5", ord: 57, mock: true, level: 2, module: "conversation", topic: "conversation", adapted: true,
  source: "全真模拟(五) 补全对话 第57题（⚠️原书 56、57 答案都印成 D，8选5 不可能重复，按语境录 Wonderful）",
  passageId: "M5-conv",
  stem: "(57) 处应填：",
  options: ["Yes, it was", "Wonderful", "I'll be there", "That's a good idea"], answer: 1,
  explanation: "上一句 What about going to the Western Hill? It's quite cool there. —— 对方提议地点并夸了一句，这里用一个词表示赞同：Wonderful.（好极了）\n⚠️ 原书把 56、57 的答案都印成了 D（That's a good idea），但 8 选 5 每个选项只能用一次，属印刷错误；56 处已用掉 D，57 只能是 Wonderful。",
  optionNotes: ["错：Yes, it was 是对过去时提问的回答，这里是提议", "对：Wonderful＝好极了，回应对方的提议", "错：I'll be there 用于答应到场，不是回应提议", "错：这句在 (56) 处已经用过了"] },
{ id: "mk5-58", paper: "M5", ord: 58, mock: true, level: 2, module: "conversation", topic: "conversation", adapted: true,
  source: "全真模拟(五) 补全对话 第58题（8选5改编为四选一）", passageId: "M5-conv",
  stem: "(58) 处应填：",
  options: ["Wonderful", "You'd better buy some fruit and sandwiches", "How about 6 o'clock in the morning", "Yes, it was"],
  answer: 1,
  explanation: "上一句 Michael 问 What should I do then?（那我该做什么），要的是**具体分工** → 让他买水果和三明治。而且下一句他接着问「你喜欢什么水果」，正好印证这里提到了 fruit。\n💡 前后一起看：空格前问什么、空格后接什么，两头都对得上才是答案。",
  optionNotes: ["错：Wonderful 是感叹，没有回答「我该做什么」", "对：给出具体任务，且下一句的 fruit 正是从这里来的", "错：时间是 (60) 处才商量的", "错：答非所问"] },
{ id: "mk5-59", paper: "M5", ord: 59, mock: true, level: 2, module: "conversation", topic: "conversation", adapted: true,
  source: "全真模拟(五) 补全对话 第59题（8选5改编为四选一）", passageId: "M5-conv",
  stem: "(59) 处应填：",
  options: ["I'll be there", "How about 6 o'clock in the morning", "What kind of fruit do you like", "I'll say I did"],
  answer: 2,
  explanation: "**看下一句**：I like oranges, watermelons, grapes, and bananas —— 全是水果，所以问的是「你喜欢什么水果」。而且空格后是问号，这里必须填问句。",
  optionNotes: ["错：不是问句，也接不上下一句的水果清单", "错：这是 (60) 处商量时间用的", "对：下一句列举的水果正是对它的回答", "错：不是问句，语义也不通"] },
{ id: "mk5-60", paper: "M5", ord: 60, mock: true, level: 2, module: "conversation", topic: "conversation", adapted: true,
  source: "全真模拟(五) 补全对话 第60题（8选5改编为四选一）", passageId: "M5-conv",
  stem: "(60) 处应填：",
  options: ["How about 6 o'clock in the morning", "I'll be there", "Wonderful", "You'd better buy some fruit and sandwiches"],
  answer: 0,
  explanation: "上一句 When shall we start off?（几点出发）问的是**时间**，空格后又说 We can get there in an hour and a half（一个半小时能到）—— 所以这里要给一个具体钟点。\n💡 **How about + 名词/doing** 是提建议的万能句式，补全对话和写作里都是高频送分点。",
  optionNotes: ["对：How about 6 o'clock in the morning? 给出具体出发时间", "错：I'll be there 是答应到场，没回答几点", "错：Wonderful 是感叹，不回答时间", "错：买东西的分工前面已经说过了"] },
]);
