/* ============================================================================
 * questions-mock4.js —— 全真模拟(四)整卷（60 道选择题 + 作文题）
 * 来源：用户提供的 PDF《英语全真模拟卷及答案解析（五套）》第四套（原书第 19-24 页）。
 * 逐题对照卷末【参考答案及解析】录入，解析取自原书【应试指导】。
 * ⚠️ 模拟卷，不是真题：只打 mock:true。
 * ========================================================================== */

window.PAPERS = (window.PAPERS || []).concat([{
  id: "M4", name: "全真模拟(四)",
  essay: "10月27日（星期六），你和同学参观了清华大学，请根据下列内容用英语写篇日记。内容应包括：老教授的热情接待，参观了图书馆、实验楼和校园等。可以适当增减细节。",
}]);

var M4_CLOZE = "Scientists who study the brain have found out a great deal about how we learn. They have (21)____ that babies learn much more from the sights and sounds around them than we (22)____ before. You can help your baby by taking advantage of her hunger to learn.\n\nFrom the (23)____ beginning, babies try to imitate the (24)____ they hear us make. They \"read\" the (25)____ on our faces and our movements. That is (26)____ it is so important to talk, sing and smile to your child. Hearing you talk is your baby's first (27)____ toward becoming a reader, because it (28)____ her to love language and to learn words.\n\nAs your child grows older, (29)____ talking with her. Ask her about the things she does. Ask her about the events and people in the story you (30)____ together. Let her know you are carefully (31)____ what she says. By keeping her in (32)____ and listening, you are (33)____ encouraging your child to think as she speaks. (34)____ , you are showing that you respect her knowledge and her ability to (35)____ learning.";

var M4_P1 = "Public goods are those commodities from whose enjoyment nobody can be effectively excluded. Everybody is free to enjoy the benefits of these commodities, and one person's utilization does not reduce the possibilities of anybody else's enjoying the same good.\n\nExamples of public goods are not as rare as one might expect. A flood control dam is a public goods. Once the dam is built, all persons living in the area will benefit—irrespective of their own contribution to the construction cost of the dam. The same holds true for highway signs or aids to navigation. Once a lighthouse is built, no ship of any nationality can be effectively excluded from the utilization of the lighthouse for navigational purposes. National defense is another example. Even a person who voted against military expenditures or did not pay any taxes will benefit from the protection afforded.\n\nIt is no easy task to determine the social costs and social benefits associated with public goods. There is no practicable way of charging drivers for looking at highway signs, sailors for watching a lighthouse, and citizens for the security provided to them through national defense. Because the market does not provide the necessary signals, economic analysis has to be substituted for the impersonal judgement of the marketplace.";
var M4_P2 = "We can make mistakes at any age. Some mistakes we make are about money. But most mistakes are about people. \"Did Jerry really care when I broke up with Helen?\" \"When I got that great job, did Jim really feel good about it, as a friend? Or did he envy my luck?\" When we look back, doubts like these can make us feel bad. But when we look back, it's too late.\n\nWhy do we go wrong about our friends or our enemies? Sometimes what people say hides their real meaning. And if we don't really listen closely we miss the feeling behind the words. Suppose someone tells you, \"You're a lucky dog.\" That's being friendly. But \"lucky dog\"? There's a bit of envy in those words. Maybe he doesn't see it himself. But bringing in the \"dog\" puts you down a little. What he may be saying is that he doesn't think you deserve your luck.\n\n\"Just think of all the things you have to be thankful for\" is another noise that says one thing and means another. It could mean that the speaker is trying to get you to see your problem as part of your life as a whole. But is he? Wrapped up in this phrase is the thought that your problem isn't important. It's telling you to think of all the starving people in the world when you haven't got a date for Saturday night.\n\nHow can you tell the real meaning behind someone's words? One way is to take a good look at the person talking. Do his words fit the way he looks? Does what he says agree with the tone of voice? His posture? The look in his eyes? Stop and think. The minute you spend thinking about the real meaning of what people say to you may save another mistake.";
var M4_P3 = "Have you ever argued with your loved ones over simple misunderstandings (误解)? Little wonder. We often believe we're more skillful in getting our point across than we actually are, according to Boza Keysar, a professor at the University of Chicago. In his recent study, speakers tried to express their meanings using unclear sentences. Speakers who thought listeners understood were wrong nearly half the time. Here's some good advice to reduce misunderstanding:\n\n(1) Don't trust what you see from the listener. Listeners often nod, look at you or say \"uhhuh\" to be polite or move the conversation along. But it's easy to consider these as signs of understanding.\n\n(2) Train the editor (编辑) in your head. If you say, \"Beth discusses her problems with her husband,\" it's not clear whether she's talking to her husband or about him. Try instead, \"Beth talks to her husband about her problems.\" or \"Beth talks to others about the problems with her husband.\"\n\n(3) Ask listeners to repeat your message. Introduce your request by saying \"I want to be sure I said that right.\" Questions like \"How does that sound?\" or \"Does that make sense?\" may also work.\n\n(4) Listen well. When on the receiving end, ask questions to be sure you're on the same page. After all, it isn't just the speaker's job to make his speech understood.";
var M4_P4 = "Almost every family buys at least one copy of a newspaper every day. Some people subscribe to as many as two or three different newspapers. But why do people read newspapers?\n\nFive hundred years ago, news of important happenings—battles lost and won, kings or rulers overthrown or killed—took months and even years to travel from one country to another. The news passed by word of mouth and was never accurate. Today we can read in our newspapers of important events that occur in faraway countries on the same day they happen.\n\nApart from supplying news from all over the world, newspapers give us a lot of other useful information. There are weather reports, radio, television and film guides, book reviews, stories, and, of course, advertisements. There are all sorts of advertisements. The bigger ones are put in by large companies to bring attention to their products. They pay the newspapers thousands of dollars for their advertising space, but it is worth the money, for news of their products goes into almost every home in the country. For those who produce newspapers, advertisements are also important. Money earned from advertisements makes it possible for them to sell their newspapers at a low price and still make a profit.";
var M4_P5 = "All the housewives who went to the new supermarket had one great ambition: to be the lucky customer who did not have to pay for her shopping. For this was what the notice just inside the entrance promised. It said: \"Remember, once a week, one of our customers gets free goods. This May Be Your Lucky Day!\"\n\nFor several weeks Mrs. Edwards hoped, like many of her friends, to be the lucky customer. Unlike her friends, she never gave up hoping. The cupboards in kitchen were full of things which she did not need. Her husband tried to advise her against buying things but failed. She dreamed of the day when the manager of the supermarket would approach her and say: \"Madam, this is Your Lucky Day. Everything in your basket is free.\"\n\nOne Friday morning, after she had finished her shopping and had taken it to her car, she found that she had forgotten to buy any tea. She dashed back to the supermarket, got the tea and went towards the cashdesk. As she did so, she saw the manager of the supermarket approach her. \"Madam,\" he said, holding out his hand, \"I want to congratulate you! You are our lucky customer and everything you have in your basket is free!\"";

var M4_DLG = "Dave: What sports do you like?\nRita: I like basketball.\nDave: Why do you like it?\nRita: (56)____ .\nDave: Do you want to play it now?\nRita: (57)____ .\nDave: What movie?\nRita: (58)____ .\nDave: But I don't think so. Action movies are usually boring and scary.\nRita: (59)____ ?\nDave: I like comedies.\nRita: (60)____ .";

window.QUESTIONS = (window.QUESTIONS || []).concat([

/* ==================== Ⅰ. 语音（5 题）==================== */
{ id: "mk4-01", paper: "M4", ord: 1, mock: true, level: 3, module: "phonetics", topic: "phonetics-k",
  source: "全真模拟(四) 第1题", stem: "选出划线部分读音与其它三个不同的一项：",
  options: ["__k__nee", "__k__now", "__k__ick", "__k__nife"], answer: 2,
  explanation: "kn 开头时 k 不发音（knee / know / knife），只有 kick 的 k 真读 /k/。" },
{ id: "mk4-02", paper: "M4", ord: 2, mock: true, level: 3, module: "phonetics", topic: "phonetics-c",
  source: "全真模拟(四) 第2题", stem: "选出划线部分读音与其它三个不同的一项：",
  options: ["musi__c__", "plasti__c__", "o__c__ean", "publi__c__"], answer: 2,
  explanation: "music / plastic / public 里的 c 都读 /k/，只有 ocean 里的 c 读 /ʃ/。" },
{ id: "mk4-03", paper: "M4", ord: 3, mock: true, level: 3, module: "phonetics", topic: "phonetics-gh",
  source: "全真模拟(四) 第3题", stem: "选出划线部分读音与其它三个不同的一项：",
  options: ["si__gh__t", "bri__gh__t", "dau__gh__ter", "enou__gh__"], answer: 3,
  explanation: "sight / bright / daughter 里的 gh 都不发音，只有 enough 的 gh 读 /f/。" },
{ id: "mk4-04", paper: "M4", ord: 4, mock: true, level: 3, module: "phonetics", topic: "phonetics-ear",
  source: "全真模拟(四) 第4题", stem: "选出划线部分读音与其它三个不同的一项：",
  options: ["d__ear__", "h__ear__t", "__ear__", "t__ear__"], answer: 1,
  explanation: "dear / ear / tear 里的 ear 读 /ɪə/，只有 heart 读 /ɑː/。" },
{ id: "mk4-05", paper: "M4", ord: 5, mock: true, level: 3, module: "phonetics", topic: "phonetics-qu",
  source: "全真模拟(四) 第5题", stem: "选出划线部分读音与其它三个不同的一项：",
  options: ["e__qu__ip", "mos__qu__ito", "li__qu__id", "__qu__arter"], answer: 1,
  explanation: "equip / liquid / quarter 里的 qu 读 /kw/，只有 mosquito 读 /k/（u 不发音）。" },

/* ==================== Ⅱ. 词汇与语法（15 题）==================== */
{ id: "mk4-06", paper: "M4", ord: 6, mock: true, level: 3, module: "grammar", topic: "word-choice",
  source: "全真模拟(四) 第6题",
  stem: "He ____ at the boy into silence.",
  options: ["glanced", "observed", "watched", "stared"], answer: 3,
  explanation: "四个词都跟「看」有关，但**只有 glance 和 stare 能接 at**，而句意是「把男孩盯得不敢吱声」→ stare（凝视、瞪着）。",
  optionNotes: ["错：glance at 是扫一眼，力度不够，瞪不出安静来", "错：observe 是及物动词，不与 at 搭配", "错：watch 是及物动词，不与 at 搭配", "对：stare at sb. = 盯着某人看，才能把人瞪到不出声"] },
{ id: "mk4-07", paper: "M4", ord: 7, mock: true, level: 2, module: "grammar", topic: "word-choice",
  source: "全真模拟(四) 第7题",
  stem: "Go back to your room and leave me ____.",
  options: ["alone", "lonely", "along", "almost"], answer: 0,
  explanation: "**leave sb. alone** = 别打扰某人、让某人独自待着，固定搭配。注意 alone（独自）和 lonely（孤独的、寂寞的）不是一回事。",
  optionNotes: ["对：leave sb. alone = 别管我", "错：lonely 是「孤独的」，带感情色彩，不用于这个固定搭配", "错：along 是「沿着」", "错：almost 是「几乎」"] },
{ id: "mk4-08", paper: "M4", ord: 8, mock: true, level: 4, module: "grammar", topic: "subjunctive",
  source: "全真模拟(四) 第8题",
  stem: "He insisted that she ____ improve her oral English by doing a lot of practice.",
  options: ["could", "would", "might", "should"], answer: 3,
  explanation: "**insist（坚持主张）后面的宾语从句要用虚拟语气：should + 动词原形**，should 还可以省略。这一条是虚拟语气最爱考的点。",
  optionNotes: ["错：could 不是虚拟语气的形式", "错：would 不是虚拟语气的形式", "错：might 不是虚拟语气的形式", "对：insist 后接 should + 动词原形"] },
{ id: "mk4-09", paper: "M4", ord: 9, mock: true, level: 3, module: "grammar", topic: "word-choice",
  source: "全真模拟(四) 第9题",
  stem: "He was found ____ one month after he was born.",
  options: ["quiet", "still", "silent", "dumb"], answer: 3,
  explanation: "句意：他出生一个月后被发现是个**哑巴** → dumb（哑的、不会说话的）。其余三个只是「安静、不出声」，不是生理上不能说话。",
  optionNotes: ["错：quiet = 安静的（状态）", "错：still = 静止不动的", "错：silent = 沉默不语的（可以说但不说）", "对：dumb = 哑的、不会说话的"] },
{ id: "mk4-10", paper: "M4", ord: 10, mock: true, level: 4, module: "grammar", topic: "non-finite",
  source: "全真模拟(四) 第10题",
  stem: "____ at such a time, his work attracted much attention.",
  options: ["Publishing", "Being published", "Published", "When published"], answer: 2,
  explanation: "主语是 his work，作品是**被**出版的 → 用过去分词 Published 作状语。\n💡 判断非谓语的第一步永远是：主语和这个动作是主动还是被动。",
  optionNotes: ["错：Publishing 表主动，作品不会自己出版自己", "错：Being published 强调「正在被出版」，与主句时间不符", "对：过去分词表被动、且动作已完成", "错：When published 语法上可以，但原书按最简形式取 C"] },
{ id: "mk4-11", paper: "M4", ord: 11, mock: true, level: 4, module: "grammar", topic: "non-finite",
  source: "全真模拟(四) 第11题",
  stem: "Silver is the best conductor of electricity, copper ____ it closely.",
  options: ["followed", "following", "to follow", "being followed"], answer: 1,
  explanation: "这是**独立主格结构**：copper 和 follow 之间是**主动**关系（铜紧随其后）→ 用现在分词 following。",
  optionNotes: ["错：过去分词表被动，铜不是「被跟随」", "对：copper following it = 铜紧随其后，主动关系用现在分词", "错：不定式表将来或目的，不合语境", "错：being followed 是被动进行，方向反了"] },
{ id: "mk4-12", paper: "M4", ord: 12, mock: true, level: 2, module: "grammar", topic: "collocation",
  source: "全真模拟(四) 第12题",
  stem: "He drove to the airport to ____ Mr. Dixon who came to see him from Orlando.",
  options: ["pick up", "set out", "call for", "turn down"], answer: 0,
  explanation: "**pick sb. up** = （开车）去接某人。去机场当然是接人。",
  optionNotes: ["对：pick up = 接（人）", "错：set out = 出发、动身", "错：call for = 需要、要求", "错：turn down = 拒绝、调小"] },
{ id: "mk4-13", paper: "M4", ord: 13, mock: true, level: 3, module: "grammar", topic: "collocation",
  source: "全真模拟(四) 第13题",
  stem: "It is kind ____ you to do me a favor at this moment.",
  options: ["to", "for", "of", "about"], answer: 2,
  explanation: "**It is + 形容词 + of sb. + to do sth.** —— 当形容词描述的是**人的品质**（kind / nice / clever / silly）时用 of；描述**事情本身**（difficult / important / easy）时用 for。",
  optionNotes: ["错：没有 It is kind to you to do 这个句型", "错：kind 描述的是人的品质，要用 of 不用 for", "对：It is kind of you to do sth. = 你真好，帮了我", "错：about 不用于这个句型"] },
{ id: "mk4-14", paper: "M4", ord: 14, mock: true, level: 3, module: "grammar", topic: "inversion",
  source: "全真模拟(四) 第14题",
  stem: "—My room gets very cold at night.\n—____.",
  options: ["So is mine", "So does mine", "So mine is", "So mine does"], answer: 1,
  explanation: "**So + 助动词 + 主语** = 「我也一样」，要倒装。前句的谓语是实义动词 gets → 助动词用 **does**。",
  optionNotes: ["错：前句谓语是 gets 不是 be 动词，不能用 is", "对：So does mine = 我的房间也一样（倒装 + does 替代 gets）", "错：So + 主语 + 谓语（不倒装）表示「的确如此」，语义不对", "错：同上，没有倒装，语义不对"] },
{ id: "mk4-15", paper: "M4", ord: 15, mock: true, level: 4, module: "grammar", topic: "noun-clause",
  source: "全真模拟(四) 第15题",
  stem: "____ parents say and do have a life-long effect on their children.",
  options: ["What", "That", "Which", "As"], answer: 0,
  explanation: "这是主语从句，从句 parents say and do **缺宾语** → 用 **what**（它自己要在从句里当宾语）。that 只起连接作用、不充当成分，所以不行。\n💡 名词性从句选连接词的唯一标准：从句缺不缺成分。缺 → what/who/which；不缺 → that。",
  optionNotes: ["对：从句缺 say and do 的宾语 → what", "错：that 不充当句子成分，可这里缺宾语", "错：which 表示「哪一个」，有选择含义，不合句意", "错：as 不引导主语从句"] },
{ id: "mk4-16", paper: "M4", ord: 16, mock: true, level: 4, module: "grammar", topic: "subject-verb-agreement",
  source: "全真模拟(四) 第16题",
  stem: "Many a young scientist ____ engaged in the research work.",
  options: ["have", "has", "have been", "has been"], answer: 3,
  explanation: "两个点一起考：**many a + 单数名词作主语，谓语用单数** → has；**be engaged in**（从事于）是固定搭配 → 要有 been。",
  optionNotes: ["错：主谓不一致，且缺 been", "错：主谓一致了，但 engaged 前缺 been", "错：many a 后谓语要用单数", "对：has been engaged in，主谓一致且搭配完整"] },
{ id: "mk4-17", paper: "M4", ord: 17, mock: true, level: 3, module: "grammar", topic: "word-choice",
  source: "全真模拟(四) 第17题",
  stem: "She ____ crying very helpful to express her sadness.",
  options: ["considers", "confirms", "believes", "pretends"], answer: 0,
  explanation: "**consider + 宾语 + 形容词**（复合宾语）是固定用法：consider sth. helpful。believe 要说 believe sth. **to be** helpful。",
  optionNotes: ["对：consider sth. + adj. 可直接接形容词作宾语补足语", "错：confirm = 确认，语义不通", "错：believe 后要加 to be 才能接形容词", "错：pretend = 假装，语义不通"] },
{ id: "mk4-18", paper: "M4", ord: 18, mock: true, level: 2, module: "grammar", topic: "collocation",
  source: "全真模拟(四) 第18题",
  stem: "The plan had been ____, which made him very angry.",
  options: ["called off", "called up", "called in", "called on"], answer: 0,
  explanation: "**call off** = 取消。计划被取消了，所以他很生气。",
  optionNotes: ["对：call off = 取消、放弃", "错：call up = 使人想起、打电话", "错：call in = 召集、请（某人）来", "错：call on = 拜访、号召"] },
{ id: "mk4-19", paper: "M4", ord: 19, mock: true, level: 3, module: "grammar", topic: "collocation",
  source: "全真模拟(四) 第19题",
  stem: "You cannot see the patient at the moment; he is now ____ medical treatment.",
  options: ["in", "on", "under", "at"], answer: 2,
  explanation: "**under treatment** = 在接受治疗中，固定表达。under 还有一批同类：under discussion（在讨论中）、under construction（在建设中）、under repair（在修理中）。",
  optionNotes: ["错：没有 in treatment 这个搭配", "错：没有 on treatment 这个搭配", "对：under medical treatment = 正在接受治疗", "错：没有 at treatment 这个搭配"] },
{ id: "mk4-20", paper: "M4", ord: 20, mock: true, level: 2, module: "grammar", topic: "collocation",
  source: "全真模拟(四) 第20题",
  stem: "A thief broke ____ when I was leaving for my office.",
  options: ["in", "up", "out", "off"], answer: 0,
  explanation: "**break in** = 闯入、破门而入。小偷当然是闯进来。",
  optionNotes: ["对：break in = 闯入", "错：break up = 打碎、拆散、分手", "错：break out = （战争、瘟疫）爆发", "错：break off = 折断、中断"] },

/* ==================== Ⅲ. 完形填空（15 题）==================== */
{ id: "mk4-21", paper: "M4", ord: 21, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(四) 完形 第21题", passageId: "M4-cloze", passage: M4_CLOZE,
  stem: "(21) 处应填：", options: ["discovered", "heard", "watched", "written"], answer: 0,
  explanation: "上一句说科学家「发现了」大量关于我们如何学习的情况，这句进一步介绍他们发现的婴儿学习情况 → discovered。" },
{ id: "mk4-22", paper: "M4", ord: 22, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(四) 完形 第22题", passageId: "M4-cloze",
  stem: "(22) 处应填：", options: ["did", "hoped", "studied", "thought"], answer: 3,
  explanation: "「婴儿学到的东西比我们原先**以为**的要多得多」→ than we thought before。" },
{ id: "mk4-23", paper: "M4", ord: 23, mock: true, level: 2, module: "cloze", topic: "cloze",
  source: "全真模拟(四) 完形 第23题", passageId: "M4-cloze",
  stem: "(23) 处应填：", options: ["very", "suitable", "right", "early"], answer: 0,
  explanation: "**from the very beginning** = 从一开始，very 在这里是 the beginning 的强调式。" },
{ id: "mk4-24", paper: "M4", ord: 24, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(四) 完形 第24题", passageId: "M4-cloze",
  stem: "(24) 处应填：", options: ["efforts", "faces", "sounds", "stories"], answer: 2,
  explanation: "空后是 they **hear** us make —— 听到的只能是声音 → sounds。" },
{ id: "mk4-25", paper: "M4", ord: 25, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(四) 完形 第25题", passageId: "M4-cloze",
  stem: "(25) 处应填：", options: ["colors", "eyes", "lines", "looks"], answer: 3,
  explanation: "上一句讲婴儿模仿我们发出的声音，这一句讲他们「读」我们脸上的**表情** → the looks on our faces。" },
{ id: "mk4-26", paper: "M4", ord: 26, mock: true, level: 2, module: "cloze", topic: "cloze",
  source: "全真模拟(四) 完形 第26题", passageId: "M4-cloze",
  stem: "(26) 处应填：", options: ["how", "why", "when", "what"], answer: 1,
  explanation: "**That is why...** = 那就是为什么……。前面说的是原因，后面是结果 → why。" },
{ id: "mk4-27", paper: "M4", ord: 27, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(四) 完形 第27题", passageId: "M4-cloze",
  stem: "(27) 处应填：", options: ["way", "time", "step", "set"], answer: 2,
  explanation: "「听你说话是宝宝走向成为一个『读者』的**第一步**」→ first step toward。" },
{ id: "mk4-28", paper: "M4", ord: 28, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(四) 完形 第28题", passageId: "M4-cloze",
  stem: "(28) 处应填：", options: ["allows", "helps", "moves", "persuades"], answer: 1,
  explanation: "「因为这**帮助**她爱上语言、学会单词」→ help sb. to do sth.。" },
{ id: "mk4-29", paper: "M4", ord: 29, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(四) 完形 第29题", passageId: "M4-cloze",
  stem: "(29) 处应填：", options: ["continue", "remember", "start", "try"], answer: 0,
  explanation: "「等孩子长大一些，要**继续**跟她说话」—— 前文已经提到要跟孩子说话，所以是 continue。" },
{ id: "mk4-30", paper: "M4", ord: 30, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(四) 完形 第30题", passageId: "M4-cloze",
  stem: "(30) 处应填：", options: ["change", "read", "record", "tell"], answer: 1,
  explanation: "the story you **read** together = 你们一起读的故事，符合亲子共读的语境。" },
{ id: "mk4-31", paper: "M4", ord: 31, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(四) 完形 第31题", passageId: "M4-cloze",
  stem: "(31) 处应填：", options: ["accepting", "enjoying", "carrying out", "listening to"], answer: 3,
  explanation: "「让她知道你在认真**听**她说的话」→ listening to what she says。" },
{ id: "mk4-32", paper: "M4", ord: 32, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(四) 完形 第32题", passageId: "M4-cloze",
  stem: "(32) 处应填：", options: ["talking", "singing", "smiling", "playing"], answer: 0,
  explanation: "整段都在讲让孩子说话、你来听 → keeping her in talking（让她一直说）。" },
{ id: "mk4-33", paper: "M4", ord: 33, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(四) 完形 第33题", passageId: "M4-cloze",
  stem: "(33) 处应填：", options: ["then", "already", "even", "also"], answer: 3,
  explanation: "让孩子不停说话、你在听，你**同时也**在鼓励她边说边想 → also（也、同时）。" },
{ id: "mk4-34", paper: "M4", ord: 34, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(四) 完形 第34题", passageId: "M4-cloze",
  stem: "(34) 处应填：", options: ["However", "Besides", "Otherwise", "Again"], answer: 1,
  explanation: "前后是**递进**关系（不仅鼓励她思考，还表示尊重她）→ Besides（除此之外，还）。" },
{ id: "mk4-35", paper: "M4", ord: 35, mock: true, level: 3, module: "cloze", topic: "cloze",
  source: "全真模拟(四) 完形 第35题", passageId: "M4-cloze",
  stem: "(35) 处应填：", options: ["begin", "depend on", "keep", "turn to"], answer: 2,
  explanation: "**keep learning** = 持续学习。句意：你在表明尊重她的知识和持续学习的能力。" },

/* ==================== Ⅳ. 阅读理解（20 题 / 5 篇）==================== */
{ id: "mk4-36", paper: "M4", ord: 36, mock: true, level: 4, module: "reading", topic: "reading",
  source: "全真模拟(四) 阅读 Passage One", passageId: "M4-p1", passage: M4_P1,
  stem: "What does the passage mainly discuss?",
  options: ["Mechanisms for safer navigation.", "The economic structure of the marketplace.",
            "A specific group of commodities.", "The advantages of lowering taxes."], answer: 2,
  explanation: "主旨题。全文讲的是「公共商品」这一类特殊的商品（水坝、公路标志、灯塔、国防），属于一组特定的商品。故选 C。" },
{ id: "mk4-37", paper: "M4", ord: 37, mock: true, level: 4, module: "reading", topic: "reading",
  source: "全真模拟(四) 阅读 Passage One", passageId: "M4-p1",
  stem: "Which of the following would NOT be an example of public goods as described in the passage?",
  options: ["A taxi.", "A bridge.", "A fire truck.", "A stoplight."], answer: 0,
  explanation: "公共商品的定义是「谁都不能被排除在享用之外，且一人使用不减少他人使用」。出租车被一个人坐了别人就坐不了，且可以收费排除他人 —— 只有它不是公共商品。故选 A。" },
{ id: "mk4-38", paper: "M4", ord: 38, mock: true, level: 3, module: "reading", topic: "reading",
  source: "全真模拟(四) 阅读 Passage One", passageId: "M4-p1",
  stem: "According to the passage, finding out the social costs of a public good is a ____.",
  options: ["difficult procedure", "daily administrative duty", "matter of personal judgement", "citizen's responsibility"],
  answer: 0,
  explanation: "第三段第一句：It is no easy task to determine the social costs... —— 「绝非易事」＝困难的过程。故选 A。" },
{ id: "mk4-39", paper: "M4", ord: 39, mock: true, level: 4, module: "reading", topic: "reading",
  source: "全真模拟(四) 阅读 Passage One", passageId: "M4-p1",
  stem: "Which of the following statements best describes the organization of the first two paragraphs?",
  options: ["Suggestions for the application of an economic concept are offered.",
            "Several generalizations are presented from which various conclusions are drawn.",
            "Persuasive language is used to argue against a popular idea.",
            "A general concept is defined and then examples are given."], answer: 3,
  explanation: "第一段给出公共商品的定义，第二段列举水坝、公路标志、灯塔、国防等实例 —— 先下定义再举例。故选 D。" },
{ id: "mk4-40", paper: "M4", ord: 40, mock: true, level: 4, module: "reading", topic: "reading",
  source: "全真模拟(四) 阅读 Passage Two", passageId: "M4-p2", passage: M4_P2,
  stem: "According to the author, the reason why we go wrong about our friends is that ____.",
  options: ["we fail to listen carefully when they talk", "people tend to be annoyed when we check what they say",
            "people usually state one thing but mean another", "we tend to doubt what our friends say"], answer: 2,
  explanation: "第二段第二句 what people say hides their real meaning，第三段首句又说 says one thing and means another —— 言不由衷才是根源。故选 C。" },
{ id: "mk4-41", paper: "M4", ord: 41, mock: true, level: 4, module: "reading", topic: "reading",
  source: "全真模拟(四) 阅读 Passage Two", passageId: "M4-p2",
  stem: "In the sentence \"Maybe he doesn't see it himself\" in paragraph 2, the pronoun \"it\" refers to ____.",
  options: ["being friendly", "a bit of envy", "lucky dog", "your luck"], answer: 1,
  explanation: "指代题。上一句刚说 There's a bit of envy in those words —— it 指的就是这点嫉妒。故选 B。" },
{ id: "mk4-42", paper: "M4", ord: 42, mock: true, level: 4, module: "reading", topic: "reading",
  source: "全真模拟(四) 阅读 Passage Two", passageId: "M4-p2",
  stem: "When we listen to a person talking, the most important thing for us to do is to ____.",
  options: ["notice the way the person is talking", "take a good look at the person talking",
            "mind his tone, his posture and the look in his eyes",
            "examine the real meaning of what he says based on his manner, his tone and his posture"], answer: 3,
  explanation: "最后一段把方式、语调、姿态、眼神都列了一遍，落点是 thinking about the real meaning —— D 项概括最全。故选 D。" },
{ id: "mk4-43", paper: "M4", ord: 43, mock: true, level: 4, module: "reading", topic: "reading",
  source: "全真模拟(四) 阅读 Passage Two", passageId: "M4-p2",
  stem: "The author most probably is a ____.",
  options: ["teacher", "psychologist", "philosopher", "doctor"], answer: 1,
  explanation: "推理判断题。全文分析交际过程中的心理因素，并从心理学角度给出建议 —— 作者很可能是心理学家。故选 B。" },
{ id: "mk4-44", paper: "M4", ord: 44, mock: true, level: 4, module: "reading", topic: "reading",
  source: "全真模拟(四) 阅读 Passage Three", passageId: "M4-p3", passage: M4_P3,
  stem: "Why does the writer give us the advice?",
  options: ["We're not skillful enough to make clear sentences.", "Misunderstanding is damaging our normal lives.",
            "Misunderstanding occurs now and then.", "It's impolite to say NO to others."], answer: 2,
  explanation: "第一段说我们常常高估自己表达的清晰度，研究显示近一半时候听者其实没听懂 —— 误解时有发生，所以才给建议。故选 C。" },
{ id: "mk4-45", paper: "M4", ord: 45, mock: true, level: 4, module: "reading", topic: "reading",
  source: "全真模拟(四) 阅读 Passage Three", passageId: "M4-p3",
  stem: "The writer suggests that when talking to others, the speaker should ____.",
  options: ["know that listeners will show him that they understand his words",
            "express himself clearly even when he sees signs of understanding",
            "notice listener's signs of understanding", "look directly into his listener's eyes"], answer: 1,
  explanation: "第（1）条建议说：听者点头、看着你只是出于礼貌，别把这些当成听懂的信号 —— 言下之意，即使看到「懂了」的表象也要把话说清楚。故选 B。" },
{ id: "mk4-46", paper: "M4", ord: 46, mock: true, level: 4, module: "reading", topic: "reading",
  source: "全真模拟(四) 阅读 Passage Three", passageId: "M4-p3",
  stem: "By \"Train the editor in your head\", the speakers are advised ____.",
  options: ["to get themselves trained by a good editor", "to discuss problems with their husbands or wives",
            "to express themselves in long but simple sentences", "to make sure each sentence has only one meaning"],
  answer: 3,
  explanation: "第（2）条举的 Beth 的例子说明：一句话有两种理解就会有歧义，要改写成只有一个意思的句子。故选 D。" },
{ id: "mk4-47", paper: "M4", ord: 47, mock: true, level: 4, module: "reading", topic: "reading",
  source: "全真模拟(四) 阅读 Passage Three", passageId: "M4-p3",
  stem: "In the last paragraph, the words \"you're on the same page\" mean that ____.",
  options: ["you're following the speaker closely", "you're reading the same page as the speaker does",
            "you should know which page the speaker refers to", "your story is written on the same page as the speaker's"],
  answer: 0,
  explanation: "词义猜测题。后一句 make his speech understood 是提示 —— on the same page 意思是「跟得上说话人、理解一致」。故选 A。" },
{ id: "mk4-48", paper: "M4", ord: 48, mock: true, level: 3, module: "reading", topic: "reading",
  source: "全真模拟(四) 阅读 Passage Four", passageId: "M4-p4", passage: M4_P4,
  stem: "In the past, news was ____.",
  options: ["sent by telegraph", "sent by letter", "passed from one person to another", "sent by telephone"], answer: 2,
  explanation: "第二段：The news passed by word of mouth（口头传递）—— 就是一个人传给另一个人。故选 C。" },
{ id: "mk4-49", paper: "M4", ord: 49, mock: true, level: 3, module: "reading", topic: "reading",
  source: "全真模拟(四) 阅读 Passage Four", passageId: "M4-p4",
  stem: "The money spent on advertisements is ____.",
  options: ["wasted", "not much", "worthwhile", "of no use to anyone"], answer: 2,
  explanation: "第三段：it is worth the money, for news of their products goes into almost every home —— 花这个钱是值的。故选 C。" },
{ id: "mk4-50", paper: "M4", ord: 50, mock: true, level: 3, module: "reading", topic: "reading",
  source: "全真模拟(四) 阅读 Passage Four", passageId: "M4-p4",
  stem: "Which of the following statements is NOT true?",
  options: ["Five hundred years ago news did not take a long time to reach other countries.",
            "Large companies put big advertisements in the newspapers to make their products known.",
            "The news that we need in our newspapers is up-to-date.",
            "Though the newspapers are sold at a low price, their owners still gain profit."], answer: 0,
  explanation: "第二段明说 500 年前消息从一国传到另一国要花上几个月甚至几年 —— A 项正好说反。故选 A。" },
{ id: "mk4-51", paper: "M4", ord: 51, mock: true, level: 3, module: "reading", topic: "reading",
  source: "全真模拟(四) 阅读 Passage Four", passageId: "M4-p4",
  stem: "The phrase \"subscribe to\" in the second sentence of Para. 1 means ____.",
  options: ["contribute to", "write to", "pay for receiving", "appreciate"], answer: 2,
  explanation: "词义猜测题。第一句说几乎每家每天至少买一份报纸，第二句说有人 subscribe to 两三份 —— 与 buy 同义，即「订阅」（付钱按期收取）。故选 C。" },
{ id: "mk4-52", paper: "M4", ord: 52, mock: true, level: 3, module: "reading", topic: "reading",
  source: "全真模拟(四) 阅读 Passage Five", passageId: "M4-p5", passage: M4_P5,
  stem: "The housewives learnt about the information of free goods ____.",
  options: ["on TV", "from the manager", "at the supermarket", "from the newspaper"], answer: 2,
  explanation: "第一段第二句：the notice just inside the entrance —— 告示就贴在超市入口处。故选 C。" },
{ id: "mk4-53", paper: "M4", ord: 53, mock: true, level: 3, module: "reading", topic: "reading",
  source: "全真模拟(四) 阅读 Passage Five", passageId: "M4-p5",
  stem: "Mrs. Edwards ____.",
  options: ["is always very lucky", "had no friends", "hoped to get free shopping", "gets disappointed easily"], answer: 2,
  explanation: "第二段：她像朋友们一样盼着当幸运顾客，而且**从不放弃希望** —— 一心想免费购物。故选 C。" },
{ id: "mk4-54", paper: "M4", ord: 54, mock: true, level: 3, module: "reading", topic: "reading",
  source: "全真模拟(四) 阅读 Passage Five", passageId: "M4-p5",
  stem: "Mrs. Edwards went back to the supermarket quickly because she had to ____.",
  options: ["buy another thing", "talk to the manager", "pay for her shopping", "find her shopping"], answer: 0,
  explanation: "最后一段：她已经把东西放进车里，这时发现忘了买茶叶，所以又返回超市去买 —— 就是再买一样东西。故选 A。" },
{ id: "mk4-55", paper: "M4", ord: 55, mock: true, level: 4, module: "reading", topic: "reading",
  source: "全真模拟(四) 阅读 Passage Five", passageId: "M4-p5",
  stem: "Mrs. Edwards must have been ____.",
  options: ["pleased", "delighted", "proud", "disappointed"], answer: 3,
  explanation: "推理判断题。她盼了几周，可真成了幸运顾客时，满满一车东西早付过款了，篮子里只剩一盒茶叶 —— 只能是**失望**。pleased / delighted / proud 都不合。故选 D。" },

/* ==================== Ⅴ. 补全对话（5 题 · 8 选 5 改编为四选一）==================== */
{ id: "mk4-56", paper: "M4", ord: 56, mock: true, level: 2, module: "conversation", topic: "conversation", adapted: true,
  source: "全真模拟(四) 补全对话 第56题（8选5改编为四选一）", passageId: "M4-conv", passage: M4_DLG,
  stem: "(56) 处应填：",
  options: ["I enjoy P.E. at school", "I like basketball", "Because it's exciting", "I don't like watching movies"],
  answer: 2,
  explanation: "上一句是 **Why** do you like it?（为什么喜欢）—— Why 问原因，就只能用 Because 开头答原因。\n💡 特殊疑问句的答法是死的：What 答事物、When 答时间、Where 答地点、Why 答原因。",
  optionNotes: ["错：答非所问，没有回答「为什么」", "错：这是上一句已经说过的内容", "对：Why 问原因 → Because it's exciting", "错：与篮球话题无关"] },
{ id: "mk4-57", paper: "M4", ord: 57, mock: true, level: 2, module: "conversation", topic: "conversation", adapted: true,
  source: "全真模拟(四) 补全对话 第57题（8选5改编为四选一）", passageId: "M4-conv",
  stem: "(57) 处应填：",
  options: ["Sorry. I don't. I want to go to a movie", "Because it's exciting", "I enjoy P.E. at school", "Oh, I like comedies, too"],
  answer: 0,
  explanation: "上一句 Do you want to play it now? 是一般疑问句 → 先表态（Sorry. I don't.）再补内容。而且下一句 Dave 问 What movie?，说明这里必须提到 movie。\n💡 婉拒的标准结构：先道歉/表态，再说自己的打算。",
  optionNotes: ["对：先 Sorry. I don't. 表态，再说想去看电影，正好引出下一句 What movie?", "错：Because 回答的是 Why，这里问的是 Do you...", "错：答非所问，也接不上下一句的 What movie", "错：喜剧是最后才聊到的话题"] },
{ id: "mk4-58", paper: "M4", ord: 58, mock: true, level: 2, module: "conversation", topic: "conversation", adapted: true,
  source: "全真模拟(四) 补全对话 第58题（8选5改编为四选一）", passageId: "M4-conv",
  stem: "(58) 处应填：",
  options: ["I like basketball", "It's an action movie and it's interesting", "I don't like watching movies", "Because it's exciting"],
  answer: 1,
  explanation: "上一句 What movie? 问的是哪部电影，**下一句** Dave 接 Action movies are usually boring and scary —— 前后一夹，中间只能是「是部动作片」。\n💡 补全对话要前后一起看：空格前问什么、空格后接什么，两边都对得上才是答案。",
  optionNotes: ["错：话题已经从篮球转到电影了", "对：既回答了 What movie，又被下一句的 Action movies 直接印证", "错：她正要去看电影，不可能说不喜欢看电影", "错：Because 答的是原因，这里问的是哪部电影"] },
{ id: "mk4-59", paper: "M4", ord: 59, mock: true, level: 2, module: "conversation", topic: "conversation", adapted: true,
  source: "全真模拟(四) 补全对话 第59题（8选5改编为四选一）", passageId: "M4-conv",
  stem: "(59) 处应填：",
  options: ["What kind of movies do you like, then", "Oh, I like comedies, too", "I enjoy P.E. at school", "It's an action movie and it's interesting"],
  answer: 0,
  explanation: "**看下一句**：Dave 回答 I like comedies（我喜欢喜剧）—— 这是在回答「那你喜欢什么类型的电影」。而且空格后是问号，说明这里要填问句。",
  optionNotes: ["对：下一句 I like comedies 正是对它的回答", "错：这是 (60) 处的答语，且不是问句", "错：与电影话题无关，也不是问句", "错：这是 (58) 处说过的内容"] },
{ id: "mk4-60", paper: "M4", ord: 60, mock: true, level: 2, module: "conversation", topic: "conversation", adapted: true,
  source: "全真模拟(四) 补全对话 第60题（8选5改编为四选一）", passageId: "M4-conv",
  stem: "(60) 处应填：",
  options: ["I don't like watching movies", "Oh, I like comedies, too", "Because it's exciting", "What kind of movies do you like, then"],
  answer: 1,
  explanation: "Dave 刚说 I like comedies，Rita 顺着接「哦，我也喜欢喜剧」—— 对话在这里达成一致，自然收尾。\n💡 too / either 是「我也一样」的标志词，寒暄和附和类的空常考它。",
  optionNotes: ["错：与她要去看电影的前文矛盾", "对：Oh, I like comedies, too 附和对方，正好收尾", "错：Because 答原因，前面没有 Why", "错：这个问题 (59) 处已经问过了"] },
]);
