/* ============================================================================
 * questions-mock2.js —— 全真模拟(二)整卷（60 道选择题 + 作文题）
 * ----------------------------------------------------------------------------
 * 来源：用户提供的 PDF《英语全真模拟卷及答案解析（五套）》第二套。
 * 逐题对照卷末【参考答案及解析】录入；两处印刷答案与解析文字矛盾的
 * （第4题、第29、46题），以解析文字+语法事实为准（下方注明）。
 * 字段：paper:"M2" + ord（卷面题号）——模考页可按整卷原始顺序考。
 * 解析取自原卷【应试指导】，压成一两句；不写 optionNotes（引擎允许缺省）。
 * ========================================================================== */

window.PAPERS = (window.PAPERS || []).concat([{
  id: "M2", name: "全真模拟(二)",
  essay: "根据下面的汉语提示，写一篇题为 “Why Should We Learn English” 的短文：（1）英语现已成为一种国际语言；（2）现在大多数书籍、报纸和杂志都以英文出版和印刷；（3）学习英语需要耐心。",
}]);

window.QUESTIONS = (window.QUESTIONS || []).concat([

/* ==================== Ⅰ. 语音（5 题）==================== */
{ id: "mk2-01", paper: "M2", ord: 1, mock: true, level: 3, module: "phonetics", topic: "phonetics-h",
  source: "全真模拟(二) 第1题",
  stem: "选出划线部分读音与其它三个不同的一项：",
  options: ["__h__onest", "g__h__ost", "ve__h__icle", "__h__otel"],
  answer: 3,
  explanation: "honest 的 h 不发音，ghost 的 gh 读 /g/（h 不单独发音），vehicle 的 h 通常也不发音——只有 hotel 的 h 真读 /h/，所以它不同。" },
{ id: "mk2-02", paper: "M2", ord: 2, mock: true, level: 3, module: "phonetics", topic: "phonetics-ai",
  source: "全真模拟(二) 第2题",
  stem: "选出划线部分读音与其它三个不同的一项：",
  options: ["f__ai__l", "portr__ai__t", "r__ai__n", "m__ai__n"],
  answer: 1,
  explanation: "ai 常读 /eɪ/：fail / rain / main。portrait（肖像）里读弱化的 /ɪ/，不同。" },
{ id: "mk2-03", paper: "M2", ord: 3, mock: true, level: 3, module: "phonetics", topic: "phonetics-x",
  source: "全真模拟(二) 第3题",
  stem: "选出划线部分读音与其它三个不同的一项：",
  options: ["e__x__ercise", "bo__x__", "e__x__act", "mi__x__"],
  answer: 2,
  explanation: "x 一般读 /ks/：exercise / box / mix。exact 里 x 读 /ɡz/（ex + 重读元音时常浊化），不同。" },
{ id: "mk2-04", paper: "M2", ord: 4, mock: true, level: 3, module: "phonetics", topic: "phonetics-ew",
  source: "全真模拟(二) 第4题 ⚠️印刷答案与语音事实矛盾，按语音事实录 B",
  stem: "选出划线部分读音与其它三个不同的一项：",
  options: ["v__iew__", "fl__ew__", "f__ew__", "n__ew__"],
  answer: 1,
  explanation: "view / few / new 里都带 /juː/（有“y”的音），flew 读 /fluː/（没有 y 音），所以 flew 不同。" },
{ id: "mk2-05", paper: "M2", ord: 5, mock: true, level: 3, module: "phonetics", topic: "phonetics-w",
  source: "全真模拟(二) 第5题",
  stem: "选出划线部分读音与其它三个不同的一项：",
  options: ["__w__eapon", "__w__hole", "__w__ater", "__w__onder"],
  answer: 1,
  explanation: "whole 里 w 不发音（读 /həʊl/），其余的 w 都读 /w/。" },

/* ==================== Ⅱ. 词汇与语法（15 题）==================== */
{ id: "mk2-06", paper: "M2", ord: 6, mock: true, level: 3, module: "grammar", topic: "collocation",
  source: "全真模拟(二) 第6题",
  stem: "The real trouble ____ their lack of confidence in their faculty.",
  options: ["lies in", "results in", "leads to", "brings about"],
  answer: 0,
  explanation: "lie in = 在于。“真正的问题在于他们对自己的才能缺乏信心。”result in / lead to / bring about 都是“导致”，方向不对。" },
{ id: "mk2-07", paper: "M2", ord: 7, mock: true, level: 3, module: "grammar", topic: "word-choice",
  source: "全真模拟(二) 第7题",
  stem: "Well, let's put our heads together and find a(n) ____ to the problem.",
  options: ["measure", "way", "solution", "method"],
  answer: 2,
  explanation: "四个词都有“办法”的意思，但后面跟 to the problem 的固定搭配只有 solution（a solution to the problem 问题的解决办法）。" },
{ id: "mk2-08", paper: "M2", ord: 8, mock: true, level: 3, module: "grammar", topic: "word-choice",
  source: "全真模拟(二) 第8题",
  stem: "It's bad policy for developing countries to sacrifice environmental protection to ____ economic growth.",
  options: ["discourage", "weaken", "promote", "create"],
  answer: 2,
  explanation: "牺牲环保来“促进”经济增长 → promote。discourage 使泄气，weaken 削弱，create 创造。" },
{ id: "mk2-09", paper: "M2", ord: 9, mock: true, level: 3, module: "grammar", topic: "collocation",
  source: "全真模拟(二) 第9题",
  stem: "He did it ____ gratitude for everything she had done for him.",
  options: ["with", "in", "with regard to", "out of"],
  answer: 3,
  explanation: "out of gratitude = 出于感激。固定搭配：out of + 情感/动机（out of pity / curiosity / gratitude）。" },
{ id: "mk2-10", paper: "M2", ord: 10, mock: true, level: 3, module: "grammar", topic: "word-choice",
  source: "全真模拟(二) 第10题",
  stem: "Stop making so much noise, for you are ____ me in my studies.",
  options: ["attracting", "disturbing", "contracting", "contacting"],
  answer: 1,
  explanation: "“别吵了，你打扰我学习了。”disturb 打扰。attract 吸引，contract 缩小，contact 联系。" },
{ id: "mk2-11", paper: "M2", ord: 11, mock: true, level: 3, module: "grammar", topic: "subjunctive",
  source: "全真模拟(二) 第11题",
  stem: "If only the committee ____ the regulations and put them into effect as soon as possible.",
  options: ["approve", "will approve", "can approve", "would approve"],
  answer: 3,
  explanation: "if only（要是……就好了）后面必须用虚拟语气，表将来的愿望用 would + 动词原形。" },
{ id: "mk2-12", paper: "M2", ord: 12, mock: true, level: 3, module: "grammar", topic: "word-choice",
  source: "全真模拟(二) 第12题",
  stem: "He claimed that he would be a ____ in the presidential election, and would win the election at last.",
  options: ["voter", "candidate", "partner", "comrade"],
  answer: 1,
  explanation: "参加总统竞选的是 candidate（候选人）。voter 选民，partner 伙伴，comrade 同志。" },
{ id: "mk2-13", paper: "M2", ord: 13, mock: true, level: 3, module: "grammar", topic: "collocation",
  source: "全真模拟(二) 第13题",
  stem: "He is quite thoughtless, for very seldom can he ____ other people's troubles.",
  options: ["agree with", "interfere with", "identify with", "rest with"],
  answer: 2,
  explanation: "identify with = 与……感同身受、体会。“他很少能体会到别人遇到困难时的感受。”注意句首 seldom 引起的倒装。" },
{ id: "mk2-14", paper: "M2", ord: 14, mock: true, level: 3, module: "grammar", topic: "relative-clause",
  viz: {"en": "Let's think of a situation (where this idiom can be used).", "rows": [["主干", "Let's think of a situation.", "咱们想一个场合"], ["括号补充", "where this idiom can be used", "这个习语能用上的（场合）——从句完整 → where"]]},
  source: "全真模拟(二) 第14题",
  stem: "Let's think of a situation ____ this idiom can be used.",
  options: ["where", "which", "that", "what"],
  answer: 0,
  explanation: "从句 this idiom can be used 是完整的（主语谓语都齐），缺的是“在什么场合”——完整从句 + 抽象地点 situation → where。" },
{ id: "mk2-15", paper: "M2", ord: 15, mock: true, level: 3, module: "grammar", topic: "subjunctive",
  source: "全真模拟(二) 第15题",
  stem: "We wouldn't lose heart even if we ____ again.",
  options: ["would fail", "failed", "had failed", "fail"],
  answer: 1,
  explanation: "主句 wouldn't（would + 原形）→ 与现在/将来相反的虚拟，even if 从句配一般过去式 failed。" },
{ id: "mk2-16", paper: "M2", ord: 16, mock: true, level: 3, module: "grammar", topic: "word-choice",
  source: "全真模拟(二) 第16题",
  stem: "The general strike is a means of ____ the total authority of the government.",
  options: ["informing", "recommending", "challenging", "transforming"],
  answer: 2,
  explanation: "总罢工是对政府绝对权威“挑战”的一种方式 → challenging。inform 通知，recommend 推荐，transform 转变。" },
{ id: "mk2-17", paper: "M2", ord: 17, mock: true, level: 3, module: "grammar", topic: "collocation",
  source: "全真模拟(二) 第17题",
  stem: "Thoughts are expressed ____ words.",
  options: ["by all means", "by no means", "by the way", "by means of"],
  answer: 3,
  explanation: "by means of = 借助、通过。“思想通过语言来表达。”by all means 务必，by no means 绝不，by the way 顺便说。" },
{ id: "mk2-18", paper: "M2", ord: 18, mock: true, level: 3, module: "grammar", topic: "passive",
  source: "全真模拟(二) 第18题",
  stem: "I got caught in the rain and my suit ____.",
  options: ["has been ruined", "had been ruined", "has ruined", "had ruined"],
  answer: 0,
  explanation: "西装被淋坏，强调对现在的影响 → 现在完成时；suit 和 ruin 是被动关系 → has been ruined。" },
{ id: "mk2-19", paper: "M2", ord: 19, mock: true, level: 3, module: "grammar", topic: "word-choice",
  source: "全真模拟(二) 第19题",
  stem: "The ship ____ from behind the fog.",
  options: ["drove", "emerged", "passed", "turned"],
  answer: 1,
  explanation: "emerge = 显现、浮现，“船从雾后面显现出来”。drive / pass / turn 一般不直接接 from 表“从……中现身”。" },
{ id: "mk2-20", paper: "M2", ord: 20, mock: true, level: 3, module: "grammar", topic: "collocation",
  source: "全真模拟(二) 第20题",
  stem: "I'd rather marry a man who had a(n) ____ of humour than one who was very attractive.",
  options: ["capability", "sight", "knowledge", "sense"],
  answer: 3,
  explanation: "sense of humour = 幽默感，固定搭配。capability 能力，sight 视界，knowledge 知识。" },

/* ==================== Ⅲ. 完形填空（15 题）==================== */
{ id: "mk2-21", paper: "M2", ord: 21, mock: true, level: 3, module: "cloze", topic: "cloze", passageId: "M2-cloze",
  source: "全真模拟(二) 完形 第21题",
  passage: "I once went to a town in the north of England on business.\nIt was about 7:30 in the evening when I reached the hotel. The manageress, a strict old lady of about 60, showed me to my room. When I asked her what time dinner was, she said there was only one sitting at 6:30, and I had (21)____ it.\n“Never mind,” I said. “I'm not very hungry. I'll just have a drink in the bar(酒吧) and a sandwich.”\n“Bar!” she (22)____ her voice. “This is a respectable hotel, young man. If you want beer, you must go somewhere else.” She spoke (23)____ a glass of beer was a dangerous drug.\nI went to a bar and had some beer and sandwiches and then went to the cinema. At about 11:30 I (24)____. Everything was in darkness. I knocked at the door, but nothing happened. The (25)____ sound was the church clock opposite, which suddenly struck the half-hour with such force that it made me jump.\n(26)____ a window opened upstairs. The old lady (27)____ and asked me what was going on. I explained who I was and she let me (28)____ after ten minutes' wait. She was in her nightdress. She told me seriously that guests were (29)____ to be back in the hotel by 11 o'clock.\nI went to bed but could not sleep. Every quarter of an hour the church clock struck and at midnight the whole hotel shook with the noise. Just before dawn, I finally (30)____.\nWhen I arrived at breakfast, everyone else had nearly (31)____ and there was not enough coffee to go round.\n“Did you (32)____ well, young man?” the old lady asked.\n“(33)____, I don't think I could go through another night in that room,” I replied. “I hardly slept at all.”\n“That's because you were (34)____ all night drinking!” she said angrily, putting (35)____ to the conversation.",
  stem: "(21) 处应填：",
  options: ["had", "passed", "missed", "caught"],
  answer: 2,
  explanation: "作者 7:30 到旅馆，晚餐只有 6:30 一场——已经“错过”了 → missed。" },
{ id: "mk2-22", paper: "M2", ord: 22, mock: true, level: 3, module: "cloze", topic: "cloze", passageId: "M2-cloze",
  source: "全真模拟(二) 完形 第22题",
  stem: "(22) 处应填：",
  options: ["lost", "lowered", "dropped", "raised"],
  answer: 3,
  explanation: "老太太一听“酒吧”就来气 → raise one's voice 提高嗓门。" },
{ id: "mk2-23", paper: "M2", ord: 23, mock: true, level: 3, module: "cloze", topic: "cloze", passageId: "M2-cloze",
  source: "全真模拟(二) 完形 第23题",
  options: ["even if", "since", "although", "as if"],
  stem: "(23) 处应填：",
  answer: 3,
  explanation: "她说话的样子“就好像”一杯啤酒是毒药似的 → as if 好像。" },
{ id: "mk2-24", paper: "M2", ord: 24, mock: true, level: 3, module: "cloze", topic: "cloze", passageId: "M2-cloze",
  source: "全真模拟(二) 完形 第24题",
  options: ["went to bed", "walked to a club", "returned to the hotel", "drove to a restaurant"],
  answer: 2,
  stem: "(24) 处应填：",
  explanation: "看完电影 11:30，接下来自然是“回到旅馆”——下文敲门没人应也印证了这一点。" },
{ id: "mk2-25", paper: "M2", ord: 25, mock: true, level: 3, module: "cloze", topic: "cloze", passageId: "M2-cloze",
  source: "全真模拟(二) 完形 第25题",
  options: ["only", "sharp", "sweet", "last"],
  answer: 0,
  stem: "(25) 处应填：",
  explanation: "一片漆黑寂静，“唯一”的声音是对面教堂的钟声 → only。" },
{ id: "mk2-26", paper: "M2", ord: 26, mock: true, level: 3, module: "cloze", topic: "cloze", passageId: "M2-cloze",
  source: "全真模拟(二) 完形 第26题",
  options: ["Firstly", "Wonderfully", "Unfortunately", "Finally"],
  answer: 3,
  stem: "(26) 处应填：",
  explanation: "敲了半天门，“终于”楼上的窗户开了 → Finally。" },
{ id: "mk2-27", paper: "M2", ord: 27, mock: true, level: 3, module: "cloze", topic: "cloze", passageId: "M2-cloze",
  source: "全真模拟(二) 完形 第27题",
  options: ["came out", "got up", "looked out", "woke up"],
  answer: 2,
  stem: "(27) 处应填：",
  explanation: "窗户开了，老太太“探头往外看”问怎么回事 → looked out。" },
{ id: "mk2-28", paper: "M2", ord: 28, mock: true, level: 3, module: "cloze", topic: "cloze", passageId: "M2-cloze",
  source: "全真模拟(二) 完形 第28题",
  options: ["down", "out", "back", "in"],
  answer: 3,
  stem: "(28) 处应填：",
  explanation: "等了十分钟她才“让我进去” → let me in。" },
{ id: "mk2-29", paper: "M2", ord: 29, mock: true, level: 3, module: "cloze", topic: "cloze", passageId: "M2-cloze",
  source: "全真模拟(二) 完形 第29题 ⚠️印刷答案字母与解析矛盾，按解析录 expected",
  options: ["ordered", "expected", "taught", "encouraged"],
  answer: 1,
  stem: "(29) 处应填：",
  explanation: "be expected to do sth. = 应该/被要求做某事。“客人应在 11 点前回到旅馆。”" },
{ id: "mk2-30", paper: "M2", ord: 30, mock: true, level: 3, module: "cloze", topic: "cloze", passageId: "M2-cloze",
  source: "全真模拟(二) 完形 第30题",
  options: ["fell asleep", "went to bed", "got up", "gave in"],
  answer: 0,
  stem: "(30) 处应填：",
  explanation: "折腾一整夜，天亮前“终于睡着了” → fall asleep（强调入睡这个状态变化；go to bed 是上床这个动作，前文已经上床了）。" },
{ id: "mk2-31", paper: "M2", ord: 31, mock: true, level: 3, module: "cloze", topic: "cloze", passageId: "M2-cloze",
  source: "全真模拟(二) 完形 第31题",
  options: ["arrived", "done", "finished", "started"],
  answer: 2,
  stem: "(31) 处应填：",
  explanation: "到餐厅时别人几乎都“吃完了”，咖啡都不够分了 → finished。" },
{ id: "mk2-32", paper: "M2", ord: 32, mock: true, level: 3, module: "cloze", topic: "cloze", passageId: "M2-cloze",
  source: "全真模拟(二) 完形 第32题",
  options: ["play", "sleep", "eat", "do"],
  answer: 1,
  stem: "(32) 处应填：",
  explanation: "老太太问的是“睡得好吗” → Did you sleep well。" },
{ id: "mk2-33", paper: "M2", ord: 33, mock: true, level: 3, module: "cloze", topic: "cloze", passageId: "M2-cloze",
  source: "全真模拟(二) 完形 第33题",
  options: ["First of all", "Never mind", "To tell you the truth", "As a result"],
  answer: 2,
  stem: "(33) 处应填：",
  explanation: "to tell you the truth = 说实话。“说实话，那个房间我一晚都待不下去了。”" },
{ id: "mk2-34", paper: "M2", ord: 34, mock: true, level: 3, module: "cloze", topic: "cloze", passageId: "M2-cloze",
  source: "全真模拟(二) 完形 第34题",
  options: ["away", "here", "down", "up"],
  answer: 3,
  stem: "(34) 处应填：",
  explanation: "be up all night = 整夜没睡。“那是因为你整夜在外面喝酒没睡！”" },
{ id: "mk2-35", paper: "M2", ord: 35, mock: true, level: 3, module: "cloze", topic: "cloze", passageId: "M2-cloze",
  source: "全真模拟(二) 完形 第35题",
  options: ["an end", "a saying", "a joke", "a pause"],
  answer: 0,
  stem: "(35) 处应填：",
  explanation: "put an end to = 结束。她生气地说完，“结束了这场对话”。" },

/* ==================== Ⅳ. 阅读理解（5 篇 × 4 题）==================== */
/* -------- Passage One：狗是人类最好的朋友 -------- */
{ id: "mk2-36", paper: "M2", ord: 36, mock: true, level: 3, module: "reading", topic: "reading", passageId: "M2-p1",
  source: "全真模拟(二) 阅读 Passage One",
  passage: "The dog has always been considered man's best friend. Always noted for being particularly faithful in watching over children, he also has his place by the fireside, in the cow pasture, on the sheep range(放牧区), and beside the hunter in forest. He is easy to train, works hard, and often performs astonishing feats. And in the frozen polar regions he was once the principal motive power, before being lately displaced by the plane and helicopter.\nBecause he howls or whines in the presence of impending death, the dog was once thought to have supernatural powers and believed to be capable of seeing gods and ghosts invisible to men. Actually, the basis for these beliefs lies in the hound's sensibility to people's feelings and his superior hearing ability and sense of smell, which enable him to detect signs hidden from human observation. His record of saving lives is outstanding, for he often gives warning of fire and other dangers not noticed by his master.\nThe dog's major contribution, however, has been to medical research. Both his diet and his structure are comparable to those of the human being, and so he has been the subject of countless demonstrations and experiments. Open-heart surgery has been made possible largely because of the dog. But his sacrifice has repaid his own species as well by safeguarding it from rabies(狂犬病), distemper, and other diseases.",
  stem: "The dog has always been noted for ____.",
  options: ["protecting children", "assisting shepherds", "helping hunters", "herding cattle"],
  answer: 0,
  explanation: "细节题。第一段第二句：Always noted for being particularly faithful in watching over children——狗以忠实地看护孩子而出名 → A。" },
{ id: "mk2-37", paper: "M2", ord: 37, mock: true, level: 3, module: "reading", topic: "reading", passageId: "M2-p1",
  source: "全真模拟(二) 阅读 Passage One",
  stem: "In the polar regions, the dog mainly ____.",
  options: ["carried supplies", "provided companionship", "tracked prey", "herded caribou(驯鹿)"],
  answer: 0,
  explanation: "细节题。第一段最后一句：在寒冷极地，狗曾是主要动力（motive power）——即用于运输，后来才被飞机和直升机取代 → A。" },
{ id: "mk2-38", paper: "M2", ord: 38, mock: true, level: 3, module: "reading", topic: "reading", passageId: "M2-p1",
  source: "全真模拟(二) 阅读 Passage One",
  stem: "Dogs are similar to human beings in ____.",
  options: ["size", "structure", "temperament", "appearance"],
  answer: 1,
  explanation: "细节题。第三段第二句：his diet and his structure are comparable to those of the human being——饮食和身体结构与人类相近 → B。" },
{ id: "mk2-39", paper: "M2", ord: 39, mock: true, level: 3, module: "reading", topic: "reading", passageId: "M2-p1",
  source: "全真模拟(二) 阅读 Passage One",
  stem: "The article does not say whether the scientists' experiments with dogs have ____.",
  options: ["benefited animals other than dogs", "served man", "helped other dogs", "contributed to medical knowledge"],
  answer: 0,
  explanation: "细节题（找没提到的）。文末说狗的牺牲保护了它自己这个物种（狂犬病等）、也促成了心脏手术——但没提到有没有惠及“狗以外的其他动物” → A。" },

/* -------- Passage Two：Lost Sea 地下湖 -------- */
{ id: "mk2-40", paper: "M2", ord: 40, mock: true, level: 3, module: "reading", topic: "reading", passageId: "M2-p2",
  source: "全真模拟(二) 阅读 Passage Two",
  passage: "Deep inside a mountain near Sweetwater in East Tennessee is a body of water known as the Lost Sea. It is listed by the Guinness Book of World Records as the world's largest underground lake. The Lost Sea is part of an extensive and historic cave system called Craighead Caverns.\nThe caverns have been known and used since the days of the Cherokee Indian nation. The cave expands into a series of huge rooms from a small opening on the side of the mountain. Approximately one mile from the entrance, in a room called “The Council Room”, many Indian artifacts have been found. Some of the items discovered include pottery, arrowheads, weapons, and jewelry.\nFor many years there were persistent rumors of a large underground lake somewhere in a cave, but it was not discovered until 1905. In that year, a thirteen-year-old boy named Ben Sands crawled through a small opening three hundred feet underground. He found himself in a large cave half filled with water.\nToday tourists visit the Lost Sea and ride far out onto it in glass-bottomed boats powered by electric motors. More than thirteen acres of water have been mapped out so far and still no end to the lake has been found. Even though teams of divers have tried to explore the Lost Sea, the full extent of it is still unknown.",
  stem: "The Lost Sea is unique because it is ____.",
  options: ["part of a historical cave system", "the biggest underground lake in the world", "listed in the Guinness Book of World Records", "the largest body of water in Tennessee"],
  answer: 1,
  explanation: "细节题。第一段第二句：吉尼斯世界纪录认定它是“世界最大的地下湖”——这是它独一无二的原因 → B。" },
{ id: "mk2-41", paper: "M2", ord: 41, mock: true, level: 3, module: "reading", topic: "reading", passageId: "M2-p2",
  source: "全真模拟(二) 阅读 Passage Two",
  stem: "Who located the Lost Sea in recent times?",
  options: ["The Cherokee Indians.", "Tourists.", "Ben Sands.", "Scientists."],
  answer: 2,
  explanation: "细节题。第三段：1905 年，13 岁男孩 Ben Sands 从地下三百英尺的小洞爬进去发现了这个湖 → C。" },
{ id: "mk2-42", paper: "M2", ord: 42, mock: true, level: 3, module: "reading", topic: "reading", passageId: "M2-p2",
  source: "全真模拟(二) 阅读 Passage Two",
  stem: "What was found in “The Council Room”?",
  options: ["A small natural opening.", "A large cave.", "Another series of rooms.", "Many old Indian objects."],
  answer: 3,
  explanation: "细节题。第二段：Council Room 里发现了很多印第安人的物品——陶器、箭头、武器、珠宝 → D。" },
{ id: "mk2-43", paper: "M2", ord: 43, mock: true, level: 3, module: "reading", topic: "reading", passageId: "M2-p2",
  source: "全真模拟(二) 阅读 Passage Two",
  stem: "It can be inferred from the passage that the Craighead Caverns presently serve as ____.",
  options: ["an underground testing site", "an Indian meeting ground", "a tourist attraction", "a motor boat race course"],
  answer: 2,
  explanation: "推断题。最后一段：如今游客坐着玻璃底电动船游湖——说明这里现在是旅游景点 → C。" },

/* -------- Passage Three：太空辐射 -------- */
{ id: "mk2-44", paper: "M2", ord: 44, mock: true, level: 3, module: "reading", topic: "reading", passageId: "M2-p3",
  source: "全真模拟(二) 阅读 Passage Three",
  passage: "Space is a dangerous place, not only because of meteors but also because of rays from the sun and other stars. The atmosphere again acts as our protective blanket on earth. Light gets through, and this is essential for plants to make the food which we eat. Heat, too, makes our environment endurable. Various kinds of rays come through the air from outer space, but enormous quantities of radiation from the sun are screened off. As soon as men leave the atmosphere they are exposed to this radiation. But their spacesuits or the walls of their spacecraft, if they are inside, do prevent a lot of radiation damage.\nRadiation is the greatest known danger to explorers in space. The unit of radiation is called “rem”. Scientists have reason to think that a man can put up with far more radiation than 0.1 rem without being damaged; the figure of 60 rems has been agreed on. The trouble is that it is extremely difficult to be sure about radiation damage—a person may feel perfectly well, but the cells of his or her sex organs may be damaged, and this will not be discovered until the birth of deformed(畸形的) children or even grandchildren. Missions of the Apollo flights have had to cross belts of high radiation and, during the outward and return journeys, the Apollo crew accumulated a large amount of rems. So far, no dangerous amounts of radiation have been reported, but the Apollo missions have been quite short. We simply do not know yet how men are going to get on when they spend weeks and months outside the protection of the atmosphere, working in a space laboratory. Drugs might help to decrease the damage done by radiation, but no really effective ones have been found so far.",
  stem: "According to the first paragraph, the atmosphere is essential to man in that ____.",
  options: ["it protects him against the harmful rays from space", "it provides sufficient light for plant growth", "it supplies the heat necessary for human survival", "it screens off the falling meteors"],
  answer: 0,
  explanation: "细节题。第一段：大气层是保护毯，挡掉了来自太阳的大量辐射——对人最关键的作用是防有害射线 → A。" },
{ id: "mk2-45", paper: "M2", ord: 45, mock: true, level: 3, module: "reading", topic: "reading", passageId: "M2-p3",
  source: "全真模拟(二) 阅读 Passage Three",
  stem: "We know from the passage that ____.",
  options: ["exposure to even tiny amounts of radiation is fatal", "the effect of exposure to radiation is slow in coming", "radiation is avoidable in space exploration", "astronauts in spacesuits needn't worry about radiation damage"],
  answer: 1,
  explanation: "推断题。第二段：辐射伤害极难确定——人可能感觉良好，但生殖细胞受损要到畸形后代出生才发现，即影响显现得慢 → B。" },
{ id: "mk2-46", paper: "M2", ord: 46, mock: true, level: 3, module: "reading", topic: "reading", passageId: "M2-p3",
  source: "全真模拟(二) 阅读 Passage Three ⚠️印刷答案字母与解析矛盾，按解析录 B",
  stem: "It can be inferred from the passage that ____.",
  options: ["the Apollo mission was very successful", "protection from space radiation is no easy job", "astronauts will have deformed children or grandchildren", "radiation is not a threat to well-protected space explorers"],
  answer: 1,
  explanation: "推断题。最后一句：药物可能有助于减轻辐射伤害，但至今没找到真正有效的——可见防辐射并非易事 → B。" },
{ id: "mk2-47", paper: "M2", ord: 47, mock: true, level: 3, module: "reading", topic: "reading", passageId: "M2-p3",
  source: "全真模拟(二) 阅读 Passage Three",
  stem: "The best title for this passage would be ____.",
  options: ["The Atmosphere and Our Environment", "Research on Radiation", "Effects of Space Radiation", "Importance of Protection Against Radiation"],
  answer: 2,
  explanation: "主旨题。全文围绕太空辐射对人的影响展开（大气挡辐射→出大气层暴露→伤害难测） → C。" },

/* -------- Passage Four：Peters 太太的钢琴 -------- */
{ id: "mk2-48", paper: "M2", ord: 48, mock: true, level: 3, module: "reading", topic: "reading", passageId: "M2-p4",
  source: "全真模拟(二) 阅读 Passage Four",
  passage: "Mrs. Peters stopped playing the piano when she began to work. She had lived in a very small flat, and there had been no room for a piano. But when she married, she had a new flat which was big enough for one. So she decided to get one and her husband agreed and helped her. She saved some money, and her parents gave her a generous amount of money for her birthday. Then she went to a shop and said, “I'll choose whichever piano does not cost too much and fits into my living room.”\nWhen she had paid for the piano, the shop assistant asked her if she would like him to get it tuned(调音) every few months. Mrs. Peters agreed.\nA few months later she heard from the shop that a man was coming to tune the piano at ten that morning. Now she had not cleaned the house yet, so it was dusty and untidy. Mrs. Peters hated having even the least amount of dirt, and felt ashamed whenever strange people saw her house like that. So she had to hurry to clean everything carefully. It meant a lot of effort, and it made her hot and tired, but anyhow, by the time the man arrived, everything was finished.\nShe opened the door, and the man was standing there with a big dog. “Good morning,” the man said politely, “Will it disturb you if I bring my dog in, please? I'm blind, and he leads me wherever I go.”",
  stem: "Mrs. Peters was soon able to buy a piano because ____.",
  options: ["her parents gave her all the money for it", "she saved enough money for it", "her husband gave her the money", "she saved some money and her relatives gave her the rest"],
  answer: 3,
  explanation: "细节题。第一段：她自己存了一些钱，父母生日时又给了一大笔——两笔加起来才买得起 → D。" },
{ id: "mk2-49", paper: "M2", ord: 49, mock: true, level: 3, module: "reading", topic: "reading", passageId: "M2-p4",
  source: "全真模拟(二) 阅读 Passage Four",
  stem: "One morning, ____.",
  options: ["a man was coming to repair her piano", "Mrs. Peters received a telephone call from the shop", "the piano was sent to her house at 10 o'clock", "Mrs. Peters was going to clean the house"],
  answer: 1,
  explanation: "细节题。第三段：她“从商店那里得到消息”，调音师当天上午十点要来——即接到商店通知 → B。" },
{ id: "mk2-50", paper: "M2", ord: 50, mock: true, level: 3, module: "reading", topic: "reading", passageId: "M2-p4",
  source: "全真模拟(二) 阅读 Passage Four",
  stem: "“It meant a lot of effort, and it made her hot and tired.” Here “it” refers to ____.",
  options: ["hating dirt", "cleaning everything", "waiting for the man", "feeling ashamed of the dirty and untidy house"],
  answer: 1,
  explanation: "词语理解题。it 指前一句说的事——赶在调音师来之前把屋子彻底打扫干净 → B。" },
{ id: "mk2-51", paper: "M2", ord: 51, mock: true, level: 3, module: "reading", topic: "reading", passageId: "M2-p4",
  source: "全真模拟(二) 阅读 Passage Four",
  stem: "Mrs. Peters had wasted her time getting everything clean as ____.",
  options: ["the dog would dirty the house", "the piano tuner could see nothing in the house", "the dog disturbed Mrs. Peters", "the piano tuner always took the dog"],
  answer: 1,
  explanation: "推断题（也是这篇的笑点）：她精心打扫是怕生人看到屋子脏乱，结果调音师是盲人，根本看不到 → B。" },

/* -------- Passage Five：雨伞的历史 -------- */
{ id: "mk2-52", paper: "M2", ord: 52, mock: true, level: 3, module: "reading", topic: "reading", passageId: "M2-p5",
  source: "全真模拟(二) 阅读 Passage Five",
  passage: "It seems so natural to put up an umbrella to keep the water off when it rains. But actually the umbrella was not invented as protection against rain. Its first use was as a shade against the sun!\nNobody knows who first invented it, but the umbrella was used in very ancient times. Probably the first to use it were the Chinese, as early as the eleventh century B.C.\nWe know that the umbrella was used in ancient Egypt and Babylon as a sunshade. And there was a strange thing connected with its use: it became a symbol of honour and authority. In the Far East in ancient times the umbrella was allowed to be used only by royalty or by those in high office.\nIn Europe, the Greeks were the first to use the umbrella as a sunshade. And the umbrella was in common use in ancient Greece. But it is believed that the first persons in Europe to use the umbrella as protection against the rain were the ancient Romans.\nDuring the Middle Ages, the use of the umbrella practically disappeared. Then it appeared again in Italy in the late sixteenth century. And again it was considered a symbol of power and authority. By 1680, the umbrella appeared in France, and later on in England.\nBy the eighteenth century, the umbrella was used against rain throughout most of Europe. Umbrellas have not changed much in style during all this time, though they have become much lighter in weight. It wasn't until the twentieth century that women's umbrellas began to be made, in a whole variety of colours.",
  stem: "Which of the following statements is NOT true about the umbrella?",
  options: ["No one exactly knows who was the inventor of the umbrella.", "The umbrella was first invented to be used as protection against the sun.", "The umbrella changed much in style in the eighteenth century.", "In Europe the Greeks were the first to use the umbrella as a sunshade."],
  answer: 2,
  explanation: "细节题（找错误项）。最后一段：这段时间里伞的样式“没怎么变”，只是变轻了——C 说十八世纪样式大变，与原文相反 → C。" },
{ id: "mk2-53", paper: "M2", ord: 53, mock: true, level: 3, module: "reading", topic: "reading", passageId: "M2-p5",
  source: "全真模拟(二) 阅读 Passage Five",
  stem: "A strange feature of the umbrella's use is that it was used as ____.",
  options: ["protection against rain", "a shade against the sun", "a symbol of honour and power", "a way of women's decoration"],
  answer: 2,
  explanation: "细节题。第三段：与伞相关的奇特之处——它成了荣耀和权力的象征，古代远东只有皇室和高官能用 → C。" },
{ id: "mk2-54", paper: "M2", ord: 54, mock: true, level: 3, module: "reading", topic: "reading", passageId: "M2-p5",
  source: "全真模拟(二) 阅读 Passage Five",
  stem: "In Europe, the umbrella was first used against the rain ____.",
  options: ["in China", "in ancient Egypt", "in Rome", "in Greece"],
  answer: 2,
  explanation: "细节题。第四段最后一句：欧洲最早用伞挡雨的是古罗马人 → C（希腊人最早用伞，但是用来遮阳）。" },
{ id: "mk2-55", paper: "M2", ord: 55, mock: true, level: 3, module: "reading", topic: "reading", passageId: "M2-p5",
  source: "全真模拟(二) 阅读 Passage Five",
  stem: "This passage talks mainly about ____.",
  options: ["how the umbrella was invented", "why the umbrella was so popular in Europe", "the development of the umbrella", "who needed umbrella first"],
  answer: 2,
  explanation: "主旨题。全文按时间线讲伞的起源、用途和形状随时代的变化——即伞的发展史 → C。" },

/* ==================== Ⅴ. 补全对话（5 题）==================== */
{ id: "mk2-56", paper: "M2", ord: 56, mock: true, level: 3, module: "conversation", topic: "conversation", passageId: "M2-conv",
  source: "全真模拟(二) 补全对话",
  passage: "A: Good morning! (56)____?\nB: Yes, may I see your production manager, Mr. Smith, please?\nA: I am sorry. Mr. Smith is (57)____.\nB: Well, I'd like to (58)____.\nA: Let me check Mr. Smith's diary. Just a moment. Yes, Mr. Smith doesn't seem to be busy on Tuesday morning and Friday afternoon.\nB: Could I make an appointment for Tuesday morning?\nA: (59)____?\nB: Yes, that'll be fine.\nA: I'll make a note of that. May I have your name, please?\nB: Yes, (60)____. You can contact me any day.\nA: OK.\nB: Thank you very much! Good-bye!\nA: Good-bye!",
  stem: "(56) 处应填：",
  options: ["Can I help you", "How long will it be", "Would 9:30 be convenient", "Yes, he does"],
  answer: 0,
  explanation: "前台开场白，后面对方直接说来意（想见 Smith 经理）→ Can I help you 需要帮忙吗。" },
{ id: "mk2-57", paper: "M2", ord: 57, mock: true, level: 3, module: "conversation", topic: "conversation", passageId: "M2-conv",
  source: "全真模拟(二) 补全对话",
  stem: "(57) 处应填：",
  options: ["It won't be long", "out on business today", "make an appointment to see him", "this is my name card"],
  answer: 1,
  explanation: "I am sorry. Mr. Smith is ____ → 抱歉他今天“出差了” → out on business today。" },
{ id: "mk2-58", paper: "M2", ord: 58, mock: true, level: 3, module: "conversation", topic: "conversation", passageId: "M2-conv",
  source: "全真模拟(二) 补全对话",
  stem: "(58) 处应填：",
  options: ["How long will it be", "this is my name card", "make an appointment to see him sometime next week", "Would 9:30 be convenient"],
  answer: 2,
  explanation: "I'd like to ____ → 想“约个下周的时间见他”；下文对方去查日程也印证了这是在预约。" },
{ id: "mk2-59", paper: "M2", ord: 59, mock: true, level: 3, module: "conversation", topic: "conversation", passageId: "M2-conv",
  source: "全真模拟(二) 补全对话",
  stem: "(59) 处应填：",
  options: ["How long will it be", "It won't be long", "Would 9:30 be convenient", "Can I help you"],
  answer: 2,
  explanation: "对方定了周二上午，前台进一步确认具体时间；下一句回答 Yes, that'll be fine → 问“9:30 方便吗”。" },
{ id: "mk2-60", paper: "M2", ord: 60, mock: true, level: 3, module: "conversation", topic: "conversation", passageId: "M2-conv",
  source: "全真模拟(二) 补全对话",
  stem: "(60) 处应填：",
  options: ["Yes, he does", "this is my name card", "It won't be long", "Would 9:30 be convenient"],
  answer: 1,
  explanation: "对方问姓名，回答“这是我的名片”，并说可随时联系 → this is my name card。" },

]);
