/* ============================================================================
 * questions-mock1b.js —— 全真模拟(一) 的语音 + 词汇语法（补录 20 题）
 * ----------------------------------------------------------------------------
 * 原来的 questions-mock.js 只录了模拟(一)的完形 15 + 阅读 20 + 补全对话 5 ＝ 40 题，
 * 卷首的语音 5 题、词汇与语法 15 题一直缺着。这里补齐，M1 凑成完整一卷（60 题）。
 * 来源：用户提供的 PDF《英语全真模拟卷及答案解析（五套）》第一套（原书第 1-6 页）。
 *
 * ⚠️ 第 7 题原书【答案】印的是 A（lest），但它自己的解析写着「句意：**如果**有足够的钱，
 *    我们明年将去欧洲旅行」，而同一段的词义表里 provided＝假如、如果 —— 按解析录 D。
 *    （lest 是「唯恐、以免」，塞进这句完全不通。）
 * ========================================================================== */

window.PAPERS = (window.PAPERS || []).concat([{
  id: "M1", name: "全真模拟(一)",
  essay: "你是王刚（Wang Gang），写一封给同学李明（Li Ming）的祝贺信，祝贺他获得复旦大学计算机科学硕士学位，并祝他今后在学习和研究方面取得成功。",
}]);

window.QUESTIONS = (window.QUESTIONS || []).concat([

/* ==================== Ⅰ. 语音（5 题）==================== */
{ id: "mk1-ph-01", paper: "M1", ord: 1, mock: true, level: 3, module: "phonetics", topic: "phonetics-u",
  source: "全真模拟(一) 第1题", stem: "选出划线部分读音与其它三个不同的一项：",
  options: ["d__u__ck", "d__u__ty", "d__u__st", "d__u__mp"], answer: 1,
  explanation: "duck / dust / dump 里的 u 都读短音 /ʌ/，只有 duty 读 /juː/。" },
{ id: "mk1-ph-02", paper: "M1", ord: 2, mock: true, level: 3, module: "phonetics", topic: "phonetics-g",
  source: "全真模拟(一) 第2题", stem: "选出划线部分读音与其它三个不同的一项：",
  options: ["__g__ain", "__g__ang", "__g__iant", "__g__rain"], answer: 2,
  explanation: "g 在 a / r 前读 /g/（gain、gang、grain），在 i / e / y 前常读 /dʒ/ —— giant 读 /dʒ/。" },
{ id: "mk1-ph-03", paper: "M1", ord: 3, mock: true, level: 3, module: "phonetics", topic: "phonetics-ow",
  source: "全真模拟(一) 第3题", stem: "选出划线部分读音与其它三个不同的一项：",
  options: ["all__ow__", "fell__ow__", "n__ow__", "c__ow__"], answer: 1,
  explanation: "allow / now / cow 里的 ow 读 /aʊ/，只有 fellow 读 /əʊ/。" },
{ id: "mk1-ph-04", paper: "M1", ord: 4, mock: true, level: 3, module: "phonetics", topic: "phonetics-y",
  source: "全真模拟(一) 第4题", stem: "选出划线部分读音与其它三个不同的一项：",
  options: ["fl__y__", "sill__y__", "simpl__y__", "cit__y__"], answer: 0,
  explanation: "单音节词末尾的 y 读 /aɪ/（fly），多音节词末尾的 y 读 /i/（silly、simply、city）。" },
{ id: "mk1-ph-05", paper: "M1", ord: 5, mock: true, level: 3, module: "phonetics", topic: "phonetics-a",
  source: "全真模拟(一) 第5题", stem: "选出划线部分读音与其它三个不同的一项：",
  options: ["bl__a__ck", "bl__a__de", "m__a__p", "s__a__ck"], answer: 1,
  explanation: "闭音节里的 a 读短音 /æ/（black、map、sack）；blade 是「元音+辅音+e」的开音节，a 读字母音 /eɪ/。" },

/* ==================== Ⅱ. 词汇与语法（15 题）==================== */
{ id: "mk1-gr-06", paper: "M1", ord: 6, mock: true, level: 2, module: "grammar", topic: "collocation",
  source: "全真模拟(一) 第6题",
  stem: "The committee is totally opposed ____ any changes being made in the plans.",
  options: ["of", "on", "to", "against"], answer: 2,
  explanation: "**be opposed to** = 反对（to 是介词，后面接名词或动名词）。",
  optionNotes: ["错：没有 opposed of 这个搭配", "错：没有 opposed on 这个搭配", "对：be opposed to = 反对", "错：oppose 本身已含「反对」，不再加 against"] },
{ id: "mk1-gr-07", paper: "M1", ord: 7, mock: true, level: 3, module: "grammar", topic: "conjunction",
  source: "全真模拟(一) 第7题（⚠️原书答案字母与解析矛盾，按解析录 D）",
  stem: "We'll visit Europe next year ____ we have enough money.",
  options: ["lest", "until", "unless", "provided"], answer: 3,
  explanation: "句意是「**如果**有足够的钱，我们明年就去欧洲」→ provided = 假如、如果（相当于 if）。\n⚠️ 原书【答案】印的是 A（lest 唯恐、以免），但它自己的解析写的句意就是「如果有足够的钱」，属印刷错误。",
  optionNotes: ["错：lest = 唯恐、以免，后面还要接虚拟语气，句意不通", "错：until = 直到……为止", "错：unless = 除非、如果不，意思正好反了", "对：provided = 假如、如果"] },
{ id: "mk1-gr-08", paper: "M1", ord: 8, mock: true, level: 3, module: "grammar", topic: "collocation",
  source: "全真模拟(一) 第8题",
  stem: "My father seemed to be in no ____ to look at my school report.",
  options: ["mood", "emotion", "attitude", "feeling"], answer: 0,
  explanation: "**be in no mood to do sth.** = 没有做某事的心情，固定词组。",
  optionNotes: ["对：be in no mood to do = 没心情做……", "错：emotion 指情绪、情感，不用于这个词组", "错：attitude 是态度", "错：feeling 是感觉，不用于这个词组"] },
{ id: "mk1-gr-09", paper: "M1", ord: 9, mock: true, level: 4, module: "grammar", topic: "subjunctive",
  source: "全真模拟(一) 第9题",
  stem: "It is important that enough money ____ to fund the project.",
  options: ["be collected", "must be collected", "is collected", "can be collected"], answer: 0,
  explanation: "**It is important / necessary / natural that + 从句** 要用虚拟语气：should + 动词原形，should 可省略 → (should) be collected。",
  optionNotes: ["对：(should) be collected，should 省略后剩动词原形", "错：虚拟语气不用 must", "错：is collected 是陈述语气，不符合该句型", "错：虚拟语气不用 can"] },
{ id: "mk1-gr-10", paper: "M1", ord: 10, mock: true, level: 3, module: "grammar", topic: "conjunction",
  source: "全真模拟(一) 第10题",
  stem: "You'd better take an umbrella with you ____ it rains.",
  options: ["nevertheless", "although", "in case", "so that"], answer: 2,
  explanation: "**in case** = 以防万一。句意：你最好带把伞，以防下雨。",
  optionNotes: ["错：nevertheless = 然而、不过（副词，不引导从句）", "错：although = 尽管，逻辑不通", "对：in case = 以防万一", "错：so that = 以便、结果，表目的或结果"] },
{ id: "mk1-gr-11", paper: "M1", ord: 11, mock: true, level: 4, module: "grammar", topic: "subjunctive",
  source: "全真模拟(一) 第11题",
  stem: "Frankly speaking, I'd rather you ____ anything about it for the time being.",
  options: ["didn't do", "haven't done", "don't do", "have done"], answer: 0,
  explanation: "**would rather + 从句**，从句要用虚拟语气：表示**现在或将来**用一般过去时，表示过去用过去完成时。这里是「现在暂时别做」→ didn't do。",
  optionNotes: ["对：would rather 后的从句用过去式表示现在/将来的愿望", "错：现在完成时不用于这个结构", "错：一般现在时不用于这个结构", "错：时态与「暂时别做」矛盾"] },
{ id: "mk1-gr-12", paper: "M1", ord: 12, mock: true, level: 3, module: "grammar", topic: "collocation",
  source: "全真模拟(一) 第12题",
  stem: "I'm sorry I can't see you immediately; but if you'd like to take a seat, I'll be with you ____.",
  options: ["for a moment", "in a moment", "for the moment", "at the moment"], answer: 1,
  explanation: "**in a moment** = 过一会儿（表将来）。四个长得很像的词组各有各的意思，只能一组一组记。",
  optionNotes: ["错：for a moment = 一会儿（表示持续了一小段时间）", "对：in a moment = 过一会儿、马上", "错：for the moment = 暂时、目前", "错：at the moment = 此刻、现在"] },
{ id: "mk1-gr-13", paper: "M1", ord: 13, mock: true, level: 4, module: "grammar", topic: "comparative",
  source: "全真模拟(一) 第13题",
  stem: "The trumpet player was certainly loud. But I wasn't bothered by his loudness ____ by his lack of talent.",
  options: ["than", "more than", "as", "so much as"], answer: 3,
  explanation: "**not so much A as B** = 与其说 A，不如说 B。句意：与其说我受不了他的音量，不如说受不了他缺乏才华。\n💡 句首的 But 已经限定了后半句要转折，A、C 项连比较级的正确形式都不是。",
  optionNotes: ["错：than 前面缺比较级", "错：more than 意思反了（变成「更受不了音量」）", "错：as 单独用不成这个结构", "对：not so much A as B = 与其说 A 不如说 B"] },
{ id: "mk1-gr-14", paper: "M1", ord: 14, mock: true, level: 3, module: "grammar", topic: "word-choice",
  source: "全真模拟(一) 第14题",
  stem: "Our new house is very ____ for me as I can get to the office in five minutes.",
  options: ["adaptable", "comfortable", "convenient", "available"], answer: 2,
  explanation: "as 引导的原因状语从句给了提示：五分钟就能到办公室 —— 说的是**方便** → convenient。",
  optionNotes: ["错：adaptable = 可适应的、可改编的", "错：comfortable = 舒适的（讲身体感受，不讲距离远近）", "对：convenient = 方便的", "错：available = 可获得的、可利用的"] },
{ id: "mk1-gr-15", paper: "M1", ord: 15, mock: true, level: 4, module: "grammar", topic: "word-choice",
  source: "全真模拟(一) 第15题",
  stem: "Our journey was slow because the train stopped ____ at different villages.",
  options: ["suddenly", "gradually", "continuously", "continually"], answer: 3,
  explanation: "continuously 和 continually 都译成「连续不断地」，但 **continually 隐含中间有停顿**（一次又一次地），continuously 是完全不间断。火车在各个村庄停车，显然是「停了又停」→ continually。",
  optionNotes: ["错：suddenly = 突然地", "错：gradually = 逐渐地", "错：continuously 指毫不间断，与「一站一站停」矛盾", "对：continually = 一次又一次地（中间有间隔）"] },
{ id: "mk1-gr-16", paper: "M1", ord: 16, mock: true, level: 2, module: "grammar", topic: "collocation",
  source: "全真模拟(一) 第16题",
  stem: "We love peace, yet we are not the kind of people to yield ____ any military threat.",
  options: ["up", "to", "in", "at"], answer: 1,
  explanation: "**yield to** = 屈服于、向……让步，固定词组。",
  optionNotes: ["错：yield up 是「交出、放弃（某物）」", "对：yield to = 屈服于", "错：yield in 不成搭配", "错：yield at 不成搭配"] },
{ id: "mk1-gr-17", paper: "M1", ord: 17, mock: true, level: 3, module: "grammar", topic: "word-choice",
  source: "全真模拟(一) 第17题",
  stem: "I'm very sorry to have ____ you with so many questions on such an occasion.",
  options: ["interfered", "offended", "impressed", "bothered"], answer: 3,
  explanation: "**bother sb. with sth.** = 用某事麻烦某人。句意：这种场合还问你这么多问题，真不好意思。",
  optionNotes: ["错：interfere = 干涉、妨碍（interfere with sth.）", "错：offend = 得罪、冒犯", "错：impress = 给……留下印象（impress sb. with sth. 语义不合）", "对：bother sb. with sth. = 拿某事麻烦某人"] },
{ id: "mk1-gr-18", paper: "M1", ord: 18, mock: true, level: 4, module: "grammar", topic: "subjunctive",
  source: "全真模拟(一) 第18题",
  stem: "If the whole operation ____ beforehand, a great deal of time and money would have been lost.",
  options: ["was not planned", "has not been planned", "had not been planned", "were not planned"], answer: 2,
  explanation: "主句是 **would have been lost** → 这是对**过去**的虚拟，if 从句必须用 **had + 过去分词**。\n💡 虚拟语气就看主句：would do → 从句过去式（对现在）；would have done → 从句过去完成式（对过去）。",
  optionNotes: ["错：一般过去式对应的是「对现在的虚拟」", "错：现在完成时不用于虚拟条件句", "对：had not been planned，对过去的虚拟", "错：were 形式对应「对现在的虚拟」"] },
{ id: "mk1-gr-19", paper: "M1", ord: 19, mock: true, level: 3, module: "grammar", topic: "word-choice",
  source: "全真模拟(一) 第19题",
  stem: "The price of beer ____ from 50 cents to 4 dollars per liter during the summer season.",
  options: ["altered", "ranged", "separated", "differed"], answer: 1,
  explanation: "**range from A to B** = 在 A 到 B 之间变动，固定搭配。看到 from...to... 就想到 range。",
  optionNotes: ["错：alter = 改变、更改（不接 from...to... 表区间）", "对：range from...to... = 在……范围内变动", "错：separate = 分开、隔离", "错：differ = 不同、有区别"] },
{ id: "mk1-gr-20", paper: "M1", ord: 20, mock: true, level: 3, module: "grammar", topic: "comparative",
  source: "全真模拟(一) 第20题",
  stem: "You cannot be ____ careful when you drive a car.",
  options: ["very", "so", "too", "enough"], answer: 2,
  explanation: "**cannot be too + 形容词** = 无论多……都不为过。句意：开车时再小心也不过分。\n💡 这是个固定的「否定+too」特殊句式，字面像否定，意思是强烈肯定，考过很多次。",
  optionNotes: ["错：cannot be very careful 意思变成「不能很小心」，与常识相反", "错：cannot be so careful 同样是字面否定，语义不通", "对：cannot be too careful = 越小心越好", "错：enough 要放在形容词后面（careful enough），且语义不合"] },
]);
