/* ============================================================================
 * readings-graded.js —— 分级精读课文（由易到难 + 读后理解题）
 *
 * 为什么要它：原 readings.js 每篇只有 5 句 / 约 44 词，是「语法例文」，
 * 而成考真实阅读一篇 200-300 词。阅读45分+完形30分=75分（占卷面52%），
 * 却是全 app 最薄的地方。这里把精读做厚，并加上读后理解题。
 *
 * 分级（跟着章节难度自然进阶）：
 *   L1 第1-10章  ≈ 80 词   —— 句子短、全是本章语法、A1-A2
 *   L2 第11-20章 ≈ 150 词  —— 开始有从句和时态混用
 *   L3 第21-28章 ≈ 250 词  —— 逼近成考真题长度
 *
 * 结构：{ level, words, title, tip, sents:[{en,zh}], qs:[{q,opts,ans,why}] }
 *   sents —— 逐句中英，点句子看翻译、可逐句朗读（与旧 readings 渲染一致）
 *   qs    —— 读后理解题，ans 是正确选项下标(0起)，why 是为什么选它/原文依据
 *
 * ⚠️ 没有 graded 版本的章节，渲染时自动回退到 js/readings.js 的短课文。
 * ⚠️ 中文一律用全角引号“”，别在双引号 JS 字符串里用 ASCII " （会截断字符串）。
 * ========================================================================== */

window.READINGS_GRADED = {

  /* ---------------------------- 第1章 be 动词 ---------------------------- */
  1: {
    level: 1, words: 77,
    title: "My Family（我的一家）",
    tip: "全文几乎每句都有 am / is / are / was / were。读的时候盯住：主语是谁，后面跟的是哪个 be。",
    sents: [
      { en: "My name is Li Ming.", zh: "我叫李明。" },
      { en: "I am twenty-five years old.", zh: "我二十五岁。" },
      { en: "I am a worker in a shoe factory in Wenzhou.", zh: "我是温州一家鞋厂的工人。" },
      { en: "My wife is a nurse.", zh: "我妻子是护士。" },
      { en: "She is very busy every day.", zh: "她每天都很忙。" },
      { en: "We are both from a small village in Anhui.", zh: "我们俩都来自安徽的一个小村子。" },
      { en: "Ten years ago, we were students in the same middle school.", zh: "十年前，我们是同一所中学的学生。" },
      { en: "Our teachers were very kind to us.", zh: "我们的老师对我们很好。" },
      { en: "Now our son is four years old.", zh: "现在我们的儿子四岁了。" },
      { en: "He is in kindergarten.", zh: "他在上幼儿园。" },
      { en: "Life is not easy, but we are happy.", zh: "生活不容易，但我们很幸福。" },
    ],
    qs: [
      { q: "What is Li Ming's job?", opts: ["A nurse", "A worker", "A teacher"], ans: 1,
        why: "第3句：I am a worker in a shoe factory. 他是鞋厂工人。护士是他妻子。" },
      { q: "Where were Li Ming and his wife ten years ago?", opts: ["In a shoe factory", "In the same middle school", "In kindergarten"], ans: 1,
        why: "第7句：ten years ago, we were students in the same middle school（注意用的是过去式 were）。" },
      { q: "How old is their son?", opts: ["Four", "Ten", "Twenty-five"], ans: 0,
        why: "第9句：our son is four years old。25 岁是李明自己，10 是“十年前”。" },
    ],
  },

  /* ------------------- 第2章 名词单复数 & There be -------------------- */
  2: {
    level: 1, words: 77,
    title: "The Park Near My Home（我家附近的公园）",
    tip: "数一数全文用了多少个 There is / There are。规律：后面跟单数就用 is，跟复数就用 are。",
    sents: [
      { en: "There is a small park near my home.", zh: "我家附近有一个小公园。" },
      { en: "There are many tall trees in it.", zh: "里面有很多高大的树。" },
      { en: "Every morning there are a lot of old people there.", zh: "每天早上那里都有很多老人。" },
      { en: "Some of them do exercises.", zh: "他们中有些人在锻炼。" },
      { en: "There are also two or three children with their mothers.", zh: "还有两三个孩子和他们的妈妈在一起。" },
      { en: "There is a big lake in the middle of the park.", zh: "公园中间有一个大湖。" },
      { en: "There are some fish in the water.", zh: "水里有一些鱼。" },
      { en: "On Sundays there are more people.", zh: "周日的时候人更多。" },
      { en: "There is never a quiet moment, but I like this place very much.", zh: "从来没有安静的时候，但我非常喜欢这个地方。" },
    ],
    qs: [
      { q: "What is in the middle of the park?", opts: ["A big lake", "Many tall trees", "Some children"], ans: 0,
        why: "第6句：There is a big lake in the middle of the park。" },
      { q: "When are there more people in the park?", opts: ["Every morning", "On Sundays", "At night"], ans: 1,
        why: "第8句：On Sundays there are more people。" },
      { q: "What do some of the old people do in the morning?", opts: ["They swim in the lake", "They do exercises", "They read books"], ans: 1,
        why: "第4句：Some of them do exercises。them 指上一句的 old people。" },
    ],
  },

  /* -------------------------- 第3章 冠词 a/an/the -------------------------- */
  3: {
    level: 1, words: 79,
    title: "A Bookshop in Our Town（镇上的一家书店）",
    tip: "注意 a / an / the 的切换：第一次提到用 a/an，再次提到同一个东西就用 the。元音音素前用 an。",
    sents: [
      { en: "Let me tell you about a shop near my home.", zh: "让我给你讲讲我家附近的一家店。" },
      { en: "It is a small bookshop.", zh: "那是一家小书店。" },
      { en: "The shop is next to a bus station.", zh: "这家店紧挨着一个公交站。" },
      { en: "There is a big window in the front.", zh: "店面前有一扇大窗户。" },
      { en: "In the window you can see a dictionary, an English magazine and a map.", zh: "在窗户里你能看到一本词典、一本英语杂志和一张地图。" },
      { en: "The owner is an old man.", zh: "店主是一位老人。" },
      { en: "He is always very kind.", zh: "他总是很和气。" },
      { en: "The old man knows a lot about books.", zh: "这位老人对书懂得很多。" },
      { en: "If you want a good book, the bookshop is the best place in our town.", zh: "如果你想要一本好书，这家书店是我们镇上最好的地方。" },
    ],
    qs: [
      { q: "Where is the bookshop?", opts: ["Next to a bus station", "In a big city", "Behind a school"], ans: 0,
        why: "第3句：The shop is next to a bus station。" },
      { q: "What can you see in the window?", opts: ["Only some maps", "A dictionary, a magazine and a map", "Nothing at all"], ans: 1,
        why: "第5句列了三样：a dictionary, an English magazine and a map。" },
      { q: "What is the owner like?", opts: ["Young and busy", "Old and kind", "Old and angry"], ans: 1,
        why: "第6、7句：The owner is an old man. He is always very kind。" },
    ],
  },

  /* ----------------------------- 第4章 代词 ------------------------------ */
  4: {
    level: 1, words: 74,
    title: "My Classroom（我的教室）",
    tip: "盯住每个代词指的是谁：it / she / her / mine / us / him / his / them / ours。读到一个就问自己“这指的是前面哪个人或哪个东西”。",
    sents: [
      { en: "This is my classroom.", zh: "这是我的教室。" },
      { en: "It is not very big, but we all like it.", zh: "它不太大，但我们都喜欢它。" },
      { en: "My desk is near the window.", zh: "我的课桌靠着窗户。" },
      { en: "The one next to it is Wang Li's.", zh: "旁边那张是王丽的。" },
      { en: "She is my best friend.", zh: "她是我最好的朋友。" },
      { en: "Her bag is always tidy, but mine is not.", zh: "她的书包总是很整齐，但我的不是。" },
      { en: "Our teacher is Mr. Zhang.", zh: "我们的老师是张老师。" },
      { en: "He teaches us English.", zh: "他教我们英语。" },
      { en: "We often ask him questions after class, and he always helps us.", zh: "我们课后经常问他问题，他总是帮助我们。" },
      { en: "His lessons are interesting, and everyone in our class likes them.", zh: "他的课很有意思，我们班每个人都喜欢。" },
    ],
    qs: [
      { q: "Whose desk is next to the writer's desk?", opts: ["Mr. Zhang's", "Wang Li's", "Nobody's"], ans: 1,
        why: "第4句：The one next to it is Wang Li's。the one 指“那张课桌”。" },
      { q: "What does Mr. Zhang teach?", opts: ["Chinese", "English", "Math"], ans: 1,
        why: "第8句：He teaches us English。" },
      { q: "In the last sentence, what does “them” mean?", opts: ["The students", "Mr. Zhang's lessons", "The desks"], ans: 1,
        why: "最后一句：His lessons are interesting... everyone likes them。them 指前面的 lessons（课）。" },
    ],
  },

  /* --------------------- 第5章 一般现在时（三单加 s） --------------------- */
  5: {
    level: 1, words: 70,
    title: "My Sister's Day（我姐姐的一天）",
    tip: "主语是 she（第三人称单数），所以动词几乎都加了 s：works / gets / takes / looks / comes…… 找找看有几个。",
    sents: [
      { en: "My sister works in a hospital in Beijing.", zh: "我姐姐在北京一家医院工作。" },
      { en: "She gets up at six every morning.", zh: "她每天早上六点起床。" },
      { en: "She takes the subway to work.", zh: "她坐地铁去上班。" },
      { en: "Her work starts at eight.", zh: "她八点开始工作。" },
      { en: "She looks after old patients all day.", zh: "她整天照顾年长的病人。" },
      { en: "She often comes home late.", zh: "她经常很晚回家。" },
      { en: "My mother worries about her, but my sister says she likes her job.", zh: "我妈妈为她担心，但姐姐说她喜欢这份工作。" },
      { en: "On Sundays she does not work.", zh: "周日她不上班。" },
      { en: "She usually stays at home and reads books.", zh: "她通常待在家里看书。" },
      { en: "She never forgets my birthday.", zh: "她从不忘记我的生日。" },
    ],
    qs: [
      { q: "How does the sister go to work?", opts: ["By bus", "By subway", "On foot"], ans: 1,
        why: "第3句：She takes the subway to work。" },
      { q: "What does she usually do on Sundays?", opts: ["She works in the hospital", "She stays at home and reads", "She visits her mother"], ans: 1,
        why: "第8、9句：On Sundays she does not work. She usually stays at home and reads books。" },
      { q: "Why does the mother worry about her?", opts: ["Because she often comes home late", "Because she has no job", "Because she is ill"], ans: 0,
        why: "第6、7句连起来看：She often comes home late. My mother worries about her。" },
    ],
  },

  /* ------------------------- 第6章 现在进行时 --------------------------- */
  6: {
    level: 1, words: 81,
    title: "Seven O'clock in the Evening（晚上七点）",
    tip: "全文都在讲“此刻正在发生”，所以是 be + doing。注意否定式怎么写：is not working。",
    sents: [
      { en: "It is seven o'clock in the evening.", zh: "现在是晚上七点。" },
      { en: "My family are all at home.", zh: "我们全家都在家。" },
      { en: "My father is watching the news on TV.", zh: "我爸爸正在看电视新闻。" },
      { en: "My mother is cooking in the kitchen.", zh: "我妈妈正在厨房做饭。" },
      { en: "She is making noodles for us.", zh: "她正在给我们做面条。" },
      { en: "My little brother is doing his homework, but he is not working hard.", zh: "我弟弟正在写作业，但他并不认真。" },
      { en: "He is playing with his pen.", zh: "他正在玩他的笔。" },
      { en: "I am sitting by the window and writing this letter to you.", zh: "我正坐在窗边给你写这封信。" },
      { en: "Outside it is raining.", zh: "外面正在下雨。" },
      { en: "Everyone is doing something different, and our home is warm and noisy.", zh: "每个人都在做不同的事，我们的家温暖又热闹。" },
    ],
    qs: [
      { q: "What is the mother doing?", opts: ["Watching TV", "Making noodles", "Writing a letter"], ans: 1,
        why: "第4、5句：My mother is cooking... She is making noodles for us。看电视的是爸爸，写信的是作者。" },
      { q: "Is the little brother working hard?", opts: ["Yes, he is", "No, he is playing with his pen", "He is sleeping"], ans: 1,
        why: "第6、7句：he is not working hard. He is playing with his pen。" },
      { q: "What is the weather like?", opts: ["Sunny", "Raining", "Snowing"], ans: 1,
        why: "第9句：Outside it is raining。" },
    ],
  },

  /* ------------------ 第7章 数量词 some/any/much/many ------------------- */
  7: {
    level: 1, words: 83,
    title: "A Party on Saturday（周六的聚会）",
    tip: "肯定句用 some，否定/疑问用 any；不可数用 much，可数用 many。看看每个词后面跟的是什么。",
    sents: [
      { en: "I am going to have a party this Saturday.", zh: "这周六我要办一个聚会。" },
      { en: "I have some good news for my friends.", zh: "我有一些好消息要告诉朋友们。" },
      { en: "But there is a problem: I do not have much money.", zh: "但有个问题：我没有很多钱。" },
      { en: "I have some rice and a few eggs at home, but there isn't any meat.", zh: "我家里有一些米和几个鸡蛋，但没有任何肉。" },
      { en: "There aren't many drinks either.", zh: "饮料也不多。" },
      { en: "My friend Li says she can bring some fruit.", zh: "我朋友小李说她可以带些水果来。" },
      { en: "Another friend has a lot of music.", zh: "另一个朋友有很多音乐。" },
      { en: "So we don't need much money.", zh: "所以我们不需要很多钱。" },
      { en: "We only need some food, a few friends and a lot of fun.", zh: "我们只需要一些食物、几个朋友和很多快乐。" },
    ],
    qs: [
      { q: "What does the writer NOT have at home?", opts: ["Any meat", "Any rice", "Any eggs"], ans: 0,
        why: "第4句：I have some rice and a few eggs..., but there isn't any meat。米和鸡蛋是有的。" },
      { q: "What is Li going to bring?", opts: ["Some meat", "Some fruit", "Some money"], ans: 1,
        why: "第6句：she can bring some fruit。" },
      { q: "What does the writer think they really need?", opts: ["A lot of money", "Some food, a few friends and a lot of fun", "Much meat and many drinks"], ans: 1,
        why: "最后一句直接给出答案；第8句还说 we don't need much money。" },
    ],
  },

  /* --------------------- 第8章 介词（时间 / 地点） ---------------------- */
  8: {
    level: 1, words: 82,
    title: "My Small Town（我住的小镇）",
    tip: "把所有介词圈出来：in / on / at / next to / before / in the morning……体会“大地方用 in，街道用 on，门牌号和钟点用 at”。",
    sents: [
      { en: "I live in a small town in the south of China.", zh: "我住在中国南方的一个小镇上。" },
      { en: "My house is on Green Street, next to a post office.", zh: "我家在绿街上，紧挨着一家邮局。" },
      { en: "I work at a bank.", zh: "我在一家银行工作。" },
      { en: "I start work at nine in the morning and finish at five in the afternoon.", zh: "我早上九点上班，下午五点下班。" },
      { en: "On Monday I always go to the market before work.", zh: "周一我总是在上班前去市场。" },
      { en: "In summer I ride my bike to the office.", zh: "夏天我骑自行车去办公室。" },
      { en: "In winter I take the bus because it is cold.", zh: "冬天我坐公交车，因为天冷。" },
      { en: "At the weekend I often stay at home with my family.", zh: "周末我常常和家人待在家里。" },
    ],
    qs: [
      { q: "Where is the writer's house?", opts: ["On Green Street", "In the north of China", "Behind a bank"], ans: 0,
        why: "第2句：My house is on Green Street（街道用 on）。银行是工作的地方，不是住的地方。" },
      { q: "When does the writer finish work?", opts: ["At nine in the morning", "At five in the afternoon", "On Monday"], ans: 1,
        why: "第4句：start work at nine... and finish at five in the afternoon。" },
      { q: "How does the writer go to work in winter?", opts: ["By bike", "By bus", "On foot"], ans: 1,
        why: "第7句：In winter I take the bus。骑车是夏天（in summer）。" },
    ],
  },

  /* --------------------- 第9章 情态动词 can / must ---------------------- */
  9: {
    level: 1, words: 78,
    title: "How to Learn English（怎么学英语）",
    tip: "注意三个容易混的：must（必须）、needn't（不必）、must not（绝对不能）。它们后面都跟动词原形。",
    sents: [
      { en: "If you want to pass the exam, you must work hard every day.", zh: "如果你想通过考试，你必须每天用功。" },
      { en: "You cannot learn English in one night.", zh: "你不可能一晚上就学会英语。" },
      { en: "You must read something in English every morning.", zh: "你必须每天早上读点英语。" },
      { en: "You can start with easy stories.", zh: "你可以从简单的故事开始。" },
      { en: "You must also remember new words, but you needn't remember all of them.", zh: "你也必须记新单词，但你不必把它们全都记住。" },
      { en: "If you can use a word, you know it well.", zh: "如果你能用一个词，你就真的掌握它了。" },
      { en: "You must not be afraid of mistakes.", zh: "你绝不能害怕犯错。" },
      { en: "Everyone makes mistakes.", zh: "每个人都会犯错。" },
      { en: "If you keep going, you can do better than you think.", zh: "如果你坚持下去，你能做得比你以为的更好。" },
    ],
    qs: [
      { q: "What must you do every morning?", opts: ["Read something in English", "Write a long letter", "Sleep more"], ans: 0,
        why: "第3句：You must read something in English every morning。" },
      { q: "Must you remember all the new words?", opts: ["Yes, you must", "No, you needn't", "You must not remember any"], ans: 1,
        why: "第5句：but you needn't remember all of them。needn't = 不必（不是“不准”）。" },
      { q: "What must you NOT do?", opts: ["Be afraid of mistakes", "Read easy stories", "Work hard"], ans: 0,
        why: "第7句：You must not be afraid of mistakes。must not = 绝对不能。" },
    ],
  },

  /* ---------------- 第10章 将来时 will / be going to ------------------- */
  10: {
    level: 1, words: 77,
    title: "Moving to a New City（搬到新城市）",
    tip: "两种将来：be going to（已经计划好的）和 will（预测/临时决定）。看看作者哪些事是“计划好的”。",
    sents: [
      { en: "Next month I am going to move to a new city.", zh: "下个月我要搬到一个新城市。" },
      { en: "I will start a new job there.", zh: "我将在那里开始一份新工作。" },
      { en: "My company is going to open an office in Hangzhou.", zh: "我们公司打算在杭州开一间办公室。" },
      { en: "I will work there for two years.", zh: "我将在那里工作两年。" },
      { en: "I am a little worried.", zh: "我有点担心。" },
      { en: "I will not know anyone at first.", zh: "一开始我谁也不认识。" },
      { en: "But my friend says I will make new friends soon.", zh: "但我朋友说我很快就会交到新朋友。" },
      { en: "I am going to rent a small flat near the office.", zh: "我打算在办公室附近租一间小公寓。" },
      { en: "I think life there will be busy but interesting.", zh: "我觉得那里的生活会很忙，但很有意思。" },
    ],
    qs: [
      { q: "Where is the writer going to move?", opts: ["To Hangzhou", "To Beijing", "To a small village"], ans: 0,
        why: "第3句：My company is going to open an office in Hangzhou，作者要去那里工作。" },
      { q: "How long will the writer work there?", opts: ["Two months", "Two years", "Two weeks"], ans: 1,
        why: "第4句：I will work there for two years。" },
      { q: "Why is the writer worried?", opts: ["Because the new job is too hard", "Because the writer will not know anyone at first", "Because the flat is too small"], ans: 1,
        why: "第5、6句连起来：I am a little worried. I will not know anyone at first。" },
    ],
  },

  /* ================== L2 第11-20章 ≈150 词：开始有从句和时态混用 ================== */

  /* -------------------- 第11章 祈使句 & 频率副词 --------------------- */
  11: {
    level: 2, words: 143,
    title: "Rules for a New Worker（给新同事的几条规矩）",
    tip: "祈使句＝动词开头直接下命令（Always come... / Do not eat...）。再找出所有频率副词：always / never / usually / often / sometimes——注意它们放在哪个位置。",
    sents: [
      { en: "Welcome to our office.", zh: "欢迎来到我们办公室。" },
      { en: "Here are a few simple rules.", zh: "这里有几条简单的规矩。" },
      { en: "Always come to work on time.", zh: "上班永远要准时。" },
      { en: "Never leave your computer open when you go out.", zh: "出去的时候，绝不要让电脑开着。" },
      { en: "Please keep your desk clean, and do not eat lunch at your desk.", zh: "请保持桌面整洁，也不要在桌上吃午饭。" },
      { en: "We usually have a short meeting at nine every Monday.", zh: "我们通常在每周一九点开个短会。" },
      { en: "Try to be there five minutes early.", zh: "尽量提前五分钟到。" },
      { en: "If you have a question, ask your team leader first.", zh: "如果你有问题，先问你的组长。" },
      { en: "Do not be shy.", zh: "别不好意思。" },
      { en: "He is often busy in the afternoon, so it is better to ask him in the morning.", zh: "他下午经常很忙，所以最好上午去问他。" },
      { en: "Remember to write down what you learn.", zh: "记得把学到的东西写下来。" },
      { en: "You will sometimes make mistakes, and that is fine.", zh: "你有时会犯错，这没关系。" },
      { en: "Just do not make the same mistake twice.", zh: "只是别在同一个地方错两次。" },
      { en: "Turn off the lights before you leave, and never forget to lock the door.", zh: "走之前关灯，并且千万别忘了锁门。" },
      { en: "Finally, always be kind to the people around you.", zh: "最后，永远对身边的人友善。" },
      { en: "A good team is more important than a clever worker.", zh: "一个好团队比一个聪明的员工更重要。" },
    ],
    qs: [
      { q: "What should you do before you leave the office?", opts: ["Turn off the lights and lock the door", "Clean the whole office", "Call your team leader"], ans: 0,
        why: "倒数第3句：Turn off the lights before you leave, and never forget to lock the door。" },
      { q: "When is it better to ask the team leader questions?", opts: ["In the morning", "In the afternoon", "At the Monday meeting"], ans: 0,
        why: "第10句：He is often busy in the afternoon, so it is better to ask him in the morning。" },
      { q: "What does the writer think is more important?", opts: ["A clever worker", "A good team", "A clean desk"], ans: 1,
        why: "最后一句：A good team is more important than a clever worker。" },
    ],
  },

  /* ----------------- 第12章 疑问词 & 反意疑问句 ------------------ */
  12: {
    level: 2, words: 124,
    title: "A Reporter Came to Our Factory（记者来我们厂）",
    tip: "前半段把疑问词一网打尽：Who / What / Where / Why / How much / How many / Which / When。后半段注意两个反意疑问句：前肯后否、前否后肯。",
    sents: [
      { en: "My friend Anna is a reporter.", zh: "我朋友安娜是记者。" },
      { en: "Last week she came to our factory.", zh: "上周她来了我们厂。" },
      { en: "She asked us many questions.", zh: "她问了我们很多问题。" },
      { en: "Who works the longest hours here?", zh: "这里谁工作时间最长？" },
      { en: "What time do you start in the morning?", zh: "你们早上几点开工？" },
      { en: "Where do you have lunch?", zh: "你们在哪里吃午饭？" },
      { en: "Why do you like this job?", zh: "你们为什么喜欢这份工作？" },
      { en: "How much do you earn in a month?", zh: "你们一个月挣多少钱？" },
      { en: "How many people work on your line?", zh: "你们这条线上有多少人？" },
      { en: "Which part of the work is the hardest?", zh: "工作中哪一部分最难？" },
      { en: "When will the new building open?", zh: "新楼什么时候开放？" },
      { en: "We answered her one by one.", zh: "我们一个一个回答了她。" },
      { en: "Then she said with a smile: You are all very busy, aren't you?", zh: "然后她笑着说：你们都很忙，是不是？" },
      { en: "Yes, we are, but we are used to it.", zh: "是的，我们很忙，但已经习惯了。" },
      { en: "Before she left, she asked one more question: You don't want to change your job, do you?", zh: "临走前她又问了一个问题：你们不想换工作，对吧？" },
      { en: "Nobody said yes, and that surprised her.", zh: "没人说想换，这让她很意外。" },
    ],
    qs: [
      { q: "What is Anna's job?", opts: ["A worker", "A reporter", "A teacher"], ans: 1,
        why: "第1句：My friend Anna is a reporter。" },
      { q: "What was the last question Anna asked?", opts: ["How much they earn", "When the new building will open", "Whether they want to change their job"], ans: 2,
        why: "倒数第2句：You don't want to change your job, do you? 这是她临走前问的最后一个问题。" },
      { q: "Why was Anna surprised?", opts: ["Because nobody wanted to change their job", "Because the factory was very big", "Because nobody answered her"], ans: 0,
        why: "最后一句：Nobody said yes, and that surprised her。" },
    ],
  },

  /* --------------------- 第13章 比较级 & 最高级 ---------------------- */
  13: {
    level: 2, words: 140,
    title: "My Two Brothers（我的两个兄弟）",
    tip: "把所有比较级（-er / more...）和最高级（-est / the most...）圈出来。注意 less / the happiest / not as easy as 这几个变形。",
    sents: [
      { en: "I have two brothers.", zh: "我有两个兄弟。" },
      { en: "My older brother, Wang Gang, is twenty-eight.", zh: "我哥哥王刚二十八岁。" },
      { en: "My younger brother, Wang Tao, is only nineteen.", zh: "我弟弟王涛只有十九岁。" },
      { en: "Gang is taller than Tao, but Tao is stronger.", zh: "王刚比王涛高，但王涛更壮。" },
      { en: "Gang works in a bank.", zh: "王刚在银行工作。" },
      { en: "His job is easier than mine, but he says it is more boring.", zh: "他的工作比我的轻松，但他说更无聊。" },
      { en: "Tao is a driver.", zh: "王涛是司机。" },
      { en: "He earns less money than Gang, but he is the happiest person in our family.", zh: "他挣得比王刚少，但他是我们家最快乐的人。" },
      { en: "He always says that money is not the most important thing in life.", zh: "他总说钱不是人生中最重要的东西。" },
      { en: "My mother thinks Tao works the hardest of us three.", zh: "我妈妈觉得我们三个里王涛最辛苦。" },
      { en: "My father says Gang is the cleverest.", zh: "我爸爸说王刚最聪明。" },
      { en: "I am the oldest, so I have to be the most careful with money.", zh: "我最大，所以我得在花钱上最小心。" },
      { en: "Our house is not big, and life is not as easy as before.", zh: "我们家房子不大，日子也不像从前那么轻松。" },
      { en: "But we are closer than many families I know.", zh: "但我们比我认识的很多家庭都更亲近。" },
      { en: "The best thing in my life is my family.", zh: "我这辈子最好的东西就是我的家人。" },
    ],
    qs: [
      { q: "Who is the strongest of the two brothers?", opts: ["Wang Gang", "Wang Tao", "They are the same"], ans: 1,
        why: "第4句：Gang is taller than Tao, but Tao is stronger。高的是刚，壮的是涛。" },
      { q: "What does Wang Tao think about money?", opts: ["It is the most important thing", "It is not the most important thing", "He never talks about it"], ans: 1,
        why: "第9句：money is not the most important thing in life。" },
      { q: "Who does the mother think works the hardest?", opts: ["Wang Gang", "Wang Tao", "The writer"], ans: 1,
        why: "第10句：My mother thinks Tao works the hardest of us three。注意“最聪明”才是爸爸说的王刚。" },
    ],
  },

  /* ------------------------ 第14章 现在完成时 ------------------------ */
  14: {
    level: 2, words: 131,
    title: "Ten Years in This City（在这座城市的十年）",
    tip: "全文是 have/has + done。特别注意四个搭档：for / since（多久）、already / yet（已经/还没）、never / ever（从未/曾经）、just（刚刚）。",
    sents: [
      { en: "I have lived in this city for ten years.", zh: "我在这座城市住了十年。" },
      { en: "I have never thought about leaving.", zh: "我从没想过离开。" },
      { en: "I came here in 2016, and I have worked in the same company since then.", zh: "我 2016 年来的，从那时起就一直在同一家公司工作。" },
      { en: "A lot of things have changed.", zh: "很多事情都变了。" },
      { en: "The old market near my flat has gone.", zh: "我公寓附近的老市场没有了。" },
      { en: "A new subway line has opened.", zh: "一条新地铁线开通了。" },
      { en: "I have made many friends here.", zh: "我在这里交了很多朋友。" },
      { en: "Some of them have already moved to other cities, but we have kept in touch.", zh: "其中一些人已经搬去了别的城市，但我们一直有联系。" },
      { en: "My English has improved a lot in the last two years.", zh: "我的英语在过去两年里进步了很多。" },
      { en: "I have finished three courses, and I have just started a new one.", zh: "我上完了三门课，刚刚又开始了一门新的。" },
      { en: "I have not passed the exam yet.", zh: "我还没通过考试。" },
      { en: "But I have already learned much more than before.", zh: "但我已经比以前学到多得多了。" },
      { en: "Have you ever tried to learn something new after thirty?", zh: "你有没有在三十岁以后试着学一样新东西？" },
      { en: "It is not easy, but I have never regretted it.", zh: "这不容易，但我从未后悔过。" },
    ],
    qs: [
      { q: "How long has the writer lived in this city?", opts: ["Two years", "Ten years", "Three years"], ans: 1,
        why: "第1句：I have lived in this city for ten years。“两年”是英语进步的时间，“三”是课程数。" },
      { q: "Has the writer passed the exam?", opts: ["Yes, already", "Not yet", "The text does not say"], ans: 1,
        why: "第11句：I have not passed the exam yet。yet 用在否定句＝“还没”。" },
      { q: "What has happened to the old market?", opts: ["It has become bigger", "It has gone", "It has moved to the subway"], ans: 1,
        why: "第5句：The old market near my flat has gone。" },
    ],
  },

  /* ------------- 第15章 过去进行 / 过去完成 / used to -------------- */
  15: {
    level: 2, words: 134,
    title: "A Call from an Old Classmate（老同学的一个电话）",
    tip: "三种过去挤在一篇里：was doing（那时正在做）、had done（比过去更早）、used to（过去常常，现在不了）。读的时候排一下时间先后。",
    sents: [
      { en: "Last Friday evening I was cooking dinner when the phone rang.", zh: "上周五晚上我正在做饭，这时电话响了。" },
      { en: "It was my old classmate, Liu Fang.", zh: "是我的老同学刘芳。" },
      { en: "We had not spoken for five years.", zh: "我们已经五年没说过话了。" },
      { en: "She said she had moved back to our hometown in March.", zh: "她说她三月就搬回我们老家了。" },
      { en: "While we were talking, I remembered the days when we were at school.", zh: "我们聊着聊着，我想起了上学的日子。" },
      { en: "We used to walk home together every afternoon.", zh: "我们过去每天下午一起走路回家。" },
      { en: "We used to buy ice cream at the shop near the school gate.", zh: "我们以前常在校门口那家店买冰淇淋。" },
      { en: "She used to be very shy, but now she sounds confident.", zh: "她以前很害羞，但现在听起来很自信。" },
      { en: "She told me that she had opened a small shop of her own.", zh: "她告诉我她已经开了一家自己的小店。" },
      { en: "Before she called, I had been feeling tired and low.", zh: "在她打来之前，我一直觉得又累又低落。" },
      { en: "After we finished talking, I felt much better.", zh: "聊完之后，我感觉好多了。" },
      { en: "I was still smiling when my husband came home.", zh: "我丈夫回家的时候，我还在笑。" },
      { en: "He asked me what had happened, and I told him the whole story.", zh: "他问我发生了什么，我把整件事讲给他听。" },
    ],
    qs: [
      { q: "What was the writer doing when the phone rang?", opts: ["Cooking dinner", "Walking home", "Talking to her husband"], ans: 0,
        why: "第1句：I was cooking dinner when the phone rang。was doing＝电话响的那一刻正在做的事。" },
      { q: "What did the two friends use to do after school?", opts: ["Open a shop", "Walk home together", "Cook dinner together"], ans: 1,
        why: "第6句：We used to walk home together every afternoon。used to＝过去常常。" },
      { q: "How did the writer feel before the call?", opts: ["Tired and low", "Happy and confident", "Angry"], ans: 0,
        why: "第10句：Before she called, I had been feeling tired and low。打完电话后才 felt much better。" },
    ],
  },

  /* ------------------------ 第16章 被动语态 ------------------------- */
  16: {
    level: 2, words: 132,
    title: "How Our Town Has Changed（我们镇的变化）",
    tip: "整篇几乎都是「被动」：be + done（事情被人做了，但不说是谁做的）。注意各种时态的被动：was built / is used / have been planted / will be started / is being changed。",
    sents: [
      { en: "Our town has changed a lot in the last few years.", zh: "我们镇在过去几年里变化很大。" },
      { en: "A new hospital was built near the river in 2023.", zh: "2023 年在河边建了一家新医院。" },
      { en: "The old bridge was repaired last summer.", zh: "那座老桥去年夏天修好了。" },
      { en: "Now it is used by thousands of people every day.", zh: "现在每天有成千上万人从桥上通过。" },
      { en: "Many trees have been planted along the main road.", zh: "主干道两旁种了很多树。" },
      { en: "The streets are cleaned every morning before six.", zh: "街道每天早上六点前都会被打扫。" },
      { en: "Last year a big library was opened next to the school.", zh: "去年学校旁边开了一座大图书馆。" },
      { en: "Books can be borrowed for free.", zh: "书可以免费借。" },
      { en: "Children are welcomed there at the weekend.", zh: "周末那里也欢迎孩子们去。" },
      { en: "A new bus line will be started next month.", zh: "下个月将开通一条新公交线。" },
      { en: "Some old houses were pulled down, and the people who lived there were given new flats.", zh: "一些老房子被拆了，住在那儿的人分到了新公寓。" },
      { en: "Not everyone is happy about these changes.", zh: "并不是每个人都对这些变化满意。" },
      { en: "Some say the town is being changed too quickly.", zh: "有人说这个镇变得太快了。" },
      { en: "But most people agree that life here has been made much easier.", zh: "但大多数人都同意，这里的生活被变得方便多了。" },
    ],
    qs: [
      { q: "When was the new hospital built?", opts: ["In 2023", "Last summer", "Last year"], ans: 0,
        why: "第2句：A new hospital was built near the river in 2023。last summer 是修桥，last year 是开图书馆——三个时间别混。" },
      { q: "How often are the streets cleaned?", opts: ["Every weekend", "Every morning before six", "Once a month"], ans: 1,
        why: "第6句：The streets are cleaned every morning before six。" },
      { q: "What do some people complain about?", opts: ["The town is being changed too quickly", "The books are too expensive", "There is no new bus line"], ans: 0,
        why: "倒数第2句：Some say the town is being changed too quickly。书是免费借的，公交线下个月就开。" },
    ],
  },

  /* --------------- 第17章 非谓语（-ing / -ed / to do） --------------- */
  17: {
    level: 2, words: 138,
    title: "Half an Hour a Day（每天半小时）",
    tip: "找三种非谓语：动名词（Learning / Reading 当主语）、不定式（To pass / to use 表目的）、过去分词（Asked / filled 表被动）。它们都不是句子的真正谓语。",
    sents: [
      { en: "Learning a language takes time.", zh: "学一门语言需要时间。" },
      { en: "Many people give up after trying for a few weeks.", zh: "很多人试了几周就放弃了。" },
      { en: "To pass an exam, you need a plan.", zh: "要想通过考试，你需要一个计划。" },
      { en: "Reading English every day is the best way to build your feeling for the language.", zh: "每天读英语是培养语感最好的办法。" },
      { en: "Do not spend all your time doing grammar exercises.", zh: "别把所有时间都花在做语法题上。" },
      { en: "Try to use what you have learned.", zh: "试着去用你学过的东西。" },
      { en: "Speaking to a friend, writing a short diary, listening to simple songs — all these help.", zh: "和朋友说话、写短日记、听简单的歌——这些都有用。" },
      { en: "I know a woman called Zhang Min.", zh: "我认识一位叫张敏的女士。" },
      { en: "Working full time and looking after two children, she still found half an hour a day to study.", zh: "她全职工作还要带两个孩子，仍然每天挤出半小时学习。" },
      { en: "She kept a notebook filled with new words.", zh: "她有一个记满生词的本子。" },
      { en: "Asked how she did it, she just smiled and said it was a habit.", zh: "被问到她是怎么做到的，她只是笑笑说，这是个习惯。" },
      { en: "Last June she passed the exam.", zh: "去年六月她通过了考试。" },
      { en: "To do something well, you do not need much time.", zh: "要把一件事做好，你不需要很多时间。" },
      { en: "You need to keep going.", zh: "你需要的是坚持下去。" },
    ],
    qs: [
      { q: "What is the best way to build a feeling for the language?", opts: ["Doing grammar exercises", "Reading English every day", "Listening to songs only"], ans: 1,
        why: "第4句：Reading English every day is the best way...。第5句还专门说别把时间都花在语法题上。" },
      { q: "How much time did Zhang Min find each day?", opts: ["Two hours", "Half an hour", "Ten minutes"], ans: 1,
        why: "第9句：she still found half an hour a day to study。" },
      { q: "What does the writer say you really need?", opts: ["Much time", "A good teacher", "To keep going"], ans: 2,
        why: "最后两句：you do not need much time. You need to keep going。" },
    ],
  },

  /* ------------ 第18章 too...to / so...that / enough ------------- */
  18: {
    level: 2, words: 138,
    title: "Too Shy to Speak（害羞得说不出话）",
    tip: "三个句型对照着看：too...to（太…以至于不能）、so...that（如此…以至于）、enough（足够，放在形容词后面）。注意 enough 的位置：brave enough，不是 enough brave。",
    sents: [
      { en: "When I was young, I was too shy to speak in front of people.", zh: "我小时候太害羞了，没法在人前讲话。" },
      { en: "In middle school my teacher asked me to read a poem to the class.", zh: "上中学时，老师让我给全班读一首诗。" },
      { en: "I was so nervous that my hands shook.", zh: "我紧张得手都在抖。" },
      { en: "I was not brave enough to look at anyone.", zh: "我没有勇气看任何人。" },
      { en: "After twenty seconds I stopped.", zh: "二十秒后我停住了。" },
      { en: "The room was so quiet that I could hear my own heart.", zh: "教室里安静得我能听见自己的心跳。" },
      { en: "My teacher did not laugh.", zh: "我的老师没有笑。" },
      { en: "She said I was good enough to try again next week.", zh: "她说我够好了，下周可以再试一次。" },
      { en: "That week I read the poem so many times that I knew every word by heart.", zh: "那一周我把那首诗读了太多遍，每个词都背下来了。" },
      { en: "The second time, I was still nervous, but I was calm enough to finish.", zh: "第二次，我还是紧张，但已经足够冷静把它读完。" },
      { en: "Now I am old enough to understand what she did for me.", zh: "现在我长大了，足以明白她为我做了什么。" },
      { en: "She knew I was not too shy to succeed.", zh: "她知道我并不是害羞到不可能成功。" },
      { en: "I was just too young to believe in myself.", zh: "我只是太小了，还不懂得相信自己。" },
    ],
    qs: [
      { q: "Why did the writer stop after twenty seconds?", opts: ["The teacher laughed", "He/She was too nervous and not brave enough", "The poem was too long"], ans: 1,
        why: "第3、4句：I was so nervous that my hands shook. I was not brave enough to look at anyone。老师明确没有笑。" },
      { q: "What did the teacher say?", opts: ["He/She was good enough to try again", "He/She should never read again", "The poem was too hard"], ans: 0,
        why: "第8句：She said I was good enough to try again next week。" },
      { q: "Why did the writer know every word of the poem?", opts: ["The teacher taught it word by word", "He/She read it so many times", "It was a very short poem"], ans: 1,
        why: "第9句：I read the poem so many times that I knew every word by heart。so...that 表结果。" },
    ],
  },

  /* --------------- 第19章 连词 & 条件句（if） ----------------- */
  19: {
    level: 2, words: 138,
    title: "If You Want to Change Your Life（如果你想改变生活）",
    tip: "重点看 if 句：主句用将来时（will），if 从句用现在时——「主将从现」。再找 because / so that / unless / either...or / when 这些连词。",
    sents: [
      { en: "If you want to change your life, you have to start today.", zh: "如果你想改变生活，就得从今天开始。" },
      { en: "Many people say that they will study when they have time.", zh: "很多人说等有时间了就去学习。" },
      { en: "But time never comes by itself.", zh: "但时间从来不会自己出现。" },
      { en: "If you wait until everything is ready, you will wait forever.", zh: "如果你等到万事俱备，你会等一辈子。" },
      { en: "I have a friend who works in a factory.", zh: "我有个在工厂上班的朋友。" },
      { en: "He gets up at five so that he can read for an hour before work.", zh: "他五点起床，为的是能在上班前读一小时书。" },
      { en: "He is tired, but he keeps going because he knows why he is doing it.", zh: "他很累，但他坚持着，因为他知道自己为什么这么做。" },
      { en: "If he passes the exam next year, he will apply for a better job.", zh: "如果明年他通过考试，他就去申请一份更好的工作。" },
      { en: "If he does not pass, he will try again.", zh: "如果没通过，他就再考一次。" },
      { en: "Either he wins or he learns.", zh: "他要么赢，要么学到东西。" },
      { en: "When I asked him if it was hard, he said it was hard.", zh: "我问他难不难，他说难。" },
      { en: "But it was not as hard as staying where he was.", zh: "但没有待在原地那么难受。" },
      { en: "Unless you start, nothing will change.", zh: "除非你开始，否则什么都不会变。" },
    ],
    qs: [
      { q: "When does the friend read?", opts: ["Before work, after getting up at five", "At the factory during lunch", "Late at night"], ans: 0,
        why: "第6句：He gets up at five so that he can read for an hour before work。" },
      { q: "What will he do if he does not pass the exam?", opts: ["Give up", "Try again", "Change his job at once"], ans: 1,
        why: "第9句：If he does not pass, he will try again。" },
      { q: "What does the friend think is hardest?", opts: ["Getting up at five", "The exam", "Staying where he was"], ans: 2,
        why: "第11、12句：考试难，但 not as hard as staying where he was——待在原地更难受。" },
    ],
  },

  /* ------------------- 第20章 定语从句 -------------------- */
  20: {
    level: 2, words: 138,
    title: "The Teacher Who Changed My Life（改变我一生的老师）",
    tip: "每个 who / which / that / where / whose 前面都有一个「被修饰的名词」。读到关系词就往前找：它到底在说哪个词？人用 who/that，物用 which/that，地点用 where，“谁的”用 whose。",
    sents: [
      { en: "I want to tell you about a teacher who changed my life.", zh: "我想跟你讲一位改变了我一生的老师。" },
      { en: "Her name is Mrs. Chen, and she is the person that I respect most.", zh: "她叫陈老师，是我最敬重的人。" },
      { en: "She taught at a small school which stands at the foot of a hill.", zh: "她在一所坐落在山脚下的小学校教书。" },
      { en: "The classroom where we studied had no heating.", zh: "我们上课的那间教室没有暖气。" },
      { en: "In winter the children whose homes were far away often came late.", zh: "冬天里，家住得远的孩子常常迟到。" },
      { en: "Mrs. Chen never got angry with them.", zh: "陈老师从不因此生气。" },
      { en: "She always kept a pot of hot water which she shared with us.", zh: "她总备着一壶热水，分给我们喝。" },
      { en: "The books that she lent me were the first English books I ever read.", zh: "她借给我的书，是我读过的第一批英文书。" },
      { en: "There was one book whose cover was almost gone, but I read it three times.", zh: "有一本书封面都快掉光了，我却读了三遍。" },
      { en: "She is now seventy years old.", zh: "她现在七十岁了。" },
      { en: "The letters that she writes to me still arrive every spring.", zh: "她写给我的信，每年春天都还会寄到。" },
      { en: "That is the kind of teacher I hope to become one day.", zh: "那就是我希望有一天成为的那种老师。" },
    ],
    qs: [
      { q: "Where was the small school?", opts: ["At the foot of a hill", "Next to a river", "In a big city"], ans: 0,
        why: "第3句：a small school which stands at the foot of a hill。which 修饰前面的 school。" },
      { q: "What did Mrs. Chen share with the children?", opts: ["Her lunch", "A pot of hot water", "Her coat"], ans: 1,
        why: "第7句：a pot of hot water which she shared with us。" },
      { q: "What still arrives every spring?", opts: ["New books", "The letters she writes", "Her students"], ans: 1,
        why: "第11句：The letters that she writes to me still arrive every spring。" },
    ],
  },

  /* ============ L3 第21-28章 ≈200-250 词：已是成考真题长度，按考试节奏读 ============ */

  /* ---------------- 第21章 固定搭配 & 词义辨析 ----------------- */
  21: {
    level: 3, words: 222,
    title: "The Day I Stopped Waiting（我不再等待的那天）",
    tip: "这篇塞满了成考爱考的动词短语：make up one's mind / be used to / take part in / look for / look after / look forward to / pay attention to / instead of / as soon as / on time。边读边把它们圈出来，作文里能直接用。",
    sents: [
      { en: "Three years ago I made up my mind to change my life.", zh: "三年前我下定决心改变自己的生活。" },
      { en: "I was working in a small shop and I was used to an easy life.", zh: "我在一家小店上班，已经习惯了轻松的日子。" },
      { en: "But I was not happy.", zh: "但我并不快乐。" },
      { en: "One evening my cousin called and asked me to take part in a training course in the city.", zh: "一天晚上，我表哥打来电话，让我去城里参加一个培训班。" },
      { en: "At first I looked for every reason to say no.", zh: "起初我找遍了各种理由想拒绝。" },
      { en: "It was far away. It cost money. I was too old.", zh: "路太远。要花钱。我年纪太大。" },
      { en: "My cousin listened and then said only one thing: you will never know unless you try.", zh: "表哥听完只说了一句：不试你永远不会知道。" },
      { en: "The next Monday I got on the early bus.", zh: "第二个周一，我坐上了早班车。" },
      { en: "I arrived on time, but I was still afraid.", zh: "我准时到了，但心里还是发怵。" },
      { en: "The teacher asked us to pay attention to small things.", zh: "老师让我们注意那些小事。" },
      { en: "She meant how we spoke, how we listened, and how we dealt with people who were angry.", zh: "她指的是我们怎么说话、怎么倾听、怎么应对生气的人。" },
      { en: "Instead of writing everything down, she made us practise again and again.", zh: "她没让我们把一切都记下来，而是让我们一遍遍练。" },
      { en: "The course lasted two months.", zh: "培训持续了两个月。" },
      { en: "As soon as it ended, I looked for a new job.", zh: "一结束，我就去找新工作。" },
      { en: "It took me six weeks to find one.", zh: "我花了六周才找到。" },
      { en: "Now I look after a team of eight people in a hotel.", zh: "现在我在一家酒店带着八个人的团队。" },
      { en: "The work is much harder than before, and I often get home late.", zh: "工作比以前累多了，我也常常很晚回家。" },
      { en: "But I am looking forward to next year, when I will take another course.", zh: "但我很期待明年，那时我会再去上一个班。" },
      { en: "My cousin was right.", zh: "我表哥说得对。" },
      { en: "I did not become a different person. I just stopped waiting.", zh: "我并没有变成另一个人，我只是不再等待了。" },
    ],
    qs: [
      { q: "Why did the writer refuse at first?", opts: ["The course was far away, cost money, and he/she felt too old", "The cousin was not friendly", "The shop would not allow it"], ans: 0,
        why: "第5、6句给了三个理由：It was far away. It cost money. I was too old。" },
      { q: "What did the teacher make them do?", opts: ["Write everything down", "Practise again and again", "Read a long book"], ans: 1,
        why: "第12句：Instead of writing everything down, she made us practise again and again。instead of＝而不是。" },
      { q: "How long did it take to find a new job?", opts: ["Two months", "Six weeks", "Three years"], ans: 1,
        why: "第15句：It took me six weeks to find one。两个月是培训时长，三年是故事起点。" },
      { q: "What is the writer looking forward to?", opts: ["Going back to the small shop", "Taking another course next year", "Working fewer hours"], ans: 1,
        why: "第18句：I am looking forward to next year, when I will take another course。" },
    ],
  },

  /* ----------------------- 第22章 虚拟语气 ------------------------ */
  22: {
    level: 3, words: 220,
    title: "Old Wang and the Computer Course（老王和电脑课）",
    tip: "成考最爱考的虚拟语气几乎全在这篇：If I were / if he had studied, would have had / wishes he had learned / If only I had started / suggested that he take / It is important that he learn / would rather you did not。读的时候问自己：这句在说“真的”还是“不是真的”？",
    sents: [
      { en: "My neighbour Old Wang is sixty-two.", zh: "我邻居老王六十二岁。" },
      { en: "Last week he said something that I have thought about ever since.", zh: "上周他说了一句话，我一直想到现在。" },
      { en: "If I were young again, he said, I would learn a skill instead of waiting for luck.", zh: "他说：如果我能再年轻一次，我会去学门手艺，而不是等运气。" },
      { en: "Old Wang left school at fifteen.", zh: "老王十五岁就离开了学校。" },
      { en: "He often says that if he had studied harder, he would have had an easier life.", zh: "他常说，当初要是更用功，日子会好过些。" },
      { en: "For thirty years he worked on building sites.", zh: "他在工地上干了三十年。" },
      { en: "He wishes he had learned to use a computer when he was forty.", zh: "他希望自己四十岁时就学会用电脑。" },
      { en: "If only I had started then, he said, I would not be afraid of these machines now.", zh: "他说：那时候要是开始了，现在就不会怕这些机器了。" },
      { en: "Last month his daughter suggested that he take a short computer course at the community centre.", zh: "上个月他女儿建议他去社区中心上个短期电脑班。" },
      { en: "It is important that he learn something new, she told me.", zh: "她跟我说：让他学点新东西很重要。" },
      { en: "At first he refused.", zh: "起初他拒绝了。" },
      { en: "He said he was too old and that people would laugh at him.", zh: "他说自己太老了，别人会笑话他。" },
      { en: "But last Friday he went.", zh: "但上周五他还是去了。" },
      { en: "He came back with a notebook and a very serious face.", zh: "他回来时拿着一个本子，一脸严肃。" },
      { en: "If you had seen him, you would have laughed.", zh: "你要是看见他，肯定会笑。" },
      { en: "He wrote down every single word the teacher said.", zh: "老师说的每一个字他都记了下来。" },
      { en: "Yesterday he sent me a message on his phone. It was his first one.", zh: "昨天他用手机给我发了条消息，那是他人生第一条。" },
      { en: "He wrote: I would rather you did not tell anyone, but I am quite proud of myself.", zh: "他写道：我宁愿你别告诉别人，不过我还挺为自己骄傲的。" },
      { en: "I think if more people were like Old Wang, the world would be a kinder place.", zh: "我想，如果多一些老王这样的人，这世界会更温柔一点。" },
    ],
    qs: [
      { q: "What does Old Wang regret most?", opts: ["Not learning to use a computer at forty", "Leaving his job on building sites", "Moving to this neighbourhood"], ans: 0,
        why: "第7、8句：He wishes he had learned to use a computer when he was forty / If only I had started then。wish 和 if only 都表示“后悔没做”。" },
      { q: "Who suggested the computer course?", opts: ["The writer", "His daughter", "The teacher"], ans: 1,
        why: "第9句：his daughter suggested that he take a short computer course。注意 suggest 后面用 (should) take 原形。" },
      { q: "Why did Old Wang refuse at first?", opts: ["The course was too expensive", "He thought he was too old and people would laugh", "The centre was too far"], ans: 1,
        why: "第12句：He said he was too old and that people would laugh at him。" },
      { q: "What was special about the message he sent?", opts: ["It was very long", "It was his first one", "His daughter wrote it for him"], ans: 1,
        why: "第17句：It was his first one。" },
    ],
  },

  /* -------------------- 第23章 倒装 & 强调句 --------------------- */
  23: {
    level: 3, words: 203,
    title: "Four Eggs（四个鸡蛋）",
    tip: "开头就是倒装：Never have I forgotten...。找出所有把助动词提到主语前面的句子（Never / Only / Not until / Seldom / Little 开头），再找 It is/was ... that ... 强调句。",
    sents: [
      { en: "Never have I forgotten the day I first stood in front of a class.", zh: "我永远忘不了第一次站上讲台的那天。" },
      { en: "It was in 2019 that I became a teacher in a small village school.", zh: "正是在 2019 年，我成了一所乡村小学的老师。" },
      { en: "Only twenty children were there, and so poor was the school that we had no proper blackboard.", zh: "那里只有二十个孩子，学校穷得连块像样的黑板都没有。" },
      { en: "Not until I met those children did I understand what teaching means.", zh: "直到遇见那些孩子，我才明白教书意味着什么。" },
      { en: "Little did I know that they would teach me more than I taught them.", zh: "我当时根本没想到，他们教给我的比我教给他们的还多。" },
      { en: "There was one boy called Xiao Yu.", zh: "有个男孩叫小宇。" },
      { en: "Seldom did he speak.", zh: "他很少说话。" },
      { en: "It was his eyes that told you when he understood something.", zh: "是他的眼睛在告诉你，他什么时候听懂了。" },
      { en: "One morning he came early.", zh: "一天早上他来得很早。" },
      { en: "In came a thin boy with a paper bag in his hands.", zh: "一个瘦瘦的男孩捧着一个纸袋走了进来。" },
      { en: "Inside were four eggs from his family.", zh: "袋子里是他家的四个鸡蛋。" },
      { en: "Never before had anyone given me such a gift.", zh: "从来没有人送过我这样的礼物。" },
      { en: "Only after I left the village did I realise how much those two years had changed me.", zh: "直到离开那个村子，我才意识到那两年把我改变了多少。" },
      { en: "It is not the money that keeps a teacher going.", zh: "让一个老师坚持下去的，并不是钱。" },
      { en: "It is the moment when a quiet child finally puts up his hand.", zh: "而是一个安静的孩子终于举起手的那一刻。" },
      { en: "Now I work in a city school.", zh: "现在我在城里的学校教书。" },
      { en: "Here come the same problems: too many students, too little time.", zh: "同样的问题又来了：学生太多，时间太少。" },
      { en: "But whenever I feel tired, I think of Xiao Yu and those four eggs, and back comes my strength.", zh: "但每当我觉得累，我就想起小宇和那四个鸡蛋，力气就又回来了。" },
    ],
    qs: [
      { q: "When did the writer become a teacher?", opts: ["In 2019", "Two years ago", "After moving to the city"], ans: 0,
        why: "第2句强调句：It was in 2019 that I became a teacher。去掉 It was...that 就是 I became a teacher in 2019。" },
      { q: "What did Xiao Yu bring to the writer?", opts: ["A paper bag of books", "Four eggs from his family", "A letter"], ans: 1,
        why: "第10、11句：In came a thin boy with a paper bag... Inside were four eggs from his family。" },
      { q: "According to the writer, what keeps a teacher going?", opts: ["The money", "The moment a quiet child puts up his hand", "The number of students"], ans: 1,
        why: "第14、15句：It is not the money that keeps a teacher going. It is the moment when a quiet child finally puts up his hand。" },
      { q: "What does Xiao Yu rarely do?", opts: ["Come to school early", "Speak", "Do his homework"], ans: 1,
        why: "第7句倒装：Seldom did he speak＝He seldom spoke（他很少说话）。" },
    ],
  },

  /* ----------------------- 第24章 名词性从句 ------------------------ */
  24: {
    level: 3, words: 205,
    title: "What People Really Want from a Job（人们真正想从工作中得到什么）",
    tip: "整篇在练名词性从句：What... 当主语、that... 当宾语、Whether... 当主语、the fact that... 同位语。技巧：把 What/That/Whether 引导的一整块当成一个「大名词」来看。",
    sents: [
      { en: "What most people want from a job is not only money.", zh: "大多数人想从工作中得到的，不只是钱。" },
      { en: "That is what a survey of 2,000 workers showed last year.", zh: "这是去年一项针对两千名员工的调查显示的结果。" },
      { en: "The question was simple: what matters most to you at work?", zh: "问题很简单：工作中什么对你最重要？" },
      { en: "What surprised the researchers was the answer.", zh: "让研究者吃惊的是答案。" },
      { en: "Nearly half said that being respected was more important than a higher salary.", zh: "将近一半的人说，被尊重比更高的工资更重要。" },
      { en: "Whether this is true for everyone is hard to say.", zh: "这是否对每个人都成立，很难讲。" },
      { en: "But the fact that so many people gave the same answer tells us something.", zh: "但这么多人给出同样答案这一事实，说明了一些问题。" },
      { en: "What we do all day shapes who we are.", zh: "我们整天做的事，塑造了我们成为什么样的人。" },
      { en: "One woman said what she remembered about her first job was not the pay.", zh: "一位女士说，她对第一份工作的记忆并不是工资。" },
      { en: "It was the fact that her manager knew her name.", zh: "而是她的经理记得她的名字。" },
      { en: "Another man said he did not care where he worked or how long the hours were.", zh: "另一位男士说，他不在乎在哪儿工作、工时多长。" },
      { en: "What mattered to him was whether he felt useful.", zh: "对他来说重要的是，他是否觉得自己有用。" },
      { en: "The researchers also asked whether people would change jobs for more money.", zh: "研究者还问了人们是否会为了更多钱换工作。" },
      { en: "About sixty percent said that they would, but only if the new place treated them well.", zh: "约百分之六十说会，但前提是新单位要善待他们。" },
      { en: "What this means is clear: money matters, but it is not everything.", zh: "这说明的道理很清楚：钱重要，但不是全部。" },
      { en: "The report ends with a simple idea: that a good workplace is built on respect.", zh: "报告以一个简单的观点结尾：一个好的职场是建立在尊重之上的。" },
      { en: "Whoever runs a company should remember this.", zh: "无论谁在经营公司，都该记住这一点。" },
      { en: "What costs nothing may be worth the most.", zh: "不花钱的东西，可能最值钱。" },
    ],
    qs: [
      { q: "What did nearly half of the workers say?", opts: ["A higher salary is the most important thing", "Being respected is more important than a higher salary", "They would never change jobs"], ans: 1,
        why: "第5句：Nearly half said that being respected was more important than a higher salary。" },
      { q: "What did the woman remember about her first job?", opts: ["The pay", "That her manager knew her name", "The long hours"], ans: 1,
        why: "第9、10句：what she remembered... was not the pay. It was the fact that her manager knew her name。" },
      { q: "Under what condition would about sixty percent change jobs?", opts: ["Only if the new place treated them well", "Only if the hours were shorter", "They would never change"], ans: 0,
        why: "第14句：About sixty percent said that they would, but only if the new place treated them well。" },
      { q: "What is the main idea of the report?", opts: ["Money is everything at work", "A good workplace is built on respect", "Everyone should start a company"], ans: 1,
        why: "倒数第3句：a good workplace is built on respect，最后一句再强化：What costs nothing may be worth the most。" },
    ],
  },

  /* ------------------- 第25章 语音（送分题） -------------------- */
  25: {
    level: 3, words: 204,
    title: "Fifteen Minutes Out Loud（每天十五分钟，读出声）",
    tip: "这篇讲的正是语音：注意文中说的两个考点——① 词尾音容易吞掉（works / lived 的结尾）；② 同样的字母在不同词里读音不同。读的时候请真的出声读，别默读。",
    sents: [
      { en: "Many people can read English quite well but are afraid to open their mouths.", zh: "很多人英语读得不错，却不敢开口。" },
      { en: "Li Hua was one of them.", zh: "李华就是其中之一。" },
      { en: "He had studied English for six years, but when a foreign visitor asked him for directions, he could not say a word.", zh: "他学了六年英语，可当一位外国客人向他问路时，他一个字也说不出来。" },
      { en: "That evening he decided to do something about it.", zh: "那天晚上，他决定改变这件事。" },
      { en: "He began to read aloud for fifteen minutes every morning.", zh: "他开始每天早上朗读十五分钟。" },
      { en: "He chose short news reports and read them again and again until the words came out smoothly.", zh: "他挑一些短新闻，一遍遍读，直到读顺为止。" },
      { en: "At first his family laughed at him.", zh: "起初家里人笑话他。" },
      { en: "His son said he sounded strange.", zh: "他儿子说他读得怪怪的。" },
      { en: "But Li Hua kept going.", zh: "但李华坚持了下来。" },
      { en: "He recorded himself on his phone and listened to it on the bus.", zh: "他用手机把自己录下来，在公交车上听。" },
      { en: "It was painful at the beginning.", zh: "一开始很难受。" },
      { en: "He noticed that he often dropped the ending sounds.", zh: "他发现自己经常把词尾的音吞掉。" },
      { en: "Works sounded like work, and lived sounded like live.", zh: "works 听着像 work，lived 听着像 live。" },
      { en: "He also found that some words looked the same but sounded different.", zh: "他还发现有些词看着像，读音却不同。" },
      { en: "A single letter could change everything.", zh: "一个字母就能改变一切。" },
      { en: "Slowly his ear became sharper.", zh: "慢慢地，他的耳朵变灵了。" },
      { en: "Six months later, the same foreign visitor came to the shop again.", zh: "六个月后，同一位外国客人又来到店里。" },
      { en: "This time Li Hua talked with him for almost ten minutes.", zh: "这一次，李华和他聊了将近十分钟。" },
      { en: "Afterwards his son asked him when he had learned to do that.", zh: "事后他儿子问他，什么时候学会的。" },
      { en: "Reading aloud costs nothing. It only needs fifteen minutes and a little courage.", zh: "朗读不花一分钱，只需要十五分钟和一点勇气。" },
    ],
    qs: [
      { q: "What happened when the foreign visitor first asked Li Hua for directions?", opts: ["He gave clear directions", "He could not say a word", "He asked his son for help"], ans: 1,
        why: "第3句：he could not say a word。" },
      { q: "What pronunciation mistake did Li Hua notice?", opts: ["He spoke too fast", "He dropped the ending sounds", "He could not hear the difference between p and b"], ans: 1,
        why: "第12、13句：he often dropped the ending sounds. Works sounded like work..." },
      { q: "How long did he talk with the visitor six months later?", opts: ["Almost ten minutes", "Fifteen minutes", "Six minutes"], ans: 0,
        why: "第18句：Li Hua talked with him for almost ten minutes。十五分钟是每天朗读的时间，别混。" },
      { q: "What does the writer say reading aloud needs?", opts: ["A good teacher and money", "Fifteen minutes and a little courage", "A quiet room and a recorder"], ans: 1,
        why: "最后一句：It only needs fifteen minutes and a little courage。" },
    ],
  },

  /* ------------------ 第26章 补全对话（套路题） ------------------- */
  26: {
    level: 3, words: 196,
    title: "At the Doctor's（在医院）",
    tip: "补全对话考的就是这些套路：问候、请求、答谢、建议、告别。请特别记住加粗常考的固定应答：That's very kind of you / What seems to be the trouble? / Not at all / Take care。这些直接能进作文和口语。",
    sents: [
      { en: "Nurse: Good morning. Do you have an appointment?", zh: "护士：早上好，您预约了吗？" },
      { en: "Mr. Zhao: No, I don't. Is it possible to see a doctor this morning?", zh: "赵先生：没有。今天上午能看上医生吗？" },
      { en: "Nurse: Let me check. Yes, Doctor Lin can see you at ten past nine.", zh: "护士：我查一下。可以，林医生九点十分能给您看。" },
      { en: "Mr. Zhao: That's very kind of you. Thank you.", zh: "赵先生：太感谢您了。" },
      { en: "Doctor: Good morning. Please sit down. What seems to be the trouble?", zh: "医生：早上好，请坐。哪里不舒服？" },
      { en: "Mr. Zhao: I've had a bad cough for about two weeks.", zh: "赵先生：我咳嗽得厉害，有两个星期了。" },
      { en: "Doctor: I see. Have you taken anything for it?", zh: "医生：明白了。吃过什么药吗？" },
      { en: "Mr. Zhao: Only some hot water with honey. I'm afraid it hasn't helped much.", zh: "赵先生：只喝了点蜂蜜水，恐怕没什么用。" },
      { en: "Doctor: Does the cough wake you up at night?", zh: "医生：咳嗽会在夜里把您弄醒吗？" },
      { en: "Mr. Zhao: Yes, it does. That's why I finally came.", zh: "赵先生：会的。所以我才终于来了。" },
      { en: "Doctor: Let me have a look. Open your mouth, please.", zh: "医生：我看看。请张嘴。" },
      { en: "Doctor: Nothing serious. You've caught a cold, and the cough will take a few more days.", zh: "医生：不严重。您是着凉了，咳嗽还要再持续几天。" },
      { en: "Mr. Zhao: What should I do?", zh: "赵先生：我该怎么办？" },
      { en: "Doctor: Take this medicine twice a day, after meals.", zh: "医生：这个药一天两次，饭后吃。" },
      { en: "Doctor: Drink plenty of water, and try not to smoke.", zh: "医生：多喝水，尽量别抽烟。" },
      { en: "Mr. Zhao: I gave up smoking last year.", zh: "赵先生：我去年就戒烟了。" },
      { en: "Doctor: Well done. Come back next Monday if it doesn't get better.", zh: "医生：很好。如果没好转，下周一再来。" },
      { en: "Mr. Zhao: I will. Thank you very much, doctor.", zh: "赵先生：好的。非常感谢，医生。" },
      { en: "Doctor: Not at all. Take care.", zh: "医生：不客气，保重。" },
    ],
    qs: [
      { q: "How long has Mr. Zhao had the cough?", opts: ["About two weeks", "A few days", "Since last year"], ans: 0,
        why: "第6句：I've had a bad cough for about two weeks。“几天”是医生说还要再咳几天，“去年”是戒烟时间。" },
      { q: "Why did Mr. Zhao finally come to the doctor?", opts: ["His wife asked him to", "The cough woke him up at night", "He wanted to stop smoking"], ans: 1,
        why: "第9、10句：Does the cough wake you up at night? — Yes, it does. That's why I finally came。" },
      { q: "How should he take the medicine?", opts: ["Twice a day, after meals", "Three times a day, before meals", "Only at night"], ans: 0,
        why: "第14句：Take this medicine twice a day, after meals。" },
      { q: "What does the doctor say at the end?", opts: ["You must come back tomorrow", "Not at all. Take care.", "You should stop drinking water"], ans: 1,
        why: "最后一句：Not at all. Take care.（不客气，保重）——这是道谢后的标准应答，补全对话常考。" },
    ],
  },

  /* ------------------- 第27章 完形填空技巧 -------------------- */
  27: {
    level: 3, words: 215,
    title: "When One Door Closes（当一扇门关上）",
    tip: "完形填空多是这种「有起伏的小故事」。读的时候练两件事：① 抓住主人公情绪的转折点；② 留意 but / instead / by the end of 这类逻辑词——完形的空十有八九就挖在逻辑转折处。",
    sents: [
      { en: "When Zhang Lei lost his job last spring, he thought his world had ended.", zh: "去年春天张磊丢了工作时，他觉得自己的世界塌了。" },
      { en: "He was forty-three, and he had worked at the same factory since he was twenty.", zh: "他四十三岁，从二十岁起就在同一家工厂上班。" },
      { en: "For the first month he stayed at home.", zh: "头一个月他一直待在家里。" },
      { en: "He did not tell his old workmates.", zh: "他没告诉老同事们。" },
      { en: "He was afraid they would feel sorry for him.", zh: "他怕他们可怜他。" },
      { en: "One afternoon his wife came home with a small box of tools.", zh: "一天下午，他妻子拎回来一小箱工具。" },
      { en: "She put it on the table and said nothing.", zh: "她把箱子放在桌上，什么也没说。" },
      { en: "Zhang Lei looked at it for a long time.", zh: "张磊盯着它看了很久。" },
      { en: "When he was young, he had been good at fixing things.", zh: "他年轻的时候，很会修东西。" },
      { en: "Neighbours used to knock on his door when a light or a tap stopped working.", zh: "邻居家灯坏了、水龙头不出水了，以前都来敲他的门。" },
      { en: "The next day he repaired a broken chair for the old woman upstairs.", zh: "第二天他给楼上的老太太修好了一把坏椅子。" },
      { en: "She wanted to pay him, but he refused.", zh: "老太太要给钱，他没要。" },
      { en: "Instead, she told her friends.", zh: "结果她把这事告诉了她的朋友们。" },
      { en: "By the end of the month, four people had asked him for help.", zh: "到月底，已经有四个人来找他帮忙。" },
      { en: "Today Zhang Lei has a small repair shop near the market.", zh: "如今张磊在菜市场附近开了家小修理铺。" },
      { en: "He earns less than he did at the factory, but he decides his own hours.", zh: "他挣得比在工厂时少，但时间自己说了算。" },
      { en: "He says the hardest part was not losing the job.", zh: "他说最难的并不是丢工作。" },
      { en: "It was the month he spent hiding at home.", zh: "而是那个躲在家里的月份。" },
      { en: "His advice is simple: when one door closes, do not sit in the dark and wait.", zh: "他的建议很简单：一扇门关上时，别坐在黑暗里等。" },
      { en: "Go and look for the window.", zh: "去找那扇窗。" },
    ],
    qs: [
      { q: "Why didn't Zhang Lei tell his old workmates?", opts: ["He was afraid they would feel sorry for him", "He had lost their phone numbers", "He was too busy"], ans: 0,
        why: "第5句：He was afraid they would feel sorry for him。" },
      { q: "What did his wife bring home?", opts: ["A new job offer", "A small box of tools", "A chair"], ans: 1,
        why: "第6句：his wife came home with a small box of tools。椅子是他后来修的。" },
      { q: "What does Zhang Lei say was the hardest part?", opts: ["Losing the job", "The month he spent hiding at home", "Opening the repair shop"], ans: 1,
        why: "第17、18句：the hardest part was not losing the job. It was the month he spent hiding at home。" },
      { q: "What is his advice?", opts: ["Never leave a stable job", "Do not sit and wait — go and look for the window", "Always ask friends for money"], ans: 1,
        why: "最后两句：when one door closes, do not sit in the dark and wait. Go and look for the window。" },
    ],
  },

  /* ------------------- 第28章 阅读理解策略 --------------------- */
  28: {
    level: 3, words: 226,
    title: "Why We Need Sleep（我们为什么需要睡眠）",
    tip: "这是典型的成考说明文。按策略读：① 先看第一句和最后一段，抓主旨；② 每段找一个「中心句」；③ 数字（七到八小时、六小时、四点）一定圈出来，细节题必考。别逐词翻译，看不懂的词跳过去。",
    sents: [
      { en: "Sleep is something we all need, but many people treat it as a waste of time.", zh: "睡眠是我们都需要的，但很多人把它当成浪费时间。" },
      { en: "Scientists say that adults need seven to eight hours of sleep every night.", zh: "科学家说，成年人每晚需要七到八小时睡眠。" },
      { en: "Yet in big cities, a large number of people sleep less than six.", zh: "然而在大城市，很多人睡不到六小时。" },
      { en: "What happens when we do not sleep enough?", zh: "睡不够会怎么样？" },
      { en: "The most obvious result is that we feel tired.", zh: "最明显的结果是我们觉得累。" },
      { en: "But the real problems are harder to see.", zh: "但真正的问题更难被看到。" },
      { en: "Studies show that people who sleep badly find it more difficult to remember new information.", zh: "研究显示，睡不好的人更难记住新信息。" },
      { en: "Students who stay up all night before an exam often do worse than those who go to bed early.", zh: "考前通宵的学生，成绩往往不如早睡的学生。" },
      { en: "Poor sleep also affects the body.", zh: "睡眠差还会影响身体。" },
      { en: "It can make people gain weight, and over many years it may lead to heart problems.", zh: "它会让人长胖，很多年下来还可能引发心脏问题。" },
      { en: "Some research suggests that people who sleep less than six hours a night are more likely to catch colds.", zh: "有研究表明，每晚睡不到六小时的人更容易感冒。" },
      { en: "Why do so many of us sleep so little?", zh: "为什么我们这么多人睡得这么少？" },
      { en: "Phones are part of the answer.", zh: "手机是原因之一。" },
      { en: "The light from a screen tells the brain that it is still daytime.", zh: "屏幕的光在告诉大脑：现在还是白天。" },
      { en: "Another reason is worry.", zh: "另一个原因是焦虑。" },
      { en: "People lie in bed thinking about work, money or family.", zh: "人们躺在床上想着工作、钱或者家人。" },
      { en: "Experts give simple advice.", zh: "专家给的建议很简单。" },
      { en: "Go to bed at the same time every night.", zh: "每晚在同一时间上床。" },
      { en: "Keep the phone out of the bedroom.", zh: "别把手机带进卧室。" },
      { en: "Do not drink coffee after four in the afternoon.", zh: "下午四点以后别喝咖啡。" },
      { en: "None of this is difficult. The hard part is doing it every day.", zh: "这些都不难，难的是每天都做到。" },
    ],
    qs: [
      { q: "How many hours of sleep do adults need every night?", opts: ["Five to six", "Seven to eight", "Nine to ten"], ans: 1,
        why: "第2句：adults need seven to eight hours of sleep every night。“不到六小时”是很多人的实际情况，不是需要的量——细节题最爱挖这种坑。" },
      { q: "What often happens to students who stay up all night before an exam?", opts: ["They do better", "They often do worse than those who go to bed early", "They remember more"], ans: 1,
        why: "第8句：Students who stay up all night before an exam often do worse。" },
      { q: "According to the passage, why do phones affect sleep?", opts: ["They are too heavy to hold", "The light from a screen tells the brain it is still daytime", "They are always ringing"], ans: 1,
        why: "第14句：The light from a screen tells the brain that it is still daytime。" },
      { q: "What is the main idea of the last paragraph?", opts: ["Sleeping well is impossible", "The advice is simple, but doing it every day is hard", "Coffee is the biggest problem"], ans: 1,
        why: "最后一句总结：None of this is difficult. The hard part is doing it every day。主旨题看结尾的总结句。" },
    ],
  },

};
