/* ============================================================================
 * syllabus.js  ——  学习大纲主线 + 白话语法手册（随时查阅）
 * 每章：no 章号 / title / learn(懂|背|背+懂|技巧) / topics(绑定题库的知识点)
 *       / plain(大白话讲这是什么,带生活例子) / points(要点)
 *       / extra(选填,补充讲解) / examples([{en,zh}]) / pitfalls(易错点,选填)
 * App 会从第 1 章开始，掌握了才解锁下一章；本页只讲不考，做题在今日学习/练习。
 * ========================================================================== */

window.SYLLABUS = [
/* ============================ 第一部分 · 零基础地基 ====================== */
{
  no: 1, title: "be 动词 (am / is / are)", learn: "懂",
  topics: ["be-verb", "past-be"],
  plain: "be 动词就是中文里的“是”。英语规定：不同的“我/你/他”要配不同的“是”——我配 am，他/她/它配 is，你/我们/他们配 are。就像不同的锁配不同的钥匙。",
  points: ["口诀：I 用 am；he/she/it 用 is；you/we/they 用 are。", "过去“是”：am/is → was，are → were。", "否定：在 be 后面加 not（is not = isn't）。", "提问：把 be 提到句首（Are you...? / Is he...?）。"],
  examples: [
    { en: "I am a student.", zh: "我是学生。" },
    { en: "They are happy.", zh: "他们很开心。" },
    { en: "He is a doctor.", zh: "他是医生。" },
    { en: "She was ill yesterday.", zh: "她昨天病了。" },
    { en: "We were busy last week.", zh: "我们上周很忙。" },
    { en: "Is your father at home? — Yes, he is.", zh: "你爸爸在家吗？——在。" },
  ],
  pitfalls: [
    "❌ He am a teacher → ✅ He is a teacher（he 只能配 is）",
    "❌ They is students → ✅ They are students（复数配 are）",
    "❌ I am agree with you → ✅ I agree with you（agree 自己就是动词，前面不能再加 am）",
    "❌ She were late → ✅ She was late（单数过去用 was）",
  ],
},
{
  no: 2, title: "名词单复数 & There be", learn: "懂",
  topics: ["plural", "there-be"],
  plain: "一个东西 vs 好几个东西，英语要变形：一般在名词后面加 s 表示“好几个”。想说“某处有某物”用 There is/are。",
  points: ["一个 book → 两个 books（加 s）；s/x/ch/sh 结尾加 es（boxes, watches）。", "辅音+y 结尾变 ies：baby → babies。", "不规则的要背：man→men, woman→women, child→children, foot→feet, tooth→teeth。", "There is + 单数/不可数；There are + 复数。"],
  examples: [
    { en: "There are three books.", zh: "有三本书。" },
    { en: "There is a cat.", zh: "有一只猫。" },
    { en: "There is some water in the glass.", zh: "杯子里有些水。（水不可数，配 is）" },
    { en: "There are two men in the room.", zh: "房间里有两个男人。（man→men 不规则）" },
    { en: "Look at those children.", zh: "看那些孩子。（child→children）" },
  ],
  pitfalls: [
    "❌ There have many people → ✅ There are many people（“某处有”不用 have）",
    "❌ two childs → ✅ two children（不规则复数要背）",
    "就近原则：There is a pen and two books on the desk.（be 跟最近的 a pen 走，用 is）",
    "不可数名词没有复数：❌ two breads / many moneys → ✅ two pieces of bread / much money",
  ],
},
{
  no: 3, title: "冠词 a / an / the", learn: "懂",
  topics: ["article"],
  plain: "a/an 是“一个”（第一次提到、随便一个）；the 是“那个”（特指、大家都知道的那个）。a 后面接辅音开头的词，an 接元音开头的词（看读音，不看字母！）。",
  points: ["第一次提到、泛指“一个”用 a/an。", "元音音素开头用 an（an apple, an hour）。", "特指“那个”、独一无二(the sun)、第二次提到用 the。", "球类运动、三餐前不加冠词：play football, have breakfast。", "乐器前要加 the：play the piano。"],
  examples: [
    { en: "I saw an elephant.", zh: "我看见一头大象。" },
    { en: "The sun is bright.", zh: "太阳很亮。（独一无二用 the）" },
    { en: "He will be back in an hour.", zh: "他一小时后回来。（hour 的 h 不发音，元音开头）" },
    { en: "It is a useful book.", zh: "这是本有用的书。（useful 读 /ju/，辅音开头）" },
    { en: "She plays the piano, and he plays basketball.", zh: "她弹钢琴，他打篮球。（乐器加 the，球类不加）" },
  ],
  pitfalls: [
    "a/an 看读音不看字母：✅ an hour / a university　❌ a hour / an university",
    "❌ play the football → ✅ play football（球类不加 the）；❌ play piano → ✅ play the piano（乐器要加）",
    "第一次提到用 a，第二次再提就用 the：I have a dog. The dog is cute.",
  ],
},
{
  no: 4, title: "代词 (我/我的/它…)", learn: "懂",
  topics: ["pronoun", "object-pronoun", "possessive", "demonstrative"],
  plain: "代词就是代替名字的词。同一个“我”，在不同位置长得不一样：当主语用 I，当宾语用 me，“我的+名词”用 my，“我的东西”单独说用 mine。",
  points: ["主格(做主语) I/he/she/we/they；宾格(做宾语) me/him/her/us/them。", "my/your/his/her + 名词；mine/yours/his/hers 单独用。", "this/these 近，that/those 远。", "反身代词：myself, yourself, himself…（enjoy oneself 玩得开心）。"],
  examples: [
    { en: "Please help me.", zh: "请帮我。（宾语用 me）" },
    { en: "This is my book.", zh: "这是我的书。" },
    { en: "The bag is mine.", zh: "这个包是我的。（mine 单独用）" },
    { en: "He gave the apple to her.", zh: "他把苹果给了她。" },
    { en: "We enjoyed ourselves at the party.", zh: "我们在聚会上玩得很开心。" },
  ],
  pitfalls: [
    "❌ Me and him are friends → ✅ He and I are friends（做主语用主格，而且 I 放后面才礼貌）",
    "❌ This is mine book → ✅ my book 或者单独说 It is mine",
    "its 是“它的”，it's 是 it is 的缩写，考试爱混着考",
  ],
},
{
  no: 5, title: "一般现在时 (第三人称加 s)", learn: "懂",
  topics: ["present-simple", "have-has"],
  plain: "讲“经常、习惯做的事”用一般现在时。最大的坑：主语是他/她/它(第三人称单数)时，动词要加 s；have 要变 has。",
  points: ["主语 he/she/it → 动词加 s：goes, likes, watches。", "变化规则：一般加 s；o/s/x/ch/sh 结尾加 es（goes, watches）；辅音+y 变 ies（studies）。", "have → has（他有 he has）。", "否定和提问用 do/does 帮忙，动词变回原形：He doesn't go. / Does he go?", "常和 every day / usually / often 连用；客观真理也用它。"],
  examples: [
    { en: "She goes to school every day.", zh: "她每天上学。" },
    { en: "He has a bike.", zh: "他有辆自行车。" },
    { en: "My father works in a bank.", zh: "我爸爸在银行工作。" },
    { en: "He doesn't watch TV in the evening.", zh: "他晚上不看电视。" },
    { en: "Does she like music? — Yes, she does.", zh: "她喜欢音乐吗？——喜欢。" },
  ],
  pitfalls: [
    "❌ He don't like it → ✅ He doesn't like it（三单否定用 doesn't）",
    "❌ Does she likes music? → ✅ Does she like music?（does 出场后，动词变回原形）",
    "❌ He studys hard → ✅ He studies hard（辅音+y 变 ies）",
  ],
},
{
  no: 6, title: "现在进行时 (正在做)", learn: "懂",
  topics: ["present-continuous"],
  plain: "“此刻正在做”用现在进行时：be 动词 + 动词ing。看到 Look! / Listen! / now 基本就是它。",
  points: ["结构：am/is/are + 动词-ing（两件套，缺一不可）。", "变化规则：一般直接加 ing；以不发音 e 结尾去 e 加 ing（make→making）；重读闭音节双写尾字母（run→running, swim→swimming）。", "标志词：now, Look!, Listen!, at the moment。"],
  examples: [
    { en: "Look! The baby is sleeping.", zh: "看！宝宝正在睡觉。" },
    { en: "Listen! Someone is singing.", zh: "听！有人在唱歌。" },
    { en: "They are playing basketball now.", zh: "他们现在正在打篮球。" },
    { en: "I am writing a letter.", zh: "我正在写信。" },
    { en: "She is not sleeping. She is reading.", zh: "她没在睡觉，她在看书。" },
  ],
  pitfalls: [
    "❌ He is play football → ✅ He is playing football（ing 别丢）",
    "❌ He playing football → ✅ He is playing football（be 别丢）",
    "❌ runing / swiming → ✅ running / swimming（双写再加 ing）；❌ makeing → ✅ making（去 e）",
  ],
},
{
  no: 7, title: "数量词 some/any/much/many", learn: "懂",
  topics: ["some-any", "much-many", "few-little"],
  plain: "表示“多少”的词，要看后面名词能不能数。能数的(books)用 many/few；不能数的(water)用 much/little。some 多用于肯定句，any 多用于否定和疑问。",
  points: ["可数复数：many / a few(有几个) / few(几乎没有)。", "不可数：much / a little(有一点) / little(几乎没有)。", "a lot of / lots of 两边都能用。", "some 肯定句；any 否定、疑问句（表请求、建议的问句仍用 some）。", "问数量：How many + 可数复数；How much + 不可数（也问价钱）。"],
  examples: [
    { en: "I don't have any money.", zh: "我没有钱。" },
    { en: "There isn't much water.", zh: "没有多少水。" },
    { en: "There are a few eggs in the fridge.", zh: "冰箱里有几个鸡蛋。（a few = 有几个，够用）" },
    { en: "He has little time.", zh: "他几乎没时间。（little = 几乎没有）" },
    { en: "Would you like some tea?", zh: "要来点茶吗？（客气建议，问句也用 some）" },
  ],
  pitfalls: [
    "few / little 是“几乎没有”（否定味）；a few / a little 是“有一些”（肯定味），一字之差意思相反",
    "❌ many money → ✅ much money（money 不可数）；❌ much books → ✅ many books",
    "How much 还能问价钱：How much is the shirt?（这件衬衫多少钱？）",
  ],
},
{
  no: 8, title: "介词 (时间 / 地点)", learn: "背+懂",
  topics: ["preposition-time", "preposition-place"],
  plain: "介词是小词但爱考。时间口诀：大用 in(月/年/季节)、中用 on(某天)、小用 at(几点)。地点：in 里面、on 表面、at 一点。这些要多记。",
  points: ["时间：in May / in 2024 / in the morning；on Monday / on May 1st；at six / at noon / at night。", "某一天的早中晚，一律用 on：on Sunday morning。", "地点：in the box / on the wall / at the door / at school。", "常考搭配：be good at, be late for, arrive in(大地方)/at(小地方)。"],
  examples: [
    { en: "The class begins at eight.", zh: "八点上课。" },
    { en: "A picture is on the wall.", zh: "墙上有幅画。" },
    { en: "He was born in 1998.", zh: "他 1998 年出生。" },
    { en: "We have a meeting on Monday morning.", zh: "我们周一早上开会。（具体某天的早上用 on）" },
    { en: "They arrived in Beijing at night.", zh: "他们晚上到了北京。" },
  ],
  pitfalls: [
    "❌ in Monday → ✅ on Monday（具体某一天用 on）",
    "in the morning，但某天的早上要变 on：on Sunday morning（考试最爱挖这个坑）",
    "at night / in the evening，两个搭配是固定的，别互换",
    "in the tree（外来的东西在树上，比如鸟）vs on the tree（树上长的，比如苹果）",
  ],
},
{
  no: 9, title: "情态动词 can / must", learn: "懂",
  topics: ["modal-can", "modal-verb"],
  plain: "can(能/会)、must(必须)、may(可以)这类词叫情态动词。规矩就一条：后面直接跟动词原形，它自己不加 s、不加 to、不变形。",
  points: ["can/must/may/should + 动词原形。", "情态动词不加 s，也不加 to。", "must not(mustn't) = 禁止；needn't = 不必（两个意思差很远）。", "must 表推测：He must be tired.（他一定累了。）", "had better(最好) 后面也接动词原形。"],
  examples: [
    { en: "Birds can fly.", zh: "鸟会飞。" },
    { en: "You must finish it.", zh: "你必须完成它。" },
    { en: "May I come in?", zh: "我可以进来吗？" },
    { en: "You mustn't smoke here.", zh: "这里禁止吸烟。（mustn't = 禁止）" },
    { en: "You'd better go to bed early.", zh: "你最好早点睡。" },
  ],
  pitfalls: [
    "❌ He can sings → ✅ He can sing（情态动词后接原形）",
    "❌ She can to swim → ✅ She can swim（不加 to）",
    "mustn't(不许、禁止) ≠ needn't(不必)：— Must I come? — No, you needn't.（回答 must 的问句，否定用 needn't）",
  ],
},
{
  no: 10, title: "将来时 will / be going to", learn: "懂",
  topics: ["future-will"],
  plain: "说“将要做”的事。will 多用于当场决定或单纯将来；打算好了的计划、或有眼前迹象的预测(看乌云要下雨)用 be going to。",
  points: ["will + 动词原形；否定 won't。", "be going to + 动词原形：事先的打算 / 看迹象预测。", "标志词：tomorrow, next week, soon, in the future。", "重要：if/when 引导的条件、时间从句里用一般现在时代替将来时（主将从现）。"],
  examples: [
    { en: "I will call you tomorrow.", zh: "我明天给你打电话。" },
    { en: "It is going to rain.", zh: "要下雨了。（看见乌云，有迹象）" },
    { en: "We are going to visit the museum next week.", zh: "我们下周打算去参观博物馆。（事先计划）" },
    { en: "Will you join us? — Sure, I will.", zh: "你要加入我们吗？——当然。" },
    { en: "If it rains tomorrow, I will stay at home.", zh: "如果明天下雨，我就待在家。（if 从句用现在时）" },
  ],
  pitfalls: [
    "❌ He will goes → ✅ He will go（will 后接原形）",
    "❌ He going to buy it → ✅ He is going to buy it（be 别丢）",
    "主将从现：❌ If it will rain, ... → ✅ If it rains, I will...（if/when 从句不用 will）",
  ],
},
{
  no: 11, title: "祈使句 & 频率副词", learn: "懂",
  topics: ["imperative", "adverb-frequency"],
  plain: "叫别人做事(祈使句)直接用动词原形开头：Be quiet! 不许做就在前面加 Don't。频率副词(always/never)表示“多经常”，位置有讲究。",
  points: ["祈使句用动词原形开头：Open the door. 客气就加 please。", "否定祈使句：Don't + 动词原形（Don't be late.）。", "频率排序：always 总是 > usually 通常 > often 经常 > sometimes 有时 > never 从不。", "位置口诀：be 动词后、实义动词前（He is always late. / He always comes early.）。"],
  examples: [
    { en: "Be quiet, please.", zh: "请安静。" },
    { en: "He is never late.", zh: "他从不迟到。" },
    { en: "Don't touch the machine.", zh: "别碰这台机器。" },
    { en: "She usually gets up at six.", zh: "她通常六点起床。（实义动词前）" },
    { en: "Never give up.", zh: "永不放弃。" },
  ],
  pitfalls: [
    "❌ Don't to open the door → ✅ Don't open the door（Don't 后直接接原形）",
    "❌ He goes always to work by bus → ✅ He always goes to work by bus（频率副词放实义动词前）",
    "祈使句开头是原形：❌ To be quiet! / Being quiet! → ✅ Be quiet!",
  ],
},
{
  no: 12, title: "疑问词 & 反意疑问句", learn: "懂",
  topics: ["question-word", "tag-question"],
  plain: "问“什么/谁/哪里/怎样”用 what/who/where/how。反意疑问句=陈述句后面加个小尾巴，规矩是“前肯后否，前否后肯”。",
  points: ["What 什么 / Who 谁 / Where 哪里 / When 何时 / Why 为何 / How 怎样。", "How old 几岁 / How much 多少钱 / How long 多久 / How often 多常一次。", "反意疑问：前肯后否（You are..., aren't you?）；前否后肯（You didn't..., did you?）。", "回答只看事实：做了就 Yes，没做就 No（和中文的“是啊/不是”相反，别被带偏）。"],
  examples: [
    { en: "What is your name?", zh: "你叫什么名字？" },
    { en: "She is a nurse, isn't she?", zh: "她是护士，对吧？" },
    { en: "How much is the shirt?", zh: "这件衬衫多少钱？" },
    { en: "You didn't go to the party, did you? — Yes, I did.", zh: "你没去聚会，对吧？——不，我去了。（去了就答 Yes）" },
    { en: "Let's have a rest, shall we?", zh: "咱们休息一下，好吗？（Let's 的尾巴用 shall we）" },
  ],
  pitfalls: [
    "回答反意疑问句只看事实：去了就 Yes, I did；没去就 No, I didn't（中文习惯的“是的，我没去”在英语里是 No, I didn't）",
    "I am... 的反问尾巴用 aren't I：I am late, aren't I?",
    "Let's... 的尾巴是 shall we；祈使句的尾巴是 will you",
  ],
},

/* ============================ 第二部分 · 进阶核心 ======================== */
{
  no: 13, title: "比较级 & 最高级", learn: "懂",
  topics: ["comparative", "superlative", "comparison"],
  plain: "两个东西比“更…”用比较级(short→shorter)，看到 than 就用它；三个以上比“最…”用最高级，前面加 the(the tallest)。长单词用 more/most。“一样…”用 as...as 中间放原级。",
  points: ["短词：加 er / est（bigger, the biggest）；辅音+y 变 ier（easier）。", "长词：more / the most（more important）。", "不规则：good→better→best；bad→worse→worst；many/much→more→most；little→less→least。", "as + 原级 + as：和…一样；not as/so...as：不如…。", "越来越…：colder and colder；越…就越…：the more..., the more...。"],
  examples: [
    { en: "Tom is taller than Jack.", zh: "汤姆比杰克高。" },
    { en: "This is the best film.", zh: "这是最好的电影。" },
    { en: "This room is much bigger than that one.", zh: "这个房间比那个大得多。（修饰比较级用 much）" },
    { en: "He runs as fast as his brother.", zh: "他跑得和他哥哥一样快。（as...as 中间用原级）" },
    { en: "The weather is getting colder and colder.", zh: "天气越来越冷了。" },
    { en: "The more you practice, the better you will be.", zh: "你练得越多，就会越好。" },
  ],
  pitfalls: [
    "❌ more taller → ✅ taller（more 和 -er 不能叠用）",
    "❌ He runs as faster as me → ✅ as fast as（as...as 中间只能放原级）",
    "修饰比较级用 much/a little/even：✅ much better　❌ very better",
    "比较范围要排除自己：Tom is taller than any other student in his class.（any other 别丢 other）",
  ],
},
{
  no: 14, title: "现在完成时 (have done)", learn: "懂",
  topics: ["present-perfect"],
  plain: "表示“做过了、且对现在有影响”，或“到现在为止一直…”。结构：have/has + 过去分词。它关心的是“现在的结果”，所以不能和 yesterday 这种明确的过去时间连用。",
  points: ["结构：have/has + 过去分词(done)。", "标志词：already, yet, just, ever, never, since, for。", "since + 时间点（since 2015）；for + 时间段（for ten years）。", "have been to 去过(人回来了) / have gone to 去了(人还没回)。", "一旦出现具体过去时间(yesterday, last week, in 2020)，就改用一般过去时。"],
  examples: [
    { en: "I have finished my homework.", zh: "我已经写完作业了。（现在可以交了）" },
    { en: "She has lived here since 2015.", zh: "她从 2015 年起就住这儿。" },
    { en: "Have you ever been to Shanghai? — Yes, twice.", zh: "你去过上海吗？——去过两次。" },
    { en: "He has gone to London.", zh: "他去伦敦了。（人不在这儿）" },
    { en: "I have just seen the film.", zh: "我刚看完这部电影。" },
  ],
  pitfalls: [
    "❌ I have seen him yesterday → ✅ I saw him yesterday（有具体过去时间就用过去时）",
    "have been to(去过，回来了) vs have gone to(去了，还没回)：He has gone to London 意味着他现在不在这里",
    "for + 时间段 / since + 时间点：for three years / since three years ago",
    "短暂动词不能直接加 for/since：❌ has bought the bike for 2 years → ✅ has had the bike for 2 years（买是一瞬间，拥有才能延续）",
  ],
},
{
  no: 15, title: "过去进行 / 过去完成 / used to", learn: "懂",
  topics: ["past-continuous", "past-perfect", "used-to"],
  plain: "过去某刻“正在做”用 was/were doing；比过去还早的“更早的过去”用 had done；“过去常常(现在不了)”用 used to do。",
  points: ["过去进行：was/were + 动词ing，常配 when/while（when 你打电话时，我正在做饭）。", "过去完成(过去的过去)：had + 过去分词，常见于 by + 过去时间、said 等报告动词之后。", "used to do = 过去常常做（现在不做了）。", "when + 短动作，while + 正在进行的长动作。"],
  examples: [
    { en: "When you called, I was cooking.", zh: "你打电话时我在做饭。" },
    { en: "There used to be a tree here.", zh: "这儿以前有棵树。（现在没了）" },
    { en: "By the end of last year, he had learned 2000 words.", zh: "到去年年底，他已经学了 2000 个单词。" },
    { en: "She said she had seen the film before.", zh: "她说她以前看过这部电影。（“看过”发生在“说”之前）" },
    { en: "While I was reading, my brother was playing games.", zh: "我看书的时候，我弟弟在打游戏。" },
  ],
  pitfalls: [
    "had done 必须有“过去的过去”做参照，单独一件过去的事用一般过去时就行，别乱套过去完成",
    "used to do(过去常常做) vs be used to doing(习惯于做) vs be used to do(被用来做)——三兄弟长得像，意思完全不同",
    "when 短动作、while 长动作：When I was cooking, he came. ✅　考试里 while 从句用进行时：❌ He came in while I cooked → ✅ He came in while I was cooking",
  ],
},
{
  no: 16, title: "被动语态 (be done)", learn: "懂",
  topics: ["passive"],
  plain: "主动是“谁做了某事”，被动是“某事被做了”(不强调谁做)。结构：be + 过去分词。东西不会自己动，所以主语是“被处理的对象”时就用被动。",
  points: ["结构：be + 过去分词（is done / was done / will be done）。", "时态藏在 be 里：is done 现在 / was done 过去 / will be done 将来 / is being done 正在被 / has been done 已经被。", "情态动词被动：must be done / can be seen。", "带 by 表示“被谁”。"],
  examples: [
    { en: "English is spoken here.", zh: "这里说英语。" },
    { en: "The bridge was built in 1990.", zh: "这桥建于 1990 年。" },
    { en: "Rice is grown in the south.", zh: "南方种水稻。" },
    { en: "The problem must be solved at once.", zh: "这个问题必须马上解决。" },
    { en: "A new hospital will be built here next year.", zh: "明年这里要建一座新医院。" },
  ],
  pitfalls: [
    "❌ The book was wrote by him → ✅ was written（be 后面要用过去分词，不规则动词要背牢）",
    "❌ The work must finished → ✅ must be finished（be 千万别丢）",
    "happen / take place（发生）没有被动：❌ was happened → ✅ happened",
    "感官/使役动词的被动要还 to：We saw him enter. → He was seen to enter.",
  ],
},
{
  no: 17, title: "非谓语 (-ing / -ed / to do)", learn: "懂",
  topics: ["non-finite", "gerund"],
  plain: "一句话只能有一个“主要动词”，其它动词要变形。-ing 表主动/正在(令人…)；-ed 表被动/感到(人感到…)；介词后面用动名词(-ing)；想做/打算做用 to do。",
  points: ["-ing 令人…(interesting, exciting)；-ed 人感到…(interested, excited)。物用 -ing，人用 -ed（多数情况）。", "介词后接动名词：good at singing, thank you for helping。", "want / hope / decide / plan + to do。", "enjoy / finish / mind / practice / keep + doing。", "stop to do 停下来去做另一件事 / stop doing 停止做这件事。"],
  examples: [
    { en: "The film is moving; I am moved.", zh: "电影感人；我被感动了。" },
    { en: "She is good at singing.", zh: "她擅长唱歌。" },
    { en: "He wants to buy a new phone.", zh: "他想买个新手机。" },
    { en: "I enjoy reading before bed.", zh: "我喜欢睡前看书。（enjoy + doing）" },
    { en: "The girl standing there is my sister.", zh: "站在那儿的女孩是我妹妹。（-ing 表主动）" },
    { en: "He stopped to have a rest.", zh: "他停下来休息。（停下手头的事，去休息）" },
  ],
  pitfalls: [
    "❌ I am very interesting in English → ✅ interested in（人“感到”用 -ed）",
    "❌ enjoy to read → ✅ enjoy reading（enjoy/finish/mind 后只接 doing）",
    "look forward to 的 to 是介词：✅ look forward to seeing you　❌ to see you",
    "stop doing(不做了) vs stop to do(停下来去做)：He stopped smoking. 戒烟了 / He stopped to smoke. 停下来抽根烟",
  ],
},
{
  no: 18, title: "too...to / so...that / enough", learn: "懂",
  topics: ["too-to", "so-that"],
  plain: "太…以至于不能：too + 形容词 + to do。如此…以至于：so + 形容词 + that 从句。足够…能做：形容词 + enough + to do。三个句型可以互相改写，考试爱考转换。",
  points: ["too...to = 太…而不能…（自带否定意味）。", "so + 形容词/副词 + that + 句子。", "such + (a/an) + 形容词 + 名词 + that + 句子。", "enough 放形容词/副词后面：old enough, fast enough。", "互换：The box is too heavy to carry. = The box is so heavy that I can't carry it."],
  examples: [
    { en: "He is too young to drive.", zh: "他太小了，不能开车。" },
    { en: "He was so tired that he fell asleep at once.", zh: "他太累了，马上就睡着了。" },
    { en: "The box is too heavy for me to carry.", zh: "这箱子太重，我搬不动。" },
    { en: "He is old enough to go to school.", zh: "他到上学的年龄了。" },
    { en: "It is such an interesting book that I read it twice.", zh: "这书太有意思了，我读了两遍。" },
  ],
  pitfalls: [
    "❌ enough old → ✅ old enough（enough 放形容词后面）",
    "so + 形容词 vs such + 名词短语：so beautiful a girl = such a beautiful girl（词序不同）",
    "too...to 已含否定：❌ too young to not drive → ✅ too young to drive（别画蛇添足加 not）",
  ],
},
{
  no: 19, title: "连词 & 条件句 (if)", learn: "懂",
  topics: ["conjunction", "conditional"],
  plain: "连词把两句连起来：转折用 but/however、因果用 because/so、条件用 if/unless(除非)。真实条件句：if 从句用现在时，主句用将来时（主将从现）。",
  points: ["转折 but / however；因果 because / so；选择 or；并列 and。", "because 和 so 只能用一个；although 和 but 只能用一个（中文习惯“因为…所以…”，英语不行）。", "If + 一般现在时, 主句 will...（主将从现）。", "unless = if...not（除非）。", "祈使句 + and/or + 将来时：Hurry up, or you'll be late."],
  examples: [
    { en: "Take an umbrella in case it rains.", zh: "带伞以防下雨。" },
    { en: "If it rains, I will stay home.", zh: "如果下雨我就待家里。" },
    { en: "Although it was raining, he still came.", zh: "虽然下着雨，他还是来了。（不能再加 but）" },
    { en: "Hurry up, or you will miss the train.", zh: "快点，不然你会错过火车。" },
    { en: "I won't go unless you invite me.", zh: "除非你邀请我，否则我不去。" },
  ],
  pitfalls: [
    "❌ Because..., so... 连用 → 二选一：Because he was ill, he didn't come. 或 He was ill, so he didn't come.",
    "❌ Although..., but... 连用 → 同样二选一",
    "主将从现：If it will rain ❌ → If it rains ✅",
    "neither...nor / either...or 连接主语时，动词跟最近的那个走（就近一致）",
  ],
},
{
  no: 20, title: "定语从句 (who / which / that)", learn: "懂",
  topics: ["relative-clause"],
  plain: "定语从句就是“用一句话去修饰前面的名词”。指人用 who，指物用 which/that，表地点用 where，“…的”用 whose。判断方法：看从句缺什么成分。",
  points: ["指人 who/that；指物 which/that。", "从句缺主语或宾语 → 用 who/which/that；从句成分齐全、先行词是地点 → 用 where；是时间 → 用 when。", "whose + 名词 = …的（The girl whose father...）。", "介词后面只能用 which/whom：the house in which he lives。", "先行词被 the only / 序数词 / 最高级修饰时，优先用 that。"],
  extra: "快速判断口诀：先看先行词是人还是物，再看从句缺不缺主语/宾语。缺 → who/which/that；不缺 → 看意思选 where(地点)/when(时间)/whose(所属)。",
  examples: [
    { en: "The man who is talking is my teacher.", zh: "正在说话的那个人是我老师。" },
    { en: "The book which is on the desk is mine.", zh: "桌上那本书是我的。" },
    { en: "The girl whose father is a doctor studies hard.", zh: "那个爸爸是医生的女孩学习很努力。" },
    { en: "This is the house where I lived ten years ago.", zh: "这是我十年前住过的房子。（从句 I lived 成分齐全 → where）" },
    { en: "I will never forget the day when we first met.", zh: "我永远不会忘记我们初次见面的那天。" },
    { en: "He is the only student that passed the exam.", zh: "他是唯一通过考试的学生。（the only → that）" },
  ],
  pitfalls: [
    "❌ the man which → ✅ the man who/that（人不用 which）",
    "where 不是看到“地点”就用：先行词是地点但从句缺宾语时仍用 which/that——This is the house that he bought.（bought 缺宾语）",
    "❌ the pen which I write → ✅ the pen which I write with 或 the pen with which I write（介词别丢）",
  ],
},
{
  no: 21, title: "固定搭配 & 词义辨析", learn: "背+懂",
  topics: ["collocation", "word-choice"],
  plain: "固定搭配是“英语就这么配”的词组，没道理可讲，只能背(be good at, look forward to)。词义辨析是几个近义词挑最合适的，靠语感和积累。背记模块里的搭配卡就是为这章准备的。",
  points: ["be 系列：be good at / be interested in / be afraid of / be proud of / be famous for。", "动词短语：give up 放弃 / put off 推迟 / find out 查明 / take care of 照顾 / put up with 忍受。", "近义词看上下文选最合适的：borrow(借进) / lend(借出)；bring(带来) / take(带走)。", "动词+副词的短语，代词只能放中间：turn it on。"],
  examples: [
    { en: "I am interested in music.", zh: "我对音乐感兴趣。" },
    { en: "It depends on you.", zh: "这取决于你。" },
    { en: "He gave up smoking last year.", zh: "他去年戒烟了。" },
    { en: "The meeting was put off because of the rain.", zh: "会议因雨推迟了。" },
    { en: "Can I borrow your pen? Sure, I can lend it to you.", zh: "能借你的笔吗？当然，我可以借给你。" },
  ],
  pitfalls: [
    "动词+副词短语，代词放中间：✅ turn it on　❌ turn on it",
    "borrow(借进来) vs lend(借出去) vs keep(借多久)：How long can I keep the book?（keep 才能配时间段）",
    "because of + 名词；because + 完整句子",
    "look forward to / be used to / pay attention to 里的 to 都是介词，后接名词或 doing",
  ],
},

/* ============================ 第三部分 · 冲刺 & 题型 ==================== */
{
  no: 22, title: "虚拟语气 (最高频难点)", learn: "懂",
  topics: ["subjunctive"],
  plain: "虚拟语气就是“说不真实/假设/建议要求的事”。成考最爱考三种：①建议要求类 that 从句用 (should)+动词原形；②would rather + 从句用过去式；③对过去的假设用 had done + would have done。",
  points: ["建议/要求/命令类（suggest, insist, order, demand, It is important/necessary that...）→ that 从句用 (should) + 动词原形，should 常省略。", "would rather + 从句 → 用过去式：I would rather you went tomorrow。", "与现在相反：If + 过去式(be 用 were), 主句 would + 原形。", "与过去相反：If + had done, 主句 would have done。", "wish / if only + 过去式(与现在相反) / had done(与过去相反)。"],
  extra: "怎么快速识别？看到 suggest/insist/important/necessary + that，先想“(should)+原形”；看到 If 和过去完成时连用，主句配 would have done。记住：虚拟 = 故意用“错”的时态表示“这不是真的”。",
  examples: [
    { en: "It is important that he (should) be here on time.", zh: "他按时到场很重要。" },
    { en: "If only I knew the answer!", zh: "我要是知道答案就好了！（现在不知道）" },
    { en: "I suggest that we (should) start early.", zh: "我建议我们早点出发。" },
    { en: "If I were you, I would take the job.", zh: "我要是你，就接受这份工作。（我不是你）" },
    { en: "If he had studied harder, he would have passed the exam.", zh: "他当初要是更用功，就通过考试了。（没通过）" },
    { en: "I would rather you came tomorrow.", zh: "我宁愿你明天来。（从句用过去式）" },
  ],
  pitfalls: [
    "suggest 两副面孔：表“建议”→ (should)+原形；表“表明”→ 正常陈述时态：His smile suggests that he is happy.",
    "虚拟条件句里 be 一律用 were：If I were you...（不用 was）",
    "对过去假设的两半别混搭：If he had come（从句）, he would have seen her（主句）——had done 配 would have done",
    "insist 表“坚持要求”用 (should)+原形；表“坚持说(事实)”用陈述语气",
  ],
},
{
  no: 23, title: "倒装 & 强调句", learn: "懂",
  topics: ["inversion", "emphasis", "correlative"],
  plain: "否定词(Never, Not only, Hardly)放句首，句子要“部分倒装”(把助动词提到主语前)。附和别人用 So do I(我也是)/Neither do I(我也不)。强调句：It is/was + 强调部分 + that…。",
  points: ["否定词开头 → 部分倒装：Not only did he..., Never have I...。", "So + 助动词 + 主语 = 我也是（附和肯定）；Neither/Nor + 助动词 + 主语 = 我也不（附和否定）。", "助动词跟着前句时态和主语变：So do I / So did she / So can he。", "强调句：It is/was + 被强调部分 + that(人可用 who)...。判断法：去掉 It is...that 后句子仍完整。", "Here/There 开头全倒装：Here comes the bus."],
  examples: [
    { en: "Not only does he study hard, but he also plays well.", zh: "他不但学习努力，还很会玩。" },
    { en: "Never have I seen such a beautiful place.", zh: "我从没见过这么美的地方。" },
    { en: "— I like English. — So do I.", zh: "——我喜欢英语。——我也是。" },
    { en: "— She can't swim. — Neither can I.", zh: "——她不会游泳。——我也不会。" },
    { en: "It was in the park that I met him.", zh: "我就是在公园里遇见他的。（强调地点）" },
    { en: "Here comes the bus.", zh: "公交车来了。（全倒装）" },
  ],
  pitfalls: [
    "部分倒装 = 只把助动词提前，动词还原：❌ Not only he studies... → ✅ Not only does he study...",
    "So do I(我也是) ≠ So I do(我确实如此)——词序一变意思就变",
    "强调句 vs 定语从句：去掉 It is/was...that 还能读通 → 强调句；不能 → 从句",
  ],
},
{
  no: 24, title: "名词性从句", learn: "懂",
  topics: ["noun-clause"],
  plain: "把一整句话当成一个“名词”放进大句子里(做主语/宾语/表语)。最大的坑：从句一律用陈述语序（不倒装）。表“是否”用 whether/if，但句首、介词后只能用 whether。",
  points: ["宾语从句三件事：①连接词(that/if/whether/wh-词) ②陈述语序 ③时态呼应。", "主句是过去时，从句时态相应后退（said → he was...）；客观真理永远用一般现在时。", "whether 万能，if 只能在动词后：句首、介词后、和 or not 连用 → 只能 whether。", "What he said（他说的话）这类 what 从句可以当主语。"],
  examples: [
    { en: "Whether he will come is not certain.", zh: "他是否会来还不确定。（句首用 whether）" },
    { en: "I don't know where he lives.", zh: "我不知道他住哪儿。（陈述语序！）" },
    { en: "She asked if I could help her.", zh: "她问我能不能帮她。" },
    { en: "The truth is that he didn't finish the work.", zh: "事实是他没完成工作。" },
    { en: "The teacher said the earth goes around the sun.", zh: "老师说地球绕着太阳转。（真理不退时态）" },
  ],
  pitfalls: [
    "❌ I don't know where does he live → ✅ where he lives（从句用陈述语序，这是最高频错误）",
    "❌ If he will come is not certain → ✅ Whether he will come...（句首只能 whether）",
    "时态呼应：He said he *is* coming ❌ → He said he *was* coming ✅（但客观真理例外）",
  ],
},
{
  no: 25, title: "语音 (送分题)", learn: "背+懂",
  topics: ["phonetics-u", "phonetics-g", "phonetics-ow", "phonetics-y", "phonetics-a", "phonetics-ea", "phonetics-i", "phonetics-oo", "phonetics-o", "phonetics-c", "phonetics-k", "phonetics-au", "phonetics-ng", "phonetics-th", "phonetics-e", "phonetics-s", "phonetics-ear"],
  plain: "找“读音不一样”的那个词。靠记字母/字母组合的常见读法规律，比如 a-辅音-e 读 /eɪ/(name)，ea 常见 /iː/ 但 bread 读 /e/。每天跟着🔊读，耳朵熟了就是送分题。",
  points: ["魔法 e：元音+辅音+e，元音读字母本音（name, bike, home）。", "ea 三种读法：/iː/ teach · /e/ bread, ready · /eɪ/ great, break。", "oo 两种：长 /uː/ food, school · 短 /ʊ/ good, book, foot。", "-ed 三种读法：清辅音后 /t/ (helped)、浊辅音和元音后 /d/ (played)、t/d 后 /ɪd/ (wanted)。", "-s 三种读法：/s/ cats · /z/ dogs · /ɪz/ buses。"],
  examples: [
    { en: "name /eɪ/  vs  cat /æ/", zh: "同是 a，读音不同（魔法 e 让 a 读本音）" },
    { en: "teach /iː/  vs  bread /e/  vs  great /eɪ/", zh: "ea 的三种读法，bread/great 是常考例外" },
    { en: "food /uː/  vs  good /ʊ/", zh: "oo 长短两读，book/good/foot 读短音" },
    { en: "helped /t/ · played /d/ · wanted /ɪd/", zh: "-ed 的三种读法" },
    { en: "cats /s/ · dogs /z/ · buses /ɪz/", zh: "-s 的三种读法" },
  ],
  pitfalls: [
    "-ed 读音看前一个音：清辅音(p,k,s,f...)后读 /t/；t 和 d 后才读 /ɪd/——wanted 读 /ɪd/，helped 读 /t/",
    "ch 常读 /tʃ/ (China)，但 school, Christmas, chemistry 里读 /k/",
    "看字母别想当然：great 不读 /iː/，读 /eɪ/；island 的 s 不发音",
  ],
},
{
  no: 26, title: "补全对话 (套路题)", learn: "技巧",
  topics: ["conversation"],
  plain: "考日常对话的礼貌应答。把常见套路背熟就能拿分：道谢答 You're welcome、道歉答 That's all right、邀请答 I'd love to。背记模块里的金句卡就是为这章准备的。",
  points: ["道谢 ↔ You're welcome / Not at all / My pleasure。", "道歉 ↔ That's all right / It doesn't matter / Never mind。", "邀请 ↔ 接受 I'd love to / 婉拒 I'd love to, but...。", "提议帮忙 Would you like...? ↔ Yes, please / No, thanks。", "先读上下句，判断这是在 谢/歉/邀/问路/打电话，再套对应套路。"],
  examples: [
    { en: "— Thank you very much. — You're welcome.", zh: "——非常感谢。——不客气。" },
    { en: "— I'm sorry I'm late. — It doesn't matter.", zh: "——抱歉我迟到了。——没关系。" },
    { en: "— Would you like some coffee? — Yes, please.", zh: "——来点咖啡吗？——好的，谢谢。" },
    { en: "— Shall we go for a walk? — Good idea!", zh: "——我们去散步好吗？——好主意！" },
    { en: "— May I speak to Mr. Wang? — Speaking.", zh: "——请找王先生。——我就是。（电话用语）" },
  ],
  pitfalls: [
    "接电话找本人：说 Speaking. 或 This is Wang speaking.　❌ I am Wang（中式思维）",
    "别人夸你，大方回 Thank you.　❌ No, no, no（英语里不谦虚推辞）",
    "回答 Would you mind...?（介意吗）：不介意要说 No, not at all（No 才是“请便”）",
  ],
},
{
  no: 27, title: "完形填空技巧", learn: "技巧",
  topics: ["cloze"],
  plain: "别一上来就填。先花半分钟通读全文抓大意，再逐空做：每个空都问自己“考的是逻辑、搭配、还是词义？”答案的线索常在前后句，不在本句。",
  points: ["三步法：①通读抓大意(30秒) ②逐空找线索 ③回读检查通不通。", "逻辑题看前后关系：转折 but/however · 因果 so/because · 并列 and/also。", "搭配题回忆固定搭配：help sb with / go for a walk / at seven。", "词义题看上下文：前后句常把答案“说”出来（复现原则）。", "拿不准就代入选项读一遍，最顺的往往是对的。"],
  extra: "四大线索按出现频率排：①逻辑连词 ②固定搭配 ③上下文复现（前文出现过的词或同义词）④生活常识。全篇是一个故事，每个空都要服从“故事讲得通”。",
  examples: [
    { en: "He is poor, but he is happy.", zh: "他穷但快乐。（前后相反 → but）" },
    { en: "It rained hard, so we stayed at home.", zh: "雨很大，所以我们待在家。（因果 → so）" },
    { en: "I have a dog. The ____ is very cute. → dog", zh: "复现原则：空处常常就是前文出现过的词" },
    { en: "She helped me ____ my English. → with", zh: "固定搭配 help sb with sth" },
  ],
  pitfalls: [
    "只盯本句必错：完形的答案常藏在前一句或后一句里，先读完前后再选",
    "四个选项语法都对时，考的是搭配和语义，别纠结语法",
    "选完回读全文，读不顺的空重新想——“通顺”是完形的最高标准",
  ],
},
{
  no: 28, title: "阅读理解策略", learn: "技巧",
  topics: ["reading"],
  plain: "不用全读懂！先看题目和选项，圈出关键词（人名/数字/地点），再回原文找那一句。细节题找原句，主旨题看首尾段。每篇按题型套路来，正确率立刻上一个台阶。",
  points: ["先读题→带着问题回原文定位→就近找答案。", "细节题(Where/When/Why/How many)：回原文找原句，正确项常是原句“换个说法”。", "主旨题(best title / mainly about)：看首段末段和每段第一句。", "推断题(infer/learn from)：答案是原文的合理延伸，但原文没有原话。", "词义猜测题：看这个词前后一两句，常有解释或同义替换。"],
  extra: "时间分配建议：一篇 8 分钟以内。先做细节题（好定位、拿分快），主旨题放最后做——做完细节题你对全文已经有感觉了。",
  examples: [
    { en: "Question: Where does Mr. Green run? → find the place word in the text.", zh: "细节题问哪里，就回原文找地点词。" },
    { en: "What is the best title for the passage?", zh: "主旨题：看首尾段，选能盖住全文的，别选只盖一段的。" },
    { en: "The word “it” in Paragraph 2 refers to ____.", zh: "指代题：往前一两句找最近的名词，代进去读得通就是它。" },
    { en: "We can learn from the passage that ____.", zh: "推断题：选项要有原文依据，但不会是原文原话。" },
  ],
  pitfalls: [
    "凭常识选答案必错：一切以原文为准，哪怕原文说的和常识不同",
    "和原文单词重复率特别高的选项常是陷阱，正确项多半是同义改写",
    "NOT/EXCEPT 题（哪项不对）：逐项回原文核对，三对一错，慢就是快",
  ],
},
];
