/* ============================================================
 * questions-mock-C.js —— 成考专升本《政治》全真模拟卷(五)(六)选择题
 * ------------------------------------------------------------
 * 来源：《政治全真模拟卷及答案解析（六套）》第 17-24 页。
 * 提取每套 1~35 单选题(36~40 为时政，标"略"跳过)。
 * 均标 mock:true，带 module/chapter/topic/difficulty。
 * ============================================================ */

(function(){
var A = [
  { id:"mC-001", mock:true, source:"全真模拟卷五", module:"马哲", chapter:"唯物论", topic:"马哲特征", type:"single", difficulty:1,
    stem:"马克思主义哲学最根本的特点是", options:["革命性","科学性","阶级性","实践性"], answer:3,
    explanation:"实践性是马克思主义哲学区别于其他一切哲学最主要、最根本的特征。", optionNotes:["错：革命性是特征之一，但不是最根本的。","错：科学性不是最根本的区别特征。","错：阶级性不是最根本的理论特征。","对：实践性是最根本、最主要的特征。"], keyPoints:[] },
  { id:"mC-002", mock:true, source:"全真模拟卷五", module:"马哲", chapter:"唯物论", topic:"运动与静止", type:"single", difficulty:1,
    stem:"运动和静止的关系属于", options:["内容和形式的关系","本质和现象的关系","绝对和相对的关系","共性和个性的关系"], answer:2,
    explanation:"运动是绝对的、无条件的，静止是相对的、有条件的，二者是绝对和相对的关系。", optionNotes:["错：不是内容和形式的关系。","错：不是本质和现象的关系。","对：运动绝对、静止相对，是绝对和相对的关系。","错：不是共性和个性的关系。"], keyPoints:[] },
  { id:"mC-003", mock:true, source:"全真模拟卷五", module:"马哲", chapter:"唯物史观", topic:"人的价值", type:"single", difficulty:2,
    stem:"历史唯物主义认为人的价值在于", options:["个人的自我创造和自我实现","个人的自我选择和自由发展","个人主体性的增强和摆脱社会的制约","个人对社会的贡献和社会对个人的尊重"], answer:3,
    explanation:"人的价值根本上在于其创造性实践对他人和社会做出的贡献(社会价值)，同时也包括社会对个人的尊重(个人价值)。", optionNotes:["错：只强调自我实现，忽视了对社会的贡献。","错：只讲自我发展，不是历史唯物主义的观点。","错：人不能摆脱社会制约。","对：贡献与尊重的统一才是人的价值。"], keyPoints:[] },
  { id:"mC-004", mock:true, source:"全真模拟卷五", module:"马哲", chapter:"唯物论", topic:"唯物主义与唯心主义", type:"single", difficulty:1,
    stem:"坚持物质是世界的本原，意识是物质的派生物属于", options:["唯物主义","唯心主义","历史唯物主义","历史唯心主义"], answer:0,
    explanation:"主张物质第一性、意识第二性，物质是世界本原，就是唯物主义的基本立场。", optionNotes:["对：物质第一性即唯物主义。","错：唯心主义主张意识第一性。","错：范围过窄，只是历史领域。","错：历史唯心主义主张精神决定社会。"], keyPoints:[] },
  { id:"mC-005", mock:true, source:"全真模拟卷五", module:"马哲", chapter:"唯物论", topic:"唯物主义与唯心主义", type:"single", difficulty:2,
    stem:"把精神，即人们的感觉、经验、意志等看作是世界的本原是", options:["唯物主义","主观唯心主义","历史唯物主义","客观唯心主义"], answer:1,
    explanation:"把人的感觉、经验、意志当作世界本原，是主观唯心主义(客观唯心主义则把某种客观精神当本原)。", optionNotes:["错：唯物主义主张物质是本原。","对：以人的主观精神为本原是主观唯心主义。","错：不是历史观问题。","错：客观唯心主义以客观精神为本原。"], keyPoints:[] },
  { id:"mC-006", mock:true, source:"全真模拟卷五", module:"马哲", chapter:"唯物论", topic:"马哲来源", type:"single", difficulty:1,
    stem:"马克思主义哲学最直接的理论来源是", options:["德国古典哲学","圣经","空想主义","理想国"], answer:0,
    explanation:"马克思主义哲学最直接的理论来源是德国古典哲学(黑格尔辩证法和费尔巴哈唯物主义)。", optionNotes:["对：德国古典哲学是最直接的理论来源。","错：《圣经》是宗教典籍，不是理论来源。","错：空想社会主义是科学社会主义的来源。","错：《理想国》是古希腊著作，不是直接来源。"], keyPoints:[] },
  { id:"mC-007", mock:true, source:"全真模拟卷五", module:"马哲", chapter:"唯物论", topic:"物质与运动", type:"single", difficulty:1,
    stem:"物质的根本属性是", options:["静止","变化","运动","阶级斗争"], answer:2,
    explanation:"运动是物质的根本属性和存在方式，是标志一切事物变化及其过程的哲学范畴。", optionNotes:["错：静止是相对的，不是根本属性。","错：变化不是哲学上讲的根本属性表述。","对：运动是物质的根本属性。","错：阶级斗争是社会现象，不是物质属性。"], keyPoints:[] },
  { id:"mC-008", mock:true, source:"全真模拟卷五", module:"马哲", chapter:"唯物史观", topic:"社会历史规律", type:"single", difficulty:2,
    stem:"社会历史发展是一个自然历史过程。这句话是说", options:["社会发展与自然界发展一样是纯粹客观的","社会发展与自然界发展一样是有规律的","社会发展不受人的思想动机影响","社会规律与自然规律完全相同"], answer:1,
    explanation:"说社会发展是自然历史过程，是指社会像自然界一样是按客观规律运动发展的。", optionNotes:["错：社会发展有主体参与，不是纯粹客观。","对：社会像自然界一样有规律地发展。","错：社会发展中人的活动有作用。","错：社会规律与自然规律有区别，不完全相同。"], keyPoints:[] },
  { id:"mC-009", mock:true, source:"全真模拟卷五", module:"马哲", chapter:"唯物论", topic:"列宁物质定义", type:"single", difficulty:1,
    stem:"标志客观实在的哲学范畴是", options:["物质","意识","社会存在","社会意识"], answer:0,
    explanation:"物质是标志客观实在的哲学范畴，这种客观实在不依赖于人的感觉而存在。", optionNotes:["对：物质是标志客观实在的范畴。","错：意识是主观的反映。","错：社会存在是社会领域概念，范围窄。","错：社会意识是社会精神现象。"], keyPoints:[] },
  { id:"mC-010", mock:true, source:"全真模拟卷五", module:"毛中特", chapter:"毛泽东思想", topic:"毛泽东思想形成", type:"single", difficulty:2,
    stem:"毛泽东思想形成的主要标志是", options:["新民主主义革命理论的初步提出","《中国社会各阶级的分析》的发表","农村包围城市革命道路的开辟和理论上的初步阐述","着重从思想上建党的理论的阐述"], answer:2,
    explanation:"毛泽东思想形成的主要标志是农村包围城市革命道路的开辟和理论上的初步阐述。", optionNotes:["错：这不是形成的主要标志。","错：该文是萌芽阶段的著作。","对：农村包围城市道路的开辟是形成主要标志。","错：这属于建党学说，不是形成标志。"], keyPoints:[] },
  { id:"mC-011", mock:true, source:"全真模拟卷五", module:"马哲", chapter:"唯物史观", topic:"人民群众是历史创造者", type:"single", difficulty:1,
    stem:"关于历史创造者的问题，历史唯物论认为", options:["人民群众是历史的创造者","英雄人物是历史的创造者","人民群众和英雄人物共同创造了历史","上帝才是真正的历史创造者"], answer:0,
    explanation:"历史唯物主义从社会存在决定社会意识出发，肯定人民群众是历史的创造者。", optionNotes:["对：人民群众是历史的创造者。","错：夸大英雄作用是历史唯心主义。","错：折中说法不符合历史唯物论。","错：上帝创造历史是宗教唯心主义。"], keyPoints:[] },
  { id:"mC-012", mock:true, source:"全真模拟卷五", module:"毛中特", chapter:"毛泽东思想", topic:"群众路线", type:"single", difficulty:1,
    stem:"中国共产党根本的政治路线和组织路线是", options:["解放思想","独立自主","实事求是","群众路线"], answer:3,
    explanation:"把人民群众是历史创造者的原理运用于党的全部活动，形成群众路线，这是党根本的政治路线和组织路线。", optionNotes:["错：解放思想是思想路线内容。","错：独立自主是毛泽东思想活的灵魂之一。","错：实事求是是党的思想路线。","对：群众路线是党根本的政治路线和组织路线。"], keyPoints:[] },
  { id:"mC-013", mock:true, source:"全真模拟卷五", module:"毛中特", chapter:"新民主主义革命", topic:"三大法宝", type:"single", difficulty:2,
    stem:"在下列著作中，毛泽东正式地提出了新民主主义革命的三大法宝的是", options:["《新民主主义论》","《〈共产党人〉发刊词》","《中国革命和中国共产党》","《论联合政府》"], answer:1,
    explanation:"1939年10月，毛泽东在《〈共产党人〉发刊词》中正式提出统一战线、武装斗争、党的建设三大法宝。", optionNotes:["错：《新民主主义论》系统阐述新民主主义理论，非首次提三大法宝。","对：《〈共产党人〉发刊词》正式提出三大法宝。","错：该文分析中国社会和革命对象。","错：《论联合政府》阐述联合政府主张。"], keyPoints:[] },
  { id:"mC-014", mock:true, source:"全真模拟卷五", module:"毛中特", chapter:"邓小平理论", topic:"改革发展稳定", type:"single", difficulty:1,
    stem:"我国社会主义现代化建设的三个重要支点是", options:["改革、发展、稳定","改革、创新、稳定","革命、创新、发展","奋斗、发展、创新"], answer:0,
    explanation:"改革、发展、稳定是我国社会主义现代化建设的三个重要支点，贯穿现代化建设全过程。", optionNotes:["对：改革、发展、稳定是三个重要支点。","错：搭配错误。","错：搭配错误。","错：搭配错误。"], keyPoints:[] },
  { id:"mC-015", mock:true, source:"全真模拟卷五", module:"毛中特", chapter:"邓小平理论", topic:"政府与市场", type:"single", difficulty:2,
    stem:"解决市场秩序不规范的关键是", options:["充分发挥市场在资源配置上的决定作用","完善政府职能","加强宏观调控","处理好政府和市场的关系"], answer:3,
    explanation:"市场秩序不规范等问题，关键在于处理好政府和市场的关系。", optionNotes:["错：只讲市场一面，不全面。","错：只讲政府一面，不全面。","错：宏观调控是手段之一，非关键。","对：关键是处理好政府和市场的关系。"], keyPoints:[] },
  { id:"mC-016", mock:true, source:"全真模拟卷五", module:"毛中特", chapter:"习近平新时代思想", topic:"市场决定性作用", type:"single", difficulty:2,
    stem:"党的十八届三中全会通过的《中共中央关于全面深化改革若干重大问题的决定》中，把市场在资源配置中的“基础性作用”改为", options:["决定性作用","支持性作用","辅助性作用","促进性作用"], answer:0,
    explanation:"十八届三中全会把市场在资源配置中的“基础性作用”改为“决定性作用”。", optionNotes:["对：改为决定性作用。","错：表述错误。","错：表述错误。","错：表述错误。"], keyPoints:[] },
  { id:"mC-017", mock:true, source:"全真模拟卷五", module:"毛中特", chapter:"新民主主义革命", topic:"井冈山土地法", type:"single", difficulty:2,
    stem:"中国共产党领导农民实行土地改革的第一次尝试的标志性文件是", options:["《兴国土地法》","《井冈山土地法》","中共闽西第一次代表大会决议","《中国土地法大纲》"], answer:1,
    explanation:"1928年12月毛泽东制定的《井冈山土地法》，是党史上第一个土地法，标志着领导农民土改的第一次尝试。", optionNotes:["错：《兴国土地法》晚于井冈山土地法。","对：《井冈山土地法》是第一次尝试的标志。","错：不是标志性文件。","错：《中国土地法大纲》是1947年制定。"], keyPoints:[] },
  { id:"mC-018", mock:true, source:"全真模拟卷五", module:"毛中特", chapter:"新民主主义革命", topic:"新旧民主革命区别", type:"single", difficulty:2,
    stem:"区别新民主主义革命与旧民主主义革命的根本标志是", options:["革命指导思想不同","革命领导权不同","革命前途不同","革命对象不同"], answer:1,
    explanation:"革命领导权是决定革命性质的最根本因素，领导阶级不同是新旧民主主义革命的根本区别。", optionNotes:["错：指导思想不同是表现，不是根本标志。","对：领导权不同是根本标志。","错：前途不同不是根本区别。","错：革命对象大体相同。"], keyPoints:[] },
  { id:"mC-019", mock:true, source:"全真模拟卷五", module:"毛中特", chapter:"习近平新时代思想", topic:"新发展理念", type:"single", difficulty:1,
    stem:"引领发展的第一动力是", options:["绿色","创新","改革","开放"], answer:1,
    explanation:"创新是引领发展的第一动力，要把创新摆在国家发展全局的核心位置。", optionNotes:["错：绿色是发展理念之一，非第一动力。","对：创新是引领发展的第一动力。","错：改革是动力，但表述不符。","错：开放是发展理念之一。"], keyPoints:[] },
  { id:"mC-020", mock:true, source:"全真模拟卷五", module:"毛中特", chapter:"习近平新时代思想", topic:"经济总量世界第二", type:"single", difficulty:1,
    stem:"改革开放以来，我国经济持续快速发展，经济总量已跃居世界", options:["一","二","三","四"], answer:1,
    explanation:"改革开放以来我国经济持续快速发展，经济总量已跃居世界第二位。", optionNotes:["错：不是第一。","对：跃居世界第二位。","错：不是第三。","错：不是第四。"], keyPoints:[] },
  { id:"mC-021", mock:true, source:"全真模拟卷五", module:"毛中特", chapter:"初步探索", topic:"论十大关系", type:"single", difficulty:3,
    stem:"毛泽东在《论十大关系》的讲话中，提出中国社会主义建设的基本方针是", options:["解放思想，实事求是","既反保守又反冒进，在综合平衡中稳步前进","把国内外一切积极因素调动起来，为社会主义事业服务","在新的生产关系下保护和发展生产力"], answer:2,
    explanation:"《论十大关系》提出的基本方针是把国内外一切积极因素调动起来，为社会主义事业服务。", optionNotes:["错：这是后来党的思想路线表述。","错：这是经济建设方针，非《论十大关系》基本方针。","对：调动一切积极因素为社会主义服务。","错：表述不符。"], keyPoints:[] },
  { id:"mC-022", mock:true, source:"全真模拟卷五", module:"毛中特", chapter:"新民主主义革命", topic:"半殖民地开端", type:"single", difficulty:1,
    stem:"中国逐步沦为半殖民地半封建社会开始于", options:["鸦片战争","虎门销烟","第二次鸦片战争","八国联军侵华战争"], answer:0,
    explanation:"鸦片战争以后，中国逐步沦为半殖民地半封建社会。", optionNotes:["对：鸦片战争是半殖民地半封建社会的开端。","错：虎门销烟发生在鸦片战争之前。","错：第二次鸦片战争加深了程度，非开端。","错：八国联军侵华使程度进一步加深。"], keyPoints:[] },
  { id:"mC-023", mock:true, source:"全真模拟卷五", module:"毛中特", chapter:"习近平新时代思想", topic:"新时代社会主要矛盾", type:"single", difficulty:1,
    stem:"社会主义初级阶段的主要矛盾是", options:["人民日益增长的美好生活需要和不平衡不充分的发展之间的矛盾","无产阶级同资产阶级之间的矛盾","社会主义道路同资本主义道路之间的矛盾","社会主义国家同帝国主义国家之间的矛盾"], answer:0,
    explanation:"党的十九大指出，新时代我国社会主要矛盾是人民日益增长的美好生活需要和不平衡不充分的发展之间的矛盾。", optionNotes:["对：这是新时代社会主要矛盾。","错：这是旧的阶级矛盾表述。","错：这不是当前主要矛盾。","错：这是国际矛盾，非国内主要矛盾。"], keyPoints:[] },
  { id:"mC-024", mock:true, source:"全真模拟卷五", module:"毛中特", chapter:"邓小平理论", topic:"改革开放", type:"single", difficulty:1,
    stem:"我国进入社会主义现代化建设新时期最鲜明的特征是", options:["以经济建设为中心","改革开放","反腐倡廉","坚持四项基本原则"], answer:1,
    explanation:"改革开放是我国进入社会主义现代化建设新时期最鲜明的特征。", optionNotes:["错：以经济建设为中心是路线内容之一。","对：改革开放是新时期最鲜明的特征。","错：反腐倡廉不是最鲜明特征。","错：四项基本原则是立国之本。"], keyPoints:[] },
  { id:"mC-025", mock:true, source:"全真模拟卷五", module:"毛中特", chapter:"习近平新时代思想", topic:"社会保障目标", type:"single", difficulty:1,
    stem:"我国社会保障制度的基本目标是", options:["保证人们最基本的生活需要","使劳动者生活水平不断提高","保证劳动者充分就业","实现共同富裕"], answer:0,
    explanation:"社会保障的根本目标是满足人们最基本的生活需要，以安定弱势群体的生活。", optionNotes:["对：保证最基本生活需要是基本目标。","错：这是更高层次要求，非基本目标。","错：充分就业是就业政策目标。","错：共同富裕是长远目标。"], keyPoints:[] },
  { id:"mC-026", mock:true, source:"全真模拟卷五", module:"毛中特", chapter:"新民主主义革命", topic:"革命动力", type:"single", difficulty:2,
    stem:"我国改革开放和社会主义现代化建设中人数最多的党的依靠力量是", options:["农民阶级","工人阶级","科学家","资产阶级"], answer:0,
    explanation:"农民既是新民主主义革命的主力军，也是改革开放和现代化建设中人数最多的依靠力量。", optionNotes:["对：农民是人数最多的依靠力量。","错：工人阶级是领导阶级，人数不是最多。","错：科学家不是人数最多的依靠力量。","错：资产阶级不是党的依靠力量。"], keyPoints:[] },
  { id:"mC-027", mock:true, source:"全真模拟卷五", module:"毛中特", chapter:"邓小平理论", topic:"一国两制", type:"single", difficulty:1,
    stem:"中英两国政府举行香港政权交接仪式在", options:["1979年2月","1997年7月","1990年4月","1993年3月"], answer:1,
    explanation:"1997年7月1日，中英两国政府举行香港政权交接仪式，中国对香港恢复行使主权。", optionNotes:["错：年份错误。","对：1997年7月香港回归。","错：年份错误。","错：年份错误。"], keyPoints:[] },
  { id:"mC-028", mock:true, source:"全真模拟卷五", module:"毛中特", chapter:"习近平新时代思想", topic:"五位一体", type:"single", difficulty:1,
    stem:"中国特色社会主义事业总体布局是", options:["两步走战略","“四个全面”","“四个自信”","“五位一体”"], answer:3,
    explanation:"新时代中国特色社会主义事业总体布局是“五位一体”，战略布局是“四个全面”。", optionNotes:["错：两步走是战略安排，不是总体布局。","错：“四个全面”是战略布局。","错：“四个自信”不是总体布局。","对：总体布局是“五位一体”。"], keyPoints:[] },
  { id:"mC-029", mock:true, source:"全真模拟卷五", module:"毛中特", chapter:"习近平新时代思想", topic:"三者有机统一", type:"single", difficulty:2,
    stem:"发展社会主义民主政治，最根本的就是要", options:["坚持中国共产党的领导","坚持人民当家作主","坚持依法治国与党的领导的有机统一","坚持党的领导、人民当家作主和依法治国的有机统一"], answer:3,
    explanation:"党的领导、人民当家作主和依法治国三者有机统一，是发展社会主义民主政治最根本的要求。", optionNotes:["错：只讲党的领导一方面。","错：只讲人民当家作主一方面。","错：缺了人民当家作主，不完整。","对：三者有机统一才是最根本要求。"], keyPoints:[] },
  { id:"mC-030", mock:true, source:"全真模拟卷五", module:"毛中特", chapter:"邓小平理论", topic:"一国两制", type:"single", difficulty:1,
    stem:"“一国两制”构想的提出，是从解决", options:["台湾问题开始的","香港问题开始的","澳门问题开始的","香港和澳门问题开始的"], answer:0,
    explanation:"“一国两制”是邓小平为解决台湾问题最先提出的，后来运用于解决香港、澳门问题。", optionNotes:["对：最初为解决台湾问题提出。","错：香港问题是后来运用。","错：澳门问题是后来运用。","错：不是从港澳问题开始。"], keyPoints:[] },
  { id:"mC-031", mock:true, source:"全真模拟卷五", module:"毛中特", chapter:"习近平新时代思想", topic:"基本方略", type:"single", difficulty:2,
    stem:"党的十九大报告提出，坚持全面依法治国是习近平新时代中国特色社会主义思想的一条", options:["基本方针","基本政策","基本方略","指导思想"], answer:2,
    explanation:"党的十九大把新时代中国特色社会主义基本方略概括为“十四个坚持”，坚持全面依法治国是其中之一。", optionNotes:["错：表述错误。","错：表述错误。","对：属于“十四个坚持”的基本方略之一。","错：不是指导思想的表述。"], keyPoints:[] },
  { id:"mC-032", mock:true, source:"全真模拟卷五", module:"毛中特", chapter:"习近平新时代思想", topic:"最大的民生", type:"single", difficulty:1,
    stem:"最大的民生是", options:["就业","医疗","教育","基础设施"], answer:0,
    explanation:"就业是最大的民生，关系群众切身利益和社会稳定。", optionNotes:["对：就业是最大的民生。","错：医疗是重要民生，但不是“最大”。","错：教育是民生之一。","错：基础设施不是民生表述重点。"], keyPoints:[] },
  { id:"mC-033", mock:true, source:"全真模拟卷五", module:"毛中特", chapter:"习近平新时代思想", topic:"民生之基", type:"single", difficulty:1,
    stem:"人民幸福之基、社会和谐之本是", options:["政治","生态","文化","民生"], answer:3,
    explanation:"民生是人民幸福之基、社会和谐之本，要在发展中保障和改善民生。", optionNotes:["错：政治不是这一表述。","错：生态是美丽中国要求。","错：文化是精神层面。","对：民生是人民幸福之基、社会和谐之本。"], keyPoints:[] },
  { id:"mC-034", mock:true, source:"全真模拟卷五", module:"毛中特", chapter:"大国外交", topic:"人类命运共同体", type:"single", difficulty:1,
    stem:"中国特色大国外交要推动构建新型国际关系，推动构建", options:["全球共同体","全人类共同体","人类命运共同体","人类社会共同体"], answer:2,
    explanation:"新时代中国特色大国外交推动构建新型国际关系，推动构建人类命运共同体。", optionNotes:["错：表述错误。","错：表述错误。","对：推动构建人类命运共同体。","错：表述错误。"], keyPoints:[] },
  { id:"mC-035", mock:true, source:"全真模拟卷五", module:"马哲", chapter:"认识论", topic:"真理客观性", type:"single", difficulty:2,
    stem:"真理的客观性决定了真理的", options:["一元性","斗争性","相对性","绝对性"], answer:0,
    explanation:"真理的内容是客观的，同一对象的真理只有一个，所以真理的客观性决定了真理的一元性。", optionNotes:["对：客观性决定真理的一元性。","错：斗争性是矛盾属性，与此无关。","错：相对性讲真理的近似、有限。","错：绝对性讲真理的确定、无条件。"], keyPoints:[] },

  { id:"mC-036", mock:true, source:"全真模拟卷六", module:"马哲", chapter:"唯物论", topic:"马哲自然科学基础", type:"single", difficulty:1,
    stem:"马克思主义哲学产生的最主要的自然科学基础是", options:["地质学和胚胎学","动植物生理学和有机化学","机械力学","细胞学说、能量守恒与转化定律、生物进化论"], answer:3,
    explanation:"细胞学说、能量守恒与转化定律、生物进化论三大发现，为马克思主义哲学产生提供了自然科学基础。", optionNotes:["错：不是三大发现。","错：不是三大发现。","错：机械力学不是主要基础。","对：三大发现是最主要的自然科学基础。"], keyPoints:[] },
  { id:"mC-037", mock:true, source:"全真模拟卷六", module:"马哲", chapter:"唯物论", topic:"列宁物质定义", type:"single", difficulty:1,
    stem:"物质的唯一特性是", options:["不可入性","具有体积和重量","运动","客观实在性"], answer:3,
    explanation:"客观实在性是物质的普遍本质和唯一特性；运动是物质的根本属性和存在方式。", optionNotes:["错：不可入性是具体物质属性。","错：体积重量是具体物质属性。","错：运动是根本属性，不是唯一特性。","对：客观实在性是物质的唯一特性。"], keyPoints:[] },
  { id:"mC-038", mock:true, source:"全真模拟卷六", module:"马哲", chapter:"唯物论", topic:"物质概念", type:"single", difficulty:2,
    stem:"“物，物质无非是各种物的总和，而这个概念就是从这一总和中抽象出来的”出自", options:["马克思","毛泽东","列宁","恩格斯"], answer:3,
    explanation:"这句关于物质概念的论述出自恩格斯，是对物质概念的初步概括。", optionNotes:["错：不是马克思。","错：不是毛泽东。","错：不是列宁。","对：这句话出自恩格斯。"], keyPoints:[] },
  { id:"mC-039", mock:true, source:"全真模拟卷六", module:"马哲", chapter:"辩证法", topic:"矛盾普遍性与特殊性", type:"single", difficulty:2,
    stem:"白菜、芹菜、油菜、菠菜等同蔬菜的关系属于", options:["部分与整体的关系","个别与一般的关系","现象与本质的关系","形式与内容的关系"], answer:1,
    explanation:"具体蔬菜是个别，“蔬菜”是一般；共性寓于个性之中，这是个别与一般(特殊性与普遍性)的关系。", optionNotes:["错：不是部分与整体，白菜不是蔬菜的一部分。","对：是个别与一般的关系。","错：不是现象与本质。","错：不是形式与内容。"], keyPoints:[] },
  { id:"mC-040", mock:true, source:"全真模拟卷六", module:"马哲", chapter:"辩证法", topic:"辩证否定观", type:"single", difficulty:2,
    stem:"扬弃就是", options:["事物发展环节和联系环节的统一","新事物对旧事物的绝对肯定","事物发展的非连续性","新事物对旧事物的彻底否定"], answer:0,
    explanation:"扬弃即既克服又保留、既批判又继承，是发展环节和联系环节的统一。", optionNotes:["对：扬弃是发展环节和联系环节的统一。","错：不是绝对肯定。","错：否定还包含连续性(保留)。","错：不是彻底抛弃，而是有保留。"], keyPoints:[] },
  { id:"mC-041", mock:true, source:"全真模拟卷六", module:"马哲", chapter:"辩证法", topic:"辩证法总特征", type:"single", difficulty:1,
    stem:"唯物辩证法的总特征是", options:["物质决定意识的观点","联系和发展的观点","实践第一的观点","对立统一的观点"], answer:1,
    explanation:"物质世界是普遍联系和永恒发展的，联系和发展的观点是唯物辩证法的总特征。", optionNotes:["错：这是唯物论观点。","对：联系和发展是唯物辩证法总特征。","错：这是认识论观点。","错：对立统一是辩证法的实质和核心，非总特征。"], keyPoints:[] },
  { id:"mC-042", mock:true, source:"全真模拟卷六", module:"马哲", chapter:"唯物论", topic:"规律客观性", type:"single", difficulty:1,
    stem:"规律最根本的特点是", options:["客观性","相对性","稳定性","普遍性"], answer:0,
    explanation:"规律是物质运动内在的、必然的、本质的联系，客观性是规律最根本的特点。", optionNotes:["对：客观性是规律最根本的特点。","错：相对性不是最根本特点。","错：稳定性是特点之一，非最根本。","错：普遍性是特点之一，非最根本。"], keyPoints:[] },
  { id:"mC-043", mock:true, source:"全真模拟卷六", module:"马哲", chapter:"唯物论", topic:"意识起源", type:"single", difficulty:2,
    stem:"实践活动不但形成了社会存在，而且还创造了地球上“最美丽的花朵”——", options:["感觉","概念","理论","意识"], answer:3,
    explanation:"实践创造了社会存在，也创造了地球上“最美丽的花朵”——意识，使世界二重化为客观世界与主观世界。", optionNotes:["错：感觉只是意识的低级形式。","错：概念是理性认识形式。","错：理论是系统化的认识。","对：“最美丽的花朵”指意识。"], keyPoints:[] },
  { id:"mC-044", mock:true, source:"全真模拟卷六", module:"马哲", chapter:"唯物史观", topic:"上层建筑", type:"single", difficulty:2,
    stem:"上层建筑是推动还是阻碍社会的发展取决于", options:["它所服务的经济基础的性质","它是否同自己的经济基础相适合","它本身的各个部分是否协调","它是否与经济基础存在着矛盾"], answer:0,
    explanation:"上层建筑对经济基础有能动反作用，它是推动还是阻碍社会发展，最终取决于所服务的经济基础的性质。", optionNotes:["对：取决于所服务经济基础的性质。","错：是否适合影响作用大小，非根本。","错：内部协调不是决定因素。","错：这不是决定因素。"], keyPoints:[] },
  { id:"mC-045", mock:true, source:"全真模拟卷六", module:"毛中特", chapter:"党的领导", topic:"政治体制", type:"single", difficulty:1,
    stem:"政治制度的具体表现和实现形式是", options:["政治体制","政治方针","政治政策","政治大纲"], answer:0,
    explanation:"政治体制是政治制度的具体表现和实现形式，主要指党和国家的领导制度、组织制度、工作制度等。", optionNotes:["对：政治体制是政治制度的具体表现和实现形式。","错：政治方针不是这一含义。","错：政治政策不是这一含义。","错：政治大纲不是这一含义。"], keyPoints:[] },
  { id:"mC-046", mock:true, source:"全真模拟卷六", module:"毛中特", chapter:"三个代表", topic:"依法治国提出", type:"single", difficulty:2,
    stem:"党的十三届四中全会以后，江泽民进一步继承和发展了邓小平关于加强社会主义法制建设的思想，并于1996年2月提出了", options:["一国两制","三个代表","科学发展观","依法治国"], answer:3,
    explanation:"江泽民继承发展邓小平法制建设思想，1996年2月提出“依法治国”思想。", optionNotes:["错：一国两制由邓小平提出。","错：三个代表提出时间不符。","错：科学发展观是胡锦涛提出。","对：1996年2月提出依法治国。"], keyPoints:[] },
  { id:"mC-047", mock:true, source:"全真模拟卷六", module:"毛中特", chapter:"党的领导", topic:"政党制度", type:"single", difficulty:1,
    stem:"在我国的政党制度中，中国共产党是执政党，民主党派是", options:["执政党","在野党","参政党","反对党"], answer:2,
    explanation:"我国实行中国共产党领导的多党合作制度，中国共产党是执政党，民主党派是参政党。", optionNotes:["错：执政党是中国共产党。","错：民主党派不是在野党。","对：民主党派是参政党。","错：不是反对党。"], keyPoints:[] },
  { id:"mC-048", mock:true, source:"全真模拟卷六", module:"毛中特", chapter:"党的领导", topic:"国体", type:"single", difficulty:1,
    stem:"人民民主专政是我国的", options:["国体","政体","国策","制度"], answer:0,
    explanation:"人民民主专政是我国的国体(国家性质)，人民代表大会制度是我国的政体。", optionNotes:["对：人民民主专政是我国的国体。","错：政体是人民代表大会制度。","错：国策是基本政策，如计划生育。","错：制度表述不准确。"], keyPoints:[] },
  { id:"mC-049", mock:true, source:"全真模拟卷六", module:"毛中特", chapter:"新民主主义革命", topic:"新民主主义革命总路线", type:"single", difficulty:2,
    stem:"毛泽东完整地概括了中国共产党在新民主主义革命阶段的总路线和总政策的会议是", options:["八七会议","中共四大","中共七大","1948年晋绥干部会议"], answer:3,
    explanation:"1948年4月，毛泽东在《在晋绥干部会议上的讲话》中完整概括了新民主主义革命阶段的总路线和总政策。", optionNotes:["错：八七会议确立土地革命和武装斗争方针。","错：中共四大不是。","错：中共七大确立毛泽东思想为指导。","对：1948年晋绥干部会议上完整概括总路线。"], keyPoints:[] },
  { id:"mC-050", mock:true, source:"全真模拟卷六", module:"毛中特", chapter:"新民主主义革命", topic:"三大经济纲领", type:"single", difficulty:2,
    stem:"毛泽东明确提出了新民主主义的三大经济纲领的文件", options:["《目前形势和我们的任务》","《论联合政府》","《在中共七届二中全会上的讲话》","《新民主主义论》"], answer:0,
    explanation:"1947年毛泽东在《目前形势和我们的任务》中明确提出新民主主义三大经济纲领。", optionNotes:["对：《目前形势和我们的任务》提出三大经济纲领。","错：《论联合政府》非此文件。","错：七届二中全会讲党的工作重心转移。","错：《新民主主义论》系统阐述理论。"], keyPoints:[] },
  { id:"mC-051", mock:true, source:"全真模拟卷六", module:"毛中特", chapter:"习近平新时代思想", topic:"民主政治本质", type:"single", difficulty:1,
    stem:"中国特色社会主义民主政治的本质要求是", options:["人民当家作主","共产党的领导","依法治国","人人平等"], answer:0,
    explanation:"人民当家作主是中国特色社会主义民主政治的本质要求。", optionNotes:["对：人民当家作主是本质要求。","错：党的领导是根本保证。","错：依法治国是基本方式。","错：人人平等不是这一表述。"], keyPoints:[] },
  { id:"mC-052", mock:true, source:"全真模拟卷六", module:"毛中特", chapter:"习近平新时代思想", topic:"实体经济", type:"single", difficulty:1,
    stem:"“一国经济的立身之本，财富创造的根本源泉，国家强盛的重要支柱”指的是", options:["实体经济","虚拟经济","教育","科技创新"], answer:0,
    explanation:"实体经济是一国经济的立身之本、财富创造的根本源泉、国家强盛的重要支柱。", optionNotes:["对：指实体经济。","错：虚拟经济要服务于实体经济。","错：教育不是这一表述。","错：科技创新不是这一表述。"], keyPoints:[] },
  { id:"mC-053", mock:true, source:"全真模拟卷六", module:"毛中特", chapter:"习近平新时代思想", topic:"科技创新", type:"single", difficulty:1,
    stem:"国家发展全局的核心位置是", options:["人才","教育","科技创新","经济发展"], answer:2,
    explanation:"科技创新是提高社会生产力和综合国力的战略支撑，必须摆在国家发展全局的核心位置。", optionNotes:["错：人才是重要资源，非此表述。","错：教育优先发展，非此表述。","对：科技创新摆在国家发展全局核心位置。","错：经济发展是中心，非此表述。"], keyPoints:[] },
  { id:"mC-054", mock:true, source:"全真模拟卷六", module:"毛中特", chapter:"习近平新时代思想", topic:"高质量发展", type:"single", difficulty:1,
    stem:"我国经济已由高速增长阶段转向", options:["低速发展阶段","高质量发展阶段","中低速发展阶段","飞速发展阶段"], answer:1,
    explanation:"我国经济已由高速增长阶段转向高质量发展阶段。", optionNotes:["错：不是低速发展。","对：转向高质量发展阶段。","错：不是中低速发展。","错：不是飞速发展。"], keyPoints:[] },
  { id:"mC-055", mock:true, source:"全真模拟卷六", module:"毛中特", chapter:"习近平新时代思想", topic:"新发展理念", type:"single", difficulty:2,
    stem:"中国特色社会主义的本质要求是", options:["开放","协调","绿色","共享"], answer:3,
    explanation:"共享是中国特色社会主义的本质要求，坚持共享发展着力增进人民福祉。", optionNotes:["错：开放是发展理念之一。","错：协调是发展理念之一。","错：绿色是发展理念之一。","对：共享是中国特色社会主义的本质要求。"], keyPoints:[] },
  { id:"mC-056", mock:true, source:"全真模拟卷六", module:"毛中特", chapter:"习近平新时代思想", topic:"经济体制改革", type:"single", difficulty:2,
    stem:"党的十九大报告提出，经济体制改革的重点是", options:["完善产权制度和要素市场化配置","体制机制改革","刺激消费","工业强国"], answer:0,
    explanation:"党的十九大提出，经济体制改革必须以完善产权制度和要素市场化配置为重点。", optionNotes:["对：重点是完善产权制度和要素市场化配置。","错：表述宽泛，非重点。","错：刺激消费不是重点。","错：工业强国不是重点。"], keyPoints:[] },
  { id:"mC-057", mock:true, source:"全真模拟卷六", module:"马哲", chapter:"辩证法", topic:"辩证否定观", type:"single", difficulty:1,
    stem:"辩证否定的实质是", options:["发展","创新","批评","扬弃"], answer:3,
    explanation:"辩证否定的实质是“扬弃”，即既克服其消极因素又保留其积极因素。", optionNotes:["错：发展是结果，不是实质。","错：创新不是辩证否定的实质。","错：批评不是实质。","对：辩证否定的实质是扬弃。"], keyPoints:[] },
  { id:"mC-058", mock:true, source:"全真模拟卷六", module:"毛中特", chapter:"邓小平理论", topic:"三个有利于", type:"single", difficulty:2,
    stem:"“三个有利于”标准中，最根本的是", options:["人民生活标准","综合国力标准","生产力标准","实践标准"], answer:2,
    explanation:"“三个有利于”最根本的标准是生产力标准，生产力发展是增强国力、提高生活水平的基础。", optionNotes:["错：人民生活标准以生产力为基础。","错：综合国力标准以生产力为基础。","对：最根本的是生产力标准。","错：实践标准不是“三个有利于”内容。"], keyPoints:[] },
  { id:"mC-059", mock:true, source:"全真模拟卷六", module:"马哲", chapter:"辩证法", topic:"联系", type:"single", difficulty:1,
    stem:"事物内部各要素之间和事物之间相互影响、相互制约、相互作用的关系是", options:["发展","矛盾","联系","运动"], answer:2,
    explanation:"联系是指事物内部各要素之间及事物之间相互影响、相互制约、相互作用的关系。", optionNotes:["错：发展是前进上升的运动。","错：矛盾是对立统一关系。","对：这就是联系的定义。","错：运动是物质的存在方式。"], keyPoints:[] },
  { id:"mC-060", mock:true, source:"全真模拟卷六", module:"毛中特", chapter:"邓小平理论", topic:"国有经济", type:"single", difficulty:2,
    stem:"在我国现阶段的所有制结构中，国有经济对经济发展起主导作用。这种主导作用主要体现在", options:["在社会总资产中占量的优势","在所有制结构中占主体地位","对国民经济发展的控制力上","对非公有制经济的领导上"], answer:2,
    explanation:"国有经济的主导作用主要体现在对国民经济发展的控制力上，而非数量优势。", optionNotes:["错：不主要靠量的优势。","错：占主体地位的是公有制整体，非此表述。","对：主导作用体现在控制力上。","错：不是对非公经济的领导。"], keyPoints:[] },
  { id:"mC-061", mock:true, source:"全真模拟卷六", module:"毛中特", chapter:"习近平新时代思想", topic:"新发展理念", type:"single", difficulty:1,
    stem:"发展是解决我国一切问题的基础和关键，发展必须坚定不移贯彻的发展理念是", options:["创新、统筹、绿色、开放、共享","创新、统筹、生态、开放、共享","创新、协调、绿色、开放、共享","创新、协调、生态、开放、共享"], answer:2,
    explanation:"必须坚定不移贯彻创新、协调、绿色、开放、共享的新发展理念。", optionNotes:["错：应是协调，不是统筹。","错：应是协调、绿色，不是统筹、生态。","对：创新、协调、绿色、开放、共享。","错：应是绿色，不是生态。"], keyPoints:[] },
  { id:"mC-062", mock:true, source:"全真模拟卷六", module:"毛中特", chapter:"大国外交", topic:"时代主题", type:"single", difficulty:2,
    stem:"当代世界的和平问题是指", options:["在较长时期内防止新的世界大战的爆发是可能的","人类消灭了包括局部战争在内的一切战争","以和平共处五项原则为准则处理国与国之间的关系","实现国际社会广泛的、公正的和平合作"], answer:0,
    explanation:"和平问题是指在较长时期内维护世界和平、防止新的世界大战的问题。", optionNotes:["对：指较长时期内防止新的世界大战。","错：局部战争仍然存在，没有消灭。","错：这是处理国际关系的原则，非和平问题含义。","错：这是目标表述，非和平问题定义。"], keyPoints:[] },
  { id:"mC-063", mock:true, source:"全真模拟卷六", module:"毛中特", chapter:"邓小平理论", topic:"四项基本原则", type:"single", difficulty:1,
    stem:"四项基本原则是建设中国特色社会主义的", options:["政治保证","法律保证","组织保证","思想保证"], answer:0,
    explanation:"坚持四项基本原则是立国之本，是建设中国特色社会主义的政治保证。", optionNotes:["对：四项基本原则是政治保证。","错：不是法律保证。","错：不是组织保证。","错：不是思想保证。"], keyPoints:[] },
  { id:"mC-064", mock:true, source:"全真模拟卷六", module:"毛中特", chapter:"邓小平理论", topic:"人民利益", type:"single", difficulty:2,
    stem:"我国社会主义建设发展战略的出发点和归宿是", options:["四个现代化","经济发展","人民利益","可持续发展"], answer:2,
    explanation:"我国社会主义建设发展战略的出发点和归宿是人民利益。", optionNotes:["错：四个现代化是目标之一，非出发点归宿。","错：经济发展是手段。","对：出发点和归宿是人民利益。","错：可持续发展是发展要求。"], keyPoints:[] },
  { id:"mC-065", mock:true, source:"全真模拟卷六", module:"毛中特", chapter:"邓小平理论", topic:"市场经济体制", type:"single", difficulty:1,
    stem:"我国经济体制改革的目标是", options:["建立和完善市场自发调节的经济体制","建立和完善有计划的商品经济体制","建立和完善社会主义市场经济体制","建立和完善指导性计划的经济体制"], answer:2,
    explanation:"1992年党的十四大明确提出，我国经济体制改革的目标是建立社会主义市场经济体制。", optionNotes:["错：不是放任的市场自发调节。","错：不是有计划的商品经济。","对：建立和完善社会主义市场经济体制。","错：不是指导性计划经济体制。"], keyPoints:[] },
  { id:"mC-066", mock:true, source:"全真模拟卷六", module:"马哲", chapter:"唯物论", topic:"物质统一性", type:"single", difficulty:2,
    stem:"马克思主义的基石是", options:["实事求是","世界的物质统一性原理","矛盾的观点","历史唯物主义"], answer:1,
    explanation:"世界的物质统一性原理是马克思主义的基石，有助于树立唯物主义科学世界观。", optionNotes:["错：实事求是是党的思想路线。","对：世界的物质统一性原理是马克思主义的基石。","错：矛盾观点是辩证法核心，非基石。","错：历史唯物主义是重要组成部分，非基石表述。"], keyPoints:[] },
  { id:"mC-067", mock:true, source:"全真模拟卷六", module:"毛中特", chapter:"邓小平理论", topic:"一国两制", type:"single", difficulty:2,
    stem:"台湾与大陆和平统一后，台湾特别行政区可以享有比香港、澳门特别行政区更高度的自治权利，主要体现在", options:["拥有行政管理权","拥有立法权、独立的司法权和终审权","可以实行单独的财政预算","可以保留自己的军队"], answer:3,
    explanation:"按“一国两制”，台湾特别行政区还可以保留自己的军队，中央政府不派军队去台湾，这是其更高度自治的体现。", optionNotes:["错：行政管理权港澳也有。","错：立法权、司法权、终审权港澳也享有。","错：单独财政预算不是更高度自治的特殊体现。","对：保留自己的军队是更高度自治的体现。"], keyPoints:[] },
  { id:"mC-068", mock:true, source:"全真模拟卷六", module:"马哲", chapter:"唯物论", topic:"时间不可逆", type:"single", difficulty:2,
    stem:"“一寸光阴一寸金，寸金难买寸光阴”这样的至理名言，说明了时间的", options:["绝对性","不可逆性","相对性","客观性"], answer:1,
    explanation:"时间具有一维性，一去不复返，这句名言说明时间的不可逆性，要人们珍惜时间。", optionNotes:["错：不是讲绝对性。","对：说明时间的不可逆性(一维性)。","错：不是讲相对性。","错：不是讲客观性。"], keyPoints:[] },
  { id:"mC-069", mock:true, source:"全真模拟卷六", module:"毛中特", chapter:"习近平新时代思想", topic:"人民立场", type:"single", difficulty:1,
    stem:"党的一切工作的最高标准是", options:["维护最广大人民的根本利益","发展先进生产力","建立先进生产关系","发展先进文化"], answer:0,
    explanation:"党的一切工作以人民利益为出发点和落脚点，最高标准是维护最广大人民的根本利益。", optionNotes:["对：最高标准是维护最广大人民的根本利益。","错：发展生产力是重要任务，非最高标准。","错：不是这一表述。","错：发展先进文化非最高标准。"], keyPoints:[] },
  { id:"mC-070", mock:true, source:"全真模拟卷六", module:"毛中特", chapter:"习近平新时代思想", topic:"教育强国", type:"single", difficulty:1,
    stem:"中华民族伟大复兴的基础工程是建设", options:["经济强国","教育强国","政治强国","文化强国"], answer:1,
    explanation:"党的十九大指出，建设教育强国是中华民族伟大复兴的基础工程，必须把教育事业放在优先位置。", optionNotes:["错：不是这一表述。","对：教育强国是中华民族伟大复兴的基础工程。","错：不是这一表述。","错：文化强国是重要目标，非基础工程表述。"], keyPoints:[] }
];
window.QUESTION_BANK = (window.QUESTION_BANK||[]).concat(A);
})();
