/* ============================================================================
 * data-roots.js —— 音节切分 + 词根拆解
 *
 * 为什么是手写而不是算法：
 *   先试过规则算法，输出是 pro·ces·s / ex·clu·de / e·sca·la·te / settl·e·ment
 *   —— 全是错的。英文音节切分靠规则做不准，给零基础的人看错的只会更糊。
 *   词库只有 158 个词，逐个手写核对，全对才有意义。
 *
 * syl   音节切分，按美式词典的断词位置
 * parts 词根拆解 [[片段, 意思], ...]  —— 只写真有词源可讲的
 * lit   字面意思（把 parts 串起来）→ 帮你从字面推到实际意思
 * kin   同根词，用来举一反三 [[词, 字面→意思], ...]
 * 日耳曼来源的短词（shop / ship / hook / deck）没有可拆的词根，只给 syl。
 * ==========================================================================*/
window.ROOTS = {
/* ---------- 广告投放 ---------- */
w001:{syl:"bud·get"},
w002:{syl:"spend"},
w003:{syl:"cre·a·tive",parts:[["creat","创造 (creare)"],["-ive","有…性质的"]],lit:"有创造性的",
  kin:[["create","创造"],["creator","创造的人 → 达人"],["recreation","再创造 → 娱乐"]]},
w004:{syl:"ex·clude",parts:[["ex-","向外"],["clude","关闭 (claudere)"]],lit:"关到外面去",
  kin:[["include","关进来 → 包含"],["conclude","全部关上 → 下结论"],["seclude","关起来 → 隔离"]]},
w005:{syl:"pro·mo code",parts:[["pro-","向前"],["mo(te)","推动 (movere)"]],lit:"向前推 → 推广",
  kin:[["promote","往前推 → 推广/晋升"],["motion","动作"],["remote","移开的 → 遥远的"]]},
w006:{syl:"learn·ing phase"},
w007:{syl:"burn bud·get"},
w008:{syl:"de·liv·er·y",parts:[["de-","离开"],["liver","自由 (liber)"],["-y","名词"]],lit:"放走、脱手",
  kin:[["deliver","交付/送达"],["liberty","自由"],["liberal","自由的"]]},
w009:{syl:"brand ads"},
w010:{syl:"au·di·ence",parts:[["audi","听 (audire)"],["-ence","名词"]],lit:"听的人",
  kin:[["audio","声音的"],["audit","听账 → 审计"],["auditorium","听的地方 → 礼堂"]]},
w011:{syl:"scale up"},
w012:{syl:"top up"},
w013:{syl:"bal·ance",parts:[["bi-","二"],["lanc","秤盘 (lanx)"]],lit:"两个秤盘 → 平衡",
  kin:[["balanced","平衡的"],["imbalance","不平衡"]]},
w014:{syl:"place·ment",parts:[["place","位置"],["-ment","名词"]],lit:"放置的位置",
  kin:[["placed","放好的"],["replace","再放 → 替换"]]},
w015:{syl:"ad group"},
w016:{syl:"cam·paign",parts:[["camp","野地 (campus)"],["-aign","法语后缀"]],lit:"在野地上的行动 → 战役",
  kin:[["camp","营地"],["campus","校园"]]},
w017:{syl:"bid"},
w018:{syl:"tar·get·ing"},
w019:{syl:"white·list"},
w020:{syl:"pause"},
/* ---------- 数据指标 ---------- */
w021:{syl:"R·O·I",parts:[["R","Return 回报"],["O","On 相对于"],["I","Investment 投入"]],lit:"投入换回多少",
  kin:[["ROAS","Return On Ad Spend，广告口径的同一个东西"]]},
w022:{syl:"G·M·V",parts:[["G","Gross 总的"],["M","Merchandise 商品"],["V","Value 价值"]],lit:"商品成交总额（含退款）",
  kin:[["NMV","Net 净的 → 扣掉退款"]]},
w023:{syl:"N·M·V",parts:[["N","Net 净的"],["M","Merchandise 商品"],["V","Value 价值"]],lit:"扣掉退款后的成交",
  kin:[["GMV","Gross 总的 → 含退款"]]},
w024:{syl:"ba·sis",parts:[["bas","底、基 (basis)"]],lit:"底子 → 算法的底子 → 口径",
  kin:[["base","基础"],["basic","基本的"],["basement","地下室"]]},
w025:{syl:"at·tri·bu·tion",parts:[["at-","向"],["tribut","分配、给 (tribuere)"],["-ion","名词"]],lit:"分派给谁",
  kin:[["contribute","一起给 → 贡献"],["distribute","分开给 → 分发"],["tribute","进贡"]]},
w026:{syl:"re·fund rate",parts:[["re-","回"],["fund","资金"]],lit:"钱退回去",
  kin:[["fund","资金"],["funding","出资"],["refundable","可退的"]]},
w027:{syl:"C·T·R",parts:[["C","Click 点击"],["T","Through 通过"],["R","Rate 率"]],lit:"点进去的比例"},
w028:{syl:"C·P·M",parts:[["C","Cost 成本"],["P","Per 每"],["M","Mille 千 (拉丁 mille)"]],lit:"每一千次曝光的成本",
  kin:[["CPC","Per Click 每次点击"],["million","百万"],["mile","罗马的一千步 → 英里"]]},
w029:{syl:"con·ver·sion",parts:[["con-","完全"],["vers","转 (vertere)"],["-ion","名词"]],lit:"完全转过来",
  kin:[["convert","转化"],["reverse","转回去 → 反转"],["version","转出来的样子 → 版本"],["divert","转开 → 转移"]]},
w030:{syl:"A·O·V",parts:[["A","Average 平均"],["O","Order 订单"],["V","Value 价值"]],lit:"平均每单多少钱"},
w031:{syl:"week o·ver week"},
w032:{syl:"im·pres·sions",parts:[["im-","进去"],["press","压 (premere)"],["-ion","名词"]],lit:"压进去 → 留下印记",
  kin:[["express","压出来 → 表达"],["depress","往下压 → 压低"],["compress","压紧 → 压缩"],["pressure","压力"]]},
w033:{syl:"share"},
w034:{syl:"a·nom·a·ly",parts:[["a-","不"],["nom","规律、法则 (nomos)"],["-aly","名词"]],lit:"不合规律的 → 异常",
  kin:[["anonymous","没有名字的"],["autonomy","自己定规则 → 自治"]]},
w035:{syl:"bench·mark",parts:[["bench","工作台"],["mark","刻痕"]],lit:"工作台上的刻痕 → 量东西的基准线"},
w036:{syl:"mar·ket-wide"},
w037:{syl:"hy·poth·e·sis",parts:[["hypo-","在下面"],["thesis","放置、命题 (tithenai)"]],lit:"垫在下面的说法 → 待验证的假设",
  kin:[["thesis","论文"],["synthesis","放到一起 → 综合"],["hypothetical","假设的"]]},
w038:{syl:"seed·ing"},
w039:{syl:"con·ver·sion end"},
w040:{syl:"bot·tle·neck",parts:[["bottle","瓶子"],["neck","脖子"]],lit:"瓶颈 —— 中英文这次是同一个比喻"},
/* ---------- 直播运营 ---------- */
w041:{syl:"live room"},
w042:{syl:"host"},
w043:{syl:"script",parts:[["scrib/script","写 (scribere)"]],lit:"写下来的东西 → 脚本",
  kin:[["describe","写下来 → 描述"],["subscribe","在下面签 → 订阅"],["prescription","事先写 → 处方"]]},
w044:{syl:"hook"},
w045:{syl:"re·ten·tion",parts:[["re-","回、住"],["tent","拿住 (tenere)"],["-ion","名词"]],lit:"拿住不放 → 留存",
  kin:[["retain","保留"],["contain","一起拿住 → 容纳"],["maintain","用手拿住 → 维持"],["tenant","持有的人 → 租户"]]},
w046:{syl:"room-en·try rate",parts:[["en-","进入"],["try","(法语) 进"]],lit:"进去 → 进房"},
w047:{syl:"watch time"},
w048:{syl:"push sale"},
w049:{syl:"pain point"},
w050:{syl:"sell·ing point"},
w051:{syl:"give·a·way"},
w052:{syl:"vouch·er",parts:[["vouch","作保、证明"],["-er","东西"]],lit:"作保的凭据 → 券",
  kin:[["vouch for","为…作保"]]},
w053:{syl:"C·T·A",parts:[["C","Call 呼唤"],["T","To 去"],["A","Action 行动"]],lit:"叫人去做这个动作"},
w054:{syl:"ros·ter"},
w055:{syl:"add the prod·uct link"},
w056:{syl:"prod·uct card",parts:[["pro-","向前"],["duct","引导、带 (ducere)"]],lit:"带出来的东西 → 产品",
  kin:[["produce","生产"],["introduce","带进来 → 介绍"],["conduct","带着走 → 实施"],["reduce","带回去 → 减少"]]},
w057:{syl:"short vid·e·o",parts:[["vid","看 (videre)"],["-eo","拉丁词尾"]],lit:"能看的东西",
  kin:[["video","视频"],["evident","看得见的 → 明显的"],["provide","预先看到 → 提供"],["visible","可见的"]]},
w058:{syl:"screen re·cord·ing",parts:[["re-","再"],["cord","心 (cor)"]],lit:"再放回心里 → 记录下来",
  kin:[["record","记录"],["cordial","出自内心的"],["accord","心贴心 → 一致"]]},
w059:{syl:"back·ground"},
w060:{syl:"post-mor·tem",parts:[["post-","之后"],["mortem","死亡 (mors)"]],lit:"死后的检查 → 事后复盘",
  kin:[["mortal","会死的"],["postpone","放到之后 → 推迟"]]},
/* ---------- 订单履约 ---------- */
w061:{syl:"or·der"},
w062:{syl:"ful·fill·ment",parts:[["ful(l)","满"],["fill","填"],["-ment","名词"]],lit:"填满 → 把承诺填满 → 履约",
  kin:[["fulfill","履行"],["fill","填"],["fully","完全地"]]},
w063:{syl:"ship"},
w064:{syl:"de·liv·er·y time"},
w065:{syl:"track·ing num·ber"},
w066:{syl:"out of stock"},
w067:{syl:"re·stock",parts:[["re-","再"],["stock","存货"]],lit:"再进货 → 补货"},
w068:{syl:"in·ven·to·ry",parts:[["in-","进来"],["vent","来 (venire)"],["-ory","名词"]],lit:"进来的东西的清单 → 库存",
  kin:[["invent","碰上、想出 → 发明"],["event","出来的事 → 事件"],["prevent","先来一步 → 预防"],["revenue","回来的钱 → 收入"]]},
w069:{syl:"ware·house",parts:[["ware","货物 (古英语 waru)"],["house","房子"]],lit:"放货的房子"},
w070:{syl:"cus·toms clear·ance",parts:[["custom","惯例、关税"],["clear","清"],["-ance","名词"]],lit:"把关税清掉 → 清关"},
w071:{syl:"re·turn",parts:[["re-","回"],["turn","转"]],lit:"转回来 → 退货",
  kin:[["refund","钱回来 → 退款（跟 return 别混）"]]},
w072:{syl:"re·fund",parts:[["re-","回"],["fund","资金 (fundus 底)"]],lit:"资金退回 → 退款",
  kin:[["fund","资金"],["fundamental","打底的 → 根本的"],["return","货回来（别跟它混）"]]},
w073:{syl:"af·ter-sales"},
w074:{syl:"com·plaint",parts:[["com-","加强"],["plaint","拍胸哀叹 (plangere)"]],lit:"捶胸叫苦 → 投诉",
  kin:[["complain","抱怨"],["plaintiff","叫苦的人 → 原告"]]},
w075:{syl:"neg·a·tive re·view",parts:[["neg","否认 (negare)"],["-ative","形容词"]],lit:"否认的 → 负面的",
  kin:[["negate","否定"],["deny","否认"],["renege","反悔"]]},
w076:{syl:"last mile"},
w077:{syl:"free ship·ping"},
w078:{syl:"de·liv·ered"},
/* ---------- 商品定价 ---------- */
w079:{syl:"S·K·U",parts:[["S","Stock 存货"],["K","Keeping 保管"],["U","Unit 单位"]],lit:"存货管理的最小单位"},
w080:{syl:"list·ing"},
w081:{syl:"launch"},
w082:{syl:"pric·ing"},
w083:{syl:"dis·count",parts:[["dis-","去掉"],["count","计算"]],lit:"从总价里减掉算 → 折扣",
  kin:[["count","计算"],["account","算清楚 → 账户"],["discount rate","折扣率"]]},
w084:{syl:"bun·dle",parts:[["bund","绑 (bind)"],["-le","小称"]],lit:"绑成一小捆 → 组合装",
  kin:[["bind","绑"],["bond","纽带"]]},
w085:{syl:"com·mis·sion",parts:[["com-","一起"],["miss","送 (mittere)"],["-ion","名词"]],lit:"一起送出去 → 委托 → 佣金",
  kin:[["mission","任务"],["submit","送到下面 → 提交"],["transmit","送过去 → 传输"],["permit","送过 → 允许"]]},
w086:{syl:"gross mar·gin",parts:[["margin","边缘 (margo)"]],lit:"边上剩下的那一条 → 利润",
  kin:[["marginal","边缘的"],["margin rate","毛利率"]]},
w087:{syl:"cat·e·go·ry"},
w088:{syl:"rank·ing"},
w089:{syl:"com·pet·i·tor",parts:[["com-","一起"],["pet","追求 (petere)"],["-itor","人"]],lit:"一起追同一个东西的人",
  kin:[["compete","竞争"],["appetite","追求 → 食欲"],["petition","请求 → 请愿"],["repeat","再追 → 重复"]]},
w090:{syl:"main im·age"},
w091:{syl:"sam·ple",parts:[["sam","拿 (exemplum 取样)"]],lit:"取出来的一份 → 样品",
  kin:[["example","取出来给你看 → 例子"],["exemplify","举例"]]},
w092:{syl:"main push"},
w093:{syl:"in·gre·di·ent",parts:[["in-","进去"],["gred","走 (gradi)"],["-ient","形容词转名词"]],lit:"走进去的东西 → 配料成分",
  kin:[["gradual","一步一步的 → 逐渐的"],["progress","往前走 → 进展"],["degree","走下来的台阶 → 程度"]]},
w094:{syl:"shade"},
/* ---------- 平台运营 ---------- */
w095:{syl:"shop"},
w096:{syl:"sell·er"},
w097:{syl:"cre·a·tor",parts:[["creat","创造"],["-or","人"]],lit:"创造的人 → 达人",
  kin:[["create","创造"],["creative","素材（本库另一个词）"]]},
w098:{syl:"af·fil·i·ate",parts:[["af-","向"],["fili","儿子 (filius)"],["-ate","动词"]],lit:"收作儿子 → 挂靠、联盟",
  kin:[["filial","子女的"],["affiliation","隶属关系"]]},
w099:{syl:"or·gan·ic traf·fic",parts:[["organ","器官、工具 (organon)"],["-ic","形容词"]],lit:"像器官那样自己长出来的 → 自然的",
  kin:[["organ","器官"],["organize","让各部分各就各位 → 组织"]]},
w100:{syl:"vi·o·la·tion",parts:[["viol","暴力对待 (violare)"],["-ation","名词"]],lit:"强行破坏规则 → 违规",
  kin:[["violate","违反"],["violent","暴力的"]]},
w101:{syl:"ap·peal",parts:[["ap-","向"],["peal","驱、推 (pellere)"]],lit:"往上推 → 上诉、申诉",
  kin:[["expel","推出去 → 开除"],["repel","推回去 → 排斥"],["compel","推着 → 迫使"],["propel","往前推 → 推进"]]},
w102:{syl:"un·der re·view",parts:[["re-","再"],["view","看"]],lit:"再看一遍 → 审核",
  kin:[["review","复盘/审核/评价，本库里三个意思都用得到"],["preview","预先看"],["interview","互相看 → 面试"]]},
w103:{syl:"ac·count ap·proved",parts:[["ap-","向"],["prov","证明好 (probare)"]],lit:"证明它是好的 → 批准",
  kin:[["prove","证明"],["approval","审批"],["probable","可证明的 → 很可能的"]]},
w104:{syl:"B·C",parts:[["B","Business 商务"],["C","Center 中心"]],lit:"管账户的上层结构"},
w105:{syl:"dash·board"},
w106:{syl:"pull the da·ta"},
w107:{syl:"ex·port",parts:[["ex-","向外"],["port","搬运 (portare)"]],lit:"搬出去 → 导出/出口",
  kin:[["import","搬进来 → 导入"],["report","搬回来 → 汇报"],["transport","搬过去 → 运输"],["portable","能搬的 → 便携的"],["support","从下面搬住 → 支持"]]},
w108:{syl:"log"},
w109:{syl:"sign up"},
w110:{syl:"go live"},
w111:{syl:"Sho·pee"},
w112:{syl:"traf·fic struc·ture",parts:[["struct","建造 (struere)"],["-ure","名词"]],lit:"搭起来的样子 → 结构",
  kin:[["construct","一起建 → 建造"],["instruct","在里面搭 → 指导"],["destroy","反着建 → 破坏"]]},
/* ---------- 财务结算 ---------- */
w113:{syl:"set·tle·ment",parts:[["settle","安顿下来"],["-ment","名词"]],lit:"把账安顿下来 → 结算"},
w114:{syl:"pay·ment terms",parts:[["term","界限、期限 (terminus)"]],lit:"划定的界限 → 条款/期限",
  kin:[["terminal","终点"],["determine","定下界限 → 决定"],["terminate","终止"]]},
w115:{syl:"in·voice"},
w116:{syl:"quote"},
w117:{syl:"rec·on·cile",parts:[["re-","再"],["concil","开会、聚合 (concilium)"]],lit:"再坐到一起 → 对账、和解",
  kin:[["council","议会"],["conciliate","调解"]]},
w118:{syl:"pre·pay",parts:[["pre-","事先"],["pay","付"]],lit:"先付 → 预付",
  kin:[["prepaid","已预付的"],["preview","预先看"],["predict","预先说 → 预测"]]},
w119:{syl:"re·bate",parts:[["re-","回"],["bate","打掉 (abate)"]],lit:"打掉一部分退回来 → 返点"},
w120:{syl:"ex·change rate",parts:[["ex-","互相、出"],["change","换"]],lit:"换出去换进来 → 兑换"},
w121:{syl:"re·im·burse·ment",parts:[["re-","回"],["im-","进"],["burse","钱包 (bursa)"],["-ment","名词"]],lit:"把钱放回你钱包 → 报销",
  kin:[["bursary","助学金"],["purse","钱包"]]},
w122:{syl:"pur·chase or·der"},
w123:{syl:"cost"},
w124:{syl:"pay·ment re·ceived",parts:[["re-","回"],["ceive","拿 (capere)"]],lit:"拿到手 → 收到",
  kin:[["receive","收到"],["accept","接过来 → 接受"],["capture","抓住"],["deceive","拿走真相 → 欺骗"]]},
/* ---------- 协作流程 ---------- */
w125:{syl:"a·lign",parts:[["a-","向"],["lign","线 (linea)"]],lit:"排到一条线上 → 对齐",
  kin:[["line","线"],["linear","线性的"],["outline","外线 → 提纲"]]},
w126:{syl:"fol·low up"},
w127:{syl:"chase"},
w128:{syl:"sta·tus",parts:[["stat","站立 (stare)"],["-us","拉丁词尾"]],lit:"站在什么位置上 → 状态/进度",
  kin:[["state","状态"],["station","站"],["stable","站得稳的 → 稳定的"],["statue","立着的 → 雕像"]]},
w129:{syl:"blocked"},
w130:{syl:"ap·prov·al",parts:[["ap-","向"],["prov","证明好 (probare)"],["-al","名词"]],lit:"证明它可以 → 批准",
  kin:[["prove","证明"],["approve","批准"],["disprove","证伪"]]},
w131:{syl:"out of scope",parts:[["scope","看的范围 (skopein 看)"]],lit:"看得到的范围 → 职责范围",
  kin:[["telescope","看远的 → 望远镜"],["microscope","看小的 → 显微镜"]]},
w132:{syl:"men·tor",parts:[["Mentor","荷马史诗里教导忒勒马科斯的人名"]],lit:"专名变通名 → 带教人",
  kin:[["mentorship","带教关系"]]},
w133:{syl:"hand o·ver"},
w134:{syl:"flag"},
w135:{syl:"sync",parts:[["syn-","一起"],["chron","时间 (chronos)"]],lit:"同一个时间 → 同步（synchronize 的简写）",
  kin:[["synchronize","使同步"],["chronic","跟时间有关的 → 长期的"],["chronology","年表"]]},
w136:{syl:"point of con·tact",parts:[["con-","一起"],["tact","接触 (tangere)"]],lit:"碰到一起 → 接触人",
  kin:[["contact","联系"],["tangible","摸得着的"],["tactful","懂得碰触分寸的 → 得体的"]]},
w137:{syl:"a·gen·cy",parts:[["ag","做、驱动 (agere)"],["-ency","名词"]],lit:"替你做事的机构 → 代理商",
  kin:[["agent","代理人"],["act","行动"],["agenda","要做的事 → 议程"]]},
w138:{syl:"deck"},
w139:{syl:"dai·ly re·port",parts:[["re-","回"],["port","搬 (portare)"]],lit:"把情况搬回来 → 汇报",
  kin:[["export","搬出去 → 导出"],["import","搬进来"],["transport","搬过去 → 运输"]]},
w140:{syl:"drive"},
w141:{syl:"es·ca·late",parts:[["e(x)-","向上、向外"],["scal","梯子 (scala)"],["-ate","动词"]],lit:"上梯子 → 往上一级反映",
  kin:[["escalator","自动扶梯"],["scale","刻度/规模，也来自「梯子」"]]},
w142:{syl:"con·vert to full-time",parts:[["con-","完全"],["vert","转 (vertere)"]],lit:"完全转过来 → 转正",
  kin:[["conversion","转化（本库另一个词）"],["reverse","转回 → 反转"],["divert","转开"]]},
w143:{syl:"check with"},
w144:{syl:"walk me through"},
w145:{syl:"keep me post·ed",parts:[["post","邮寄、张贴 (positus 放)"]],lit:"持续把消息贴给我 → 有进展告诉我",
  kin:[["post","发帖/邮寄"],["position","放的地方 → 位置"],["deposit","放下去 → 存款"]]},
w146:{syl:"take the lead"},
/* ---------- 主体合规 ---------- */
w147:{syl:"le·gal en·ti·ty",parts:[["ent","存在 (esse 的现在分词 ens)"],["-ity","名词"]],lit:"存在着的东西 → 实体",
  kin:[["essence","本质"],["entity","实体"],["absent","不在场的"]]},
w148:{syl:"con·tract",parts:[["con-","一起"],["tract","拉 (trahere)"]],lit:"拉到一起 → 立约",
  kin:[["attract","拉过来 → 吸引"],["extract","拉出来 → 提取"],["subtract","拉走 → 减去"],["tractor","拖拉机"]]},
w149:{syl:"sign and stamp",parts:[["sign","记号 (signum)"]],lit:"落下记号 → 签字",
  kin:[["signal","信号"],["signature","签名"],["design","画出记号 → 设计"],["significant","有记号意义的 → 重要的"]]},
w150:{syl:"au·thor·i·za·tion",parts:[["author","创始人 (auctor 使增长的人)"],["-ize","使"],["-ation","名词"]],lit:"让某人有创始人的权 → 授权",
  kin:[["author","作者"],["authority","权威"],["authentic","出自本人的 → 真的"]]},
w151:{syl:"cross-bor·der"},
w152:{syl:"lo·cal",parts:[["loc","地方 (locus)"],["-al","形容词"]],lit:"跟地方有关的 → 本土的",
  kin:[["location","位置"],["locate","定位"],["allocate","分配到位置上"]]},
w153:{syl:"com·pli·ance",parts:[["com-","一起"],["pli","折、弯 (plicare)"],["-ance","名词"]],lit:"顺着一起弯 → 遵从",
  kin:[["comply","遵守"],["apply","贴上去 → 申请/应用"],["reply","折回去 → 回复"],["imply","折在里面 → 暗示"]]},
w154:{syl:"le·gal team",parts:[["leg","法律 (lex)"],["-al","形容词"]],lit:"跟法律有关的",
  kin:[["legal","法律的"],["legislation","立法"],["legitimate","合法的"],["privilege","私人的法 → 特权"]]},
w155:{syl:"li·cense",parts:[["lic","允许 (licere)"],["-ense","名词"]],lit:"被允许的凭证 → 许可证",
  kin:[["licence","英式拼法"],["illicit","不被允许的 → 非法的"]]},
w156:{syl:"ver·i·fi·ca·tion code",parts:[["ver","真 (verus)"],["-ify","使…成为"],["-ation","名词"]],lit:"使之为真 → 验证",
  kin:[["verify","核实"],["very","本义「真正地」"],["verdict","说真话 → 裁决"]]},
w157:{syl:"ac·cess",parts:[["ac-","向"],["cess","走 (cedere)"]],lit:"能走过去 → 权限/访问",
  kin:[["process","往前走 → 过程"],["proceed","继续走"],["exceed","走出界 → 超过"],["recede","往回走 → 后退"],["succeed","接着走 → 成功"]]},
w158:{syl:"re·port·ing line"},
};
