/* ============================================================================
 * data-phrases.js —— 短语 / 句型模块
 * 每天一个模块。练法：看中文 → 先出声说 → 再点开对照 → 自评说出来了/卡住了
 * items: {zh, en, tip?}   tip 是用法提醒，只在容易说错的地方给
 * ==========================================================================*/
window.MODULES = [
{id:"m01",name:"催进度",tag:"日常沟通",why:"你一周催了 7 次不同的事。规律很简单：问状态用 status，问回复用 reply，两个词覆盖八成。",items:[
 {zh:"这些啥进度",en:"What's the status on these?"},
 {zh:"这个有回复吗",en:"Any reply on this?"},
 {zh:"早上的回复了吗",en:"Did they reply to the one from this morning?"},
 {zh:"上午的主播 看播的结论有吗",en:"Do we have the review notes for this morning's host?"},
 {zh:"又一天没推送哦",en:"Another day with no post."},
 {zh:"麻烦尽快回复一下",en:"Please reply as soon as you can."},
 {zh:"今天周四了，不是说这周到吗。现在什么情况了啊",en:"It's Thursday. You said it would arrive this week — where are we now?",tip:"where are we now 比 what happened 客气，但压力更大。"},
 {zh:"还是上次那个问题，还没动",en:"Same issue as last time. Still no movement."},
 {zh:"这个我问第三次了。今天能给我个时间吗?",en:"This is my third ask. Can you give me a date today?",tip:"升级时给对方一个具体动作，比重复催有效。"},
 {zh:"今天还没回复我就得往上反映了",en:"If there's no reply today, I'll have to escalate.",tip:"escalate 很重，用之前先给对方一次机会。"}]},

{id:"m02",name:"约时间 · 定 deadline",tag:"日常沟通",why:"「大概今天几点啊」你一周说了 16 次，是你全部句子里最高频的一句。",items:[
 {zh:"大概今天几点啊",en:"What time today, roughly?"},
 {zh:"我看约的今天早上 11 点",en:"I have us down for 11 this morning."},
 {zh:"月底活动方案 周五前要对齐哦",en:"We need to align on the month-end plan before Friday."},
 {zh:"明天视频 ok 的话 艾特我建计划哈",en:"If the video is ready tomorrow, tag me and I'll build the campaign."},
 {zh:"今天预约面试的实习生来了吗",en:"Did the intern we booked for today show up?"},
 {zh:"我们定个时间过一遍",en:"Let's set a time to go through it."},
 {zh:"明天之前给我，行吗?",en:"Can you get it to me by tomorrow?",tip:"用 by 不用 before。by tomorrow 含明天，不会争。"},
 {zh:"这个不着急，下周也行",en:"No rush on this — next week is fine."},
 {zh:"我们改到下周一，可以吗",en:"Can we move it to Monday?"},
 {zh:"这个最晚什么时候要",en:"What's the latest you need this?"}]},

{id:"m03",name:"确认信息",tag:"日常沟通",why:"只需要学会一个词：中文的「对吧/是吧」，英语就是句尾加 right?。语法不完美，但非母语者之间全世界都这么说。",items:[
 {zh:"就用这个对吧",en:"We'll use this one, right?"},
 {zh:"现在是没有隐藏的是吧",en:"It's not hidden now, right?"},
 {zh:"还有确认一下，这个是没有 ttms 的对吧",en:"Just to confirm — this one has no TTMS, right?"},
 {zh:"这个视频是最终版的吗",en:"Is this the final version?"},
 {zh:"这里是不是打错了",en:"Is this a typo?"},
 {zh:"对 一开始在别的地方开的",en:"Right — it was opened somewhere else at first."},
 {zh:"我理解对吗?",en:"Am I understanding this right?"},
 {zh:"那我就按这个来",en:"Then I'll go with this."},
 {zh:"你是说全部都要改吗",en:"Do you mean all of them need changing?"},
 {zh:"我再念一遍你听：一零零",en:"Let me say it again: one zero zero.",tip:"数字说完立刻重复，这一个习惯能省你一半返工。"}]},

{id:"m04",name:"听不懂 · 救场",tag:"必修",why:"你原话里没这一类，因为打字不需要。但一开口就需要 —— 对方也是非母语者，听不懂是常态，不是失误。会救场的能撑住整场会。",items:[
 {zh:"你能再说一遍吗，慢一点",en:"Sorry, could you say that again more slowly?"},
 {zh:"我没听清",en:"Sorry, I didn't catch that."},
 {zh:"你是说 X 还是 Y?",en:"Do you mean X or Y?"},
 {zh:"你能打出来吗?",en:"Could you type it?",tip:"最高效的兜底。数字、账号名、日期一律让对方打字，别靠听。"},
 {zh:"我重复一遍你确认下：你要的是……对吗?",en:"Let me repeat it back — you want …, correct?"},
 {zh:"会后我用文字再确认一遍",en:"I'll confirm this in writing after the call."},
 {zh:"等一下，我查一下",en:"One second, let me check."},
 {zh:"我不确定，我查完回你",en:"I'm not sure. Let me check and come back to you."},
 {zh:"这个词我不懂，什么意思?",en:"Sorry, I don't know that word — what does it mean?"},
 {zh:"能换个简单的说法吗",en:"Could you put that more simply?"}]},

{id:"m05",name:"提要求 · 派活",tag:"日常沟通",why:"你的口头习惯是「XX 一下」「XX 下」—— 英语一律翻成 Please + 动词。最简单，也最不会出错。",items:[
 {zh:"投流码同步下",en:"Send me the promo codes."},
 {zh:"登记一下 投流码这些",en:"Please log the promo codes."},
 {zh:"这个视频的 code 快点给我",en:"I need the code for this video — it's urgent."},
 {zh:"你把这个 Excel 上传飞书",en:"Please upload this Excel to Feishu."},
 {zh:"麻烦把账号同步过来",en:"Please send over the account details."},
 {zh:"把充值流程同步下",en:"Please walk me through the top-up process."},
 {zh:"pin 一下",en:"Please pin it."},
 {zh:"这个交给你，周五给我",en:"This one is yours — get it to me by Friday."},
 {zh:"你先做，不确定的问我",en:"Start on it, and ask me if anything is unclear."},
 {zh:"帮我把这两个数核一下",en:"Please double-check these two numbers for me."}]},

{id:"m06",name:"拒绝 · 推迟 · 转交",tag:"日常沟通",why:"分三档说。转交是你最常用也最安全的一档 —— 你手册里本来就写了「一律先转给带教人」，这是制度，不是推脱。",items:[
 {zh:"不行",en:"No, we can't do that.",tip:"别只说一个 No。加半句就从生硬变正常。"},
 {zh:"搞不定",en:"We can't get it done."},
 {zh:"今天还是投不了品广",en:"We still can't run brand ads today."},
 {zh:"周一再冲",en:"Let's push again on Monday."},
 {zh:"这个要等审批",en:"This needs approval first."},
 {zh:"这个要问 BD",en:"You'll need to ask BD on this."},
 {zh:"我这边没这个权限",en:"I don't have access to that."},
 {zh:"我需要先跟带教人确认",en:"I need to check with my mentor first."},
 {zh:"这部分数据我这边不能提供，我帮你转给 BD",en:"I can't share this data — I'll hand you to the BD."},
 {zh:"这个超出我的职责范围了",en:"That's out of my scope."}]},

{id:"m07",name:"汇报进度",tag:"日常沟通",why:"编号式你已经会了。这里补日常口头版，和最有用的卡点式 —— 你手册的铁律是「无异常也要发」，卡住了也得说。",items:[
 {zh:"好的 我一直在跟进的",en:"OK — I'm still following up."},
 {zh:"已经加急在处理了",en:"We've put a rush on it."},
 {zh:"PPT 我加进去了",en:"I've added it to the deck.",tip:"说 deck 不说 PPT —— 老外多数不说 PPT。"},
 {zh:"我都加进去了",en:"I've added all of it."},
 {zh:"还在催合同流程",en:"I'm still chasing the contract."},
 {zh:"卡在 X，在等 Y",en:"It's blocked on X. We're waiting on Y."},
 {zh:"没进展，原因是 X",en:"No progress. The reason is X.",tip:"对应你手册的「取不到就写取不到 + 原因」。"},
 {zh:"三件事：一、已通过；二、还剩 10%；三、法务有异议",en:"Three things: one, approved; two, 10% left; three, legal has objections."},
 {zh:"今天没有异常",en:"Nothing unusual today."},
 {zh:"明天应该能出结果",en:"We should have a result tomorrow."}]},

{id:"m08",name:"追问细节",tag:"日常沟通",why:"你追问的核心词是「哪个」—— 英语是 which，不是 what。选项已知问 which，选项未知问 what。你的场景基本全是 which。",items:[
 {zh:"哪个户",en:"Which account?"},
 {zh:"现在用的是哪个 BC 哪个户啊",en:"Which BC and which account is it on now?"},
 {zh:"我们付款美元的主体是哪个啊",en:"Which legal entity pays in USD?"},
 {zh:"这个手机号在谁那",en:"Who has this phone number?"},
 {zh:"视频会发在哪个账号上?",en:"Which account will post the video?"},
 {zh:"预算多少一天?结束日期是什么时候?",en:"What's the daily budget? And what's the end date?",tip:"一次问两个数字就拆成两句。中文能连着问，英语连着问对方会漏答。"},
 {zh:"这个数是什么口径",en:"What's the basis for this number?"},
 {zh:"为什么会掉这么多",en:"Why did it drop this much?"},
 {zh:"这是我们的问题还是大盘的问题",en:"Is this on our side or is it market-wide?"},
 {zh:"下一步谁做什么",en:"Who does what next?"}]},

{id:"m09",name:"订单 · 物流",tag:"电商",why:"跨境电商每天都在问的三件事：发了没、到哪了、什么时候到。三个句型解决八成。",items:[
 {zh:"这些什么时候发货?",en:"When do these ship?"},
 {zh:"单号发我",en:"Send me the tracking number."},
 {zh:"现在到哪了?",en:"Where is it now?"},
 {zh:"这批货卡在清关",en:"The shipment is stuck at customs."},
 {zh:"物流时效大概几天?",en:"How many days is the delivery time?"},
 {zh:"跨境和本土的时效不一样",en:"Cross-border and local have different delivery times."},
 {zh:"这单是从海外仓发的吗?",en:"Is this one shipping from the overseas warehouse?"},
 {zh:"多少单按时妥投?",en:"How many were delivered on time?"},
 {zh:"客户说没收到",en:"The customer says it never arrived."},
 {zh:"我们得给个准确的到货时间",en:"We need to give them a firm delivery date."}]},

{id:"m10",name:"库存 · 补货",tag:"电商",why:"断货是直播间最贵的错误。这一组的关键词只有两个：out of stock 和 restock。",items:[
 {zh:"库存还剩多少?",en:"How much inventory is left?"},
 {zh:"主推的 SKU 断货了",en:"The main SKU is out of stock."},
 {zh:"什么时候能补货?",en:"When can we restock?"},
 {zh:"这个够播几场?",en:"How many streams will this cover?"},
 {zh:"先别推这个品，货不够",en:"Let's hold off on this one — we don't have enough stock."},
 {zh:"下周大促要提前备货",en:"We need to stock up before next week's campaign."},
 {zh:"这个色号最好卖，多备点",en:"This shade sells best — stock more of it."},
 {zh:"链接先下架，等补货",en:"Take the listing down until we restock."},
 {zh:"库存表是哪个人在更新?",en:"Who updates the inventory sheet?"},
 {zh:"缺货会直接影响 ROI",en:"A stockout hits ROI directly."}]},

{id:"m11",name:"退款 · 售后 · 客诉",tag:"电商",why:"退款率是你天天在看的指标（一周 18 次）。但你要能说清「不是广告问题」—— 这是划责任，不是甩锅。",items:[
 {zh:"退款率在涨",en:"The refund rate is climbing."},
 {zh:"退款率异常先转运营，不是广告问题",en:"A refund-rate spike goes to ops first. It's not an ads problem.",tip:"return 是货回来，refund 是钱回去，别混。"},
 {zh:"主要退款原因是什么?",en:"What's the main refund reason?"},
 {zh:"收到三个物流的客诉",en:"We got three complaints about delivery."},
 {zh:"两个差评提到赠品",en:"Two negative reviews mention the gift."},
 {zh:"这个要走售后，不走广告",en:"This is an after-sales issue, not an ads one."},
 {zh:"高退款率会吃掉 ROI",en:"A high refund rate eats ROI."},
 {zh:"我们能拿到退款明细吗?",en:"Can we get the refund breakdown?"},
 {zh:"这个链接的退款率明显偏高",en:"This listing's refund rate is clearly above the rest."},
 {zh:"先查是不是发错货",en:"First check whether we shipped the wrong item."}]},

{id:"m12",name:"商品 · 上架 · 定价",tag:"电商",why:"上新和定价的沟通全是「哪个品、多少钱、什么时候上」。注意 listing 这个词要用熟。",items:[
 {zh:"这周主推哪个 SKU?",en:"Which SKU are we pushing this week?"},
 {zh:"链接已经上架了",en:"The listing is live now."},
 {zh:"先下架，改完再上",en:"Take it down, fix it, then relist."},
 {zh:"到手价是多少?",en:"What's the final price?"},
 {zh:"两个店定价不一样",en:"Pricing is different on the two shops."},
 {zh:"毛利撑不住再打折了",en:"The margin can't take another discount."},
 {zh:"上组合装之后客单价涨了",en:"AOV went up after we added the bundle."},
 {zh:"主图上要有价格",en:"The main image needs the price on it."},
 {zh:"加一下新品的词",en:"Please add the keywords for the new products."},
 {zh:"这个成分在越南不能这么宣称",en:"We can't make that ingredient claim in Vietnam.",tip:"合规问题，一定要说清楚，别含糊。"}]},

{id:"m13",name:"达人合作 · 寄样",tag:"电商",why:"达人（creator）是你 GMV 的主要来源之一。这一组是从找人到出视频的全流程。",items:[
 {zh:"给这个达人寄样了吗?",en:"Have we sent samples to this creator?"},
 {zh:"我们给多少佣金?",en:"What commission rate are we offering?"},
 {zh:"他的视频什么时候发?",en:"When is his video going up?"},
 {zh:"这条视频没挂车",en:"This video has no product link.",tip:"「挂车」外国人不懂，一定要说 product link。"},
 {zh:"先等等达人回复吧",en:"Let's wait for the creator's reply."},
 {zh:"这是 KOL 素材，别自动排除",en:"It's a KOL creative — don't auto-exclude it."},
 {zh:"把这个达人加白名单",en:"Add this creator to the whitelist."},
 {zh:"这几个达人的数据能拉给我吗?",en:"Can you pull the numbers for these creators?"},
 {zh:"他要求提高佣金",en:"He's asking for a higher commission."},
 {zh:"授权到什么时候?",en:"How long does the authorization run?"}]},

{id:"m14",name:"大促 · 活动报名",tag:"电商",why:"平台大促是电商的节奏点。报名、排期、备货、复盘，四步的说法固定。",items:[
 {zh:"我们报名这次大促了吗?",en:"Did we sign up for this campaign?"},
 {zh:"报名截止到什么时候?",en:"When does sign-up close?"},
 {zh:"活动排期出来了吗?",en:"Is the campaign schedule out?"},
 {zh:"这次的机制是满减还是秒杀?",en:"Is it spend-and-save or a flash sale this time?"},
 {zh:"大促当天加多少预算?",en:"How much extra budget for the campaign day?"},
 {zh:"提前三天开始预热",en:"We start warming up three days out."},
 {zh:"平台给我们什么资源位?",en:"What placements is the platform giving us?"},
 {zh:"我们的目标是多少?",en:"What's our target?"},
 {zh:"活动结束后一周内出复盘",en:"We'll have the review out within a week after it ends."},
 {zh:"这次比上次涨了多少?",en:"How much did we grow versus last time?"}]},

{id:"m15",name:"财务 · 对账 · 付款",tag:"电商",why:"钱的事最不能含糊。这一组每句都要能说准，尤其是账期和汇率。",items:[
 {zh:"什么时候结算?",en:"When is the settlement date?"},
 {zh:"账期是多久?",en:"What are the payment terms?",tip:"30 天账期说 net 30 或 30-day payment terms。"},
 {zh:"要有发票才能付款",en:"We need the invoice before we can pay."},
 {zh:"月底前对一次账",en:"Let's reconcile before month end."},
 {zh:"他们要我们预付 30%",en:"They want us to prepay 30%."},
 {zh:"回款到了吗?",en:"Has the payment been received?"},
 {zh:"用哪个汇率?",en:"Which exchange rate are we using?"},
 {zh:"合同需要尽快走完审批盖章",en:"The contract needs to be signed and stamped as soon as possible."},
 {zh:"这笔走哪个主体付?",en:"Which legal entity pays this one?"},
 {zh:"充值到账要多久?",en:"How long does the top-up take to land?"}]},

{id:"m16",name:"平台违规 · 申诉",tag:"电商",why:"封号和卡审会直接让你当天没法投。这一组是你跟平台和代理商交涉时的固定说法。",items:[
 {zh:"这个户还在卡审",en:"The account is still under review."},
 {zh:"账户违规卡审已经审核通过",en:"The account review passed."},
 {zh:"因为什么违规?",en:"What was the violation?"},
 {zh:"我们昨天提了申诉",en:"We filed an appeal yesterday."},
 {zh:"申诉一般几天有结果?",en:"How long does an appeal usually take?"},
 {zh:"这个素材过不了审",en:"This creative won't pass review."},
 {zh:"希望周一可以下户开始投放",en:"We hope the account goes live Monday so we can start."},
 {zh:"能帮我们跟平台反馈一下吗?",en:"Could you raise this with the platform for us?"},
 {zh:"我们的反馈是希望之后避免被误判",en:"We're flagging this so it doesn't get misjudged next time."},
 {zh:"这条规则是最近才改的吗?",en:"Was this rule changed recently?"}]},

{id:"m17",name:"跟代理商谈条件",tag:"电商",why:"你跟 Max、Livelab 这类代理商谈的核心就三件：返点、账期、服务范围。这一组直接照着说。",items:[
 {zh:"达标的话返点多少?",en:"What's the rebate if we hit the target?"},
 {zh:"这个价格我们要再谈一下",en:"We need to talk about this price again."},
 {zh:"服务范围里包含什么?",en:"What's included in the scope?"},
 {zh:"这个不在合同里",en:"That's not in the contract."},
 {zh:"我们想要具体数字，只看大概不够",en:"We want the exact numbers — rough figures aren't enough."},
 {zh:"尽量多给一些吧",en:"Give us as much as you can, please."},
 {zh:"能不能先试一个月?",en:"Can we start with a one-month trial?"},
 {zh:"这个条件我们接受不了",en:"We can't accept these terms."},
 {zh:"我需要跟上级确认再回你",en:"I need to check with my manager and come back to you."},
 {zh:"我们把这个写进合同吧",en:"Let's put this in the contract."}]},

{id:"m18",name:"定规则 · 划责任",tag:"管理",why:"这些是你培训手册里的铁律。带越南实习生、跟代理商划边界都要用，而且句式几乎不变，换个名词就复用。",items:[
 {zh:"报数不写口径 = 没报数",en:"A number without its basis is not a number."},
 {zh:"素材判断一律用近 7 天",en:"Always judge creatives on the last 7 days."},
 {zh:"改预算、关素材、改 ROI 目标 —— 这三个都要审批",en:"Budget, creatives and ROI targets all need approval."},
 {zh:"没批就是越权",en:"Doing it without approval is out of scope."},
 {zh:"任何其他人要求你改广告，一律先转给带教人",en:"If anyone else asks you to change an ad, send them to your mentor first."},
 {zh:"CODE、达人、素材来源、授权 → BD 负责",en:"Codes, creators, creative sources and licensing — that's BD's side."},
 {zh:"给谁发消息 需要谁配合",en:"Say who you're messaging and whose help you need."},
 {zh:"无异常也要发",en:"Send an update even when there's no anomaly."},
 {zh:"取不到就写「取不到 + 原因」",en:"If you can't get the number, write N/A plus the reason."},
 {zh:"宁可多报一次，不要漏报一次",en:"Better to over-report once than miss once."},
 {zh:"不编数、不藏错、不越权",en:"Don't fabricate numbers, don't hide mistakes, don't exceed your authority."},
 {zh:"四条战线永远分表分行，不能合并",en:"The four lines always stay in separate tables. Never merge them."}]},

{id:"m19",name:"下结论 · 讲数据",tag:"管理",why:"周报的书面句式你已经有了。这里是开会时用嘴说出来的版本 —— 句子更短、更直接。",items:[
 {zh:"两个店就是不能统一，1 店 1 口径",en:"The two shops can't share one basis. One shop, one basis."},
 {zh:"跨境和本土的定价、时效、退款率都不一样，一合并，任何结论都是错的",en:"Cross-border and local differ on price, delivery time and refund rate. Merge them and every conclusion is wrong."},
 {zh:"GMV Max 赚今天的钱，品牌广告修明天的转化率",en:"GMV Max earns today's money. Brand ads fix tomorrow's conversion."},
 {zh:"我们 A→C 的种草效率是强项，瓶颈在收割端",en:"Our A-to-C is strong. The bottleneck is at the conversion end."},
 {zh:"断流不只是今天少花钱，而是系统重新进入学习期",en:"A delivery stop isn't just less spend today — the system re-enters the learning phase."},
 {zh:"一个人看 7 天归因，另一个看 30 天 O5A",en:"One of us is on 7-day attribution, the other on 30-day O5A.",tip:"这是你解释「口径不一致」的万能句。"},
 {zh:"余额不足花费 7 天",en:"The balance won't cover seven days."},
 {zh:"本土店有一条素材明显在跑飞",en:"One creative on the local shop is clearly burning budget."},
 {zh:"半小时消耗上千，ROI 低于 1",en:"It spent up to a thousand in half an hour, with ROI under one."},
 {zh:"任何砍预算的建议都要带 7 天数据",en:"Any proposal to cut budget must come with seven days of data."},
 {zh:"这个结论会随季度复盘更新",en:"This conclusion gets updated each quarterly review."},
 {zh:"这是我们的问题，不是大盘的",en:"This is on us, not the market."}]},

{id:"m20",name:"开场 · 收尾 · 寒暄",tag:"必修",why:"会议的头三十秒和最后三十秒是最容易慌的两段。背下来就不用临场想。",items:[
 {zh:"大家都到了吗?我们开始吧",en:"Is everyone here? Let's get started."},
 {zh:"今天想过三件事",en:"I'd like to cover three things today."},
 {zh:"我先说一下背景",en:"Let me give you some background first."},
 {zh:"抱歉我迟到了",en:"Sorry I'm late."},
 {zh:"你先说",en:"Please go ahead."},
 {zh:"我补充一点",en:"Let me add one thing."},
 {zh:"我们时间差不多了",en:"We're almost out of time."},
 {zh:"我总结一下下一步",en:"Let me sum up the next steps."},
 {zh:"我会后发文字给大家",en:"I'll send a written summary after this."},
 {zh:"谢谢大家，有问题随时找我",en:"Thanks everyone — reach out anytime."}]},

{id:"m21",name:"会议里的常用动作",tag:"必修",why:"不是词汇问题，是「插话、打断、要发言权」这些动作不会做，会就全程听别人说。",items:[
 {zh:"我能说一句吗?",en:"Can I jump in here?"},
 {zh:"等一下，我有个问题",en:"Sorry, can I ask a question?"},
 {zh:"这个我们能回到刚才那一点吗",en:"Can we go back to that earlier point?"},
 {zh:"我不同意，原因是……",en:"I don't agree, and here's why."},
 {zh:"我同意，但有个前提",en:"I agree, but with one condition."},
 {zh:"这个我们会后单独聊",en:"Let's take this offline."},
 {zh:"我记一下",en:"Let me note that down."},
 {zh:"这个谁负责?",en:"Who owns this?"},
 {zh:"我们今天能定下来吗?",en:"Can we decide this today?"},
 {zh:"我需要更多时间想一下",en:"I need more time to think about it."}]},

{id:"m22",name:"跟越南同事降速",tag:"方法",why:"你和 Mia、Gigi 都是二语者。最大风险不是你词不够，是双方各自听错还都以为听懂了。这一节是六条习惯，不是句子。",items:[
 {zh:"一句话只说一件事。中文可以一口气说三件，英语拆成三句",en:"One idea per sentence."},
 {zh:"数字说完立刻重复一遍",en:"The budget is 100 — one zero zero."},
 {zh:"关键结论一定落书面",en:"I'll put this in Feishu after."},
 {zh:"让对方复述回来，别问 understand",en:"Can you repeat the number back to me?",tip:"问 understand? 对方一定说 yes，问了没用。"},
 {zh:"别用动词短语：run it by → check with",en:"Let me check with him.",tip:"phrasal verb 是二语者之间最大的歧义来源。"},
 {zh:"缩写只用最通用的：别用 EOD / COB",en:"Please send it by end of today."}]},
];
