/* ============================================================================
 * data-words.js —— 工作英语词库
 * 字段：id / en / zh / pos / cat / gloss(具体注释) / ex(例句，尽量用你的原话)
 *       note(工作用法或易混提醒，可选)
 * cat 用来生成「同类干扰项」——4选1 的错误选项必须来自同一分类，
 *     否则选项一眼就能排除，题目形同虚设。
 * ==========================================================================*/
window.CATS = {
  ads:     { name: "广告投放",   color: "#2E7DD1" },
  metric:  { name: "数据指标",   color: "#0A7A69" },
  live:    { name: "直播运营",   color: "#B4478A" },
  fulfill: { name: "订单履约",   color: "#C0672A" },
  product: { name: "商品定价",   color: "#7A5AC7" },
  platform:{ name: "平台运营",   color: "#1E8E7E" },
  finance: { name: "财务结算",   color: "#8A6D1F" },
  collab:  { name: "协作流程",   color: "#4A6D8C" },
  entity:  { name: "主体合规",   color: "#A8443A" },
};

window.WORDS = [
/* ---------------- 广告投放 ads ---------------- */
{id:"w001",en:"budget",zh:"预算",pos:"n.",cat:"ads",gloss:"一个广告计划能花的钱。日预算 daily budget，总预算 total budget。",ex:{en:"What's the daily budget, and what's the end date?",zh:"预算多少一天，结束日期跑到什么时候"},note:"改预算是审批项 —— Budget changes need approval."},
{id:"w002",en:"spend",zh:"消耗（花掉的钱）",pos:"n./v.",cat:"ads",gloss:"实际花出去的钱。你说的「消耗」就是这个词。cost 也能用，但同行之间 spend 更常见。",ex:{en:"It spent a few hundred in about half an hour.",zh:"突然在半小时左右消耗几百"}},
{id:"w003",en:"creative",zh:"素材",pos:"n.",cat:"ads",gloss:"投放用的视频或图片。注意：是可数名词，一条素材 a creative，多条 creatives。",ex:{en:"Exclude the low-quality creative.",zh:"排除掉这条差素材"},note:"你一周说了 126 次「素材」，这是你最该背熟的词。"},
{id:"w004",en:"exclude",zh:"排除",pos:"v.",cat:"ads",gloss:"把某条素材或某个达人从投放里剔掉。",ex:{en:"We excluded this creative several times but it won't go.",zh:"这条素材我们排除了几次都排除不掉"},note:"排除素材本身要审批 —— excluding a creative needs approval."},
{id:"w005",en:"promo code",zh:"投流码 / CODE",pos:"n.",cat:"ads",gloss:"达人视频授权投流用的码。你原话里的「投流码」「code」都是它。",ex:{en:"Send me the promo codes.",zh:"投流码同步下"},note:"你一周提了 45 次，全库第二高频。"},
{id:"w006",en:"learning phase",zh:"学习期",pos:"n.",cat:"ads",gloss:"广告刚开或刚改完，系统在试探人群的阶段。这期间数据不准，别下结论。",ex:{en:"Don't judge it in the learning phase.",zh:"学习期别急着判断"}},
{id:"w007",en:"burn budget",zh:"跑飞",pos:"v.",cat:"ads",gloss:"素材短时间猛花钱但不出单。你说的「跑飞」用这个最准。",ex:{en:"One creative on the local shop is clearly burning budget.",zh:"发现本土店有一条素材明显在跑飞"}},
{id:"w008",en:"delivery",zh:"投放（广告的跑量）",pos:"n.",cat:"ads",gloss:"广告在跑的状态。注意这个词在电商里还有「配送」的意思，靠上下文区分。",ex:{en:"Delivery stopped because the balance hit zero.",zh:"余额到零了所以断流了"},note:"歧义词：广告场景=投放，物流场景=配送。"},
{id:"w009",en:"brand ads",zh:"品牌广告 / 品广",pos:"n.",cat:"ads",gloss:"做认知和种草的广告，不直接看当天 ROI。",ex:{en:"GMV Max earns today's money. Brand ads fix tomorrow's conversion.",zh:"GMV Max 赚今天的钱，品牌广告修明天的转化率"}},
{id:"w010",en:"audience",zh:"人群",pos:"n.",cat:"ads",gloss:"广告投给谁。人群包 audience package。",ex:{en:"We need the ACC audience size for these brands.",zh:"需要这些品牌的 acc 人群规模"}},
{id:"w011",en:"scale up",zh:"起量 / 放量",pos:"v.",cat:"ads",gloss:"加预算把跑量做大。反过来是 scale down 或 pause。",ex:{en:"What we tested, the result, then scale up or pause.",zh:"测了什么、结果、放大还是停止"}},
{id:"w012",en:"top up",zh:"充值",pos:"v.",cat:"ads",gloss:"给广告账户加钱。名词是 top-up。",ex:{en:"Could you top up the balance this week?",zh:"老师这几天给余额安排点呗"}},
{id:"w013",en:"balance",zh:"余额",pos:"n.",cat:"ads",gloss:"账户里还剩多少钱。",ex:{en:"The balance won't cover seven days.",zh:"余额不足花费 7 天"}},
{id:"w014",en:"placement",zh:"广告位 / 版位",pos:"n.",cat:"ads",gloss:"广告出现的位置。",ex:{en:"Which placement is this running on?",zh:"这个跑在哪个版位"}},
{id:"w015",en:"ad group",zh:"广告组",pos:"n.",cat:"ads",gloss:"投放结构里的一层：推广系列 campaign > 广告组 ad group > 广告 ad。",ex:{en:"Update the daily budget for this ad group.",zh:"把这个广告组的日预算改一下"}},
{id:"w016",en:"campaign",zh:"推广系列 / 活动",pos:"n.",cat:"ads",gloss:"投放结构最上面一层。也可指一场营销活动。",ex:{en:"Which campaign is this creative in?",zh:"这条素材在哪个推广系列里"}},
{id:"w017",en:"bid",zh:"出价",pos:"n./v.",cat:"ads",gloss:"愿意为一次转化付多少。不出价的智能投放叫 NoBid。",ex:{en:"We're running NoBid on this one.",zh:"这个跑的是不出价"}},
{id:"w018",en:"targeting",zh:"定向",pos:"n.",cat:"ads",gloss:"限定投给什么人。放开定向 = broad targeting。",ex:{en:"Let's go broad on targeting first.",zh:"先放开定向跑"}},
{id:"w019",en:"whitelist",zh:"白名单",pos:"n./v.",cat:"ads",gloss:"允许清单。反过来是 blacklist 黑名单。",ex:{en:"Add this creator to the whitelist.",zh:"把这个达人加白名单"}},
{id:"w020",en:"pause",zh:"暂停 / 关掉",pos:"v.",cat:"ads",gloss:"停掉一个广告但不删。关素材说 pause the creative。",ex:{en:"I paused it, but I'd rather you confirm first.",zh:"我先暂停了，不过还是要你确认下"},note:"关素材是审批项，别自己动手。"},
/* ---------------- 数据指标 metric ---------------- */
{id:"w021",en:"ROI",zh:"投流回报",pos:"n.",cat:"metric",gloss:"花 1 块换回多少成交。读作 R-O-I，也有人说 ROAS。",ex:{en:"Check the last 7 days for creatives with ROI under one.",zh:"排查近 7 天 ROI 低于 1 的素材"},note:"你一周说了 94 次。ROI 低于 1 = ROI under one。"},
{id:"w022",en:"GMV",zh:"成交额",pos:"n.",cat:"metric",gloss:"含退款的总成交。读作 G-M-V。",ex:{en:"This week's GMV was 206,190 CNY, down 23.42% WoW.",zh:"本周 GMV 为 206,190 CNY，环比下降 23.42%"}},
{id:"w023",en:"NMV",zh:"净成交",pos:"n.",cat:"metric",gloss:"扣掉退款后的成交。GMV 减退款。",ex:{en:"NMV is GMV minus refunds.",zh:"净成交等于成交额减退款"},note:"报数一定要说清是 GMV 还是 NMV —— 这就是你说的「口径」。"},
{id:"w024",en:"basis",zh:"口径",pos:"n.",cat:"metric",gloss:"这个数是怎么算出来的。也可以说 definition。你最该背的一个词。",ex:{en:"A number without its basis is not a number.",zh:"报数不写口径 = 没报数"},note:"「1 店 1 口径」= one shop, one basis."},
{id:"w025",en:"attribution",zh:"归因",pos:"n.",cat:"metric",gloss:"一笔成交算在谁头上、算多少天。7 天归因 7-day attribution。",ex:{en:"One of us is on 7-day attribution, the other on 30-day O5A.",zh:"一个人看 7 天归因，另一个看 30 天 O5A"}},
{id:"w026",en:"refund rate",zh:"退款率",pos:"n.",cat:"metric",gloss:"退款占成交的比例。高退款率直接吃掉 ROI。",ex:{en:"A refund-rate spike goes to ops first.",zh:"退款率异常先转运营"}},
{id:"w027",en:"CTR",zh:"点击率",pos:"n.",cat:"metric",gloss:"点击除以曝光。读作 C-T-R。",ex:{en:"CTR dropped today.",zh:"今天点击率掉了"}},
{id:"w028",en:"CPM",zh:"千次曝光成本",pos:"n.",cat:"metric",gloss:"每一千次曝光要花多少钱。CPM 高 = 流量贵。",ex:{en:"CPM is too high.",zh:"千展成本太高了"}},
{id:"w029",en:"conversion",zh:"转化",pos:"n.",cat:"metric",gloss:"看的人变成买的人。转化率 conversion rate / CVR。",ex:{en:"This shows post-entry conversion is still solid.",zh:"说明用户进入直播间后的转化能力仍然较好"}},
{id:"w030",en:"AOV",zh:"客单价",pos:"n.",cat:"metric",gloss:"平均每单多少钱。全称 average order value。",ex:{en:"Our AOV went up after we added the bundle.",zh:"上了组合装之后客单价涨了"}},
{id:"w031",en:"week over week",zh:"环比（周）",pos:"adv.",cat:"metric",gloss:"跟上周比。缩写 WoW。跟去年同期比是 year over year / YoY。",ex:{en:"GMV is down 23% week over week.",zh:"GMV 环比下降 23%"},note:"口语直接说 down 23 WoW，别念全称。"},
{id:"w032",en:"impressions",zh:"曝光",pos:"n.",cat:"metric",gloss:"被看到多少次。永远用复数。",ex:{en:"Impressions are flat but CTR is down.",zh:"曝光没变但点击率掉了"}},
{id:"w033",en:"share",zh:"份额",pos:"n.",cat:"metric",gloss:"占大盘的比例。市场份额 market share。",ex:{en:"Market share rose to 1.32%.",zh:"市场份额涨到 1.32%"}},
{id:"w034",en:"anomaly",zh:"异动 / 异常",pos:"n.",cat:"metric",gloss:"数据突然不对。你手册里的「无异常也要发」就是它。",ex:{en:"Send an update even when there's no anomaly.",zh:"无异常也要发"}},
{id:"w035",en:"benchmark",zh:"基准 / 对标值",pos:"n.",cat:"metric",gloss:"用来比的参照线，比如行业平均。",ex:{en:"We're below the category benchmark.",zh:"我们低于类目基准"}},
{id:"w036",en:"market-wide",zh:"大盘层面的",pos:"adj.",cat:"metric",gloss:"整个市场都这样，不是你一家的问题。「大盘」= the market。",ex:{en:"Our live traffic has been poor — is this a market-wide drop?",zh:"这几天我们直播间流量都比较差，这个是大盘原因影响吗"},note:"这是你甩锅和自查的关键一问。"},
{id:"w037",en:"hypothesis",zh:"假设",pos:"n.",cat:"metric",gloss:"要验证的猜想。复数 hypotheses。",ex:{en:"Validate one hypothesis per week.",zh:"一周验证一个假设"}},
{id:"w038",en:"seeding",zh:"种草",pos:"n.",cat:"metric",gloss:"让人先认识、先想要，还没到买。对应 A→C 这一段。",ex:{en:"Our seeding efficiency is strong.",zh:"我们的种草效率是强项"}},
{id:"w039",en:"conversion end",zh:"收割端",pos:"n.",cat:"metric",gloss:"漏斗最后成交的那一段，C→V。",ex:{en:"The bottleneck is at the conversion end.",zh:"瓶颈在收割端"}},
{id:"w040",en:"bottleneck",zh:"瓶颈",pos:"n.",cat:"metric",gloss:"卡住整条链路的那一环。",ex:{en:"Our A-to-C is strong. The bottleneck is C-to-V.",zh:"我们 A→C 是强项，瓶颈在 C→V"}},
/* ---------------- 直播运营 live ---------------- */
{id:"w041",en:"live room",zh:"直播间",pos:"n.",cat:"live",gloss:"也常直接说 the live 或 the stream。开播 go live。",ex:{en:"Room 2 traffic dropped.",zh:"2 号直播间流量掉了"}},
{id:"w042",en:"host",zh:"主播",pos:"n.",cat:"live",gloss:"镜头前的人。助播 assistant host。",ex:{en:"The host didn't follow the script.",zh:"主播没按话术走"}},
{id:"w043",en:"script",zh:"话术",pos:"n.",cat:"live",gloss:"主播要说的内容脚本。也可说 talk track。",ex:{en:"The talk track lacks pain points.",zh:"话术缺痛点"}},
{id:"w044",en:"hook",zh:"钩子 / 开场",pos:"n.",cat:"live",gloss:"前三秒抓住人的那句话或画面。",ex:{en:"Focus on optimizing the opening hook and retention.",zh:"建议重点优化开场 Hook 和留存"}},
{id:"w045",en:"retention",zh:"留存",pos:"n.",cat:"live",gloss:"人进来之后留多久。留不住就没转化。",ex:{en:"Retention is the problem, not traffic.",zh:"问题在留存，不是流量"}},
{id:"w046",en:"room-entry rate",zh:"进房率",pos:"n.",cat:"live",gloss:"刷到的人有多少点进来。",ex:{en:"Room-entry rate dropped 22%.",zh:"进房率掉了 22%"}},
{id:"w047",en:"watch time",zh:"观看时长",pos:"n.",cat:"live",gloss:"平均看多久。avg. watch time。",ex:{en:"Watch time fell to 14 seconds.",zh:"平均观看时长掉到 14 秒"}},
{id:"w048",en:"push sale",zh:"促单",pos:"v./n.",cat:"live",gloss:"催着观众下单的那一段。也可说 close the sale。",ex:{en:"Push sale was too weak.",zh:"促单太弱了"}},
{id:"w049",en:"pain point",zh:"痛点",pos:"n.",cat:"live",gloss:"用户的困扰。讲痛点才有人听。",ex:{en:"Not enough pain-point emphasis.",zh:"痛点强调不够"}},
{id:"w050",en:"selling point",zh:"卖点",pos:"n.",cat:"live",gloss:"产品好在哪。利益点 benefit 是卖点对用户的意义。",ex:{en:"Highlight the selling points.",zh:"把卖点讲透"}},
{id:"w051",en:"giveaway",zh:"赠品",pos:"n.",cat:"live",gloss:"送的东西。也可说 gift 或 freebie。",ex:{en:"Keep emphasizing the gift.",zh:"一直强调赠品"}},
{id:"w052",en:"voucher",zh:"优惠券",pos:"n.",cat:"live",gloss:"抵扣券。美式也说 coupon。",ex:{en:"Push the voucher every 7 minutes.",zh:"每 7 分钟推一次优惠券"}},
{id:"w053",en:"CTA",zh:"行动号召",pos:"n.",cat:"live",gloss:"叫人下单/点链接的那句话。call to action。",ex:{en:"70% CTA, 30% pain points.",zh:"七成行动号召，三成痛点"}},
{id:"w054",en:"roster",zh:"排班表",pos:"n.",cat:"live",gloss:"谁什么时候播。也可说 schedule。",ex:{en:"Host roster for August.",zh:"8 月主播排班"}},
{id:"w055",en:"add the product link",zh:"挂车",pos:"v.",cat:"live",gloss:"视频或直播里挂上商品链接。不挂车 = no product link。",ex:{en:"This video has no product link.",zh:"这条视频没挂车"},note:"这是你们内部术语，外国人不懂「挂车」，一定要说 product link。"},
{id:"w056",en:"product card",zh:"商品卡",pos:"n.",cat:"live",gloss:"不靠直播和视频，直接从商品页成交的入口。",ex:{en:"Product card GMV is growing.",zh:"商品卡成交在涨"}},
{id:"w057",en:"short video",zh:"短视频",pos:"n.",cat:"live",gloss:"区别于直播的内容形式。",ex:{en:"What's the short-video share of total GMV?",zh:"短视频占总成交多少"}},
{id:"w058",en:"screen recording",zh:"录屏",pos:"n.",cat:"live",gloss:"把屏幕录下来。",ex:{en:"Send me the screen recording.",zh:"录屏发我"}},
{id:"w059",en:"background",zh:"背景 / 视觉",pos:"n.",cat:"live",gloss:"直播间的布景。",ex:{en:"Change the live-room background.",zh:"换一下直播间背景"}},
{id:"w060",en:"post-mortem",zh:"复盘",pos:"n.",cat:"live",gloss:"事后总结。日常说 review 更多，正式场合 post-mortem。",ex:{en:"Weekly review is done.",zh:"周复盘做完了"}},
/* ---------------- 订单履约 fulfill ---------------- */
{id:"w061",en:"order",zh:"订单",pos:"n.",cat:"fulfill",gloss:"下单 place an order。出单多说 orders are coming in。",ex:{en:"The main driver was a 26.67% drop in hourly orders.",zh:"主要原因是每小时成交量下降 26.67%"}},
{id:"w062",en:"fulfillment",zh:"履约",pos:"n.",cat:"fulfill",gloss:"从下单到送到手的全过程。动词 fulfill。",ex:{en:"Fulfillment is the local team's side.",zh:"履约是本地团队负责"}},
{id:"w063",en:"ship",zh:"发货",pos:"v.",cat:"fulfill",gloss:"把货发出去。已发货 shipped。",ex:{en:"When do these ship?",zh:"这些什么时候发货"}},
{id:"w064",en:"delivery time",zh:"物流时效",pos:"n.",cat:"fulfill",gloss:"多久能到。也说 lead time。",ex:{en:"Cross-border and local differ on price and delivery time.",zh:"跨境和本土的定价、物流时效都不一样"}},
{id:"w065",en:"tracking number",zh:"物流单号",pos:"n.",cat:"fulfill",gloss:"查件用的号。面单 shipping label。",ex:{en:"Send me the tracking number.",zh:"单号发我"}},
{id:"w066",en:"out of stock",zh:"缺货 / 断货",pos:"adj.",cat:"fulfill",gloss:"没货了。名词 stockout。",ex:{en:"The top SKU is out of stock.",zh:"主推的 SKU 断货了"}},
{id:"w067",en:"restock",zh:"补货",pos:"v.",cat:"fulfill",gloss:"把货补上。备货 stock up。",ex:{en:"When can we restock?",zh:"什么时候能补货"}},
{id:"w068",en:"inventory",zh:"库存",pos:"n.",cat:"fulfill",gloss:"还有多少货。英式也说 stock。",ex:{en:"How much inventory is left?",zh:"库存还剩多少"}},
{id:"w069",en:"warehouse",zh:"仓库",pos:"n.",cat:"fulfill",gloss:"海外仓 overseas warehouse，保税仓 bonded warehouse。",ex:{en:"Is it shipping from the overseas warehouse?",zh:"这是从海外仓发吗"}},
{id:"w070",en:"customs clearance",zh:"清关",pos:"n.",cat:"fulfill",gloss:"货过海关。报关 declare。卡关 stuck at customs。",ex:{en:"The shipment is stuck at customs.",zh:"这批货卡在清关"}},
{id:"w071",en:"return",zh:"退货",pos:"n./v.",cat:"fulfill",gloss:"货退回来。退款是 refund，两个别混。",ex:{en:"The return rate is climbing.",zh:"退货率在涨"},note:"return = 货回来；refund = 钱回去。"},
{id:"w072",en:"refund",zh:"退款",pos:"n./v.",cat:"fulfill",gloss:"把钱退给买家。",ex:{en:"High refund rate eats ROI.",zh:"高退款率吃掉 ROI"}},
{id:"w073",en:"after-sales",zh:"售后",pos:"n.",cat:"fulfill",gloss:"卖完之后的服务。也说 customer service。",ex:{en:"That's an after-sales issue, not an ads issue.",zh:"那是售后问题，不是广告问题"}},
{id:"w074",en:"complaint",zh:"客诉",pos:"n.",cat:"fulfill",gloss:"客户投诉。动词 complain。",ex:{en:"We got three complaints about delivery.",zh:"收到三个物流的客诉"}},
{id:"w075",en:"negative review",zh:"差评",pos:"n.",cat:"fulfill",gloss:"坏评价。好评率 positive rating。",ex:{en:"Two negative reviews mention the gift.",zh:"两个差评提到赠品"}},
{id:"w076",en:"last mile",zh:"尾程 / 最后一公里",pos:"n.",cat:"fulfill",gloss:"从本地仓到买家手上那一段。头程是 first leg。",ex:{en:"Last mile is where we lose the days.",zh:"时间都耗在尾程"}},
{id:"w077",en:"free shipping",zh:"包邮",pos:"n.",cat:"fulfill",gloss:"不收运费。运费 shipping fee。",ex:{en:"Free shipping over 200.",zh:"满 200 包邮"}},
{id:"w078",en:"delivered",zh:"已妥投 / 已签收",pos:"adj.",cat:"fulfill",gloss:"货已经到买家手上。",ex:{en:"How many were delivered on time?",zh:"多少单按时妥投"}},
/* ---------------- 商品定价 product ---------------- */
{id:"w079",en:"SKU",zh:"单品 / 规格",pos:"n.",cat:"product",gloss:"具体到颜色规格的一个货号。读作 S-K-U 或 skew。",ex:{en:"Which SKU are we pushing this week?",zh:"这周主推哪个 SKU"}},
{id:"w080",en:"listing",zh:"商品链接 / 详情页",pos:"n.",cat:"product",gloss:"平台上那个商品页。上架 list，下架 delist。",ex:{en:"The listing is live now.",zh:"链接已经上架了"}},
{id:"w081",en:"launch",zh:"上新",pos:"n./v.",cat:"product",gloss:"新品上线。新品 new product。",ex:{en:"Please add the keywords for the new products.",zh:"加一下新品的词哦"}},
{id:"w082",en:"pricing",zh:"定价",pos:"n.",cat:"product",gloss:"定多少钱。到手价 final price。",ex:{en:"Pricing is different on the two shops.",zh:"两个店定价不一样"}},
{id:"w083",en:"discount",zh:"折扣",zh2:"",pos:"n./v.",cat:"product",gloss:"打折。满减 spend-and-save，秒杀 flash sale。",ex:{en:"How deep is the discount?",zh:"折扣打到多少"}},
{id:"w084",en:"bundle",zh:"组合装 / 套装",pos:"n.",cat:"product",gloss:"几件一起卖。三件套 a three-piece bundle。",ex:{en:"The whitening three-piece bundle is the main push.",zh:"美白三件套是主推"}},
{id:"w085",en:"commission",zh:"佣金",pos:"n.",cat:"product",gloss:"给达人或平台的分成。佣金率 commission rate。",ex:{en:"What commission rate are we offering?",zh:"我们给多少佣金"}},
{id:"w086",en:"gross margin",zh:"毛利",pos:"n.",cat:"product",gloss:"卖价减成本。毛利率 margin 或 gross margin rate。",ex:{en:"The margin can't take another discount.",zh:"毛利撑不住再打折了"}},
{id:"w087",en:"category",zh:"类目",pos:"n.",cat:"product",gloss:"商品分类，比如护肤 skincare、彩妆 makeup。",ex:{en:"We rank fourth in the category.",zh:"我们在类目里排第四"}},
{id:"w088",en:"ranking",zh:"榜单 / 排名",pos:"n.",cat:"product",gloss:"排行榜。上榜 make the ranking。",ex:{en:"Pull the top 10 ahead of us.",zh:"把我们前面的 top10 拉一下"}},
{id:"w089",en:"competitor",zh:"竞品 / 竞对",pos:"n.",cat:"product",gloss:"抢同一批客人的对手。",ex:{en:"What are competitors doing?",zh:"竞品在做什么"}},
{id:"w090",en:"main image",zh:"主图",pos:"n.",cat:"product",gloss:"商品列表里显示的第一张图。",ex:{en:"The main image needs the price on it.",zh:"主图上要有价格"}},
{id:"w091",en:"sample",zh:"样品 / 试用装",pos:"n.",cat:"product",gloss:"寄给达人试用的货。寄样 send samples。",ex:{en:"Have we sent samples to this creator?",zh:"给这个达人寄样了吗"}},
{id:"w092",en:"main push",zh:"主推",pos:"n.",cat:"product",gloss:"这一阶段重点卖的品。",ex:{en:"Which product is the main push this month?",zh:"这个月主推哪个品"}},
{id:"w093",en:"ingredient",zh:"成分",pos:"n.",cat:"product",gloss:"美妆护肤必用。功效 claim / benefit。",ex:{en:"We can't claim that ingredient in Vietnam.",zh:"这个成分在越南不能这么宣称"}},
{id:"w094",en:"shade",zh:"色号",pos:"n.",cat:"product",gloss:"彩妆的颜色编号。",ex:{en:"Which shade is selling best?",zh:"哪个色号卖得最好"}},
/* ---------------- 平台运营 platform ---------------- */
{id:"w095",en:"shop",zh:"店铺",pos:"n.",cat:"platform",gloss:"跨境店 cross-border shop，本土店 local shop。",ex:{en:"The two shops can't share one basis.",zh:"两个店就是不能统一口径"}},
{id:"w096",en:"seller",zh:"商家",pos:"n.",cat:"platform",gloss:"卖东西的一方。卖家后台 seller center。",ex:{en:"Check it in Seller Center.",zh:"在商家后台看"}},
{id:"w097",en:"creator",zh:"达人",pos:"n.",cat:"platform",gloss:"带货的内容作者。头部达人 top creator，也说 influencer / KOL。",ex:{en:"It's a KOL creative, don't auto-exclude.",zh:"这是 KOL 素材，别自动排除"}},
{id:"w098",en:"affiliate",zh:"联盟 / 达人带货",pos:"n.",cat:"platform",gloss:"达人卖货拿佣金的那套机制。",ex:{en:"Most of the GMV comes from affiliate videos.",zh:"大部分成交来自达人视频"}},
{id:"w099",en:"organic traffic",zh:"自然流量",pos:"n.",cat:"platform",gloss:"没花钱来的流量。付费流量 paid traffic。",ex:{en:"Organic traffic is down but paid is flat.",zh:"自然流量掉了，付费没变"}},
{id:"w100",en:"violation",zh:"违规",pos:"n.",cat:"platform",gloss:"踩平台规则。处罚 penalty，封号 account ban。",ex:{en:"The account review passed — no violation.",zh:"账户违规卡审已经审核通过"}},
{id:"w101",en:"appeal",zh:"申诉",pos:"n./v.",cat:"platform",gloss:"对处罚提出异议。",ex:{en:"We filed an appeal yesterday.",zh:"昨天提了申诉"}},
{id:"w102",en:"under review",zh:"审核中 / 卡审",pos:"adj.",cat:"platform",gloss:"平台还在审，没放行。",ex:{en:"The account is still under review.",zh:"这个户还在卡审"}},
{id:"w103",en:"account approved",zh:"下户（开户完成）",pos:"phr.",cat:"platform",gloss:"广告账户批下来能投了。",ex:{en:"We hope the account goes live Monday so we can start.",zh:"希望周一可以下户开始投放"}},
{id:"w104",en:"BC",zh:"商务中心 / BC",pos:"n.",cat:"platform",gloss:"Business Center，管账户的上层结构。读字母。",ex:{en:"Which BC and which account is it on now?",zh:"现在用的是哪个 BC 哪个户"}},
{id:"w105",en:"dashboard",zh:"后台 / 看板",pos:"n.",cat:"platform",gloss:"看数据的界面。你说的「后台」用这个或 back end。",ex:{en:"Walk me through each dashboard, from login to pulling numbers.",zh:"走一遍每个后台从登录到取数的路径"}},
{id:"w106",en:"pull the data",zh:"拉数据 / 取数",pos:"phr.",cat:"platform",gloss:"把报表导出来。也说 export。",ex:{en:"Please remember to pull last week's live-room data.",zh:"老师记得帮我们拉一下上周的直播间数据"}},
{id:"w107",en:"export",zh:"导出",pos:"v./n.",cat:"platform",gloss:"下载成表格。",ex:{en:"Export it and upload to Feishu.",zh:"导出来上传飞书"}},
{id:"w108",en:"log",zh:"登记",pos:"v.",cat:"platform",gloss:"记录到表里。也说 record 或 enter。",ex:{en:"Please log the promo codes.",zh:"登记一下 投流码这些"},note:"你一周说了 14 次「登记」。"},
{id:"w109",en:"sign up",zh:"报名（活动）",pos:"v.",cat:"platform",gloss:"报名参加平台大促。",ex:{en:"Did we sign up for the Double Day campaign?",zh:"我们报名 Double Day 了吗"}},
{id:"w110",en:"go live",zh:"上线 / 开播",pos:"v.",cat:"platform",gloss:"东西正式跑起来。也指开始直播。",ex:{en:"When does it go live?",zh:"什么时候上线"}},
{id:"w111",en:"Shopee",zh:"虾皮",pos:"n.",cat:"platform",gloss:"东南亚电商平台。念 shoppee。",ex:{en:"It's FB traffic going to Shopee local.",zh:"这个是 FB 引流到虾皮本土"}},
{id:"w112",en:"traffic structure",zh:"流量结构",pos:"n.",cat:"platform",gloss:"流量分别从哪来、各占多少。",ex:{en:"Let's look at the traffic structure first.",zh:"先看流量结构"}},
/* ---------------- 财务结算 finance ---------------- */
{id:"w113",en:"settlement",zh:"结算",pos:"n.",cat:"finance",gloss:"平台把钱结给你。动词 settle。",ex:{en:"When is the settlement date?",zh:"什么时候结算"}},
{id:"w114",en:"payment terms",zh:"账期",pos:"n.",cat:"finance",gloss:"多久付一次款。30 天账期 = 30-day payment terms 或 net 30。",ex:{en:"What are the payment terms?",zh:"账期是多久"}},
{id:"w115",en:"invoice",zh:"发票",pos:"n.",cat:"finance",gloss:"收款凭证。开发票 issue an invoice。",ex:{en:"We need the invoice before we can pay.",zh:"要有发票才能付款"}},
{id:"w116",en:"quote",zh:"报价",pos:"n./v.",cat:"finance",gloss:"给个价。询价 get a quote / request a quote。",ex:{en:"No problem, I'll have him request a quote.",zh:"没问题我让他去询价了"}},
{id:"w117",en:"reconcile",zh:"对账",pos:"v.",cat:"finance",gloss:"两边的数对一遍。名词 reconciliation。",ex:{en:"Let's reconcile before month end.",zh:"月底前对一次账"}},
{id:"w118",en:"prepay",zh:"预付",pos:"v.",cat:"finance",gloss:"先付钱。预付款 prepayment / deposit。",ex:{en:"They want us to prepay 30%.",zh:"他们要我们预付 30%"}},
{id:"w119",en:"rebate",zh:"返点",pos:"n.",cat:"finance",gloss:"达到量之后退回来的钱。你跟代理商谈的就是这个。",ex:{en:"What's the rebate if we hit the target?",zh:"达标的话返点多少"}},
{id:"w120",en:"exchange rate",zh:"汇率",pos:"n.",cat:"finance",gloss:"两种货币的换算。",ex:{en:"Which exchange rate are we using?",zh:"用哪个汇率"}},
{id:"w121",en:"reimbursement",zh:"报销",pos:"n.",cat:"finance",gloss:"垫的钱要回来。动词 reimburse。",ex:{en:"Submit it for reimbursement.",zh:"提交报销"}},
{id:"w122",en:"purchase order",zh:"采购单 / PO",pos:"n.",cat:"finance",gloss:"正式下单的凭证。读作 P-O。",ex:{en:"We can't start without a PO.",zh:"没有 PO 开不了工"}},
{id:"w123",en:"cost",zh:"成本",pos:"n.",cat:"finance",gloss:"花的钱。广告场景里 cost 也常指消耗。",ex:{en:"Today's cost is 100.",zh:"今天消耗 100"}},
{id:"w124",en:"payment received",zh:"回款",pos:"phr.",cat:"finance",gloss:"钱到账了。",ex:{en:"Has the payment been received?",zh:"回款到了吗"}},
/* ---------------- 协作流程 collab ---------------- */
{id:"w125",en:"align",zh:"对齐 / 拉齐",pos:"v.",cat:"collab",gloss:"把大家的理解和目标统一。align on something。",ex:{en:"We need to align on the month-end plan before Friday.",zh:"月底活动方案 周五前要对齐哦"}},
{id:"w126",en:"follow up",zh:"跟进",pos:"v.",cat:"collab",gloss:"持续推着一件事往前走。名词 follow-up。",ex:{en:"OK — I'm still following up.",zh:"好的 我一直在跟进的"}},
{id:"w127",en:"chase",zh:"催",pos:"v.",cat:"collab",gloss:"催人办事。比 follow up 更急一点。",ex:{en:"I'm still chasing the contract.",zh:"还在催合同流程"}},
{id:"w128",en:"status",zh:"进度",pos:"n.",cat:"collab",gloss:"事情到哪一步了。问进度用这个词最省事。",ex:{en:"What's the status on these?",zh:"这些啥进度"},note:"催进度只要会这一个词就够用。"},
{id:"w129",en:"blocked",zh:"卡住了",pos:"adj.",cat:"collab",gloss:"被别的事挡住动不了。blocked on X = 卡在 X。",ex:{en:"It's blocked on X. We're waiting on Y.",zh:"卡在 X，在等 Y"}},
{id:"w130",en:"approval",zh:"审批",pos:"n.",cat:"collab",gloss:"要上级批。动词 approve。走审批 go through approval。",ex:{en:"Budget change needs approval.",zh:"改预算要审批"}},
{id:"w131",en:"out of scope",zh:"越权 / 超出职责",pos:"phr.",cat:"collab",gloss:"不是你该动的。你手册里的「越权」用这个最准。",ex:{en:"Changing the budget is out of my scope.",zh:"改预算属于越权"}},
{id:"w132",en:"mentor",zh:"带教人",pos:"n.",cat:"collab",gloss:"带你的人。你手册里带教人和汇报人是同一个。",ex:{en:"I need to confirm with my mentor first.",zh:"我需要先跟带教人确认"},note:"你一周说了 75 次「带教」。"},
{id:"w133",en:"hand over",zh:"转交 / 交接",pos:"v.",cat:"collab",gloss:"把事交给别人。名词 handover。",ex:{en:"I can't share this data — I'll hand you to the BD.",zh:"这部分数据我这边不能提供，我帮你转给 BD"}},
{id:"w134",en:"flag",zh:"反馈 / 提出来",pos:"v.",cat:"collab",gloss:"把问题摆到台面上。比 report 轻，比 complain 中性。",ex:{en:"If anything can't be agreed, flag it in time.",zh:"如果涉及到协商不了的及时反馈"}},
{id:"w135",en:"sync",zh:"同步",pos:"v./n.",cat:"collab",gloss:"互通信息。也指一个短会 a quick sync。",ex:{en:"Please send over the account — let's sync after.",zh:"账号同步过来，之后我们对一下"},note:"你说的「同步下」多数其实是 send / send over，不是 sync。"},
{id:"w136",en:"point of contact",zh:"对接人",pos:"n.",cat:"collab",gloss:"负责跟你联络的那个人。缩写 POC。",ex:{en:"Who's the point of contact on their side?",zh:"他们那边对接人是谁"}},
{id:"w137",en:"agency",zh:"代理商",pos:"n.",cat:"collab",gloss:"帮你投广告或做服务的外部公司。",ex:{en:"I asked the agency to pull the numbers.",zh:"我让代理商拉数了"}},
{id:"w138",en:"deck",zh:"PPT / 汇报文件",pos:"n.",cat:"collab",gloss:"老外几乎不说 PPT，说 deck 或 slides。",ex:{en:"I've added it to the deck.",zh:"PPT 我加进去了"},note:"重要:说 PPT 对方可能听不懂，说 deck。"},
{id:"w139",en:"daily report",zh:"日报",pos:"n.",cat:"collab",gloss:"每天交的进度。周报 weekly report。",ex:{en:"Send the daily report before you leave.",zh:"每天下班前要发日报"}},
{id:"w140",en:"drive",zh:"推进",pos:"v.",cat:"collab",gloss:"主动把事往前推。比 push 正式一点。",ex:{en:"I'll drive the contract this week.",zh:"这周我来推合同"}},
{id:"w141",en:"escalate",zh:"上升 / 找上级",pos:"v.",cat:"collab",gloss:"催不动就往上反映。用之前先提醒对方。",ex:{en:"If there's no reply today, I'll have to escalate.",zh:"今天还没回复我就得往上反映了"},note:"这个词很重，用之前先给对方一次机会。"},
{id:"w142",en:"convert to full-time",zh:"转正",pos:"phr.",cat:"collab",gloss:"实习转正式。",ex:{en:"Two interns want to convert.",zh:"两个实习生想转正"}},
{id:"w143",en:"check with",zh:"跟某人确认",pos:"phr.",cat:"collab",gloss:"问一下某人。别用 run it by —— 二语者容易听不懂。",ex:{en:"Let me check with my mentor.",zh:"我跟带教人确认下"}},
{id:"w144",en:"walk me through",zh:"给我讲一遍流程",pos:"phr.",cat:"collab",gloss:"让对方一步一步演示。非常好用。",ex:{en:"Please walk me through the top-up process.",zh:"把充值流程同步下"}},
{id:"w145",en:"keep me posted",zh:"有进展告诉我",pos:"phr.",cat:"collab",gloss:"结束对话时最好用的一句。",ex:{en:"Keep me posted on this.",zh:"这个有进展跟我说"}},
{id:"w146",en:"take the lead",zh:"牵头",pos:"phr.",cat:"collab",gloss:"谁负责主导这件事。",ex:{en:"Who takes the lead on this?",zh:"这个谁牵头"}},
/* ---------------- 主体合规 entity ---------------- */
{id:"w147",en:"legal entity",zh:"主体（公司实体）",pos:"n.",cat:"entity",gloss:"签合同、收付款的那家公司。你说的「主体」就是它。",ex:{en:"Which legal entity pays in USD?",zh:"我们付款美元的主体是哪个啊"},note:"别说 subject 或 body，那是错的。"},
{id:"w148",en:"contract",zh:"合同",pos:"n.",cat:"entity",gloss:"签的协议。补充协议 addendum / supplementary agreement。",ex:{en:"We can't start running ads before the contract is signed.",zh:"合同未盖章前，是没办法开始投放的"}},
{id:"w149",en:"sign and stamp",zh:"签字盖章",pos:"phr.",cat:"entity",gloss:"中国和越南都要盖章，英美只签字，所以要说全。",ex:{en:"The contract still needs to be signed and stamped.",zh:"合同需要尽快走完审批盖章"}},
{id:"w150",en:"authorization",zh:"授权",pos:"n.",cat:"entity",gloss:"允许对方使用你的品牌或素材。授权书 authorization letter。",ex:{en:"Codes, creators and authorization are BD's side.",zh:"CODE、达人、授权 → BD 负责"}},
{id:"w151",en:"cross-border",zh:"跨境",pos:"adj.",cat:"entity",gloss:"货或钱跨国。跨境店 cross-border shop。",ex:{en:"We're adding brand ads on the cross-border shop tomorrow.",zh:"这个明天上跨境店品广"}},
{id:"w152",en:"local",zh:"本土",pos:"adj.",cat:"entity",gloss:"在当地注册、当地发货。本土店 local shop。",ex:{en:"The local shop has a runaway creative.",zh:"本土店有条素材在跑飞"}},
{id:"w153",en:"compliance",zh:"合规",pos:"n.",cat:"entity",gloss:"符合法规和平台规则。",ex:{en:"Legal needs to check compliance first.",zh:"法务要先看合规"}},
{id:"w154",en:"legal team",zh:"法务",pos:"n.",cat:"entity",gloss:"公司管合同和法律的部门。",ex:{en:"Both legal teams still have objections.",zh:"合同双方法务有异议"}},
{id:"w155",en:"license",zh:"许可证 / 资质",pos:"n.",cat:"entity",gloss:"营业执照、投资许可证这类。",ex:{en:"They asked for our business license.",zh:"他们要我们的营业执照"}},
{id:"w156",en:"verification code",zh:"验证码",pos:"n.",cat:"entity",gloss:"登录或注册时收到的码。",ex:{en:"This email needs a verification code.",zh:"这个邮箱需要一个验证码"}},
{id:"w157",en:"access",zh:"权限",pos:"n.",cat:"entity",gloss:"能不能进、能不能看。没权限 I don't have access。",ex:{en:"I don't have access to that.",zh:"我这边没这个权限"}},
{id:"w158",en:"reporting line",zh:"汇报线",pos:"n.",cat:"entity",gloss:"你向谁汇报。",ex:{en:"Your mentor and your reporting line are the same person.",zh:"本岗位的带教人与汇报人是同一个人"}},
];
