/* 自动生成，别手改。
 * AUTO_IPA  词典音标（多词短语由成分词音标拼接）
 * AUDIO     单词的真人录音文件（Wikimedia Commons，CC 授权）
 * AUDIO_SEQ 多词短语的逐词真人录音；整条短语没有真人录音，整读走语音合成
 */
window.AUTO_IPA = {
  w001:"/ˈbʌdʒ.ɪt/",
  w002:"/spɛnd/",
  w003:"/kɹiˈeɪtɪv/",
  w004:"/ɪksˈkluːd/",
  w005:"/ˈpɹəʊməʊ kəʊd/",
  w006:"/ˈlɝnɪŋ ·phase/",
  w007:"/bɝn ˈbʌdʒ.ɪt/",
  w008:"/dɪˈlɪv(ə)ɹi/",
  w009:"/bɹand ædz/",
  w010:"/ˈɔːdi.əns/",
  w011:"/skeɪl ʌp/",
  w012:"/tɑp ʌp/",
  w013:"/ˈbæləns/",
  w014:"/ˈpleɪsmənt/",
  w015:"/æd ɡɹuːp/",
  w016:"/kæmˈpeɪn/",
  w017:"/bɪd/",
  w020:"/pɔz/",
  w024:"/ˈbeɪsɪs/",
  w026:"/·refund ɹeɪt/",
  w029:"/kənˈvɝʒən/",
  w031:"/wik ˈoʊ.vɚ wik/",
  w032:"/ɪmˈpɹɛʃənz/",
  w033:"/ʃɛəɹ/",
  w034:"/əˈnɑməli/",
  w036:"/ˈmɑɹkɪt waɪd/",
  w037:"/haɪˈpɑː.θə.sɪs/",
  w038:"/ˈsiːdɪŋ/",
  w039:"/kənˈvɝʒən ɛnd/",
  w041:"/lɪv ɹuːm/",
  w042:"/hoʊst/",
  w043:"/skɹɪpt/",
  w044:"/huːk/",
  w046:"/ɹuːm ˈɛntɹi ɹeɪt/",
  w047:"/wɑt͡ʃ taɪm/",
  w048:"/[pʷʊʃ] seɪl/",
  w049:"/peɪn pɔɪnt/",
  w050:"/ˈsɛlɪŋ pɔɪnt/",
  w052:"/ˈvaʊtʃə(ɹ)/",
  w054:"/ˈɹɑstɚ/",
  w055:"/æd the ˈpɹɒd.əkt lɪŋk/",
  w056:"/ˈpɹɒd.əkt kɑɹd/",
  w057:"/ʃɔɹt ˈvɪ.diˌoʊ/",
  w058:"/skɹiːn ·recording/",
  w059:"/ˈbæk.ɡɹaʊnd/",
  w060:"/poʊst ·mortem/",
  w061:"/ˈɔɹdɚ/",
  w063:"/ʃɪp/",
  w064:"/dɪˈlɪv(ə)ɹi taɪm/",
  w065:"/ˈtɹækɪŋ ˈnʌmbə/",
  w066:"/aʊt of stɑk/",
  w068:"/ɪnˈvɛn.tə.ɹi/",
  w070:"/ˈkʌstəmz ·clearance/",
  w071:"/ɹɪˈtɝn/",
  w073:"/ˈæf.tɚ seɪlz/",
  w074:"/kəmˈpleɪnt/",
  w075:"/-ɾɪv ɹɪˈvjuː/",
  w076:"/læst maɪ̯l/",
  w077:"/fɹiː ˈʃɪpɪŋ/",
  w078:"/dɪˈlɪv.ɚd/",
  w080:"/ˈlɪstɪŋ/",
  w081:"/lɔnt͡ʃ/",
  w082:"/ˈpɹaɪsɪŋ/",
  w083:"/dɪsˈkaʊnt/",
  w084:"/ˈbʌnd(ə)l/",
  w085:"/kəˈmɪʃən/",
  w086:"/ɡɹoʊs ˈmɑːɹdʒ(ə)n/",
  w087:"/ˈkætəˌɡɔɹi/",
  w088:"/ˈɹænk.ɪŋ/",
  w090:"/meɪn ˈɪmɪd͡ʒ/",
  w091:"/sæːm.pəl/",
  w092:"/meɪn [pʷʊʃ]/",
  w093:"/ɪnˈɡɹiːdi.ənt/",
  w094:"/ʃeɪd/",
  w095:"/ʃɑp/",
  w096:"/ˈsɛlə/",
  w097:"/kɹiˈeɪtɚ/",
  w098:"/əˈfɪl.i.et/",
  w099:"/ɔɹˈɡænɪk ˈtɹæfɪk/",
  w100:"/ˌvaɪəˈleɪʃən/",
  w101:"/əˈpiːl/",
  w102:"/ˈʌndɚ ɹɪˈvjuː/",
  w103:"/ə.ˈkaʊnt əˈpɹuːvd/",
  w104:"/biːˈsiː/",
  w105:"/ˈdæʃˌbɔː(ɹ)d/",
  w106:"/[pʰʊːɫ] the ˈdætə/",
  w107:"/ˈɛks.pɔːt/",
  w108:"/lɑɡ/",
  w109:"/saɪn ʌp/",
  w110:"/ɡoʊ lɪv/",
  w112:"/ˈtɹæfɪk ˈstɹʌktʃɚ/",
  w113:"/ˈset.l.mənt/",
  w114:"/ˈpeɪmənt tɝmz/",
  w115:"/ˈɪnˌvɔɪs/",
  w116:"/kwəʊt/",
  w117:"/ˈɹɛkənsaɪl/",
  w119:"/ɹəˈbeɪt/",
  w120:"/ɛksˈtʃeɪndʒ ɹeɪt/",
  w121:"/ˌɹiː.ɪmˈbɜːs.mənt/",
  w122:"/ˈpɝtʃəs ˈɔɹdɚ/",
  w123:"/ˈkɔst/",
  w124:"/ˈpeɪmənt ɹɪˈsiːvd/",
  w125:"/æˈlaɪn/",
  w126:"/ˈfɑloʊ ʌp/",
  w127:"/tʃeɪs/",
  w128:"/ˈstæt.əs/",
  w130:"/əˈpɹuvəl/",
  w131:"/aʊt of ˈskoʊp/",
  w132:"/ˈmɛn.tɔː/",
  w133:"/hænd ˈoʊ.vɚ/",
  w134:"/flæɡ/",
  w135:"/sɪŋk/",
  w136:"/pɔɪnt of ·contact/",
  w137:"/ˈeɪ.dʒən.si/",
  w138:"/dɛk/",
  w139:"/ˈdeɪli ɹɪˈpɔɹt/",
  w140:"/dɹaɪv/",
  w141:"/ˈɛs.kə.leɪt/",
  w142:"/ˈkɑn.vəɹt to fʊl taɪm/",
  w143:"/t͡ʃɛk ·with/",
  w144:"/wɔk me through/",
  w145:"/kiːp me poʊstɪd/",
  w146:"/teɪk the lɛd/",
  w147:"/ˈliɡəl ˈen.tɪ.ti/",
  w148:"/ˈkɑntɹækt/",
  w149:"/saɪn and stæmp/",
  w151:"/kɹɔs ˈbɔɹdɚ/",
  w152:"/ˈloʊkl̩/",
  w153:"/kəmˈplaɪəns/",
  w154:"/ˈliɡəl tiːm/",
  w155:"/ˈlaɪsəns/",
  w156:"/·verification kəʊd/",
  w157:"/ˈækˌsɛs/",
  w158:"/·reporting laɪn/",
};
window.AUDIO = {
  w001:"budget.ogg",
  w002:"spend.ogg",
  w004:"exclude.ogg",
  w008:"delivery.ogg",
  w010:"audience.wav",
  w013:"balance.ogg",
  w014:"placement.ogg",
  w016:"campaign.ogg",
  w017:"bid.ogg",
  w019:"whitelist.ogg",
  w020:"pause.ogg",
  w024:"basis.ogg",
  w029:"conversion.ogg",
  w032:"impressions.ogg",
  w033:"share.ogg",
  w034:"anomaly.ogg",
  w037:"hypothesis.ogg",
  w042:"host.ogg",
  w043:"script.ogg",
  w044:"hook.ogg",
  w054:"roster.ogg",
  w059:"background.ogg",
  w061:"order.ogg",
  w063:"ship.ogg",
  w071:"return.ogg",
  w072:"refund.ogg",
  w074:"complaint.ogg",
  w078:"delivered.ogg",
  w081:"launch.ogg",
  w083:"discount.ogg",
  w084:"bundle.ogg",
  w085:"commission.ogg",
  w087:"category.ogg",
  w093:"ingredient.wav",
  w094:"shade.ogg",
  w095:"shop.ogg",
  w097:"creator.ogg",
  w098:"affiliate.ogg",
  w101:"appeal.ogg",
  w104:"bc.ogg",
  w107:"export.wav",
  w108:"log.ogg",
  w113:"settlement.ogg",
  w115:"invoice.ogg",
  w116:"quote.ogg",
  w117:"reconcile.ogg",
  w123:"cost.ogg",
  w127:"chase.ogg",
  w128:"status.ogg",
  w129:"blocked.ogg",
  w130:"approval.ogg",
  w134:"flag.ogg",
  w137:"agency.ogg",
  w138:"deck.ogg",
  w140:"drive.ogg",
  w148:"contract.ogg",
  w152:"local.ogg",
  w153:"compliance.ogg",
  w155:"license.ogg",
  w157:"access.ogg",
};
window.AUDIO_SEQ = {
  w005:[{"w": "promo", "f": "promo.ogg"}, {"w": "code", "f": "code.wav"}],
  w006:[{"w": "learning", "f": "learning.ogg"}, {"w": "phase", "f": null}],
  w007:[{"w": "burn", "f": "burn.ogg"}, {"w": "budget", "f": "budget.ogg"}],
  w009:[{"w": "brand", "f": "brand.ogg"}, {"w": "ads", "f": "ads.ogg"}],
  w011:[{"w": "scale", "f": "scale.ogg"}, {"w": "up", "f": "up.ogg"}],
  w012:[{"w": "top", "f": "top.ogg"}, {"w": "up", "f": "up.ogg"}],
  w015:[{"w": "ad", "f": "ad.ogg"}, {"w": "group", "f": null}],
  w026:[{"w": "refund", "f": "refund.ogg"}, {"w": "rate", "f": "rate.ogg"}],
  w031:[{"w": "week", "f": "week.ogg"}, {"w": "over", "f": "over.ogg"}, {"w": "week", "f": "week.ogg"}],
  w036:[{"w": "market", "f": "market.ogg"}, {"w": "wide", "f": "wide.ogg"}],
  w039:[{"w": "conversion", "f": "conversion.ogg"}, {"w": "end", "f": "end.ogg"}],
  w041:[{"w": "live", "f": "live.ogg"}, {"w": "room", "f": null}],
  w046:[{"w": "room", "f": null}, {"w": "entry", "f": "entry.wav"}, {"w": "rate", "f": "rate.ogg"}],
  w047:[{"w": "watch", "f": "watch.ogg"}, {"w": "time", "f": "time.ogg"}],
  w048:[{"w": "push", "f": "push.ogg"}, {"w": "sale", "f": "sale.ogg"}],
  w049:[{"w": "pain", "f": "pain.ogg"}, {"w": "point", "f": "point.ogg"}],
  w050:[{"w": "selling", "f": null}, {"w": "point", "f": "point.ogg"}],
  w055:[{"w": "add", "f": "add.ogg"}, {"w": "the", "f": null}, {"w": "product", "f": null}, {"w": "link", "f": "link.ogg"}],
  w056:[{"w": "product", "f": null}, {"w": "card", "f": "card.ogg"}],
  w057:[{"w": "short", "f": "short.ogg"}, {"w": "video", "f": "video.ogg"}],
  w058:[{"w": "screen", "f": "screen.ogg"}, {"w": "recording", "f": null}],
  w060:[{"w": "post", "f": "post.ogg"}, {"w": "mortem", "f": null}],
  w064:[{"w": "delivery", "f": "delivery.ogg"}, {"w": "time", "f": "time.ogg"}],
  w066:[{"w": "out", "f": "out.ogg"}, {"w": "of", "f": null}, {"w": "stock", "f": "stock.ogg"}],
  w070:[{"w": "customs", "f": "customs.ogg"}, {"w": "clearance", "f": null}],
  w073:[{"w": "after", "f": "after.ogg"}, {"w": "sales", "f": "sales.ogg"}],
  w075:[{"w": "negative", "f": "negative.ogg"}, {"w": "review", "f": "review.ogg"}],
  w076:[{"w": "last", "f": "last.ogg"}, {"w": "mile", "f": "mile.ogg"}],
  w077:[{"w": "free", "f": "free.ogg"}, {"w": "shipping", "f": "shipping.wav"}],
  w086:[{"w": "gross", "f": "gross.ogg"}, {"w": "margin", "f": "margin.ogg"}],
  w090:[{"w": "main", "f": "main.ogg"}, {"w": "image", "f": "image.ogg"}],
  w092:[{"w": "main", "f": "main.ogg"}, {"w": "push", "f": "push.ogg"}],
  w099:[{"w": "organic", "f": "organic.ogg"}, {"w": "traffic", "f": "traffic.ogg"}],
  w102:[{"w": "under", "f": "under.ogg"}, {"w": "review", "f": "review.ogg"}],
  w103:[{"w": "account", "f": "account.ogg"}, {"w": "approved", "f": "approved.ogg"}],
  w106:[{"w": "pull", "f": "pull.ogg"}, {"w": "the", "f": null}, {"w": "data", "f": "data.ogg"}],
  w109:[{"w": "sign", "f": "sign.ogg"}, {"w": "up", "f": "up.ogg"}],
  w110:[{"w": "go", "f": "go.ogg"}, {"w": "live", "f": "live.ogg"}],
  w112:[{"w": "traffic", "f": "traffic.ogg"}, {"w": "structure", "f": "structure.ogg"}],
  w114:[{"w": "payment", "f": "payment.ogg"}, {"w": "terms", "f": "terms.ogg"}],
  w120:[{"w": "exchange", "f": "exchange.ogg"}, {"w": "rate", "f": "rate.ogg"}],
  w122:[{"w": "purchase", "f": "purchase.ogg"}, {"w": "order", "f": "order.ogg"}],
  w124:[{"w": "payment", "f": "payment.ogg"}, {"w": "received", "f": "received.ogg"}],
  w126:[{"w": "follow", "f": "follow.ogg"}, {"w": "up", "f": "up.ogg"}],
  w131:[{"w": "out", "f": "out.ogg"}, {"w": "of", "f": null}, {"w": "scope", "f": "scope.ogg"}],
  w133:[{"w": "hand", "f": "hand.ogg"}, {"w": "over", "f": "over.ogg"}],
  w136:[{"w": "point", "f": "point.ogg"}, {"w": "of", "f": null}, {"w": "contact", "f": "contact.ogg"}],
  w139:[{"w": "daily", "f": "daily.ogg"}, {"w": "report", "f": "report.ogg"}],
  w142:[{"w": "convert", "f": "convert.ogg"}, {"w": "to", "f": null}, {"w": "full", "f": "full.ogg"}, {"w": "time", "f": "time.ogg"}],
  w143:[{"w": "check", "f": "check.ogg"}, {"w": "with", "f": null}],
  w144:[{"w": "walk", "f": "walk.ogg"}, {"w": "me", "f": null}, {"w": "through", "f": null}],
  w145:[{"w": "keep", "f": "keep.ogg"}, {"w": "me", "f": null}, {"w": "posted", "f": "posted.ogg"}],
  w146:[{"w": "take", "f": "take.ogg"}, {"w": "the", "f": null}, {"w": "lead", "f": "lead.ogg"}],
  w147:[{"w": "legal", "f": "legal.ogg"}, {"w": "entity", "f": "entity.ogg"}],
  w149:[{"w": "sign", "f": "sign.ogg"}, {"w": "and", "f": null}, {"w": "stamp", "f": "stamp.ogg"}],
  w151:[{"w": "cross", "f": "cross.ogg"}, {"w": "border", "f": "border.ogg"}],
  w154:[{"w": "legal", "f": "legal.ogg"}, {"w": "team", "f": "team.ogg"}],
  w156:[{"w": "verification", "f": null}, {"w": "code", "f": "code.wav"}],
  w158:[{"w": "reporting", "f": null}, {"w": "line", "f": "line.ogg"}],
};
