/* ===== questions.js 题库 =====
   window.QUESTIONS = [ ... ]，每题字段见 README。
   - level: 1预备 / 2基础 / 3提升 / 4冲刺(真题)
   - type : choice(四选一) | fill(填空) | solve(解答)
   - stem/options/explanation/steps 里公式用 $...$ 包（KaTeX 渲染）
   数学答案已逐题核算；你可以照格式往下加题。
*/
window.QUESTIONS = [

/* ==================================================================
   零、启蒙 · 数学扫盲 (level 0)  —— 连根号/字母/次方都忘了也能做
   配套读本见 lessons.js（首页「📘 从零开始」）
   ================================================================== */
{ id:'z01', module:'literacy', topic:'用字母表示数', level:0, type:'choice',
  stem:'小明有 $x$ 块糖，妈妈又给了 3 块，现在一共有几块？',
  options:['$x+3$','$3x$','$x-3$','$x\\times3$'], answer:0,
  explanation:'"又给了 3 块"就是在原来的基础上加 3。',
  steps:['原来有 $x$ 块','增加 3 块就是 $x+3$'],
  optionNotes:['正确：原来的加上 3','$3x$ 是"3 乘 x"，意思不对','那是少了 3 块','那是 x 的 3 倍，不对'] },

{ id:'z02', module:'literacy', topic:'用字母表示数', level:0, type:'choice',
  stem:'$2x$ 表示的是',
  options:['2 加 x','2 乘以 x','x 的 2 倍再加 2','二十几'], answer:1,
  explanation:'数字和字母挨着写，中间省略了乘号。',
  steps:['$2x$ 就是 $2\\times x$','数字和字母挨着 = 相乘'],
  optionNotes:['不是加','正确：$2\\times x$','没有额外加 2','这不是一个具体数'] },

{ id:'z03', module:'literacy', topic:'正数负数', level:0, type:'choice',
  stem:'$2-5=$',
  options:['$3$','$-3$','$7$','$-7$'], answer:1,
  explanation:'从 2 往左（变小的方向）走 5 步。',
  steps:['在数轴上从 2 出发','往左走 5 步：$2\\to1\\to0\\to-1\\to-2\\to-3$','结果是 $-3$'],
  optionNotes:['方向反了','正确：走到 $-3$','那是 $2+5$','算多了'] },

{ id:'z04', module:'literacy', topic:'正数负数', level:0, type:'fill',
  stem:'$-3+5=$ ______',
  answer:['2'],
  explanation:'从 $-3$ 往右走 5 步。',
  steps:['从 $-3$ 出发往右走 5 步','$-3\\to-2\\to-1\\to0\\to1\\to2$，到 $2$'] },

{ id:'z05', module:'literacy', topic:'分数小数', level:0, type:'fill',
  stem:'$\\dfrac12+\\dfrac12=$ ______',
  answer:['1'],
  explanation:'两个"一半"合起来是一整个。',
  steps:['$\\dfrac12$ 是一半','两个一半拼起来 = 1'] },

{ id:'z06', module:'literacy', topic:'分数小数', level:0, type:'choice',
  stem:'$\\dfrac14$ 写成小数是',
  options:['$0.4$','$0.25$','$0.5$','$1.4$'], answer:1,
  explanation:'四分之一 = 0.25（把 1 平均切 4 份，取 1 份）。',
  steps:['$\\dfrac14$ 是把 1 切成 4 份取 1 份','$1\\div4=0.25$'],
  optionNotes:['那不是四分之一','正确：$\\dfrac14=0.25$','那是二分之一','把小数点点错了'] },

{ id:'z07', module:'literacy', topic:'平方与次方', level:0, type:'choice',
  stem:'$3^2$（3 的平方）等于',
  options:['$6$','$9$','$5$','$8$'], answer:1,
  explanation:'平方就是自己乘自己：$3\\times3$。',
  steps:['$3^2=3\\times3$','$=9$'],
  optionNotes:['那是 $3\\times2$，看错了','正确：$3\\times3=9$','那是 $3+2$','那是 $2^3$'] },

{ id:'z08', module:'literacy', topic:'平方与次方', level:0, type:'fill',
  stem:'$5^2=$ ______',
  answer:['25'],
  explanation:'$5\\times5$。',
  steps:['$5^2=5\\times5=25$'] },

{ id:'z09', module:'literacy', topic:'平方与次方', level:0, type:'fill',
  stem:'$2^3=$ ______（三个 2 相乘）',
  answer:['8'],
  explanation:'右上角的 3 表示乘 3 个 2。',
  steps:['$2^3=2\\times2\\times2$','$=8$'] },

{ id:'z10', module:'literacy', topic:'认识根号', level:0, type:'choice',
  stem:'$\\sqrt{9}$（根号 9）等于',
  options:['$3$','$4.5$','$81$','$18$'], answer:0,
  explanation:'根号反过来问："谁的平方等于 9？"',
  steps:['找一个数，它的平方等于 9','$3\\times3=9$，所以 $\\sqrt9=3$'],
  optionNotes:['正确：$3^2=9$','根号不是除以 2','那是 $9^2$','那是 $9\\times2$'] },

{ id:'z11', module:'literacy', topic:'认识根号', level:0, type:'fill',
  stem:'$\\sqrt{16}=$ ______',
  answer:['4'],
  explanation:'哪个数的平方是 16？',
  steps:['$4\\times4=16$','所以 $\\sqrt{16}=4$'] },

{ id:'z12', module:'literacy', topic:'认识根号', level:0, type:'fill',
  stem:'$\\sqrt{25}=$ ______',
  answer:['5'],
  explanation:'哪个数的平方是 25？',
  steps:['$5\\times5=25$','所以 $\\sqrt{25}=5$'] },

{ id:'z13', module:'literacy', topic:'运算顺序', level:0, type:'choice',
  stem:'$2+3\\times4=$',
  options:['$20$','$14$','$24$','$9$'], answer:1,
  explanation:'先乘除后加减：先算 $3\\times4$。',
  steps:['先算乘法 $3\\times4=12$','再加：$2+12=14$'],
  optionNotes:['这是从左往右硬算的错误','正确：先乘后加得 14','算错了','漏了乘法'] },

{ id:'z14', module:'literacy', topic:'运算顺序', level:0, type:'fill',
  stem:'$(1+2)\\times3=$ ______',
  answer:['9'],
  explanation:'有括号先算括号。',
  steps:['先算括号：$1+2=3$','再乘：$3\\times3=9$'] },

{ id:'z15', module:'literacy', topic:'代入求值', level:0, type:'choice',
  stem:'当 $x=2$ 时，$x+3$ 等于',
  options:['$5$','$6$','$23$','$1$'], answer:0,
  explanation:'把 $x$ 换成 2 再算。',
  steps:['把 $x$ 换成 2','$2+3=5$'],
  optionNotes:['正确：$2+3=5$','那是 $2\\times3$','把数字拼一起了','那是 $x-3$? 也不对'] },

{ id:'z16', module:'literacy', topic:'代入求值', level:0, type:'fill',
  stem:'当 $x=3$ 时，$2x+1=$ ______',
  answer:['7'],
  explanation:'$2x$ 是 2 乘 x，先乘后加。',
  steps:['把 $x$ 换成 3：$2\\times3+1$','先乘：$6+1$','$=7$'] },

{ id:'z17', module:'literacy', topic:'代入求值', level:0, type:'fill',
  stem:'当 $x=3$ 时，$x^2=$ ______',
  answer:['9'],
  explanation:'$x^2$ 是 $x\\times x$。',
  steps:['把 $x$ 换成 3：$3^2$','$=3\\times3=9$'] },

{ id:'z18', module:'literacy', topic:'解简单方程', level:0, type:'choice',
  stem:'解方程 $x+3=7$，$x$ 等于',
  options:['$10$','$4$','$21$','$3$'], answer:1,
  explanation:'两边同时减 3（加过去的减回来）。',
  steps:['两边同时减 3','$x=7-3=4$'],
  optionNotes:['那是 $7+3$','正确：$x=4$','那是 $7\\times3$','没解出来'] },

{ id:'z19', module:'literacy', topic:'解简单方程', level:0, type:'fill',
  stem:'解方程 $2x=10$，$x=$ ______',
  answer:['5'],
  explanation:'两边同时除以 2（乘上去的除回来）。',
  steps:['两边同时除以 2','$x=10\\div2=5$'] },

{ id:'z20', module:'literacy', topic:'认识函数', level:0, type:'choice',
  stem:'已知 $f(x)=x+1$，那么 $f(2)$ 等于',
  options:['$f\\times2$','$3$','$2$','$12$'], answer:1,
  explanation:'把 2 投进"加 1"这台机器。',
  steps:['$f(2)$ 就是把 2 代入 $x+1$','$2+1=3$'],
  optionNotes:['$f(2)$ 不是 f 乘 2','正确：$2+1=3$','忘了加 1','把数字拼一起了'] },

{ id:'z21', module:'literacy', topic:'认识函数', level:0, type:'fill',
  stem:'已知 $f(x)=2x$，求 $f(3)=$ ______',
  answer:['6'],
  explanation:'把 3 投进"乘 2"这台机器。',
  steps:['$f(3)$ 就是把 3 代入 $2x$','$2\\times3=6$'] },

/* ---- 启蒙·补充题（让每个扫盲点都有 4 道左右，过关小测够用）---- */
{ id:'z22', module:'literacy', topic:'用字母表示数', level:0, type:'fill',
  stem:'一支笔 $x$ 元，买 3 支要多少钱？（写成式子）', answer:['3x','3*x'],
  explanation:'单价 × 数量。', steps:['每支 $x$ 元，3 支就是 $3\\times x=3x$'] },
{ id:'z23', module:'literacy', topic:'用字母表示数', level:0, type:'choice',
  stem:'比 $x$ 大 5 的数是', options:['$x+5$','$5x$','$x-5$','$x\\div5$'], answer:0,
  explanation:'"大 5"就是加 5。', steps:['比 $x$ 大 5 → $x+5$'],
  optionNotes:['正确','那是 x 的 5 倍','那是小 5','那是除以 5'] },
{ id:'z24', module:'literacy', topic:'正数负数', level:0, type:'fill',
  stem:'$-5+3=$ ______', answer:['-2'],
  explanation:'从 -5 往右走 3 步。', steps:['$-5\\to-4\\to-3\\to-2$，到 $-2$'] },
{ id:'z25', module:'literacy', topic:'正数负数', level:0, type:'choice',
  stem:'$0-4=$', options:['$4$','$-4$','$0$','$-0$'], answer:1,
  explanation:'从 0 往左走 4 步。', steps:['$0-4=-4$'],
  optionNotes:['方向反了','正确','不是 0','没有 -0 这种写法'] },
{ id:'z26', module:'literacy', topic:'分数小数', level:0, type:'fill',
  stem:'$\\dfrac12$ 写成小数是 ______', answer:['0.5'],
  explanation:'二分之一 = 0.5。', steps:['$1\\div2=0.5$'] },
{ id:'z27', module:'literacy', topic:'分数小数', level:0, type:'choice',
  stem:'$\\dfrac34+\\dfrac14=$', options:['$\\dfrac12$','$1$','$\\dfrac47$','$\\dfrac44$… 等于几?'], answer:1,
  explanation:'分母相同，分子相加：$3+1=4$，$\\frac44=1$。', steps:['$\\dfrac34+\\dfrac14=\\dfrac{3+1}{4}=\\dfrac44=1$'],
  optionNotes:['分子要相加','正确：合成一整个','分母不能相加','$\\frac44$ 就是 1'] },
{ id:'z28', module:'literacy', topic:'运算顺序', level:0, type:'fill',
  stem:'$6-2\\times3=$ ______', answer:['0'],
  explanation:'先乘后减。', steps:['先算 $2\\times3=6$','再 $6-6=0$'] },
{ id:'z29', module:'literacy', topic:'运算顺序', level:0, type:'choice',
  stem:'$(4-1)\\times2=$', options:['$7$','$6$','$2$','$8$'], answer:1,
  explanation:'先算括号。', steps:['括号 $4-1=3$','$3\\times2=6$'],
  optionNotes:['没先算括号','正确','算错','算错'] },
{ id:'z30', module:'literacy', topic:'解简单方程', level:0, type:'fill',
  stem:'解方程 $x-4=1$，$x=$ ______', answer:['5'],
  explanation:'两边加 4。', steps:['两边同时加 4：$x=1+4=5$'] },
{ id:'z31', module:'literacy', topic:'解简单方程', level:0, type:'choice',
  stem:'解方程 $3x=9$，$x=$', options:['$27$','$3$','$6$','$12$'], answer:1,
  explanation:'两边除以 3。', steps:['两边同时除以 3：$x=9\\div3=3$'],
  optionNotes:['那是 $3\\times9$','正确','算错','算错'] },
{ id:'z32', module:'literacy', topic:'认识函数', level:0, type:'fill',
  stem:'已知 $f(x)=x-2$，求 $f(5)=$ ______', answer:['3'],
  explanation:'把 5 投进去。', steps:['$f(5)=5-2=3$'] },
{ id:'z33', module:'literacy', topic:'认识函数', level:0, type:'choice',
  stem:'已知 $f(x)=3x$，$f(2)=$', options:['$5$','$6$','$32$','$1$'], answer:1,
  explanation:'把 2 投进去，$3\\times2$。', steps:['$f(2)=3\\times2=6$'],
  optionNotes:['那是 3+2','正确','把数字拼一起了','不对'] },

/* ==================================================================
   一、预备 · 初高中衔接 (level 1)
   ================================================================== */
// —— 不等式（配套第10课，之前没有题）——
{ id:'n01', module:'prep', topic:'不等式', level:1, type:'choice',
  stem:'下列哪个数满足 $x\\ge 2$？', options:['$1$','$0$','$2$','$-1$'], answer:2,
  explanation:'$\\ge$ 含"等于"，2 本身也满足。', steps:['$x\\ge2$ 表示 x 是 2 或比 2 大','选项里只有 2 满足'],
  optionNotes:['1 比 2 小','0 比 2 小','正确：2 满足（含等于）','负数更小'] },
{ id:'n02', module:'prep', topic:'不等式', level:1, type:'fill',
  stem:'解不等式 $x-1\\ge 0$，得 $x\\ge$ ______（填数字）', answer:['1'],
  explanation:'像解方程那样移项。', steps:['两边同时加 1：$x\\ge 1$'] },
{ id:'n03', module:'prep', topic:'不等式', level:1, type:'choice',
  stem:'$x\\le 2$ 表示 x 是', options:['比 2 大的数','是 2 或比 2 小的数','只能是 2','比 2 大或等于 2'], answer:1,
  explanation:'$\\le$ = 小于或等于。', steps:['$\\le$ 读作"小于或等于"','所以 x 是 2 或比 2 小'],
  optionNotes:['方向反了','正确','不止能取 2','那是 $\\ge$'] },
{ id:'p01', module:'prep', topic:'定义域', level:1, type:'choice',
  stem:'函数 $f(x)=\\sqrt{x-2}$ 的定义域是',
  options:['$x>2$','$x\\ge 2$','$x\\le 2$','全体实数'], answer:1,
  explanation:'根号里的东西不能是负数，所以要 $x-2\\ge 0$。',
  steps:['根号里 $\\ge 0$：$x-2\\ge 0$','解得 $x\\ge 2$'],
  optionNotes:['漏了等号，$x=2$ 时根号里是 0，可以取','正确：$x-2\\ge0$','不等号方向反了','分母/根号有限制，不是全体'] },

{ id:'p02', module:'prep', topic:'定义域', level:1, type:'choice',
  stem:'函数 $f(x)=\\dfrac{1}{x-3}$ 的定义域是',
  options:['$x\\ne 3$','$x>3$','$x\\ge 3$','全体实数'], answer:0,
  explanation:'分母不能等于 0。',
  steps:['分母 $x-3\\ne 0$','所以 $x\\ne 3$'],
  optionNotes:['正确：分母不为 0','分母只要不为 0，不用大于','同上','$x=3$ 时分母为 0，不行'] },

{ id:'p03', module:'prep', topic:'指数对数', level:1, type:'choice',
  stem:'$2^{3}\\cdot 2^{2}=$',
  options:['$2^{5}=32$','$2^{6}=64$','$4^{5}$','$2^{1}$'], answer:0,
  explanation:'同底数相乘，指数相加。',
  steps:['$a^m\\cdot a^n=a^{m+n}$','$2^{3+2}=2^{5}=32$'],
  optionNotes:['正确：指数相加 $3+2=5$','指数相乘错了','底数不变，不是 4','指数是相加不是相减'] },

{ id:'p04', module:'prep', topic:'指数对数', level:1, type:'fill',
  stem:'化简 $(x^{2})^{3}=$ ______',
  answer:['x^6','x^{6}'],
  explanation:'幂的幂，指数相乘。',
  steps:['$(a^m)^n=a^{mn}$','$(x^2)^3=x^{2\\times3}=x^6$'] },

{ id:'p05', module:'prep', topic:'指数对数', level:1, type:'fill',
  stem:'把 $x^{-2}$ 写成分数形式：______',
  answer:['1/x^2','1/x^{2}','\\frac{1}{x^2}'],
  explanation:'负指数就是取倒数。',
  steps:['$a^{-n}=\\dfrac{1}{a^n}$','$x^{-2}=\\dfrac{1}{x^2}$'] },

{ id:'p06', module:'prep', topic:'指数对数', level:1, type:'fill',
  stem:'$\\ln e^{3}=$ ______',
  answer:['3'],
  explanation:'$\\ln$ 和 $e$ 是一对逆运算，$\\ln e^x=x$。',
  steps:['$\\ln e^x = x$','所以 $\\ln e^3 = 3$'] },

{ id:'p07', module:'prep', topic:'三角函数', level:1, type:'choice',
  stem:'$\\sin\\dfrac{\\pi}{2}=$',
  options:['$0$','$\\dfrac12$','$1$','$-1$'], answer:2,
  explanation:'$\\frac{\\pi}{2}$ 就是 90°，正弦值为 1。',
  steps:['$\\frac{\\pi}{2}=90^\\circ$','$\\sin 90^\\circ = 1$'],
  optionNotes:['那是 $\\sin 0$','那是 $\\sin\\frac{\\pi}{6}$','正确','正弦最小才是 -1'] },

{ id:'p08', module:'prep', topic:'三角函数', level:1, type:'fill',
  stem:'$\\sin^{2}x+\\cos^{2}x=$ ______',
  answer:['1'],
  explanation:'三角最基本的平方关系，必须记死。',
  steps:['平方关系：$\\sin^2x+\\cos^2x=1$（恒等式，任何 x 都成立）'] },

{ id:'p09', module:'prep', topic:'因式分解', level:1, type:'choice',
  stem:'$x^{2}-5x+6=$',
  options:['$(x-2)(x-3)$','$(x+2)(x+3)$','$(x-1)(x-6)$','$(x-2)(x+3)$'], answer:0,
  explanation:'找两个数，乘积是 6、和是 5：就是 2 和 3。',
  steps:['要凑：两数之积 $=6$，两数之和 $=5$','$2\\times3=6,\\ 2+3=5$','所以 $=(x-2)(x-3)$'],
  optionNotes:['正确','展开是 $x^2+5x+6$，符号不对','$1\\times6=6$ 但 $1+6=7$，不对','展开中间项是 $+x$，不对'] },

{ id:'p10', module:'prep', topic:'因式分解', level:1, type:'fill',
  stem:'解方程 $x^{2}-x-2=0$，两个根是 ______（用逗号隔开）',
  answer:['2,-1','-1,2','x=2,x=-1'],
  explanation:'先因式分解再让每个括号等于 0。',
  steps:['$x^2-x-2=(x-2)(x+1)=0$','$x-2=0\\Rightarrow x=2$；$x+1=0\\Rightarrow x=-1$'] },

/* ==================================================================
   二、基础 (level 2)：极限 / 连续 / 求导公式 / 基本积分
   ================================================================== */
{ id:'b01', module:'limit', topic:'极限计算', level:2, type:'choice',
  stem:'$\\displaystyle\\lim_{x\\to 2}\\dfrac{x^{2}-4}{x-2}=$',
  options:['$0$','$2$','$4$','不存在'], answer:2,
  explanation:'这是 $\\frac00$ 型，先把分子因式分解，约掉 $(x-2)$。',
  steps:['分子 $x^2-4=(x-2)(x+2)$','约掉 $(x-2)$：$=\\lim_{x\\to2}(x+2)$','代入 $x=2$：$=4$'],
  optionNotes:['没约分直接代成 0','算错了','正确：约分后代入得 4','约分后极限存在'] },

{ id:'b02', module:'limit', topic:'极限计算', level:2, type:'choice',
  stem:'$\\displaystyle\\lim_{x\\to 0}\\dfrac{\\sin 3x}{x}=$',
  options:['$1$','$3$','$0$','$\\dfrac13$'], answer:1,
  explanation:'用第一重要极限 $\\frac{\\sin\\square}{\\square}\\to1$，凑出 $3x$。',
  steps:['$\\dfrac{\\sin 3x}{x}=3\\cdot\\dfrac{\\sin 3x}{3x}$','当 $x\\to0$，$\\dfrac{\\sin 3x}{3x}\\to1$','所以极限 $=3\\times1=3$'],
  optionNotes:['忘了乘系数 3','正确','这不是趋于 0','系数记反了'] },

{ id:'b03', module:'limit', topic:'极限计算', level:2, type:'choice',
  stem:'$\\displaystyle\\lim_{x\\to\\infty}\\dfrac{3x^{2}+1}{2x^{2}-x}=$',
  options:['$0$','$\\dfrac32$','$\\dfrac23$','$\\infty$'], answer:1,
  explanation:'$x\\to\\infty$ 时看最高次项系数之比。',
  steps:['分子分母同除以 $x^2$：$\\dfrac{3+1/x^2}{2-1/x}$','$x\\to\\infty$ 时 $1/x^2,1/x\\to0$','$=\\dfrac{3}{2}$'],
  optionNotes:['不是 0，同次','正确：最高次系数比 3:2','上下写反了','同次数极限有限，不是无穷'] },

{ id:'b04', module:'derivative', topic:'导数计算', level:2, type:'fill',
  stem:'$(x^{5})\'=$ ______',
  answer:['5x^4','5x^{4}'],
  explanation:'幂函数求导：指数拿下来，次数减 1。',
  steps:['$(x^n)\'=nx^{n-1}$','$(x^5)\'=5x^{5-1}=5x^4$'] },

{ id:'b05', module:'derivative', topic:'导数计算', level:2, type:'choice',
  stem:'$(3x^{2}+2x)\'=$',
  options:['$6x+2$','$3x+2$','$6x^{2}+2$','$6x$'], answer:0,
  explanation:'逐项求导，系数保留。',
  steps:['$(3x^2)\'=3\\cdot2x=6x$','$(2x)\'=2$','相加 $=6x+2$'],
  optionNotes:['正确','第一项系数没乘 2','次数没减 1','漏了第二项的导数 2'] },

{ id:'b06', module:'derivative', topic:'导数计算', level:2, type:'fill',
  stem:'$(\\ln x)\'=$ ______',
  answer:['1/x','\\frac{1}{x}'],
  explanation:'自然对数求导是基本公式，要记住。',
  steps:['基本公式：$(\\ln x)\'=\\dfrac1x$'] },

{ id:'b07', module:'derivative', topic:'导数计算', level:2, type:'choice',
  stem:'设 $f(x)=x^{3}$，则 $f\'(1)=$',
  options:['$1$','$2$','$3$','$0$'], answer:2,
  explanation:'先求导再代入。',
  steps:['$f\'(x)=3x^2$','代入 $x=1$：$f\'(1)=3\\times1^2=3$'],
  optionNotes:['那是 $f(1)$','算错','正确','导数不为 0'] },

{ id:'b08', module:'integral_indef', topic:'不定积分', level:2, type:'fill',
  stem:'$\\displaystyle\\int x^{2}\\,dx=$ ______（记得 $+C$）',
  answer:['x^3/3+C','\\frac{x^3}{3}+C','x^{3}/3'],
  explanation:'积分是求导的逆运算：次数加 1，再除以新次数。',
  steps:['$\\int x^n dx=\\dfrac{x^{n+1}}{n+1}+C$','$\\int x^2 dx=\\dfrac{x^3}{3}+C$'] },

{ id:'b09', module:'integral_indef', topic:'不定积分', level:2, type:'choice',
  stem:'$\\displaystyle\\int\\cos x\\,dx=$',
  options:['$\\sin x+C$','$-\\sin x+C$','$\\cos x+C$','$-\\cos x+C$'], answer:0,
  explanation:'$\\cos$ 的原函数是 $\\sin$。',
  steps:['因为 $(\\sin x)\'=\\cos x$','所以 $\\int\\cos x\\,dx=\\sin x+C$'],
  optionNotes:['正确','那是 $\\int\\sin x$ 的负号搞混了','积分不会不变','$-\\cos$ 是 $\\int\\sin x$'] },

{ id:'b10', module:'integral_indef', topic:'不定积分', level:2, type:'fill',
  stem:'$\\displaystyle\\int e^{x}\\,dx=$ ______',
  answer:['e^x+C','e^{x}+C'],
  explanation:'$e^x$ 积分还是自己。',
  steps:['$(e^x)\'=e^x$','所以 $\\int e^x dx=e^x+C$'] },

{ id:'b11', module:'derivative', topic:'导数计算', level:2, type:'fill',
  stem:'$(\\cos x)\'=$ ______',
  answer:['-sinx','-\\sin x','-sin x'],
  explanation:'余弦求导有个负号，别丢。',
  steps:['$(\\cos x)\'=-\\sin x$（记住负号）'] },

{ id:'b12', module:'derivative', topic:'导数应用', level:2, type:'choice',
  stem:'曲线 $y=x^{2}$ 在点 $x=1$ 处切线的斜率是',
  options:['$1$','$2$','$3$','$0$'], answer:1,
  explanation:'切线斜率就是该点的导数值。',
  steps:['$y\'=2x$','切线斜率 $=y\'(1)=2\\times1=2$'],
  optionNotes:['那是 $y(1)$','正确：$y\'(1)=2$','算错','切线不水平'] },

/* ==================================================================
   三、提升 (level 3)：导数应用 / 换元分部 / 定积分
   ================================================================== */
{ id:'u01', module:'application', topic:'导数应用', level:3, type:'choice',
  stem:'曲线 $y=x^{2}$ 在点 $(1,1)$ 处的切线方程是',
  options:['$y=2x-1$','$y=2x+1$','$y=x$','$y=2x$'], answer:0,
  explanation:'切线：先求斜率 $y\'(1)$，再用点斜式。',
  steps:['$y\'=2x$，斜率 $k=y\'(1)=2$','点斜式：$y-1=2(x-1)$','整理得 $y=2x-1$'],
  optionNotes:['正确','截距符号错了','斜率不是 1','没过点 (1,1)'] },

{ id:'u02', module:'application', topic:'导数应用', level:3, type:'choice',
  stem:'函数 $f(x)=x^{3}-3x$ 的单调增区间是',
  options:['$(-1,1)$','$(-\\infty,-1)$ 和 $(1,+\\infty)$','$(0,+\\infty)$','$(-\\infty,+\\infty)$'], answer:1,
  explanation:'求 $f\'>0$ 的区间就是增区间。',
  steps:['$f\'(x)=3x^2-3=3(x-1)(x+1)$','令 $f\'>0$：$x<-1$ 或 $x>1$','所以增区间是 $(-\\infty,-1)$ 与 $(1,+\\infty)$'],
  optionNotes:['这里 $f\'<0$，是减区间','正确','只对了一半','有增有减，不是全增'] },

{ id:'u03', module:'application', topic:'导数应用', level:3, type:'fill',
  stem:'函数 $f(x)=x^{2}-4x+3$ 的极小值是 ______',
  answer:['-1'],
  explanation:'先求驻点，再算函数值。',
  steps:['$f\'(x)=2x-4=0\\Rightarrow x=2$','$f\'\'=2>0$，$x=2$ 处取极小','$f(2)=4-8+3=-1$'] },

{ id:'u04', module:'integral_indef', topic:'不定积分', level:3, type:'fill',
  stem:'$\\displaystyle\\int 2x\\,e^{x^{2}}\\,dx=$ ______',
  answer:['e^{x^2}+C','e^x^2+C','e^{x^{2}}+C'],
  explanation:'凑微分（换元）：注意到 $2x$ 正好是 $x^2$ 的导数。',
  steps:['令 $u=x^2$，则 $du=2x\\,dx$','原式 $=\\int e^u\\,du=e^u+C$','换回 $=e^{x^2}+C$'] },

{ id:'u05', module:'integral_indef', topic:'不定积分', level:3, type:'choice',
  stem:'$\\displaystyle\\int\\sin x\\cos x\\,dx=$',
  options:['$\\dfrac12\\sin^{2}x+C$','$\\sin^{2}x+C$','$-\\cos^{2}x+C$','$\\cos x\\sin x+C$'], answer:0,
  explanation:'凑微分：$\\cos x\\,dx=d(\\sin x)$。',
  steps:['令 $u=\\sin x$，$du=\\cos x\\,dx$','$\\int u\\,du=\\dfrac{u^2}{2}+C$','$=\\dfrac12\\sin^2x+C$'],
  optionNotes:['正确','少除以 2','思路可行但形式和答案差常数','这不是积分结果'] },

{ id:'u06', module:'integral_indef', topic:'不定积分', level:3, type:'fill',
  stem:'$\\displaystyle\\int x\\,e^{x}\\,dx=$ ______',
  answer:['(x-1)e^x+C','xe^x-e^x+C','(x-1)e^{x}+C'],
  explanation:'分部积分：$\\int u\\,dv=uv-\\int v\\,du$。',
  steps:['取 $u=x,\\ dv=e^x dx$，则 $du=dx,\\ v=e^x$','$\\int xe^x dx=xe^x-\\int e^x dx$','$=xe^x-e^x+C=(x-1)e^x+C$'] },

{ id:'u07', module:'integral_def', topic:'定积分', level:3, type:'fill',
  stem:'$\\displaystyle\\int_{0}^{1}x^{2}\\,dx=$ ______',
  answer:['1/3','\\frac{1}{3}'],
  explanation:'先求原函数，再代上下限相减。',
  steps:['原函数 $\\dfrac{x^3}{3}$','$\\left[\\dfrac{x^3}{3}\\right]_0^1=\\dfrac13-0=\\dfrac13$'] },

{ id:'u08', module:'integral_def', topic:'定积分', level:3, type:'choice',
  stem:'$\\displaystyle\\int_{0}^{\\pi}\\sin x\\,dx=$',
  options:['$0$','$1$','$2$','$-2$'], answer:2,
  explanation:'$\\sin$ 的原函数是 $-\\cos$。',
  steps:['$\\int\\sin x\\,dx=-\\cos x$','$[-\\cos x]_0^{\\pi}=-\\cos\\pi+\\cos0=1+1=2$'],
  optionNotes:['积分号别忘代限','算错','正确','符号弄反了'] },

{ id:'u09', module:'integral_def', topic:'定积分', level:3, type:'choice',
  stem:'$\\displaystyle\\int_{-1}^{1}x^{3}\\,dx=$',
  options:['$0$','$\\dfrac12$','$2$','$\\dfrac14$'], answer:0,
  explanation:'$x^3$ 是奇函数，在对称区间 $[-1,1]$ 上积分为 0。',
  steps:['$x^3$ 是奇函数：$f(-x)=-f(x)$','奇函数在 $[-a,a]$ 上积分 $=0$','所以结果为 0'],
  optionNotes:['正确：奇函数对称抵消','不用真算，是 0','不是 2','不是 1/4'] },

{ id:'u10', module:'derivative', topic:'导数计算', level:3, type:'fill',
  stem:'$(\\sin 2x)\'=$ ______',
  answer:['2cos2x','2\\cos 2x','2cos 2x'],
  explanation:'复合函数用链式法则：外层导数 × 内层导数。',
  steps:['外层 $\\sin$ 求导得 $\\cos 2x$','内层 $2x$ 求导得 $2$','相乘 $=2\\cos 2x$'] },

{ id:'u11', module:'application', topic:'导数应用', level:3, type:'fill',
  stem:'函数 $f(x)=x^{3}-3x^{2}$ 的极大值是 ______',
  answer:['0'],
  explanation:'求驻点，用二阶导判断哪个是极大。',
  steps:['$f\'(x)=3x^2-6x=3x(x-2)$，驻点 $x=0,2$','$f\'\'(x)=6x-6$；$f\'\'(0)=-6<0$，$x=0$ 处极大','$f(0)=0$'] },

{ id:'u12', module:'integral_def', topic:'定积分', level:3, type:'fill',
  stem:'$\\displaystyle\\int_{1}^{2}\\dfrac{1}{x}\\,dx=$ ______',
  answer:['ln2','\\ln 2','ln 2'],
  explanation:'$\\frac1x$ 的原函数是 $\\ln|x|$。',
  steps:['$\\int\\dfrac1x dx=\\ln|x|$','$[\\ln x]_1^2=\\ln2-\\ln1=\\ln2$'] },

/* ==================================================================
   三·五、循序渐进的解答题（level 1~3，先自己写再对照）
   —— 让基础阶段的人也有"完整写一道"的练习，不至于一上来就撞真题
   ================================================================== */
{ id:'s01', module:'literacy', topic:'代入求值', level:1, type:'solve',
  stem:'已知 $f(x)=x^{2}+1$，求 $f(2)$。',
  answer:['5'], explanation:'把 x 换成 2，先算平方再加。',
  steps:['把 $x$ 换成 2：$f(2)=2^2+1$','先算平方：$2^2=4$','$4+1=5$'] },

{ id:'s02', module:'literacy', topic:'解简单方程', level:1, type:'solve',
  stem:'解方程 $2x+3=11$。',
  answer:['x=4','4'], explanation:'先把 +3 移过去，再把 ×2 除回来。',
  steps:['两边同时减 3：$2x=11-3=8$','两边同时除以 2：$x=8\\div2=4$'] },

{ id:'s03', module:'limit', topic:'极限计算', level:2, type:'solve',
  stem:'求 $\\displaystyle\\lim_{x\\to2}\\dfrac{x^{2}-4}{x-2}$。',
  answer:['4'], explanation:'$\\frac00$ 型，先因式分解约掉 $(x-2)$。',
  steps:['分子 $x^2-4=(x-2)(x+2)$','约掉 $(x-2)$：$=\\lim_{x\\to2}(x+2)$','代入 $x=2$：$=4$'] },

{ id:'s04', module:'derivative', topic:'导数计算', level:2, type:'solve',
  stem:'求函数 $y=x^{3}+2x$ 的导数 $y\'$。',
  answer:["3x^2+2","y'=3x^2+2"], explanation:'逐项用幂函数求导公式。',
  steps:['$(x^3)\'=3x^2$','$(2x)\'=2$','相加：$y\'=3x^2+2$'] },

{ id:'s05', module:'integral_indef', topic:'不定积分', level:2, type:'solve',
  stem:'计算 $\\displaystyle\\int(3x^{2}+1)\\,dx$。',
  answer:['x^3+x+C'], explanation:'逐项积分，别忘 $+C$。',
  steps:['$\\int3x^2dx=x^3$','$\\int1dx=x$','合起来：$x^3+x+C$'] },

{ id:'s06', module:'integral_def', topic:'定积分', level:3, type:'solve',
  stem:'求 $\\displaystyle\\int_{0}^{1}2x\\,dx$。',
  answer:['1'], explanation:'先求原函数，再代上下限相减。',
  steps:['原函数：$\\int2x\\,dx=x^2$','代限：$[x^2]_0^1=1^2-0^2$','$=1$'] },

{ id:'s07', module:'application', topic:'导数应用', level:3, type:'solve',
  stem:'求 $y=x^{2}-4x+3$ 的极小值。',
  answer:['-1'], explanation:'解 $y\'=0$ 找驻点，二阶导判断极小。',
  steps:['$y\'=2x-4$，令 $=0$ 得 $x=2$','$y\'\'=2>0$，$x=2$ 处是极小','$y(2)=4-8+3=-1$'] },

/* ==================================================================
   三·六、核心知识点巩固题（⭐核心必考：极限/导数/积分/导数应用，多练确保会）
   ================================================================== */
// —— 极限计算 ——
{ id:'k1', module:'limit', topic:'极限计算', level:2, type:'choice',
  stem:'$\\displaystyle\\lim_{x\\to0}\\dfrac{\\sin 5x}{x}=$',
  options:['$1$','$5$','$0$','$\\dfrac15$'], answer:1,
  explanation:'用第一重要极限，凑出 $5x$。',
  steps:['$\\dfrac{\\sin 5x}{x}=5\\cdot\\dfrac{\\sin 5x}{5x}$','$\\dfrac{\\sin 5x}{5x}\\to1$','所以 $=5\\times1=5$'],
  optionNotes:['忘了乘系数 5','正确','不是 0','系数记反了'] },
{ id:'k2', module:'limit', topic:'极限计算', level:2, type:'fill',
  stem:'$\\displaystyle\\lim_{x\\to\\infty}\\dfrac{3x-1}{x+2}=$ ______',
  answer:['3'], explanation:'x 很大时看最高次系数之比。',
  steps:['分子分母同除以 x：$\\dfrac{3-1/x}{1+2/x}$','$1/x\\to0$','$=\\dfrac{3}{1}=3$'] },
{ id:'k3', module:'limit', topic:'极限计算', level:2, type:'fill',
  stem:'$\\displaystyle\\lim_{x\\to3}\\dfrac{x^2-9}{x-3}=$ ______',
  answer:['6'], explanation:'0/0 型，先约分。',
  steps:['分子 $x^2-9=(x-3)(x+3)$','约掉 $(x-3)$ 得 $x+3$','代入 $x=3$：$=6$'] },
{ id:'k4', module:'limit', topic:'极限计算', level:3, type:'choice',
  stem:'$\\displaystyle\\lim_{x\\to\\infty}\\left(1+\\dfrac1x\\right)^{x}=$',
  options:['$1$','$e$','$0$','$\\infty$'], answer:1,
  explanation:'第二重要极限，直接是 e。',
  steps:['这是第二重要极限的标准形','$\\lim_{x\\to\\infty}(1+\\frac1x)^x=e$'],
  optionNotes:['不是 1','正确：等于 $e\\approx2.718$','不是 0','有极限，不是无穷'] },

// —— 导数计算 ——
{ id:'d1', module:'derivative', topic:'导数计算', level:2, type:'fill',
  stem:'$(x^{6})\'=$ ______', answer:['6x^5','6x^{5}'],
  explanation:'幂函数求导。', steps:['$(x^n)\'=nx^{n-1}$','$(x^6)\'=6x^5$'] },
{ id:'d2', module:'derivative', topic:'导数计算', level:2, type:'choice',
  stem:'$(2x^{3}-x)\'=$',
  options:['$6x^{2}-1$','$2x^{2}-1$','$6x^{2}-x$','$6x^{3}$'], answer:0,
  explanation:'逐项求导。', steps:['$(2x^3)\'=6x^2$','$(-x)\'=-1$','合起来 $6x^2-1$'],
  optionNotes:['正确','第一项系数没乘 3','第二项没求导','次数没减 1'] },
{ id:'d3', module:'derivative', topic:'导数计算', level:2, type:'fill',
  stem:'$(e^{x}+x)\'=$ ______', answer:['e^x+1','e^{x}+1'],
  explanation:'逐项求导。', steps:['$(e^x)\'=e^x$','$(x)\'=1$','合起来 $e^x+1$'] },
{ id:'d4', module:'derivative', topic:'导数计算', level:2, type:'fill',
  stem:'设 $f(x)=x^{2}$，则 $f\'(3)=$ ______', answer:['6'],
  explanation:'先求导再代入。', steps:['$f\'(x)=2x$','$f\'(3)=2\\times3=6$'] },
{ id:'d5', module:'derivative', topic:'导数计算', level:3, type:'choice',
  stem:'$(x\\cos x)\'=$',
  options:['$\\cos x-x\\sin x$','$\\cos x+x\\sin x$','$-\\sin x$','$\\sin x$'], answer:0,
  explanation:'乘积法则 $(uv)\'=u\'v+uv\'$。',
  steps:['$u=x,v=\\cos x$','$u\'v=\\cos x$；$uv\'=x\\cdot(-\\sin x)$','合起来 $\\cos x-x\\sin x$'],
  optionNotes:['正确','$\\cos x$ 的导数是 $-\\sin x$，符号错','漏了第一项','漏了第一项'] },

// —— 不定积分 ——
{ id:'i1', module:'integral_indef', topic:'不定积分', level:2, type:'fill',
  stem:'$\\displaystyle\\int x^{4}\\,dx=$ ______', answer:['x^5/5+C','\\frac{x^5}{5}+C','x^5/5'],
  explanation:'次数+1除以新次数。', steps:['$\\int x^n dx=\\dfrac{x^{n+1}}{n+1}+C$','$=\\dfrac{x^5}{5}+C$'] },
{ id:'i2', module:'integral_indef', topic:'不定积分', level:2, type:'choice',
  stem:'$\\displaystyle\\int(2x+3)\\,dx=$',
  options:['$x^{2}+3x+C$','$2x^{2}+3x+C$','$x^{2}+3+C$','$2+C$'], answer:0,
  explanation:'逐项积分。', steps:['$\\int2x\\,dx=x^2$','$\\int3\\,dx=3x$','合起来 $x^2+3x+C$'],
  optionNotes:['正确','第一项应除以 2','常数 3 积分是 3x','都没积对'] },
{ id:'i3', module:'integral_indef', topic:'不定积分', level:2, type:'fill',
  stem:'$\\displaystyle\\int\\sin x\\,dx=$ ______', answer:['-cosx+C','-\\cos x+C','-cos x'],
  explanation:'sin 的原函数是 -cos。', steps:['$(-\\cos x)\'=\\sin x$','所以 $\\int\\sin x\\,dx=-\\cos x+C$'] },
{ id:'i4', module:'integral_indef', topic:'不定积分', level:2, type:'fill',
  stem:'$\\displaystyle\\int 3x^{2}\\,dx=$ ______', answer:['x^3+C','x^{3}+C','x^3'],
  explanation:'系数保留，次数+1。', steps:['$\\int3x^2dx=3\\cdot\\dfrac{x^3}{3}=x^3$','加常数 $+C$'] },

// —— 定积分 ——
{ id:'j1', module:'integral_def', topic:'定积分', level:2, type:'fill',
  stem:'$\\displaystyle\\int_{0}^{2}x\\,dx=$ ______', answer:['2'],
  explanation:'原函数代上下限。', steps:['原函数 $\\dfrac{x^2}{2}$','$\\left[\\dfrac{x^2}{2}\\right]_0^2=\\dfrac42-0=2$'] },
{ id:'j2', module:'integral_def', topic:'定积分', level:2, type:'choice',
  stem:'$\\displaystyle\\int_{0}^{1}3x^{2}\\,dx=$',
  options:['$1$','$3$','$\\dfrac13$','$0$'], answer:0,
  explanation:'原函数是 $x^3$。', steps:['$\\int3x^2dx=x^3$','$[x^3]_0^1=1-0=1$'],
  optionNotes:['正确','没代限','原函数错','不是 0'] },
{ id:'j3', module:'integral_def', topic:'定积分', level:3, type:'fill',
  stem:'$\\displaystyle\\int_{0}^{1}e^{x}\\,dx=$ ______', answer:['e-1','e-1'],
  explanation:'原函数 $e^x$。', steps:['$[e^x]_0^1=e^1-e^0=e-1$'] },
{ id:'j4', module:'integral_def', topic:'定积分', level:3, type:'choice',
  stem:'$\\displaystyle\\int_{-2}^{2}x^{3}\\,dx=$',
  options:['$0$','$8$','$4$','$16$'], answer:0,
  explanation:'奇函数在对称区间上积分为 0。',
  steps:['$x^3$ 是奇函数','对称区间 $[-2,2]$ 上正负抵消','$=0$'],
  optionNotes:['正确：奇函数抵消','不用算，是 0','不是 4','不是 16'] },

// —— 导数应用 ——
{ id:'a1', module:'application', topic:'导数应用', level:3, type:'fill',
  stem:'函数 $y=x^{2}-2x$ 的极小值是 ______', answer:['-1'],
  explanation:'解 y\'=0 找驻点再代入。', steps:['$y\'=2x-2=0\\Rightarrow x=1$','$y\'\'=2>0$，极小','$y(1)=1-2=-1$'] },
{ id:'a2', module:'application', topic:'导数应用', level:3, type:'fill',
  stem:'曲线 $y=x^{3}$ 在 $x=1$ 处切线的斜率是 ______', answer:['3'],
  explanation:'斜率=该点导数。', steps:['$y\'=3x^2$','$y\'(1)=3\\times1=3$'] },
{ id:'a3', module:'application', topic:'导数应用', level:3, type:'choice',
  stem:'函数 $f(x)=x^{2}-6x+5$ 的单调减区间是',
  options:['$x<3$','$x>3$','$x<0$','全体实数'], answer:0,
  explanation:'求 f\'<0 的区间。',
  steps:['$f\'(x)=2x-6$','令 $f\'<0$：$2x-6<0\\Rightarrow x<3$','所以减区间是 $x<3$'],
  optionNotes:['正确：$f\'<0$ 得 $x<3$','那是增区间','算错','有增有减'] },

/* ==================================================================
   四、冲刺 · 真题 (level 4) —— 全真模拟(一) 高数(二)，共 28 题
   ================================================================== */
// —— 选择题 1~10 ——
{ id:'e1_01', module:'limit', topic:'极限计算', level:4, type:'choice',
  stem:'下列极限等于 $1$ 的是',
  options:['$\\displaystyle\\lim_{x\\to\\infty}\\dfrac{\\arctan x}{x}$','$\\displaystyle\\lim_{x\\to0}\\dfrac{\\arctan x}{x}$','$\\displaystyle\\lim_{x\\to\\infty}\\dfrac{2x+1}{3x+5}$','$\\displaystyle\\lim_{x\\to\\infty}\\dfrac{\\sin x}{x}$'], answer:1,
  explanation:'考等价无穷小与有界量×无穷小。$x\\to0$ 时 $\\arctan x\\sim x$。',
  steps:['A：$\\arctan x$ 有界、$\\frac1x\\to0$，乘积 $\\to0$','B：$x\\to0$ 时 $\\arctan x\\sim x$，比值 $\\to1$ ✓','C：同次系数比 $\\to\\frac23$','D：$\\sin x$ 有界、$\\frac1x\\to0$，$\\to0$'],
  optionNotes:['有界量乘无穷小，等于 0','正确：等价无穷小 $\\arctan x\\sim x$','极限是 $\\frac23$','有界量乘无穷小，等于 0'] },

{ id:'e1_02', module:'derivative', topic:'连续性', level:4, type:'choice',
  stem:'函数 $y=|x|+1$ 在 $x=0$ 处',
  options:['无定义','不连续','连续但不可导','可导'], answer:2,
  explanation:'绝对值函数在 0 处是个"尖角"，连续但左右导数不相等。',
  steps:['$x=0$ 时 $y=1$，有定义','$\\lim_{x\\to0}(|x|+1)=1=y(0)$，连续','左导数 $=-1$，右导数 $=+1$，不相等 $\\Rightarrow$ 不可导'],
  optionNotes:['$x=0$ 有定义','极限存在且等于函数值，连续','正确：尖点连续不可导','左右导数不等，不可导'] },

{ id:'e1_03', module:'application', topic:'导数应用', level:4, type:'choice',
  stem:'函数 $y=\\dfrac12\\left(e^{x}+e^{-x}\\right)$ 在区间 $(-1,1)$ 内',
  options:['单调减少','单调增加','不增不减','有增有减'], answer:3,
  explanation:'求导后看符号在区间内是否变号。',
  steps:['$y\'=\\dfrac12(e^x-e^{-x})$','令 $y\'=0$ 得 $x=0$','$x>0$ 时 $y\'>0$（增）；$x<0$ 时 $y\'<0$（减）','所以在 $(-1,1)$ 内有增有减'],
  optionNotes:['只在 $x<0$ 部分减','只在 $x>0$ 部分增','导数会变号，不是恒不变','正确：以 $x=0$ 为界，先减后增'] },

{ id:'e1_04', module:'application', topic:'导数应用', level:4, type:'choice',
  stem:'函数 $f(x)=x^{4}-24x^{2}+6x$ 的凸区间是',
  options:['$(-\\infty,0)$','$(-2,2)$','$(0,+\\infty)$','$(-\\infty,+\\infty)$'], answer:1,
  explanation:'凸区间就是 $f\'\'(x)<0$ 的区间。',
  steps:['$f\'(x)=4x^3-48x+6$','$f\'\'(x)=12x^2-48=12(x^2-4)$','令 $f\'\'<0$：$x^2-4<0\\Rightarrow -2<x<2$','所以凸区间为 $(-2,2)$'],
  optionNotes:['这里 $f\'\'$ 未必负','正确：$f\'\'<0$ 得 $(-2,2)$','$f\'\'$ 在此不恒负','$f\'\'$ 会变号，不是全区间'] },

{ id:'e1_05', module:'integral_def', topic:'定积分', level:4, type:'choice',
  stem:'设 $\\displaystyle\\int_{0}^{x}f(t)\\,dt=\\dfrac{x^{4}}{2}$，则 $\\displaystyle\\int_{0}^{4}\\dfrac{1}{\\sqrt{x}}f(\\sqrt{x})\\,dx=$',
  options:['$2$','$4$','$8$','$16$'], answer:3,
  explanation:'先由条件求出 $f$（对上限 $x$ 求导），再代入换元算积分。',
  steps:['由 $\\int_0^{x}f(t)dt=\\dfrac{x^4}{2}$，两边对上限 $x$ 求导：$f(x)=\\left(\\dfrac{x^4}{2}\\right)\'=2x^3$','代入 $\\sqrt x$：$f(\\sqrt x)=2(\\sqrt x)^3=2x^{3/2}$','$\\int_0^4\\dfrac{1}{\\sqrt x}\\cdot 2x^{3/2}\\,dx=\\int_0^4 2x\\,dx$','$=[x^2]_0^4=16$'],
  optionNotes:['求 $f$ 时别弄错','系数没乘对','漏了系数','正确：$f(x)=2x^3$，最后 $\\int_0^4 2x\\,dx=16$'] },

{ id:'e1_06', module:'integral_def', topic:'定积分', level:4, type:'choice',
  stem:'积分 $\\displaystyle\\int_{-\\pi/2}^{\\pi/2}\\dfrac{\\sin x}{1+\\cos x}\\,dx=$',
  options:['$-1$','$0$','$1$','$2$'], answer:1,
  explanation:'被积函数是奇函数，积分区间对称，直接得 0。',
  steps:['记 $g(x)=\\dfrac{\\sin x}{1+\\cos x}$','$\\sin(-x)=-\\sin x,\\ \\cos(-x)=\\cos x$，故 $g(-x)=-g(x)$，是奇函数','奇函数在对称区间 $[-\\frac\\pi2,\\frac\\pi2]$ 上积分为 $0$'],
  optionNotes:['奇函数对称抵消，不是 -1','正确：奇函数积分为 0','抵消为 0，不是 1','不是 2'] },

{ id:'e1_07', module:'integral_def', topic:'反常积分', level:4, type:'choice',
  stem:'若 $\\displaystyle\\int_{-\\infty}^{0}e^{kx}\\,dx=\\dfrac13$，则 $k$ 等于',
  options:['$\\dfrac13$','$-\\dfrac13$','$3$','$-3$'], answer:2,
  explanation:'反常积分收敛要求 $k>0$，算出后令其等于 $\\frac13$。',
  steps:['$\\int_{-\\infty}^0 e^{kx}dx=\\left[\\dfrac{1}{k}e^{kx}\\right]_{-\\infty}^0$（需 $k>0$ 才收敛）','$=\\dfrac1k(1-0)=\\dfrac1k$','令 $\\dfrac1k=\\dfrac13\\Rightarrow k=3$'],
  optionNotes:['那是 $\\frac1k$ 的值，不是 k','k 必须为正才收敛','正确：$\\frac1k=\\frac13\\Rightarrow k=3$','k 为负积分发散'] },

{ id:'e1_08', module:'multivar', topic:'多元偏导', level:4, type:'choice',
  stem:'设 $z=x e^{xy}$，则 $\\dfrac{\\partial z}{\\partial x}=$',
  options:['$xy e^{xy}$','$x^{2}e^{xy}$','$e^{xy}$','$(1+xy)e^{xy}$'], answer:3,
  explanation:'把 $y$ 当常数，对 $x$ 用乘积法则。',
  steps:['$z=x\\cdot e^{xy}$，对 $x$ 求导（$y$ 看常数）','$\\dfrac{\\partial z}{\\partial x}=1\\cdot e^{xy}+x\\cdot e^{xy}\\cdot y$','$=(1+xy)e^{xy}$'],
  optionNotes:['漏了第一项 $e^{xy}$','没用乘积法则','漏了第二项','正确：乘积法则展开'] },

{ id:'e1_09', module:'multivar', topic:'多元偏导', level:4, type:'choice',
  stem:'设函数 $z=\\ln xy+e^{x^{2}y}$，则 $\\dfrac{\\partial z}{\\partial y}\\Big|_{(1,2)}=$',
  options:['$\\dfrac12-2e^{2}$','$\\dfrac12+e^{2}$','$1+2e^{2}$','$1+e^{2}$'], answer:1,
  explanation:'对 $y$ 求偏导，再代入点 $(1,2)$。',
  steps:['$\\dfrac{\\partial z}{\\partial y}=\\dfrac{1}{y}+e^{x^2y}\\cdot x^2$（$\\ln xy=\\ln x+\\ln y$，对 y 得 $\\frac1y$）','代入 $x=1,y=2$：$\\dfrac12+e^{2}\\cdot1$','$=\\dfrac12+e^2$'],
  optionNotes:['符号错','正确：$\\frac12+e^2$','第一项应为 $\\frac1y=\\frac12$','第一项算成 1 了'] },

{ id:'e1_10', module:'probability', topic:'概率', level:4, type:'choice',
  stem:'把两封信随机投入标号 $1,2,3,4$ 的 4 个邮筒中，则 $1,2$ 号邮筒各有一封信的概率等于',
  options:['$\\dfrac{1}{16}$','$\\dfrac{1}{12}$','$\\dfrac18$','$\\dfrac14$'], answer:2,
  explanation:'古典概率：有利结果数 ÷ 总结果数。',
  steps:['每封信有 4 种投法，两封信总方法数 $=4^2=16$','1、2 号各一封（可重复排列）：$A_2^2=2$ 种','$P=\\dfrac{2}{16}=\\dfrac18$'],
  optionNotes:['分子不是 1','分母不是 12','正确：$\\frac{2}{16}=\\frac18$','偏大了'] },

// —— 填空题 11~20 ——
{ id:'e1_11', module:'limit', topic:'极限计算', level:4, type:'fill',
  stem:'$\\displaystyle\\lim_{x\\to\\infty}\\left(1-\\dfrac{2}{x}\\right)^{3x}=$ ______',
  answer:['e^{-6}','e^-6','1/e^6'],
  explanation:'第二重要极限：凑成 $(1+\\frac1\\square)^\\square\\to e$。',
  steps:['$\\left(1-\\dfrac2x\\right)^{3x}=\\left[\\left(1-\\dfrac2x\\right)^{-x/2}\\right]^{-6}$','中括号内 $\\to e$','所以极限 $=e^{-6}$'] },

{ id:'e1_12', module:'derivative', topic:'导数计算', level:4, type:'fill',
  stem:'$y=\\arctan e^{x}$，则 $y\'\\big|_{x=0}=$ ______',
  answer:['1/2','\\frac{1}{2}'],
  explanation:'复合求导：$(\\arctan u)\'=\\frac{u\'}{1+u^2}$。',
  steps:['$y\'=\\dfrac{1}{1+(e^x)^2}\\cdot e^x=\\dfrac{e^x}{1+e^{2x}}$','代入 $x=0$：$\\dfrac{1}{1+1}=\\dfrac12$'] },

{ id:'e1_13', module:'derivative', topic:'隐函数', level:4, type:'fill',
  stem:'设 $y=y(x)$ 由 $x^{2}+2xy-y^{2}=2x$ 确定，且 $y\\big|_{x=2}=0$，则 $y\'\\big|_{x=2}=$ ______',
  answer:['-1/2','-\\frac{1}{2}'],
  explanation:'隐函数求导：两边对 $x$ 求导，把 $y$ 看成 $x$ 的函数。',
  steps:['两边对 $x$ 求导：$2x+2y+2xy\'-2yy\'=2$','解出 $y\'=\\dfrac{2-2x-2y}{2x-2y}=\\dfrac{1-x-y}{x-y}$','代入 $x=2,y=0$：$\\dfrac{1-2-0}{2-0}=-\\dfrac12$'] },

{ id:'e1_14', module:'application', topic:'导数应用', level:4, type:'fill',
  stem:'曲线 $x^{2}+y^{2}=2x$ 在点 $(1,1)$ 处的切线方程为 ______',
  answer:['y=1'],
  explanation:'隐函数求导得斜率，发现斜率为 0，切线水平。',
  steps:['两边对 $x$ 求导：$2x+2yy\'=2$，即 $y\'=\\dfrac{1-x}{y}$','代入 $(1,1)$：$y\'=\\dfrac{1-1}{1}=0$','斜率为 0 且过 $(1,1)$，切线方程 $y=1$'] },

{ id:'e1_15', module:'application', topic:'导数应用', level:4, type:'fill',
  stem:'曲线 $y=x^{3}-3x^{2}+2x+1$ 的拐点是 ______（写成坐标）',
  answer:['(1,1)'],
  explanation:'拐点：$f\'\'=0$ 且两侧变号处。',
  steps:['$y\'=3x^2-6x+2$，$y\'\'=6x-6$','令 $y\'\'=0$ 得 $x=1$，两侧变号','$y(1)=1-3+2+1=1$，拐点为 $(1,1)$'] },

{ id:'e1_16', module:'integral_indef', topic:'不定积分', level:4, type:'fill',
  stem:'$\\displaystyle\\int(\\sqrt{x}-1)\\left(1+\\dfrac{1}{x}\\right)dx=$ ______',
  answer:['\\frac{2}{3}x^{3/2}-x+2x^{1/2}-ln|x|+C','2/3 x^{3/2}-x+2\\sqrt{x}-\\ln|x|+C'],
  explanation:'先把括号乘开，再逐项积分。',
  steps:['乘开：$(\\sqrt x-1)(1+\\frac1x)=x^{1/2}-1+x^{-1/2}-x^{-1}$','逐项积分：$\\int x^{1/2}=\\frac23x^{3/2}$，$\\int(-1)=-x$，$\\int x^{-1/2}=2x^{1/2}$，$\\int(-x^{-1})=-\\ln|x|$','合起来：$\\dfrac23x^{3/2}-x+2x^{1/2}-\\ln|x|+C$'] },

{ id:'e1_17', module:'integral_indef', topic:'不定积分', level:4, type:'fill',
  stem:'$\\displaystyle\\int\\sin 2x\\cos x\\,dx=$ ______',
  answer:['-\\frac{2}{3}\\cos^3 x+C','-2/3 cos^3x+C'],
  explanation:'用 $\\sin2x=2\\sin x\\cos x$，再凑微分。',
  steps:['$\\sin2x\\cos x=2\\sin x\\cos^2 x$','$\\int 2\\sin x\\cos^2x\\,dx=-2\\int\\cos^2x\\,d(\\cos x)$','$=-2\\cdot\\dfrac{\\cos^3x}{3}+C=-\\dfrac23\\cos^3x+C$'] },

{ id:'e1_18', module:'integral_def', topic:'定积分', level:4, type:'fill',
  stem:'$\\displaystyle\\int_{-1}^{1}\\dfrac{x}{\\sqrt{10-6x}}\\,dx=$ ______',
  answer:['2/27','\\frac{2}{27}'],
  explanation:'换元 $t=\\sqrt{10-6x}$（真题解法之一）。',
  steps:['令 $t=\\sqrt{10-6x}$，则 $x=\\dfrac{10-t^2}{6}$，$dx=-\\dfrac{t}{3}dt$','$x:-1\\to1$ 对应 $t:4\\to2$','化简积分并计算，结果为 $\\dfrac{2}{27}$（详细代数较长，可让 AI 展开每一步）'] },

{ id:'e1_19', module:'integral_def', topic:'定积分', level:4, type:'fill',
  stem:'$\\displaystyle\\int_{1}^{e}\\ln x\\,dx=$ ______',
  answer:['1'],
  explanation:'分部积分：$\\int\\ln x\\,dx=x\\ln x-x$。',
  steps:['$\\int\\ln x\\,dx=x\\ln x-\\int x\\cdot\\frac1x dx=x\\ln x-x$','$[x\\ln x-x]_1^e=(e\\cdot1-e)-(0-1)=0-(-1)=1$'] },

{ id:'e1_20', module:'multivar', topic:'多元偏导', level:4, type:'fill',
  stem:'若 $z=\\ln(x+e^{y})$，则 $\\dfrac{\\partial^{2}z}{\\partial x\\partial y}=$ ______',
  answer:['-\\frac{e^y}{(x+e^y)^2}','-e^y/(x+e^y)^2'],
  explanation:'先求 $\\frac{\\partial z}{\\partial x}$，再对 $y$ 求偏导。',
  steps:['$\\dfrac{\\partial z}{\\partial x}=\\dfrac{1}{x+e^y}$','再对 $y$ 求导：$\\dfrac{\\partial}{\\partial y}(x+e^y)^{-1}=-(x+e^y)^{-2}\\cdot e^y$','$=-\\dfrac{e^y}{(x+e^y)^2}$'] },

// —— 解答题 21~28 ——
{ id:'e1_21', module:'limit', topic:'极限计算', level:4, type:'solve',
  stem:'计算 $\\displaystyle\\lim_{x\\to0}\\dfrac{x^{2}}{1-\\sqrt{1-x^{2}}}$.',
  answer:['2'],
  explanation:'分母有根号，用"有理化"（分子分母同乘共轭式）。',
  steps:['分子分母同乘 $1+\\sqrt{1-x^2}$','分母变为 $(1-\\sqrt{1-x^2})(1+\\sqrt{1-x^2})=1-(1-x^2)=x^2$','原式 $=\\dfrac{x^2(1+\\sqrt{1-x^2})}{x^2}=1+\\sqrt{1-x^2}$','令 $x\\to0$：$=1+1=2$'] },

{ id:'e1_22', module:'limit', topic:'极限计算', level:4, type:'solve',
  stem:'求极限 $\\displaystyle\\lim_{x\\to0}\\left(\\dfrac{1}{x}-\\dfrac{1}{e^{x}-1}\\right)$.',
  answer:['1/2','\\frac{1}{2}'],
  explanation:'先通分变成 $\\frac00$ 型，再用等价无穷小 / 泰勒或洛必达。',
  steps:['通分：$\\dfrac{e^x-1-x}{x(e^x-1)}$','$x\\to0$ 时分母 $x(e^x-1)\\sim x\\cdot x=x^2$','分子 $e^x-1-x\\sim\\dfrac{x^2}{2}$','所以极限 $=\\dfrac{x^2/2}{x^2}=\\dfrac12$'] },

{ id:'e1_23', module:'integral_def', topic:'反常积分', level:4, type:'solve',
  stem:'求 $\\displaystyle\\int_{0}^{+\\infty}x e^{-x}\\,dx$.',
  answer:['1'],
  explanation:'分部积分 + 取极限（反常积分）。',
  steps:['分部：$\\int xe^{-x}dx=-xe^{-x}+\\int e^{-x}dx=-xe^{-x}-e^{-x}$','取 $[0,a]$ 并令 $a\\to+\\infty$','$\\lim_{a\\to\\infty}(-ae^{-a}-e^{-a})-(0-1)=0-0+1=1$'] },

{ id:'e1_24', module:'multivar', topic:'多元偏导', level:4, type:'solve',
  stem:'设 $f\'\'$ 存在，$z=\\dfrac{1}{x}f(xy)+y f(x+y)$，求 $\\dfrac{\\partial^{2}z}{\\partial x\\partial y}$.',
  answer:["yf''(xy)+f'(x+y)+yf''(x+y)"],
  explanation:'先对 $x$ 求偏导，再对 $y$ 求偏导；注意链式法则和乘积法则。',
  steps:['$\\dfrac{\\partial z}{\\partial x}=-\\dfrac{1}{x^2}f(xy)+\\dfrac{1}{x}f\'(xy)\\cdot y+y f\'(x+y)$','再对 $y$ 求导，逐项处理','$-\\frac{1}{x^2}f(xy)\\to-\\frac1x f\'(xy)$；$\\frac{y}{x}f\'(xy)\\to\\frac1x f\'(xy)+yf\'\'(xy)$；$yf\'(x+y)\\to f\'(x+y)+yf\'\'(x+y)$','合并（前两项抵消）：$\\dfrac{\\partial^2z}{\\partial x\\partial y}=y f\'\'(xy)+f\'(x+y)+y f\'\'(x+y)$'] },

{ id:'e1_25', module:'probability', topic:'概率', level:4, type:'solve',
  stem:'一个袋子中有 5 个球，编号 $1,2,3,4,5$，同时从中任取 3 个，以 $X$ 表示取出的 3 个球中的最大号码，求随机变量 $X$ 的概率分布.',
  answer:['P(X=3)=1/10,P(X=4)=3/10,P(X=5)=6/10'],
  explanation:'总取法 $C_5^3=10$；$X=k$ 表示"$k$ 是最大"，即其余两个从 $1..k-1$ 里选。',
  steps:['总数 $C_5^3=10$，$X$ 只能取 $3,4,5$','$P(X=3)=\\dfrac{C_2^2}{C_5^3}=\\dfrac{1}{10}$（另两个来自 {1,2}）','$P(X=4)=\\dfrac{C_3^2}{10}=\\dfrac{3}{10}$','$P(X=5)=\\dfrac{C_4^2}{10}=\\dfrac{6}{10}=\\dfrac35$','分布表：$X:3,4,5$；$P:\\frac1{10},\\frac3{10},\\frac6{10}$'] },

{ id:'e1_26', module:'application', topic:'导数应用', level:4, type:'solve',
  stem:'求 $y=f(x)=2x^{3}-3x^{2}-12x+14$ 的极值点和极值，以及函数曲线的凸凹区间和拐点.',
  answer:['极大f(-1)=21,极小f(2)=-6,拐点(1/2,15/2)'],
  explanation:'一阶导找极值，二阶导找凸凹和拐点。',
  steps:['$y\'=6x^2-6x-12=6(x-2)(x+1)$，驻点 $x=-1,2$','$y\'\'=12x-6$；$y\'\'(-1)=-18<0$ 取极大 $f(-1)=21$；$y\'\'(2)=18>0$ 取极小 $f(2)=-6$','令 $y\'\'=0$ 得 $x=\\dfrac12$：$x<\\frac12$ 时 $y\'\'<0$ 凸，$x>\\frac12$ 时 $y\'\'>0$ 凹','$f(\\frac12)=\\dfrac{15}{2}$，拐点 $\\left(\\dfrac12,\\dfrac{15}{2}\\right)$'] },

{ id:'e1_27', module:'multivar', topic:'全微分', level:4, type:'solve',
  stem:'设 $z=\\sin(xy^{2})+e^{x^{2}y}$，求 $dz$.',
  answer:['dz=[y^2cos(xy^2)+2xy e^{x^2y}]dx+[2xy cos(xy^2)+x^2 e^{x^2y}]dy'],
  explanation:'全微分 $dz=\\frac{\\partial z}{\\partial x}dx+\\frac{\\partial z}{\\partial y}dy$，分别求两个偏导。',
  steps:['$\\dfrac{\\partial z}{\\partial x}=\\cos(xy^2)\\cdot y^2+e^{x^2y}\\cdot 2xy$','$\\dfrac{\\partial z}{\\partial y}=\\cos(xy^2)\\cdot 2xy+e^{x^2y}\\cdot x^2$','$dz=\\left[y^2\\cos(xy^2)+2xy\\,e^{x^2y}\\right]dx+\\left[2xy\\cos(xy^2)+x^2e^{x^2y}\\right]dy$'] },

{ id:'e1_28', module:'application', topic:'中值定理', level:4, type:'solve',
  stem:'当 $x>0$ 时，证明 $e^{x}>1+x$.',
  answer:['构造G(x)=e^x-1-x,单调递增'],
  explanation:'构造辅助函数，用单调性证明。',
  steps:['令 $G(x)=e^x-1-x$','$G\'(x)=e^x-1$，当 $x>0$ 时 $G\'(x)>0$，故 $G$ 在 $[0,+\\infty)$ 上单调递增','$G(0)=0$，所以 $x>0$ 时 $G(x)>G(0)=0$','即 $e^x-1-x>0$，亦即 $e^x>1+x$'] }

];
